/**
 * 幻灯片编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 *
 * 与 rich-text-editor / spreadsheet-editor 保持同一套约定（详见各自 strings.ts 头部说明）：
 * 单工具的几十条 UI 文案不进首屏语言包 `core/i18n/locales/*`，
 * 而是在工具被懒加载时由 `registerSlideStrings` 合并进 i18next，键路径保持 `tools.slide.*`。
 * 工具元数据（名称/描述）仍写在 `core/i18n/locales/*` 的 `toolsMeta` 中。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { slide: StringTree } };

const zh: ResourceTree = {
  tools: {
    slide: {
      docTitle: '演示文稿标题',
      titlePlaceholder: '未命名演示文稿',
      importHint: '拖入或选择 .pptx 文件导入幻灯片',
      unsupportedTip: '图表、SmartArt、公式等复杂对象将显示为占位框',
      newDoc: '新建文稿',
      importPptx: '导入 PPTX',
      exportPptx: '导出 PPTX',
      importing: '导入中…',
      exporting: '导出中…',
      present: '放映',
      exitPresent: '退出放映（Esc）',
      prevSlide: '上一页',
      nextSlide: '下一页',
      addSlide: '新建幻灯片',
      duplicate: '复制此页',
      deleteSlide: '删除此页',
      moveUp: '上移',
      moveDown: '下移',
      insertLabel: '插入',
      insertText: '文本框',
      insertImage: '图片',
      insertLine: '线条',
      insertTable: '表格',
      insertShape: '形状',
      shapeRect: '矩形',
      shapeRoundRect: '圆角矩形',
      shapeEllipse: '椭圆',
      shapeTriangle: '三角形',
      shapeStar: '星形',
      shapeArrow: '箭头',
      undo: '撤销',
      redo: '重做',
      zoomIn: '放大',
      zoomOut: '缩小',
      zoomFit: '适应窗口',
      bringForward: '上移一层',
      sendBackward: '下移一层',
      panelPage: '页面',
      panelElement: '元素',
      panelText: '文字',
      panelTheme: '主题与母版',
      axisX: 'X 坐标',
      axisY: 'Y 坐标',
      widthLabel: '宽度',
      heightLabel: '高度',
      rotation: '旋转角度',
      flipH: '水平翻转',
      flipV: '垂直翻转',
      fill: '填充色',
      fillNone: '无填充',
      stroke: '描边色',
      strokeWidth: '线宽',
      opacity: '不透明度',
      cornerRadius: '圆角',
      fontFamily: '字体',
      fontSize: '字号',
      bold: '加粗',
      italic: '斜体',
      underline: '下划线',
      strike: '删除线',
      color: '文字颜色',
      lineHeight: '行距',
      bullet: '项目符号',
      alignLeft: '左对齐',
      alignCenter: '居中对齐',
      alignRight: '右对齐',
      background: '页面背景',
      themeColor: '主题色',
      applyAll: '应用到全部页面',
      applyCurrent: '仅应用到当前页',
      restoreTheme: '还原默认',
      showPlaceholders: '显示母版占位符',
      canvasAria: '幻灯片画布',
      noSelection: '未选中元素',
      selected: '已选中 {{count}} 个元素',
      slidesLabel: '页数',
      downgraded: '{{count}} 个不支持元素已转为占位框',
      saved: '已保存到本地草稿',
      saving: '停止编辑后自动保存',
      err: {
        EMPTY: '演示文稿为空',
        NOT_PPTX: '仅支持 .pptx 文件',
        UNSUPPORTED_LEGACY_PPT: '暂不支持旧版 .ppt / .dps / .key 格式，请另存为 .pptx 后重试',
        TOO_LARGE: '文件超出 {{max}}MB 限制',
        IMPORT_FAILED: '演示文稿解析失败',
        EXPORT_FAILED: 'PPTX 导出失败',
        RENDER_FAILED: '画布渲染失败',
        RUNTIME_FAILED: '画布初始化失败，请刷新页面重试',
        IMAGE_DECODE_FAILED: '图片解码失败',
        UNSUPPORTED_MEDIA: '不支持的图片格式',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    slide: {
      docTitle: 'Presentation title',
      titlePlaceholder: 'Untitled presentation',
      importHint: 'Drop or pick a .pptx file to import slides',
      unsupportedTip: 'Charts, SmartArt and equations are downgraded to placeholder frames',
      newDoc: 'New deck',
      importPptx: 'Import PPTX',
      exportPptx: 'Export PPTX',
      importing: 'Importing…',
      exporting: 'Exporting…',
      present: 'Present',
      exitPresent: 'Exit slideshow (Esc)',
      prevSlide: 'Previous slide',
      nextSlide: 'Next slide',
      addSlide: 'New slide',
      duplicate: 'Duplicate slide',
      deleteSlide: 'Delete slide',
      moveUp: 'Move up',
      moveDown: 'Move down',
      insertLabel: 'Insert',
      insertText: 'Text box',
      insertImage: 'Image',
      insertLine: 'Line',
      insertTable: 'Table',
      insertShape: 'Shape',
      shapeRect: 'Rectangle',
      shapeRoundRect: 'Rounded rectangle',
      shapeEllipse: 'Ellipse',
      shapeTriangle: 'Triangle',
      shapeStar: 'Star',
      shapeArrow: 'Arrow',
      undo: 'Undo',
      redo: 'Redo',
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out',
      zoomFit: 'Fit to window',
      bringForward: 'Bring forward',
      sendBackward: 'Send backward',
      panelPage: 'Slide',
      panelElement: 'Element',
      panelText: 'Text',
      panelTheme: 'Theme & master',
      axisX: 'X position',
      axisY: 'Y position',
      widthLabel: 'Width',
      heightLabel: 'Height',
      rotation: 'Rotation',
      flipH: 'Flip horizontal',
      flipV: 'Flip vertical',
      fill: 'Fill',
      fillNone: 'No fill',
      stroke: 'Stroke',
      strokeWidth: 'Stroke width',
      opacity: 'Opacity',
      cornerRadius: 'Corner radius',
      fontFamily: 'Font',
      fontSize: 'Size',
      bold: 'Bold',
      italic: 'Italic',
      underline: 'Underline',
      strike: 'Strikethrough',
      color: 'Text color',
      lineHeight: 'Line height',
      bullet: 'Bullets',
      alignLeft: 'Align left',
      alignCenter: 'Align center',
      alignRight: 'Align right',
      background: 'Slide background',
      themeColor: 'Theme color',
      applyAll: 'Apply to all slides',
      applyCurrent: 'Apply to this slide only',
      restoreTheme: 'Reset to default',
      showPlaceholders: 'Show master placeholders',
      canvasAria: 'Slide canvas',
      noSelection: 'No element selected',
      selected: '{{count}} elements selected',
      slidesLabel: 'Slides',
      downgraded: '{{count}} unsupported objects turned into placeholders',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop editing',
      err: {
        EMPTY: 'The presentation is empty',
        NOT_PPTX: 'Only .pptx files are supported',
        UNSUPPORTED_LEGACY_PPT:
          'Legacy .ppt / .dps / .key files are not supported, please save as .pptx',
        TOO_LARGE: 'File exceeds the {{max}}MB limit',
        IMPORT_FAILED: 'Failed to parse the presentation',
        EXPORT_FAILED: 'PPTX export failed',
        RENDER_FAILED: 'Canvas rendering failed',
        RUNTIME_FAILED: 'Canvas failed to initialize, please reload the page',
        IMAGE_DECODE_FAILED: 'Failed to decode the image',
        UNSUPPORTED_MEDIA: 'Unsupported image format',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    slide: {
      docTitle: '簡報標題',
      titlePlaceholder: '未命名簡報',
      importHint: '拖曳或選擇 .pptx 檔案匯入投影片',
      unsupportedTip: '圖表、SmartArt、方程式等複雜物件將顯示為預留位置',
      newDoc: '新增簡報',
      importPptx: '匯入 PPTX',
      exportPptx: '匯出 PPTX',
      importing: '匯入中…',
      exporting: '匯出中…',
      present: '放映',
      exitPresent: '結束放映（Esc）',
      prevSlide: '上一頁',
      nextSlide: '下一頁',
      addSlide: '新增投影片',
      duplicate: '複製此頁',
      deleteSlide: '刪除此頁',
      moveUp: '上移',
      moveDown: '下移',
      insertLabel: '插入',
      insertText: '文字方塊',
      insertImage: '圖片',
      insertLine: '線條',
      insertTable: '表格',
      insertShape: '形狀',
      shapeRect: '矩形',
      shapeRoundRect: '圓角矩形',
      shapeEllipse: '橢圓',
      shapeTriangle: '三角形',
      shapeStar: '星形',
      shapeArrow: '箭頭',
      undo: '復原',
      redo: '重做',
      zoomIn: '放大',
      zoomOut: '縮小',
      zoomFit: '符合視窗',
      bringForward: '上移一層',
      sendBackward: '下移一層',
      panelPage: '頁面',
      panelElement: '元素',
      panelText: '文字',
      panelTheme: '主題與母片',
      axisX: 'X 座標',
      axisY: 'Y 座標',
      widthLabel: '寬度',
      heightLabel: '高度',
      rotation: '旋轉角度',
      flipH: '水平翻轉',
      flipV: '垂直翻轉',
      fill: '填滿色彩',
      fillNone: '無填滿',
      stroke: '外框色彩',
      strokeWidth: '線條寬度',
      opacity: '不透明度',
      cornerRadius: '圓角',
      fontFamily: '字型',
      fontSize: '字級',
      bold: '粗體',
      italic: '斜體',
      underline: '底線',
      strike: '刪除線',
      color: '文字色彩',
      lineHeight: '行距',
      bullet: '項目符號',
      alignLeft: '靠左對齊',
      alignCenter: '置中對齊',
      alignRight: '靠右對齊',
      background: '頁面背景',
      themeColor: '主題色彩',
      applyAll: '套用至所有頁面',
      applyCurrent: '僅套用至本頁',
      restoreTheme: '還原預設',
      showPlaceholders: '顯示母片預留位置',
      canvasAria: '投影片畫布',
      noSelection: '未選取元素',
      selected: '已選取 {{count}} 個元素',
      slidesLabel: '頁數',
      downgraded: '{{count}} 個不支援物件已轉為預留位置',
      saved: '已儲存至本機草稿',
      saving: '停止編輯後自動儲存',
      err: {
        EMPTY: '簡報內容為空',
        NOT_PPTX: '僅支援 .pptx 檔案',
        UNSUPPORTED_LEGACY_PPT: '不支援舊版 .ppt / .dps / .key，請另存為 .pptx 後再試',
        TOO_LARGE: '檔案超過 {{max}}MB 限制',
        IMPORT_FAILED: '簡報解析失敗',
        EXPORT_FAILED: 'PPTX 匯出失敗',
        RENDER_FAILED: '畫布轉譯失敗',
        RUNTIME_FAILED: '畫布初始化失敗，請重新載入頁面',
        IMAGE_DECODE_FAILED: '圖片解碼失敗',
        UNSUPPORTED_MEDIA: '不支援的圖片格式',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    slide: {
      docTitle: 'プレゼンタイトル',
      titlePlaceholder: '無題のプレゼン',
      importHint: '.pptx ファイルをドロップまたは選択してスライドを読み込む',
      unsupportedTip: 'グラフ・SmartArt・数式などの複雑な図形はプレースホルダーとして表示されます',
      newDoc: '新規プレゼン',
      importPptx: 'PPTX を読み込み',
      exportPptx: 'PPTX を書き出し',
      importing: '読み込み中…',
      exporting: '書き出し中…',
      present: 'スライドショー',
      exitPresent: '終了（Esc）',
      prevSlide: '前のスライド',
      nextSlide: '次のスライド',
      addSlide: 'スライドを追加',
      duplicate: 'このスライドを複製',
      deleteSlide: 'このスライドを削除',
      moveUp: '上へ移動',
      moveDown: '下へ移動',
      insertLabel: '挿入',
      insertText: 'テキストボックス',
      insertImage: '画像',
      insertLine: '線',
      insertTable: '表',
      insertShape: '図形',
      shapeRect: '四角形',
      shapeRoundRect: '角丸四角形',
      shapeEllipse: '楕円',
      shapeTriangle: '三角形',
      shapeStar: '星',
      shapeArrow: '矢印',
      undo: '元に戻す',
      redo: 'やり直す',
      zoomIn: '拡大',
      zoomOut: '縮小',
      zoomFit: 'ウィンドウに合わせる',
      bringForward: '前面へ',
      sendBackward: '背面へ',
      panelPage: 'スライド',
      panelElement: '要素',
      panelText: '文字',
      panelTheme: 'テーマとマスター',
      axisX: 'X 座標',
      axisY: 'Y 座標',
      widthLabel: '幅',
      heightLabel: '高さ',
      rotation: '回転角度',
      flipH: '左右反転',
      flipV: '上下反転',
      fill: '塗りつぶし',
      fillNone: '塗りつぶしなし',
      stroke: '枠線',
      strokeWidth: '線の太さ',
      opacity: '不透明度',
      cornerRadius: '角の丸み',
      fontFamily: 'フォント',
      fontSize: '文字サイズ',
      bold: '太字',
      italic: '斜体',
      underline: '下線',
      strike: '取り消し線',
      color: '文字色',
      lineHeight: '行間',
      bullet: '箇条書き',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      background: 'スライドの背景',
      themeColor: 'テーマカラー',
      applyAll: 'すべてのスライドに適用',
      applyCurrent: '現在のスライドのみ適用',
      restoreTheme: '既定に戻す',
      showPlaceholders: 'マスターのプレースホルダーを表示',
      canvasAria: 'スライドキャンバス',
      noSelection: '要素が未選択です',
      selected: '{{count}} 個の要素を選択中',
      slidesLabel: 'スライド数',
      downgraded: '{{count}} 個の非対応オブジェクトをプレースホルダーに変換しました',
      saved: 'ローカル下書きに保存しました',
      saving: '編集を止めると自動保存します',
      err: {
        EMPTY: 'プレゼンテーションが空です',
        NOT_PPTX: '.pptx ファイルのみ対応しています',
        UNSUPPORTED_LEGACY_PPT:
          '旧形式の .ppt / .dps / .key には対応していません。.pptx で保存し直してください',
        TOO_LARGE: 'ファイルが {{max}}MB の上限を超えています',
        IMPORT_FAILED: 'プレゼンテーションの解析に失敗しました',
        EXPORT_FAILED: 'PPTX の書き出しに失敗しました',
        RENDER_FAILED: 'キャンバスの描画に失敗しました',
        RUNTIME_FAILED: 'キャンバスの初期化に失敗しました。ページを再読み込みしてください',
        IMAGE_DECODE_FAILED: '画像のデコードに失敗しました',
        UNSUPPORTED_MEDIA: '対応していない画像形式です',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    slide: {
      docTitle: 'Titre de la présentation',
      titlePlaceholder: 'Présentation sans titre',
      importHint: 'Déposez ou choisissez un fichier .pptx pour importer les diapositives',
      unsupportedTip:
        'Les graphiques, SmartArt et équations sont convertis en cadres réservés à du contenu',
      newDoc: 'Nouvelle présentation',
      importPptx: 'Importer PPTX',
      exportPptx: 'Exporter PPTX',
      importing: 'Import…',
      exporting: 'Export…',
      present: 'Diaporama',
      exitPresent: 'Quitter le diaporama (Échap)',
      prevSlide: 'Diapositive précédente',
      nextSlide: 'Diapositive suivante',
      addSlide: 'Nouvelle diapositive',
      duplicate: 'Dupliquer la diapositive',
      deleteSlide: 'Supprimer la diapositive',
      moveUp: 'Monter',
      moveDown: 'Descendre',
      insertLabel: 'Insérer',
      insertText: 'Zone de texte',
      insertImage: 'Image',
      insertLine: 'Ligne',
      insertTable: 'Tableau',
      insertShape: 'Forme',
      shapeRect: 'Rectangle',
      shapeRoundRect: 'Rectangle arrondi',
      shapeEllipse: 'Ellipse',
      shapeTriangle: 'Triangle',
      shapeStar: 'Étoile',
      shapeArrow: 'Flèche',
      undo: 'Annuler',
      redo: 'Rétablir',
      zoomIn: 'Zoom avant',
      zoomOut: 'Zoom arrière',
      zoomFit: 'Ajuster à la fenêtre',
      bringForward: 'Avancer',
      sendBackward: 'Reculer',
      panelPage: 'Diapositive',
      panelElement: 'Élément',
      panelText: 'Texte',
      panelTheme: 'Thème et masque',
      axisX: 'Position X',
      axisY: 'Position Y',
      widthLabel: 'Largeur',
      heightLabel: 'Hauteur',
      rotation: 'Rotation',
      flipH: 'Miroir horizontal',
      flipV: 'Miroir vertical',
      fill: 'Remplissage',
      fillNone: 'Sans remplissage',
      stroke: 'Contour',
      strokeWidth: 'Épaisseur du contour',
      opacity: 'Opacité',
      cornerRadius: 'Rayon des coins',
      fontFamily: 'Police',
      fontSize: 'Taille',
      bold: 'Gras',
      italic: 'Italique',
      underline: 'Souligné',
      strike: 'Barré',
      color: 'Couleur du texte',
      lineHeight: 'Interligne',
      bullet: 'Puces',
      alignLeft: 'Aligner à gauche',
      alignCenter: 'Centrer',
      alignRight: 'Aligner à droite',
      background: 'Fond de diapositive',
      themeColor: 'Couleur du thème',
      applyAll: 'Appliquer à toutes les diapositives',
      applyCurrent: 'Appliquer à cette diapositive',
      restoreTheme: 'Rétablir par défaut',
      showPlaceholders: 'Afficher les espaces réservés du masque',
      canvasAria: 'Canevas de diapositive',
      noSelection: 'Aucun élément sélectionné',
      selected: '{{count}} éléments sélectionnés',
      slidesLabel: 'Diapositives',
      downgraded: '{{count}} objets non pris en charge convertis en espaces réservés',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement automatique après la saisie',
      err: {
        EMPTY: 'La présentation est vide',
        NOT_PPTX: 'Seuls les fichiers .pptx sont pris en charge',
        UNSUPPORTED_LEGACY_PPT:
          'Les anciens formats .ppt / .dps / .key ne sont pas pris en charge, enregistrez en .pptx',
        TOO_LARGE: 'Le fichier dépasse la limite de {{max}} Mo',
        IMPORT_FAILED: "Échec de l'analyse de la présentation",
        EXPORT_FAILED: "Échec de l'export PPTX",
        RENDER_FAILED: 'Échec du rendu du canevas',
        RUNTIME_FAILED: "Échec de l'initialisation du canevas, rechargez la page",
        IMAGE_DECODE_FAILED: "Échec du décodage de l'image",
        UNSUPPORTED_MEDIA: "Format d'image non pris en charge",
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    slide: {
      docTitle: 'Präsentationstitel',
      titlePlaceholder: 'Unbenannte Präsentation',
      importHint: '.pptx-Datei hierher ziehen oder auswählen, um Folien zu importieren',
      unsupportedTip: 'Diagramme, SmartArt und Formeln werden zu Platzhalterrahmen vereinfacht',
      newDoc: 'Neue Präsentation',
      importPptx: 'PPTX importieren',
      exportPptx: 'PPTX exportieren',
      importing: 'Importiere…',
      exporting: 'Exportiere…',
      present: 'Präsentieren',
      exitPresent: 'Präsentation beenden (Esc)',
      prevSlide: 'Vorherige Folie',
      nextSlide: 'Nächste Folie',
      addSlide: 'Neue Folie',
      duplicate: 'Folie duplizieren',
      deleteSlide: 'Folie löschen',
      moveUp: 'Nach oben',
      moveDown: 'Nach unten',
      insertLabel: 'Einfügen',
      insertText: 'Textfeld',
      insertImage: 'Bild',
      insertLine: 'Linie',
      insertTable: 'Tabelle',
      insertShape: 'Form',
      shapeRect: 'Rechteck',
      shapeRoundRect: 'Abgerundetes Rechteck',
      shapeEllipse: 'Ellipse',
      shapeTriangle: 'Dreieck',
      shapeStar: 'Stern',
      shapeArrow: 'Pfeil',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      zoomIn: 'Vergrößern',
      zoomOut: 'Verkleinern',
      zoomFit: 'An Fenster anpassen',
      bringForward: 'Nach vorn',
      sendBackward: 'Nach hinten',
      panelPage: 'Folie',
      panelElement: 'Element',
      panelText: 'Text',
      panelTheme: 'Design und Master',
      axisX: 'X-Position',
      axisY: 'Y-Position',
      widthLabel: 'Breite',
      heightLabel: 'Höhe',
      rotation: 'Drehung',
      flipH: 'Horizontal spiegeln',
      flipV: 'Vertikal spiegeln',
      fill: 'Füllung',
      fillNone: 'Keine Füllung',
      stroke: 'Rahmen',
      strokeWidth: 'Rahmenbreite',
      opacity: 'Deckkraft',
      cornerRadius: 'Eckenradius',
      fontFamily: 'Schriftart',
      fontSize: 'Schriftgröße',
      bold: 'Fett',
      italic: 'Kursiv',
      underline: 'Unterstrichen',
      strike: 'Durchgestrichen',
      color: 'Textfarbe',
      lineHeight: 'Zeilenabstand',
      bullet: 'Aufzählungszeichen',
      alignLeft: 'Linksbündig',
      alignCenter: 'Zentriert',
      alignRight: 'Rechtsbündig',
      background: 'Folienhintergrund',
      themeColor: 'Designfarbe',
      applyAll: 'Auf alle Folien anwenden',
      applyCurrent: 'Nur auf diese Folie anwenden',
      restoreTheme: 'Auf Standard zurücksetzen',
      showPlaceholders: 'Master-Platzhalter anzeigen',
      canvasAria: 'Folienzeichenfläche',
      noSelection: 'Kein Element ausgewählt',
      selected: '{{count}} Elemente ausgewählt',
      slidesLabel: 'Folien',
      downgraded: '{{count}} nicht unterstützte Objekte wurden zu Platzhaltern',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Bearbeitung',
      err: {
        EMPTY: 'Die Präsentation ist leer',
        NOT_PPTX: 'Nur .pptx-Dateien werden unterstützt',
        UNSUPPORTED_LEGACY_PPT:
          'Alte .ppt- / .dps- / .key-Dateien werden nicht unterstützt, speichern Sie als .pptx',
        TOO_LARGE: 'Die Datei überschreitet das Limit von {{max}} MB',
        IMPORT_FAILED: 'Präsentation konnte nicht gelesen werden',
        EXPORT_FAILED: 'PPTX-Export fehlgeschlagen',
        RENDER_FAILED: 'Zeichenfläche konnte nicht gerendert werden',
        RUNTIME_FAILED: 'Zeichenfläche konnte nicht initialisiert werden, Seite neu laden',
        IMAGE_DECODE_FAILED: 'Bild konnte nicht dekodiert werden',
        UNSUPPORTED_MEDIA: 'Nicht unterstütztes Bildformat',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    slide: {
      docTitle: 'Titolo presentazione',
      titlePlaceholder: 'Presentazione senza titolo',
      importHint: 'Trascina o scegli un file .pptx per importare le diapositive',
      unsupportedTip: 'Grafici, SmartArt e formule vengono convertiti in cornici segnaposto',
      newDoc: 'Nuova presentazione',
      importPptx: 'Importa PPTX',
      exportPptx: 'Esporta PPTX',
      importing: 'Importazione…',
      exporting: 'Esportazione…',
      present: 'Presenta',
      exitPresent: 'Esci dalla presentazione (Esc)',
      prevSlide: 'Diapositiva precedente',
      nextSlide: 'Diapositiva successiva',
      addSlide: 'Nuova diapositiva',
      duplicate: 'Duplica diapositiva',
      deleteSlide: 'Elimina diapositiva',
      moveUp: 'Sposta su',
      moveDown: 'Sposta giù',
      insertLabel: 'Inserisci',
      insertText: 'Casella di testo',
      insertImage: 'Immagine',
      insertLine: 'Linea',
      insertTable: 'Tabella',
      insertShape: 'Forma',
      shapeRect: 'Rettangolo',
      shapeRoundRect: 'Rettangolo arrotondato',
      shapeEllipse: 'Ellisse',
      shapeTriangle: 'Triangolo',
      shapeStar: 'Stella',
      shapeArrow: 'Freccia',
      undo: 'Annulla',
      redo: 'Ripeti',
      zoomIn: 'Ingrandisci',
      zoomOut: 'Riduci',
      zoomFit: 'Adatta alla finestra',
      bringForward: 'Porta avanti',
      sendBackward: 'Porta indietro',
      panelPage: 'Diapositiva',
      panelElement: 'Elemento',
      panelText: 'Testo',
      panelTheme: 'Tema e master',
      axisX: 'Posizione X',
      axisY: 'Posizione Y',
      widthLabel: 'Larghezza',
      heightLabel: 'Altezza',
      rotation: 'Rotazione',
      flipH: 'Specchio orizzontale',
      flipV: 'Specchio verticale',
      fill: 'Riempimento',
      fillNone: 'Senza riempimento',
      stroke: 'Contorno',
      strokeWidth: 'Spessore contorno',
      opacity: 'Opacità',
      cornerRadius: 'Raggio angoli',
      fontFamily: 'Carattere',
      fontSize: 'Dimensione',
      bold: 'Grassetto',
      italic: 'Corsivo',
      underline: 'Sottolineato',
      strike: 'Barrato',
      color: 'Colore testo',
      lineHeight: 'Interlinea',
      bullet: 'Elenco puntato',
      alignLeft: 'Allinea a sinistra',
      alignCenter: 'Centra',
      alignRight: 'Allinea a destra',
      background: 'Sfondo diapositiva',
      themeColor: 'Colore del tema',
      applyAll: 'Applica a tutte le diapositive',
      applyCurrent: 'Applica solo a questa diapositiva',
      restoreTheme: 'Ripristina predefinito',
      showPlaceholders: 'Mostra segnaposto del master',
      canvasAria: 'Area di disegno diapositiva',
      noSelection: 'Nessun elemento selezionato',
      selected: '{{count}} elementi selezionati',
      slidesLabel: 'Diapositive',
      downgraded: '{{count}} oggetti non supportati convertiti in segnaposto',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la modifica',
      err: {
        EMPTY: 'La presentazione è vuota',
        NOT_PPTX: 'Sono supportati solo i file .pptx',
        UNSUPPORTED_LEGACY_PPT:
          'I formati .ppt / .dps / .key precedenti non sono supportati, salva come .pptx',
        TOO_LARGE: 'Il file supera il limite di {{max}} MB',
        IMPORT_FAILED: 'Analisi della presentazione non riuscita',
        EXPORT_FAILED: 'Esportazione PPTX non riuscita',
        RENDER_FAILED: 'Rendering dell’area di disegno non riuscito',
        RUNTIME_FAILED: 'Inizializzazione dell’area di disegno non riuscita, ricarica la pagina',
        IMAGE_DECODE_FAILED: 'Decodifica dell’immagine non riuscita',
        UNSUPPORTED_MEDIA: 'Formato immagine non supportato',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    slide: {
      docTitle: 'Título de la presentación',
      titlePlaceholder: 'Presentación sin título',
      importHint: 'Arrastra o elige un archivo .pptx para importar diapositivas',
      unsupportedTip: 'Gráficos, SmartArt y ecuaciones se convierten en marcos de marcador',
      newDoc: 'Nueva presentación',
      importPptx: 'Importar PPTX',
      exportPptx: 'Exportar PPTX',
      importing: 'Importando…',
      exporting: 'Exportando…',
      present: 'Presentar',
      exitPresent: 'Salir de la presentación (Esc)',
      prevSlide: 'Diapositiva anterior',
      nextSlide: 'Diapositiva siguiente',
      addSlide: 'Nueva diapositiva',
      duplicate: 'Duplicar diapositiva',
      deleteSlide: 'Eliminar diapositiva',
      moveUp: 'Subir',
      moveDown: 'Bajar',
      insertLabel: 'Insertar',
      insertText: 'Cuadro de texto',
      insertImage: 'Imagen',
      insertLine: 'Línea',
      insertTable: 'Tabla',
      insertShape: 'Forma',
      shapeRect: 'Rectángulo',
      shapeRoundRect: 'Rectángulo redondeado',
      shapeEllipse: 'Elipse',
      shapeTriangle: 'Triángulo',
      shapeStar: 'Estrella',
      shapeArrow: 'Flecha',
      undo: 'Deshacer',
      redo: 'Rehacer',
      zoomIn: 'Acercar',
      zoomOut: 'Alejar',
      zoomFit: 'Ajustar a la ventana',
      bringForward: 'Traer al frente',
      sendBackward: 'Enviar al fondo',
      panelPage: 'Diapositiva',
      panelElement: 'Elemento',
      panelText: 'Texto',
      panelTheme: 'Tema y patrón',
      axisX: 'Posición X',
      axisY: 'Posición Y',
      widthLabel: 'Ancho',
      heightLabel: 'Alto',
      rotation: 'Rotación',
      flipH: 'Voltear horizontal',
      flipV: 'Voltear vertical',
      fill: 'Relleno',
      fillNone: 'Sin relleno',
      stroke: 'Contorno',
      strokeWidth: 'Grosor del contorno',
      opacity: 'Opacidad',
      cornerRadius: 'Radio de esquina',
      fontFamily: 'Fuente',
      fontSize: 'Tamaño',
      bold: 'Negrita',
      italic: 'Cursiva',
      underline: 'Subrayado',
      strike: 'Tachado',
      color: 'Color del texto',
      lineHeight: 'Interlineado',
      bullet: 'Viñetas',
      alignLeft: 'Alinear a la izquierda',
      alignCenter: 'Centrar',
      alignRight: 'Alinear a la derecha',
      background: 'Fondo de diapositiva',
      themeColor: 'Color del tema',
      applyAll: 'Aplicar a todas las diapositivas',
      applyCurrent: 'Aplicar solo a esta diapositiva',
      restoreTheme: 'Restablecer predeterminado',
      showPlaceholders: 'Mostrar marcadores de posición del patrón',
      canvasAria: 'Lienzo de diapositiva',
      noSelection: 'Ningún elemento seleccionado',
      selected: '{{count}} elementos seleccionados',
      slidesLabel: 'Diapositivas',
      downgraded: '{{count}} objetos no compatibles convertidos en marcadores',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de editar',
      err: {
        EMPTY: 'La presentación está vacía',
        NOT_PPTX: 'Solo se admiten archivos .pptx',
        UNSUPPORTED_LEGACY_PPT:
          'Los formatos .ppt / .dps / .key anteriores no son compatibles, guarda como .pptx',
        TOO_LARGE: 'El archivo supera el límite de {{max}} MB',
        IMPORT_FAILED: 'No se pudo analizar la presentación',
        EXPORT_FAILED: 'La exportación a PPTX falló',
        RENDER_FAILED: 'Error al dibujar el lienzo',
        RUNTIME_FAILED: 'No se pudo inicializar el lienzo, recarga la página',
        IMAGE_DECODE_FAILED: 'No se pudo decodificar la imagen',
        UNSUPPORTED_MEDIA: 'Formato de imagen no compatible',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    slide: {
      docTitle: 'Título da apresentação',
      titlePlaceholder: 'Apresentação sem título',
      importHint: 'Arraste ou escolha um ficheiro .pptx para importar os diapositivos',
      unsupportedTip: 'Gráficos, SmartArt e equações são convertidos em molduras de reserva',
      newDoc: 'Nova apresentação',
      importPptx: 'Importar PPTX',
      exportPptx: 'Exportar PPTX',
      importing: 'A importar…',
      exporting: 'A exportar…',
      present: 'Apresentar',
      exitPresent: 'Sair da apresentação (Esc)',
      prevSlide: 'Diapositivo anterior',
      nextSlide: 'Diapositivo seguinte',
      addSlide: 'Novo diapositivo',
      duplicate: 'Duplicar diapositivo',
      deleteSlide: 'Eliminar diapositivo',
      moveUp: 'Mover para cima',
      moveDown: 'Mover para baixo',
      insertLabel: 'Inserir',
      insertText: 'Caixa de texto',
      insertImage: 'Imagem',
      insertLine: 'Linha',
      insertTable: 'Tabela',
      insertShape: 'Forma',
      shapeRect: 'Retângulo',
      shapeRoundRect: 'Retângulo arredondado',
      shapeEllipse: 'Elipse',
      shapeTriangle: 'Triângulo',
      shapeStar: 'Estrela',
      shapeArrow: 'Seta',
      undo: 'Anular',
      redo: 'Refazer',
      zoomIn: 'Ampliar',
      zoomOut: 'Reduzir',
      zoomFit: 'Ajustar à janela',
      bringForward: 'Trazer para a frente',
      sendBackward: 'Enviar para trás',
      panelPage: 'Diapositivo',
      panelElement: 'Elemento',
      panelText: 'Texto',
      panelTheme: 'Tema e modelo',
      axisX: 'Posição X',
      axisY: 'Posição Y',
      widthLabel: 'Largura',
      heightLabel: 'Altura',
      rotation: 'Rotação',
      flipH: 'Espelhar na horizontal',
      flipV: 'Espelhar na vertical',
      fill: 'Preenchimento',
      fillNone: 'Sem preenchimento',
      stroke: 'Contorno',
      strokeWidth: 'Espessura do contorno',
      opacity: 'Opacidade',
      cornerRadius: 'Raio dos cantos',
      fontFamily: 'Fonte',
      fontSize: 'Tamanho',
      bold: 'Negrito',
      italic: 'Itálico',
      underline: 'Sublinhado',
      strike: 'Rasurado',
      color: 'Cor do texto',
      lineHeight: 'Espaçamento entre linhas',
      bullet: 'Marcadores',
      alignLeft: 'Alinhar à esquerda',
      alignCenter: 'Centrar',
      alignRight: 'Alinhar à direita',
      background: 'Fundo do diapositivo',
      themeColor: 'Cor do tema',
      applyAll: 'Aplicar a todos os diapositivos',
      applyCurrent: 'Aplicar apenas a este diapositivo',
      restoreTheme: 'Restaurar predefinição',
      showPlaceholders: 'Mostrar marcadores do modelo',
      canvasAria: 'Tela do diapositivo',
      noSelection: 'Nenhum elemento selecionado',
      selected: '{{count}} elementos selecionados',
      slidesLabel: 'Diapositivos',
      downgraded: '{{count}} objetos não suportados convertidos em marcadores',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de editar',
      err: {
        EMPTY: 'A apresentação está vazia',
        NOT_PPTX: 'Apenas ficheiros .pptx são suportados',
        UNSUPPORTED_LEGACY_PPT:
          'Os formatos antigos .ppt / .dps / .key não são suportados, guarde como .pptx',
        TOO_LARGE: 'O ficheiro excede o limite de {{max}} MB',
        IMPORT_FAILED: 'Falha ao analisar a apresentação',
        EXPORT_FAILED: 'Falha ao exportar PPTX',
        RENDER_FAILED: 'Falha ao desenhar a tela',
        RUNTIME_FAILED: 'Falha ao inicializar a tela, recarregue a página',
        IMAGE_DECODE_FAILED: 'Falha ao descodificar a imagem',
        UNSUPPORTED_MEDIA: 'Formato de imagem não suportado',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const slideStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具被懒加载时调用，键路径 tools.slide.*） */
export function registerSlideStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(slideStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
