/**
 * 照片编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 *
 * 与 slide-editor / flowchart-editor 保持同一套约定（详见各自 strings.ts 头部说明）：
 * 单工具的近百条 UI 文案不进首屏语言包 `core/i18n/locales/*`，
 * 而是在工具被懒加载时由 `registerPhotoStrings` 合并进 i18next，键路径保持 `tools.photo.*`。
 * 工具元数据（名称/描述）仍写在 `core/i18n/locales/*` 的 `toolsMeta` 中。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { photo: StringTree } };

const zh: ResourceTree = {
  tools: {
    photo: {
      docTitle: '画布名称',
      present: '放映',
      exitPresent: '退出放映（Esc）',
      presentLoading: '正在生成放映画面…',
      presentFailed: '放映画面生成失败',
      titlePlaceholder: '未命名画布',
      newCanvas: '新建画布',
      importImage: '导入图片',
      importProject: '导入工程',
      exportImage: '导出图片',
      exportProject: '导出工程',
      clear: '清空',
      stats: '{{width}} × {{height}} px · 图层 {{count}}',
      saved: '已保存到本地草稿',
      saving: '停止编辑后自动保存',
      degraded: '草稿过大，仅保存结构（图层内容已清空）',
      hint: '所有编辑都在浏览器本地完成，图片不会上传；支持 PNG / JPEG / WEBP 导出与工程文件续编',
      openHint: '拖入或选择一张图片，将作为新图层打开',
      emptyHint: '还没有图层：先「导入图片」，或用右下角按钮新建空白 / 文字 / 形状图层',
      canvasAria: 'photo canvas',

      dialogNew: '新建画布',
      preset: '预设尺寸',
      widthLabel: '宽度',
      heightLabel: '高度',
      background: '画布背景',
      bgTransparent: '透明',
      bgWhite: '白色',
      bgBlack: '黑色',
      create: '创建',
      cancel: '取消',

      toolMove: '移动',
      toolRectSelect: '矩形选区',
      toolEllipseSelect: '椭圆选区',
      toolLasso: '套索',
      toolCrop: '裁剪',
      toolBrush: '画笔',
      toolEraser: '橡皮',
      toolEyedropper: '吸管',
      toolFill: '油漆桶',
      toolText: '文字',
      toolShape: '形状',
      toolHand: '抓手',

      color: '颜色',
      size: '笔刷大小',
      hardness: '硬度',
      opacity: '不透明度',
      feather: '羽化',
      shapeKind: '图形',
      applyCrop: '应用裁剪',
      cancelCrop: '取消裁剪',
      zoomIn: '放大',
      zoomOut: '缩小',
      zoomFit: '适应窗口',
      zoomActual: '100%',
      undo: '撤销',
      redo: '重做',
      deselect: '取消选区',
      canvasMenu: '画布右键菜单',
      canvasOps: '画布操作',
      selectionOps: '选区操作',
      ctxFill: '填充选区（前景色）',
      ctxClear: '清除选区内容',
      ctxLayerViaCopy: '通过拷贝新建图层',
      ctxInvert: '反选',
      ctxExportSelection: '导出选区为 PNG',
      ctxSelectAll: '全选',
      ctxPaste: '粘贴图层',
      foreground: '前景色',
      picked: '已吸取 {{color}}',
      pickTransparent: '该处是透明像素，前景色未改变',
      eyedropperHint: '在画布上点击即可吸取颜色（按住 Alt 可在任意工具下临时吸取）',

      tabLayers: '图层',
      tabProperty: '属性',
      tabAdjust: '调整',
      tabFilter: '滤镜',

      addRaster: '空白图层',
      addText: '文字图层',
      addShape: '形状图层',
      duplicate: '复制图层',
      delete: '删除图层',
      mergeDown: '向下合并',
      flatten: '合并可见',
      visible: '显示',
      hidden: '隐藏',
      lock: '锁定',
      unlock: '解锁',
      blend: '混合模式',
      rename: '重命名',
      layerMenu: '图层操作菜单',
      newLayer: '新建图层',
      layerOps: '图层操作',
      layerRaster: '图层 {{n}}',
      layerGroup: '编组 {{n}}',
      layerAdjust: '调整图层 {{n}}',
      layerSmart: '智能对象 {{n}}',
      kindGroup: '编组',
      kindAdjust: '调整',
      kindSmart: '智能',
      histOpen: '打开文档',
      histEdit: '编辑',
      histBrush: '画笔',
      histErase: '橡皮',
      histFill: '填充',
      histCrop: '裁剪',
      histResize: '画布尺寸',
      histAddLayer: '新建图层',
      histDeleteLayer: '删除图层',
      histDuplicate: '复制图层',
      histReorder: '调整顺序',
      histMerge: '合并图层',
      histFlatten: '拼合可见',
      histMove: '移动',
      histRename: '重命名',
      tabHistory: '历史',
      historyCurrent: '当前',
      historyClear: '清空历史',
      historyCount: '共 {{n}} 步',
      addGroup: '新建编组',
      groupFromLayer: '从图层新建编组',
      leaveGroup: '移出编组',
      ungroup: '解散编组',
      groupIsolate: '整体合成（组内先合并）',
      groupPassThrough: '穿透混合（组内独立混合）',
      collapse: '折叠',
      expand: '展开',
      histGroup: '编组',
      addAdjustment: '新建调整图层',
      psdExport: '导出 PSD',
      psdExporting: '正在导出…',
      psdHint: '导出为 PSD 后可在 Photoshop / Photopea 继续编辑图层',
      psdDone: '已导出 PSD',
      psdDegraded: '{{n}} 处（调整图层 / 智能对象 / 文字形状）已栅格化，导出后不可再改参数',
      toSmart: '转换为智能对象',
      rasterize: '栅格化',
      smartTitle: '智能对象',
      smartSource: '源像素 {{w}} × {{h}}：缩放 / 旋转不会重采样',
      adjustHint: '调整图层作用于其下方全部图层，参数随时可改',
      mask: '图层蒙版',
      maskRevealAll: '显示全部',
      maskHideAll: '隐藏全部',
      maskFromSelection: '从选区生成',
      maskRemove: '删除蒙版',
      maskEnable: '启用',
      maskInvert: '反相',
      maskDensity: '浓度',
      maskFeather: '羽化',
      maskEdit: '编辑蒙版',
      maskEditing: '正在编辑蒙版',
      maskHint: '蒙版用灰度控制显示范围：进入编辑后画笔涂白显示、橡皮涂黑隐藏',
      layerText: '文字 {{n}}',
      layerShape: '形状 {{n}}',
      copySuffix: ' 副本',
      textPlaceholder: '双击编辑文字',
      blendMode: {
        normal: '正常',
        multiply: '正片叠底',
        screen: '滤色',
        overlay: '叠加',
        darken: '变暗',
        lighten: '变亮',
        'color-dodge': '颜色减淡',
        difference: '差值',
        exclusion: '排除',
        hue: '色相',
        saturation: '饱和度',
        color: '颜色',
        luminosity: '明度',
      },
      shape: {
        rect: '矩形',
        roundRect: '圆角矩形',
        ellipse: '椭圆',
        line: '直线',
        arrow: '箭头',
        star: '星形',
      },
      up: '上移一层',
      down: '下移一层',
      noLayer: '暂无图层',

      posX: 'X 坐标',
      posY: 'Y 坐标',
      rotation: '旋转',
      flipH: '水平翻转',
      flipV: '垂直翻转',
      fontSize: '字号',
      fontFamily: '字体',
      bold: '加粗',
      italic: '斜体',
      underline: '下划线',
      alignLeft: '左对齐',
      alignCenter: '居中',
      alignRight: '右对齐',
      fill: '填充色',
      stroke: '描边色',
      strokeWidth: '描边宽度',
      cornerRadius: '圆角',
      textContent: '文字内容',

      brightness: '亮度',
      contrast: '对比度',
      saturation: '饱和度',
      hue: '色相',
      temperature: '色温',
      exposure: '曝光',
      sharpen: '锐化',
      resetAdjust: '还原调整',

      filterGrayscale: '灰度',
      filterSepia: '复古',
      filterInvert: '反相',
      filterBlur: '模糊',
      filterSharpen: '锐化',
      filterEmboss: '浮雕',
      filterEdge: '边缘',
      filterNoise: '噪点',
      filterPixelate: '像素化',
      filterPosterize: '色调分离',
      hintGrayscale: '去掉全部色彩，转为黑白',
      hintSepia: '棕褐色调，模拟老照片',
      hintInvert: '颜色取反，生成负片',
      hintBlur: '高斯柔化，弱化细节',
      hintSharpen: '增强边缘对比，画面更清晰',
      hintEmboss: '突出轮廓，形成立体压印感',
      hintEdge: '只保留轮廓线条',
      hintNoise: '叠加颗粒，模拟胶片质感',
      hintPixelate: '马赛克化，隐藏细节',
      hintPosterize: '压缩色阶，形成色块',

      statusZoom: '缩放 {{scale}}%',
      statusCursor: '光标 {{x}}, {{y}}',
      statusSelection: '选区 {{width}} × {{height}}',
      statusMemory: '占用约 {{size}}',
      exportTitle: '导出图片',
      format: '格式',
      quality: '质量',
      qualityHint: '{{value}}%',
      exportSelectionOnly: '仅导出选区',
      download: '下载',

      err: {
        NOT_IMAGE: '请选择 PNG / JPEG / WEBP / GIF / BMP 图片',
        EMPTY: '文件为空',
        TOO_LARGE: '文件超出 {{max}}MB 限制',
        IMAGE_DECODE_FAILED: '图片解码失败',
        NOT_PROJECT: '这不是本工具的工程文件（.photo.json）',
        PARSE_FAILED: '工程文件解析失败',
        UNSUPPORTED_VERSION: '工程文件版本过高，请更新后重试',
        INVALID_SIZE: '画布尺寸需在 {{min}} – {{max}} 之间',
        RUNTIME_FAILED: '画布初始化失败，请刷新页面重试',
        EXPORT_FAILED: '图片导出失败',
        PSD_FAILED: 'PSD 导出失败',
        MERGE_FAILED: '只有位图图层可以向下合并',
        NO_LAYER: '请先选中一个图层',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    photo: {
      docTitle: 'Canvas name',
      present: 'Present',
      exitPresent: 'Exit (Esc)',
      presentLoading: 'Preparing the slideshow…',
      presentFailed: 'Failed to build the slideshow',
      titlePlaceholder: 'Untitled canvas',
      newCanvas: 'New canvas',
      importImage: 'Import image',
      importProject: 'Open project',
      exportImage: 'Export image',
      exportProject: 'Save project',
      clear: 'Clear',
      stats: '{{width}} × {{height}} px · {{count}} layers',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop editing',
      degraded: 'Draft too large: structure only, layer pixels were dropped',
      hint: 'Everything runs locally in your browser; export PNG / JPEG / WEBP or save a project to keep editing',
      openHint: 'Drop or pick an image to open it as a new layer',
      emptyHint: 'No layers yet: import an image, or add a blank / text / shape layer',
      canvasAria: 'photo canvas',

      dialogNew: 'New canvas',
      preset: 'Preset',
      widthLabel: 'Width',
      heightLabel: 'Height',
      background: 'Background',
      bgTransparent: 'Transparent',
      bgWhite: 'White',
      bgBlack: 'Black',
      create: 'Create',
      cancel: 'Cancel',

      toolMove: 'Move',
      toolRectSelect: 'Rect select',
      toolEllipseSelect: 'Ellipse select',
      toolLasso: 'Lasso',
      toolCrop: 'Crop',
      toolBrush: 'Brush',
      toolEraser: 'Eraser',
      toolEyedropper: 'Eyedropper',
      toolFill: 'Bucket',
      toolText: 'Text',
      toolShape: 'Shape',
      toolHand: 'Hand',

      color: 'Color',
      size: 'Brush size',
      hardness: 'Hardness',
      opacity: 'Opacity',
      feather: 'Feather',
      shapeKind: 'Shape',
      applyCrop: 'Apply crop',
      cancelCrop: 'Cancel crop',
      zoomIn: 'Zoom in',
      zoomOut: 'Zoom out',
      zoomFit: 'Fit to window',
      zoomActual: '100%',
      undo: 'Undo',
      redo: 'Redo',
      deselect: 'Deselect',
      canvasMenu: 'Canvas context menu',
      canvasOps: 'Canvas',
      selectionOps: 'Selection',
      ctxFill: 'Fill selection (foreground)',
      ctxClear: 'Clear selection content',
      ctxLayerViaCopy: 'Layer via copy',
      ctxInvert: 'Invert selection',
      ctxExportSelection: 'Export selection as PNG',
      ctxSelectAll: 'Select all',
      ctxPaste: 'Paste layer',
      foreground: 'Foreground',
      picked: 'Picked {{color}}',
      pickTransparent: 'That pixel is transparent; foreground colour unchanged',
      eyedropperHint: 'Click the canvas to pick a colour (hold Alt to sample with any tool)',

      tabLayers: 'Layers',
      tabProperty: 'Properties',
      tabAdjust: 'Adjust',
      tabFilter: 'Filters',

      addRaster: 'Blank layer',
      addText: 'Text layer',
      addShape: 'Shape layer',
      duplicate: 'Duplicate',
      delete: 'Delete',
      mergeDown: 'Merge down',
      flatten: 'Flatten visible',
      visible: 'Show',
      hidden: 'Hide',
      lock: 'Lock',
      unlock: 'Unlock',
      blend: 'Blend mode',
      rename: 'Rename',
      layerMenu: 'Layer actions',
      newLayer: 'New layer',
      layerOps: 'Layer actions',
      layerRaster: 'Layer {{n}}',
      layerGroup: 'Group {{n}}',
      layerAdjust: 'Adjustment {{n}}',
      layerSmart: 'Smart Object {{n}}',
      kindGroup: 'Group',
      kindAdjust: 'Adjust',
      kindSmart: 'Smart',
      histOpen: 'Open document',
      histEdit: 'Edit',
      histBrush: 'Brush',
      histErase: 'Eraser',
      histFill: 'Fill',
      histCrop: 'Crop',
      histResize: 'Canvas size',
      histAddLayer: 'New layer',
      histDeleteLayer: 'Delete layer',
      histDuplicate: 'Duplicate layer',
      histReorder: 'Reorder',
      histMerge: 'Merge layers',
      histFlatten: 'Flatten visible',
      histMove: 'Move',
      histRename: 'Rename',
      tabHistory: 'History',
      historyCurrent: 'current',
      historyClear: 'Clear history',
      historyCount: '{{n}} steps',
      addGroup: 'New group',
      groupFromLayer: 'Group from layer',
      leaveGroup: 'Move out of group',
      ungroup: 'Ungroup',
      groupIsolate: 'Isolate (merge group first)',
      groupPassThrough: 'Pass-through (blend individually)',
      collapse: 'Collapse',
      expand: 'Expand',
      histGroup: 'Group',
      addAdjustment: 'New adjustment layer',
      psdExport: 'Export PSD',
      psdExporting: 'Exporting…',
      psdHint: 'Export as PSD to keep editing layers in Photoshop / Photopea',
      psdDone: 'PSD exported',
      psdDegraded:
        '{{n}} item(s) (adjustments, smart objects, text/shapes) were rasterized and can no longer be re-parameterized',
      toSmart: 'Convert to smart object',
      rasterize: 'Rasterize',
      smartTitle: 'Smart object',
      smartSource: 'Source {{w}} × {{h}}: scaling or rotating does not resample',
      adjustHint: 'An adjustment layer affects everything below it and stays editable',
      mask: 'Layer mask',
      maskRevealAll: 'Reveal all',
      maskHideAll: 'Hide all',
      maskFromSelection: 'From selection',
      maskRemove: 'Delete mask',
      maskEnable: 'Enable',
      maskInvert: 'Invert',
      maskDensity: 'Density',
      maskFeather: 'Feather',
      maskEdit: 'Edit mask',
      maskEditing: 'Editing mask',
      maskHint:
        'A mask controls visibility by grayscale: while editing, brush paints white to reveal and eraser paints black to hide',
      layerText: 'Text {{n}}',
      layerShape: 'Shape {{n}}',
      copySuffix: ' copy',
      textPlaceholder: 'Double-click to edit text',
      blendMode: {
        normal: 'Normal',
        multiply: 'Multiply',
        screen: 'Screen',
        overlay: 'Overlay',
        darken: 'Darken',
        lighten: 'Lighten',
        'color-dodge': 'Color dodge',
        difference: 'Difference',
        exclusion: 'Exclusion',
        hue: 'Hue',
        saturation: 'Saturation',
        color: 'Color',
        luminosity: 'Luminosity',
      },
      shape: {
        rect: 'Rectangle',
        roundRect: 'Rounded rectangle',
        ellipse: 'Ellipse',
        line: 'Line',
        arrow: 'Arrow',
        star: 'Star',
      },
      up: 'Move up',
      down: 'Move down',
      noLayer: 'No layers',

      posX: 'X position',
      posY: 'Y position',
      rotation: 'Rotation',
      flipH: 'Flip horizontal',
      flipV: 'Flip vertical',
      fontSize: 'Font size',
      fontFamily: 'Font',
      bold: 'Bold',
      italic: 'Italic',
      underline: 'Underline',
      alignLeft: 'Align left',
      alignCenter: 'Align center',
      alignRight: 'Align right',
      fill: 'Fill',
      stroke: 'Stroke',
      strokeWidth: 'Stroke width',
      cornerRadius: 'Corner radius',
      textContent: 'Text',

      brightness: 'Brightness',
      contrast: 'Contrast',
      saturation: 'Saturation',
      hue: 'Hue',
      temperature: 'Temperature',
      exposure: 'Exposure',
      sharpen: 'Sharpen',
      resetAdjust: 'Reset adjustments',

      filterGrayscale: 'Grayscale',
      filterSepia: 'Sepia',
      filterInvert: 'Invert',
      filterBlur: 'Blur',
      filterSharpen: 'Sharpen',
      filterEmboss: 'Emboss',
      filterEdge: 'Edges',
      filterNoise: 'Noise',
      filterPixelate: 'Pixelate',
      filterPosterize: 'Posterize',
      hintGrayscale: 'Remove all colour and turn the photo black & white',
      hintSepia: 'Warm brown tone, like an old photograph',
      hintInvert: 'Invert colours to produce a negative',
      hintBlur: 'Soften the image and hide fine detail',
      hintSharpen: 'Boost edge contrast for a crisper look',
      hintEmboss: 'Emphasise contours for a stamped relief',
      hintEdge: 'Keep outlines only',
      hintNoise: 'Add film-like grain',
      hintPixelate: 'Mosaic blocks that hide detail',
      hintPosterize: 'Reduce tones to flat colour blocks',

      statusZoom: 'Zoom {{scale}}%',
      statusCursor: 'Cursor {{x}}, {{y}}',
      statusSelection: 'Selection {{width}} × {{height}}',
      statusMemory: 'About {{size}} in use',
      exportTitle: 'Export image',
      format: 'Format',
      quality: 'Quality',
      qualityHint: '{{value}}%',
      exportSelectionOnly: 'Selection only',
      download: 'Download',

      err: {
        NOT_IMAGE: 'Pick a PNG / JPEG / WEBP / GIF / BMP image',
        EMPTY: 'The file is empty',
        TOO_LARGE: 'File exceeds the {{max}}MB limit',
        IMAGE_DECODE_FAILED: 'Failed to decode the image',
        NOT_PROJECT: 'This is not a photo editor project (.photo.json)',
        PARSE_FAILED: 'Failed to parse the project file',
        UNSUPPORTED_VERSION: 'Project version is too new, please update the app',
        INVALID_SIZE: 'Canvas size must be between {{min}} and {{max}}',
        RUNTIME_FAILED: 'Canvas failed to initialize, please reload the page',
        EXPORT_FAILED: 'Image export failed',
        PSD_FAILED: 'PSD export failed',
        MERGE_FAILED: 'Only raster layers can be merged down',
        NO_LAYER: 'Select a layer first',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    photo: {
      docTitle: '畫布名稱',
      present: '放映',
      exitPresent: '結束放映（Esc）',
      presentLoading: '正在產生放映畫面…',
      presentFailed: '放映畫面產生失敗',
      titlePlaceholder: '未命名畫布',
      newCanvas: '新增畫布',
      importImage: '匯入圖片',
      importProject: '開啟專案',
      exportImage: '匯出圖片',
      exportProject: '儲存專案',
      clear: '清空',
      stats: '{{width}} × {{height}} px · 圖層 {{count}}',
      saved: '已儲存至本機草稿',
      saving: '停止編輯後自動儲存',
      degraded: '草稿過大，僅儲存結構（圖層內容已清空）',
      hint: '所有編輯都在瀏覽器本機完成，圖片不會上傳；可匯出 PNG / JPEG / WEBP 或儲存專案續編',
      openHint: '拖曳或選擇一張圖片，將作為新圖層開啟',
      emptyHint: '還沒有圖層：先「匯入圖片」，或用右下角按鈕新增空白 / 文字 / 形狀圖層',
      canvasAria: 'photo canvas',

      dialogNew: '新增畫布',
      preset: '預設尺寸',
      widthLabel: '寬度',
      heightLabel: '高度',
      background: '畫布背景',
      bgTransparent: '透明',
      bgWhite: '白色',
      bgBlack: '黑色',
      create: '建立',
      cancel: '取消',

      toolMove: '移動',
      toolRectSelect: '矩形選取',
      toolEllipseSelect: '橢圓選取',
      toolLasso: '套索',
      toolCrop: '裁剪',
      toolBrush: '畫筆',
      toolEraser: '橡皮擦',
      toolEyedropper: '滴管',
      toolFill: '油漆桶',
      toolText: '文字',
      toolShape: '形狀',
      toolHand: '抓手',

      color: '顏色',
      size: '筆刷大小',
      hardness: '硬度',
      opacity: '不透明度',
      feather: '羽化',
      shapeKind: '圖形',
      applyCrop: '套用裁剪',
      cancelCrop: '取消裁剪',
      zoomIn: '放大',
      zoomOut: '縮小',
      zoomFit: '符合視窗',
      zoomActual: '100%',
      undo: '復原',
      redo: '重做',
      deselect: '取消選取',
      canvasMenu: '畫布右鍵選單',
      canvasOps: '畫布操作',
      selectionOps: '選取範圍操作',
      ctxFill: '填滿選取範圍（前景色）',
      ctxClear: '清除選取內容',
      ctxLayerViaCopy: '透過拷貝新增圖層',
      ctxInvert: '反選',
      ctxExportSelection: '匯出選取範圍為 PNG',
      ctxSelectAll: '全選',
      ctxPaste: '貼上圖層',
      foreground: '前景色',
      picked: '已吸取 {{color}}',
      pickTransparent: '該處是透明像素，前景色未改變',
      eyedropperHint: '在畫布上點擊即可吸取顏色（按住 Alt 可在任意工具下臨時吸取）',

      tabLayers: '圖層',
      tabProperty: '屬性',
      tabAdjust: '調整',
      tabFilter: '濾鏡',

      addRaster: '空白圖層',
      addText: '文字圖層',
      addShape: '形狀圖層',
      duplicate: '複製圖層',
      delete: '刪除圖層',
      mergeDown: '向下合併',
      flatten: '合併可見',
      visible: '顯示',
      hidden: '隱藏',
      lock: '鎖定',
      unlock: '解鎖',
      blend: '混合模式',
      rename: '重新命名',
      layerMenu: '圖層操作選單',
      newLayer: '新增圖層',
      layerOps: '圖層操作',
      layerRaster: '圖層 {{n}}',
      layerGroup: '群組 {{n}}',
      layerAdjust: '調整圖層 {{n}}',
      layerSmart: '智慧物件 {{n}}',
      kindGroup: '群組',
      kindAdjust: '調整',
      kindSmart: '智慧',
      histOpen: '開啟文件',
      histEdit: '編輯',
      histBrush: '畫筆',
      histErase: '橡皮擦',
      histFill: '填色',
      histCrop: '裁剪',
      histResize: '畫布尺寸',
      histAddLayer: '新增圖層',
      histDeleteLayer: '刪除圖層',
      histDuplicate: '複製圖層',
      histReorder: '調整順序',
      histMerge: '合併圖層',
      histFlatten: '拼合可見',
      histMove: '移動',
      histRename: '重新命名',
      tabHistory: '歷史',
      historyCurrent: '目前',
      historyClear: '清除歷史',
      historyCount: '共 {{n}} 步',
      addGroup: '新增群組',
      groupFromLayer: '從圖層新增群組',
      leaveGroup: '移出群組',
      ungroup: '解散群組',
      groupIsolate: '整體合成（群組內先合併）',
      groupPassThrough: '穿透混合（群組內各自混合）',
      collapse: '摺疊',
      expand: '展開',
      histGroup: '群組',
      addAdjustment: '新增調整圖層',
      psdExport: '匯出 PSD',
      psdExporting: '正在匯出…',
      psdHint: '匯出為 PSD 後可在 Photoshop / Photopea 繼續編輯圖層',
      psdDone: '已匯出 PSD',
      psdDegraded: '{{n}} 處（調整圖層／智慧物件／文字形狀）已點陣化，匯出後無法再改參數',
      toSmart: '轉換為智慧物件',
      rasterize: '點陣化',
      smartTitle: '智慧物件',
      smartSource: '原始像素 {{w}} × {{h}}：縮放／旋轉不會重新取樣',
      adjustHint: '調整圖層作用於其下方所有圖層且隨時可改',
      mask: '圖層遮色片',
      maskRevealAll: '全部顯示',
      maskHideAll: '全部隱藏',
      maskFromSelection: '從選取範圍產生',
      maskRemove: '刪除遮色片',
      maskEnable: '啟用',
      maskInvert: '反相',
      maskDensity: '濃度',
      maskFeather: '羽化',
      maskEdit: '編輯遮色片',
      maskEditing: '正在編輯遮色片',
      maskHint: '遮色片以灰階控制顯示範圍：進入編輯後畫筆塗白顯示、橡皮擦塗黑隱藏',
      layerText: '文字 {{n}}',
      layerShape: '形狀 {{n}}',
      copySuffix: ' 副本',
      textPlaceholder: '按兩下編輯文字',
      blendMode: {
        normal: '正常',
        multiply: '正片疊底',
        screen: '濾色',
        overlay: '疊加',
        darken: '變暗',
        lighten: '變亮',
        'color-dodge': '顏色減淡',
        difference: '差值',
        exclusion: '排除',
        hue: '色相',
        saturation: '飽和度',
        color: '顏色',
        luminosity: '明度',
      },
      shape: {
        rect: '矩形',
        roundRect: '圓角矩形',
        ellipse: '橢圓',
        line: '直線',
        arrow: '箭頭',
        star: '星形',
      },
      up: '上移一層',
      down: '下移一層',
      noLayer: '暫無圖層',

      posX: 'X 座標',
      posY: 'Y 座標',
      rotation: '旋轉',
      flipH: '水平翻轉',
      flipV: '垂直翻轉',
      fontSize: '字級',
      fontFamily: '字型',
      bold: '粗體',
      italic: '斜體',
      underline: '底線',
      alignLeft: '靠左',
      alignCenter: '置中',
      alignRight: '靠右',
      fill: '填滿',
      stroke: '外框',
      strokeWidth: '外框寬度',
      cornerRadius: '圓角',
      textContent: '文字內容',

      brightness: '亮度',
      contrast: '對比',
      saturation: '飽和度',
      hue: '色相',
      temperature: '色溫',
      exposure: '曝光',
      sharpen: '銳化',
      resetAdjust: '還原調整',

      filterGrayscale: '灰階',
      filterSepia: '復古',
      filterInvert: '負片',
      filterBlur: '模糊',
      filterSharpen: '銳化',
      filterEmboss: '浮雕',
      filterEdge: '邊緣',
      filterNoise: '雜訊',
      filterPixelate: '像素化',
      filterPosterize: '色調分離',
      hintGrayscale: '移除全部色彩，轉為黑白',
      hintSepia: '棕褐色調，模擬老照片',
      hintInvert: '顏色反轉，產生負片',
      hintBlur: '柔化畫面，弱化細節',
      hintSharpen: '強化邊緣對比，畫面更清晰',
      hintEmboss: '凸顯輪廓，形成立體壓印感',
      hintEdge: '只保留輪廓線條',
      hintNoise: '疊加顆粒，模擬底片質感',
      hintPixelate: '馬賽克化，隱藏細節',
      hintPosterize: '壓縮色階，形成色塊',

      statusZoom: '縮放 {{scale}}%',
      statusCursor: '游標 {{x}}, {{y}}',
      statusSelection: '選取 {{width}} × {{height}}',
      statusMemory: '約佔用 {{size}}',
      exportTitle: '匯出圖片',
      format: '格式',
      quality: '品質',
      qualityHint: '{{value}}%',
      exportSelectionOnly: '僅匯出選取範圍',
      download: '下載',

      err: {
        NOT_IMAGE: '請選擇 PNG / JPEG / WEBP / GIF / BMP 圖片',
        EMPTY: '檔案是空的',
        TOO_LARGE: '檔案超過 {{max}}MB 限制',
        IMAGE_DECODE_FAILED: '圖片解碼失敗',
        NOT_PROJECT: '這不是照片編輯器的專案檔（.photo.json）',
        PARSE_FAILED: '專案檔解析失敗',
        UNSUPPORTED_VERSION: '專案檔版本過新，請更新後再試',
        INVALID_SIZE: '畫布尺寸需在 {{min}} – {{max}} 之間',
        RUNTIME_FAILED: '畫布初始化失敗，請重新載入頁面',
        EXPORT_FAILED: '圖片匯出失敗',
        PSD_FAILED: 'PSD 匯出失敗',
        MERGE_FAILED: '只有點陣圖層可以向下合併',
        NO_LAYER: '請先選取一個圖層',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    photo: {
      docTitle: 'キャンバス名',
      present: 'スライドショー',
      exitPresent: '終了（Esc）',
      presentLoading: '表示用の画像を生成中…',
      presentFailed: '表示用の画像の生成に失敗しました',
      titlePlaceholder: '無題のキャンバス',
      newCanvas: '新規キャンバス',
      importImage: '画像を読み込み',
      importProject: 'プロジェクトを開く',
      exportImage: '画像を書き出し',
      exportProject: 'プロジェクトを保存',
      clear: 'クリア',
      stats: '{{width}} × {{height}} px · レイヤー {{count}}',
      saved: 'ローカル下書きに保存しました',
      saving: '編集を止めると自動保存します',
      degraded: '下書きが大きすぎるため構造のみ保存（レイヤーの内容は空になります）',
      hint: 'すべてブラウザ内で処理され、画像はアップロードされません。PNG / JPEG / WEBP 書き出しとプロジェクト保存に対応',
      openHint: '画像をドロップまたは選択すると、新しいレイヤーとして開きます',
      emptyHint:
        'レイヤーがありません：画像を読み込むか、空白 / 文字 / 図形レイヤーを追加してください',
      canvasAria: 'photo canvas',

      dialogNew: '新規キャンバス',
      preset: 'プリセット',
      widthLabel: '幅',
      heightLabel: '高さ',
      background: '背景',
      bgTransparent: '透明',
      bgWhite: '白',
      bgBlack: '黒',
      create: '作成',
      cancel: 'キャンセル',

      toolMove: '移動',
      toolRectSelect: '長方形選択',
      toolEllipseSelect: '楕円選択',
      toolLasso: '投げ縄',
      toolCrop: 'トリミング',
      toolBrush: 'ブラシ',
      toolEraser: '消しゴム',
      toolEyedropper: 'スポイト',
      toolFill: 'バケツ',
      toolText: 'テキスト',
      toolShape: '図形',
      toolHand: 'ハンド',

      color: '色',
      size: 'ブラシサイズ',
      hardness: '硬さ',
      opacity: '不透明度',
      feather: 'ぼかし',
      shapeKind: '図形',
      applyCrop: 'トリミングを適用',
      cancelCrop: 'トリミングを中止',
      zoomIn: '拡大',
      zoomOut: '縮小',
      zoomFit: 'ウィンドウに合わせる',
      zoomActual: '100%',
      undo: '元に戻す',
      redo: 'やり直す',
      deselect: '選択解除',
      canvasMenu: 'キャンバスのコンテキストメニュー',
      canvasOps: 'キャンバス操作',
      selectionOps: '選択範囲の操作',
      ctxFill: '選択範囲を塗りつぶし（描画色）',
      ctxClear: '選択範囲を消去',
      ctxLayerViaCopy: 'コピーして新規レイヤー',
      ctxInvert: '選択範囲を反転',
      ctxExportSelection: '選択範囲を PNG で書き出し',
      ctxSelectAll: 'すべて選択',
      ctxPaste: 'レイヤーを貼り付け',
      foreground: '描画色',
      picked: '{{color}} を取得しました',
      pickTransparent: 'そのピクセルは透明です。描画色は変更していません',
      eyedropperHint: 'キャンバスをクリックして色を取得（Alt 押下で他のツール中でも取得できます）',

      tabLayers: 'レイヤー',
      tabProperty: 'プロパティ',
      tabAdjust: '調整',
      tabFilter: 'フィルター',

      addRaster: '空白レイヤー',
      addText: 'テキストレイヤー',
      addShape: '図形レイヤー',
      duplicate: '複製',
      delete: '削除',
      mergeDown: '下のレイヤーと結合',
      flatten: '表示レイヤーを結合',
      visible: '表示',
      hidden: '非表示',
      lock: 'ロック',
      unlock: 'ロック解除',
      blend: 'ブレンドモード',
      rename: '名前変更',
      layerMenu: 'レイヤーメニュー',
      newLayer: 'レイヤーを作成',
      layerOps: 'レイヤー操作',
      layerRaster: 'レイヤー {{n}}',
      layerGroup: 'グループ {{n}}',
      layerAdjust: '調整レイヤー {{n}}',
      layerSmart: 'スマートオブジェクト {{n}}',
      kindGroup: 'グループ',
      kindAdjust: '調整',
      kindSmart: 'スマート',
      histOpen: 'ドキュメントを開く',
      histEdit: '編集',
      histBrush: 'ブラシ',
      histErase: '消しゴム',
      histFill: '塗りつぶし',
      histCrop: 'トリミング',
      histResize: 'キャンバスサイズ',
      histAddLayer: 'レイヤーを新規作成',
      histDeleteLayer: 'レイヤーを削除',
      histDuplicate: 'レイヤーを複製',
      histReorder: '順序を変更',
      histMerge: 'レイヤーを結合',
      histFlatten: '表示レイヤーを統合',
      histMove: '移動',
      histRename: '名前を変更',
      tabHistory: '履歴',
      historyCurrent: '現在',
      historyClear: '履歴をクリア',
      historyCount: '{{n}} ステップ',
      addGroup: 'グループを新規作成',
      groupFromLayer: 'レイヤーからグループを作成',
      leaveGroup: 'グループから移動',
      ungroup: 'グループを解除',
      groupIsolate: 'グループを統合して合成',
      groupPassThrough: 'パススルー（個別に混合）',
      collapse: '折りたたむ',
      expand: '展開',
      histGroup: 'グループ',
      addAdjustment: '調整レイヤーを新規作成',
      psdExport: 'PSD を書き出し',
      psdExporting: '書き出し中…',
      psdHint: 'PSD で書き出すと Photoshop / Photopea でレイヤーを編集できます',
      psdDone: 'PSD を書き出しました',
      psdDegraded:
        '{{n}} 箇所（調整レイヤー／スマートオブジェクト／テキスト・シェイプ）はラスタライズされ、書き出し後はパラメーターを変更できません',
      toSmart: 'スマートオブジェクトに変換',
      rasterize: 'ラスタライズ',
      smartTitle: 'スマートオブジェクト',
      smartSource: '元画像 {{w}} × {{h}}：拡大縮小・回転でも再サンプリングしません',
      adjustHint: '調整レイヤーは下にあるすべてに作用し、後から変更できます',
      mask: 'レイヤーマスク',
      maskRevealAll: 'すべて表示',
      maskHideAll: 'すべて非表示',
      maskFromSelection: '選択範囲から作成',
      maskRemove: 'マスクを削除',
      maskEnable: '有効',
      maskInvert: '反転',
      maskDensity: '濃度',
      maskFeather: 'ぼかし',
      maskEdit: 'マスクを編集',
      maskEditing: 'マスク編集中',
      maskHint:
        'マスクはグレースケールで表示範囲を制御します。編集中はブラシで白（表示）、消しゴムで黒（非表示）を描きます',
      layerText: 'テキスト {{n}}',
      layerShape: '図形 {{n}}',
      copySuffix: ' のコピー',
      textPlaceholder: 'ダブルクリックでテキストを編集',
      blendMode: {
        normal: '通常',
        multiply: '乗算',
        screen: 'スクリーン',
        overlay: 'オーバーレイ',
        darken: '比較（暗）',
        lighten: '比較（明）',
        'color-dodge': '覆い焼きカラー',
        difference: '差の絶対値',
        exclusion: '除外',
        hue: '色相',
        saturation: '彩度',
        color: 'カラー',
        luminosity: '輝度',
      },
      shape: {
        rect: '四角形',
        roundRect: '角丸四角形',
        ellipse: '楕円',
        line: '直線',
        arrow: '矢印',
        star: '星',
      },
      up: '前面へ',
      down: '背面へ',
      noLayer: 'レイヤーなし',

      posX: 'X 座標',
      posY: 'Y 座標',
      rotation: '回転',
      flipH: '左右反転',
      flipV: '上下反転',
      fontSize: '文字サイズ',
      fontFamily: 'フォント',
      bold: '太字',
      italic: '斜体',
      underline: '下線',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      fill: '塗りつぶし',
      stroke: '枠線',
      strokeWidth: '枠線の太さ',
      cornerRadius: '角の丸み',
      textContent: 'テキスト',

      brightness: '明るさ',
      contrast: 'コントラスト',
      saturation: '彩度',
      hue: '色相',
      temperature: '色温度',
      exposure: '露出',
      sharpen: 'シャープ',
      resetAdjust: '調整をリセット',

      filterGrayscale: 'グレースケール',
      filterSepia: 'セピア',
      filterInvert: '反転',
      filterBlur: 'ぼかし',
      filterSharpen: 'シャープ',
      filterEmboss: 'エンボス',
      filterEdge: '輪郭',
      filterNoise: 'ノイズ',
      filterPixelate: 'モザイク',
      filterPosterize: 'ポスタリゼーション',
      hintGrayscale: '色をすべて除去し白黒にします',
      hintSepia: '古い写真のような褐色調にします',
      hintInvert: '色を反転してネガにします',
      hintBlur: '全体を柔らかくし細部を目立たなくします',
      hintSharpen: '輪郭のコントラストを強めて鮮明にします',
      hintEmboss: '輪郭を強調して立体感を出します',
      hintEdge: '輪郭線だけを残します',
      hintNoise: 'フィルムのような粒状感を加えます',
      hintPixelate: 'モザイク状にして細部を隠します',
      hintPosterize: '階調を減らして色のブロックにします',

      statusZoom: 'ズーム {{scale}}%',
      statusCursor: 'カーソル {{x}}, {{y}}',
      statusSelection: '選択 {{width}} × {{height}}',
      statusMemory: '使用量 約 {{size}}',
      exportTitle: '画像を書き出し',
      format: '形式',
      quality: '品質',
      qualityHint: '{{value}}%',
      exportSelectionOnly: '選択範囲のみ',
      download: 'ダウンロード',

      err: {
        NOT_IMAGE: 'PNG / JPEG / WEBP / GIF / BMP 画像を選んでください',
        EMPTY: 'ファイルが空です',
        TOO_LARGE: 'ファイルが {{max}}MB の上限を超えています',
        IMAGE_DECODE_FAILED: '画像のデコードに失敗しました',
        NOT_PROJECT: '写真エディターのプロジェクト（.photo.json）ではありません',
        PARSE_FAILED: 'プロジェクトの解析に失敗しました',
        UNSUPPORTED_VERSION: 'プロジェクトのバージョンが新しすぎます。アプリを更新してください',
        INVALID_SIZE: 'キャンバスサイズは {{min}} – {{max}} の範囲で指定してください',
        RUNTIME_FAILED: 'キャンバスの初期化に失敗しました。ページを再読み込みしてください',
        EXPORT_FAILED: '画像の書き出しに失敗しました',
        PSD_FAILED: 'PSD の書き出しに失敗しました',
        MERGE_FAILED: 'ラスターレイヤーだけを下のレイヤーと結合できます',
        NO_LAYER: '先にレイヤーを選択してください',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    photo: {
      docTitle: 'Nom du canevas',
      present: 'Présenter',
      exitPresent: 'Quitter (Échap)',
      presentLoading: 'Préparation du diaporama…',
      presentFailed: 'Échec de la préparation du diaporama',
      titlePlaceholder: 'Canevas sans titre',
      newCanvas: 'Nouveau canevas',
      importImage: 'Importer une image',
      importProject: 'Ouvrir un projet',
      exportImage: 'Exporter l’image',
      exportProject: 'Enregistrer le projet',
      clear: 'Vider',
      stats: '{{width}} × {{height}} px · {{count}} calques',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement automatique après la saisie',
      degraded:
        'Brouillon trop volumineux : structure seule, les pixels des calques ont été supprimés',
      hint: 'Tout se déroule localement dans le navigateur, aucune image n’est envoyée ; export PNG / JPEG / WEBP et projet rééditable',
      openHint: 'Déposez ou choisissez une image pour l’ouvrir comme nouveau calque',
      emptyHint: 'Aucun calque : importez une image, ou ajoutez un calque vide / texte / forme',
      canvasAria: 'photo canvas',

      dialogNew: 'Nouveau canevas',
      preset: 'Préréglage',
      widthLabel: 'Largeur',
      heightLabel: 'Hauteur',
      background: 'Fond',
      bgTransparent: 'Transparent',
      bgWhite: 'Blanc',
      bgBlack: 'Noir',
      create: 'Créer',
      cancel: 'Annuler',

      toolMove: 'Déplacer',
      toolRectSelect: 'Sélection rectangulaire',
      toolEllipseSelect: 'Sélection elliptique',
      toolLasso: 'Lasso',
      toolCrop: 'Recadrer',
      toolBrush: 'Pinceau',
      toolEraser: 'Gomme',
      toolEyedropper: 'Pipette',
      toolFill: 'Pot de peinture',
      toolText: 'Texte',
      toolShape: 'Forme',
      toolHand: 'Main',

      color: 'Couleur',
      size: 'Taille du pinceau',
      hardness: 'Dureté',
      opacity: 'Opacité',
      feather: 'Adoucissement',
      shapeKind: 'Forme',
      applyCrop: 'Appliquer le recadrage',
      cancelCrop: 'Annuler le recadrage',
      zoomIn: 'Zoom avant',
      zoomOut: 'Zoom arrière',
      zoomFit: 'Ajuster à la fenêtre',
      zoomActual: '100 %',
      undo: 'Annuler',
      redo: 'Rétablir',
      deselect: 'Désélectionner',
      canvasMenu: 'Menu contextuel du canevas',
      canvasOps: 'Canevas',
      selectionOps: 'Sélection',
      ctxFill: 'Remplir la sélection (couleur de premier plan)',
      ctxClear: 'Effacer le contenu de la sélection',
      ctxLayerViaCopy: 'Calque via copie',
      ctxInvert: 'Inverser la sélection',
      ctxExportSelection: 'Exporter la sélection en PNG',
      ctxSelectAll: 'Tout sélectionner',
      ctxPaste: 'Coller le calque',
      foreground: 'Premier plan',
      picked: '{{color}} prélevée',
      pickTransparent: 'Ce pixel est transparent ; la couleur de premier plan est inchangée',
      eyedropperHint:
        'Cliquez sur le canevas pour prélever une couleur (Alt pour prélever avec n’importe quel outil)',

      tabLayers: 'Calques',
      tabProperty: 'Propriétés',
      tabAdjust: 'Réglages',
      tabFilter: 'Filtres',

      addRaster: 'Calque vide',
      addText: 'Calque de texte',
      addShape: 'Calque de forme',
      duplicate: 'Dupliquer',
      delete: 'Supprimer',
      mergeDown: 'Fusionner vers le bas',
      flatten: 'Fusionner les calques visibles',
      visible: 'Afficher',
      hidden: 'Masquer',
      lock: 'Verrouiller',
      unlock: 'Déverrouiller',
      blend: 'Mode de fusion',
      rename: 'Renommer',
      layerMenu: 'Menu du calque',
      newLayer: 'Nouveau calque',
      layerOps: 'Actions du calque',
      layerRaster: 'Calque {{n}}',
      layerGroup: 'Groupe {{n}}',
      layerAdjust: 'Calque de réglage {{n}}',
      layerSmart: 'Objet dynamique {{n}}',
      kindGroup: 'Groupe',
      kindAdjust: 'Réglage',
      kindSmart: 'Dynamique',
      histOpen: 'Ouvrir le document',
      histEdit: 'Modifier',
      histBrush: 'Pinceau',
      histErase: 'Gomme',
      histFill: 'Remplir',
      histCrop: 'Recadrer',
      histResize: 'Taille de la toile',
      histAddLayer: 'Nouveau calque',
      histDeleteLayer: 'Supprimer le calque',
      histDuplicate: 'Dupliquer le calque',
      histReorder: 'Réorganiser',
      histMerge: 'Fusionner les calques',
      histFlatten: 'Aplatir les calques visibles',
      histMove: 'Déplacer',
      histRename: 'Renommer',
      tabHistory: 'Historique',
      historyCurrent: 'actuel',
      historyClear: 'Effacer l’historique',
      historyCount: '{{n}} étapes',
      addGroup: 'Nouveau groupe',
      groupFromLayer: 'Grouper depuis le calque',
      leaveGroup: 'Sortir du groupe',
      ungroup: 'Dissoudre le groupe',
      groupIsolate: 'Fusionner le groupe avant composition',
      groupPassThrough: 'Pass-through (mélange individuel)',
      collapse: 'Réduire',
      expand: 'Développer',
      histGroup: 'Groupe',
      addAdjustment: 'Nouveau calque de réglage',
      psdExport: 'Exporter en PSD',
      psdExporting: 'Export en cours…',
      psdHint: 'Le PSD reste modifiable dans Photoshop / Photopea',
      psdDone: 'PSD exporté',
      psdDegraded:
        '{{n}} élément(s) (réglages, objets dynamiques, textes/formes) ont été pixellisés',
      toSmart: 'Convertir en objet dynamique',
      rasterize: 'Pixelliser',
      smartTitle: 'Objet dynamique',
      smartSource: 'Source {{w}} × {{h}} : la mise à l’échelle ne rééchantillonne pas',
      adjustHint: 'Un calque de réglage affecte tout ce qui est en dessous et reste modifiable',
      mask: 'Masque de calque',
      maskRevealAll: 'Tout afficher',
      maskHideAll: 'Tout masquer',
      maskFromSelection: 'Depuis la sélection',
      maskRemove: 'Supprimer le masque',
      maskEnable: 'Activer',
      maskInvert: 'Inverser',
      maskDensity: 'Densité',
      maskFeather: 'Adoucir',
      maskEdit: 'Modifier le masque',
      maskEditing: 'Modification du masque',
      maskHint:
        'Le masque contrôle la visibilité en niveaux de gris : en édition, le pinceau peint en blanc pour afficher, la gomme en noir pour masquer',
      layerText: 'Texte {{n}}',
      layerShape: 'Forme {{n}}',
      copySuffix: ' copie',
      textPlaceholder: 'Double-cliquez pour modifier le texte',
      blendMode: {
        normal: 'Normal',
        multiply: 'Produit',
        screen: 'Écran',
        overlay: 'Incrustation',
        darken: 'Obscurcir',
        lighten: 'Éclaircir',
        'color-dodge': 'Densité couleur −',
        difference: 'Différence',
        exclusion: 'Exclusion',
        hue: 'Teinte',
        saturation: 'Saturation',
        color: 'Couleur',
        luminosity: 'Luminosité',
      },
      shape: {
        rect: 'Rectangle',
        roundRect: 'Rectangle arrondi',
        ellipse: 'Ellipse',
        line: 'Ligne',
        arrow: 'Flèche',
        star: 'Étoile',
      },
      up: 'Monter',
      down: 'Descendre',
      noLayer: 'Aucun calque',

      posX: 'Position X',
      posY: 'Position Y',
      rotation: 'Rotation',
      flipH: 'Miroir horizontal',
      flipV: 'Miroir vertical',
      fontSize: 'Taille de police',
      fontFamily: 'Police',
      bold: 'Gras',
      italic: 'Italique',
      underline: 'Souligné',
      alignLeft: 'Aligner à gauche',
      alignCenter: 'Centrer',
      alignRight: 'Aligner à droite',
      fill: 'Remplissage',
      stroke: 'Contour',
      strokeWidth: 'Épaisseur du contour',
      cornerRadius: 'Rayon des coins',
      textContent: 'Texte',

      brightness: 'Luminosité',
      contrast: 'Contraste',
      saturation: 'Saturation',
      hue: 'Teinte',
      temperature: 'Température',
      exposure: 'Exposition',
      sharpen: 'Netteté',
      resetAdjust: 'Réinitialiser les réglages',

      filterGrayscale: 'Niveaux de gris',
      filterSepia: 'Sépia',
      filterInvert: 'Inverser',
      filterBlur: 'Flou',
      filterSharpen: 'Netteté',
      filterEmboss: 'Relief',
      filterEdge: 'Contours',
      filterNoise: 'Grain',
      filterPixelate: 'Pixelliser',
      filterPosterize: 'Postériser',
      hintGrayscale: 'Supprime toutes les couleurs pour un rendu noir et blanc',
      hintSepia: 'Teinte brune chaude, comme une vieille photo',
      hintInvert: 'Inverse les couleurs pour un négatif',
      hintBlur: 'Adoucit l’image et atténue les détails',
      hintSharpen: 'Renforce le contraste des contours pour plus de netteté',
      hintEmboss: 'Met en relief les contours comme une empreinte',
      hintEdge: 'Ne conserve que les lignes de contour',
      hintNoise: 'Ajoute un grain semblable à une pellicule',
      hintPixelate: 'Mosaïque qui masque les détails',
      hintPosterize: 'Réduit les tons à des blocs de couleur',

      statusZoom: 'Zoom {{scale}} %',
      statusCursor: 'Curseur {{x}}, {{y}}',
      statusSelection: 'Sélection {{width}} × {{height}}',
      statusMemory: 'Environ {{size}} utilisés',
      exportTitle: 'Exporter l’image',
      format: 'Format',
      quality: 'Qualité',
      qualityHint: '{{value}} %',
      exportSelectionOnly: 'Sélection uniquement',
      download: 'Télécharger',

      err: {
        NOT_IMAGE: 'Choisissez une image PNG / JPEG / WEBP / GIF / BMP',
        EMPTY: 'Le fichier est vide',
        TOO_LARGE: 'Le fichier dépasse la limite de {{max}} Mo',
        IMAGE_DECODE_FAILED: 'Échec du décodage de l’image',
        NOT_PROJECT: 'Ce n’est pas un projet de l’éditeur photo (.photo.json)',
        PARSE_FAILED: 'Échec de l’analyse du projet',
        UNSUPPORTED_VERSION: 'Version de projet trop récente, veuillez mettre à jour',
        INVALID_SIZE: 'La taille du canevas doit être comprise entre {{min}} et {{max}}',
        RUNTIME_FAILED: 'Échec de l’initialisation du canevas, rechargez la page',
        EXPORT_FAILED: 'Échec de l’export de l’image',
        PSD_FAILED: 'Échec de l’export PSD',
        MERGE_FAILED: 'Seuls les calques matriciels peuvent être fusionnés vers le bas',
        NO_LAYER: 'Sélectionnez d’abord un calque',
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    photo: {
      docTitle: 'Leinwandname',
      present: 'Präsentieren',
      exitPresent: 'Beenden (Esc)',
      presentLoading: 'Präsentationsansicht wird erstellt…',
      presentFailed: 'Präsentationsansicht fehlgeschlagen',
      titlePlaceholder: 'Unbenannte Leinwand',
      newCanvas: 'Neue Leinwand',
      importImage: 'Bild importieren',
      importProject: 'Projekt öffnen',
      exportImage: 'Bild exportieren',
      exportProject: 'Projekt speichern',
      clear: 'Leeren',
      stats: '{{width}} × {{height}} px · {{count}} Ebenen',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Bearbeitung',
      degraded: 'Entwurf zu groß: nur Struktur gespeichert, Ebeneninhalte wurden verworfen',
      hint: 'Alles läuft lokal im Browser, keine Bilddaten werden hochgeladen; PNG / JPEG / WEBP Export und weiterbearbeitbare Projektdatei',
      openHint: 'Bild hierher ziehen oder auswählen, um es als neue Ebene zu öffnen',
      emptyHint:
        'Noch keine Ebenen: Bild importieren oder eine leere / Text- / Form-Ebene hinzufügen',
      canvasAria: 'photo canvas',

      dialogNew: 'Neue Leinwand',
      preset: 'Voreinstellung',
      widthLabel: 'Breite',
      heightLabel: 'Höhe',
      background: 'Hintergrund',
      bgTransparent: 'Transparent',
      bgWhite: 'Weiß',
      bgBlack: 'Schwarz',
      create: 'Erstellen',
      cancel: 'Abbrechen',

      toolMove: 'Verschieben',
      toolRectSelect: 'Rechteckige Auswahl',
      toolEllipseSelect: 'Elliptische Auswahl',
      toolLasso: 'Lasso',
      toolCrop: 'Zuschneiden',
      toolBrush: 'Pinsel',
      toolEraser: 'Radierer',
      toolEyedropper: 'Pipette',
      toolFill: 'Füllwerkzeug',
      toolText: 'Text',
      toolShape: 'Form',
      toolHand: 'Hand',

      color: 'Farbe',
      size: 'Pinselgröße',
      hardness: 'Härte',
      opacity: 'Deckkraft',
      feather: 'Weiche Kante',
      shapeKind: 'Form',
      applyCrop: 'Zuschneiden anwenden',
      cancelCrop: 'Zuschneiden abbrechen',
      zoomIn: 'Vergrößern',
      zoomOut: 'Verkleinern',
      zoomFit: 'An Fenster anpassen',
      zoomActual: '100 %',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      deselect: 'Auswahl aufheben',
      canvasMenu: 'Kontextmenü der Leinwand',
      canvasOps: 'Leinwand',
      selectionOps: 'Auswahl',
      ctxFill: 'Auswahl füllen (Vordergrundfarbe)',
      ctxClear: 'Auswahlinhalt löschen',
      ctxLayerViaCopy: 'Ebene über Kopie',
      ctxInvert: 'Auswahl umkehren',
      ctxExportSelection: 'Auswahl als PNG exportieren',
      ctxSelectAll: 'Alles auswählen',
      ctxPaste: 'Ebene einfügen',
      foreground: 'Vordergrundfarbe',
      picked: '{{color}} übernommen',
      pickTransparent: 'Dieser Pixel ist transparent; Vordergrundfarbe bleibt unverändert',
      eyedropperHint:
        'Auf die Leinwand klicken, um eine Farbe aufzunehmen (Alt zum Aufnehmen mit jedem Werkzeug)',

      tabLayers: 'Ebenen',
      tabProperty: 'Eigenschaften',
      tabAdjust: 'Anpassen',
      tabFilter: 'Filter',

      addRaster: 'Leere Ebene',
      addText: 'Textebene',
      addShape: 'Formebene',
      duplicate: 'Duplizieren',
      delete: 'Löschen',
      mergeDown: 'Nach unten vereinen',
      flatten: 'Sichtbare vereinen',
      visible: 'Anzeigen',
      hidden: 'Ausblenden',
      lock: 'Sperren',
      unlock: 'Entsperren',
      blend: 'Füllmodus',
      rename: 'Umbenennen',
      layerMenu: 'Ebenenmenü',
      newLayer: 'Neue Ebene',
      layerOps: 'Ebenenaktionen',
      layerRaster: 'Ebene {{n}}',
      layerGroup: 'Gruppe {{n}}',
      layerAdjust: 'Einstellungsebene {{n}}',
      layerSmart: 'Smartobjekt {{n}}',
      kindGroup: 'Gruppe',
      kindAdjust: 'Einstellung',
      kindSmart: 'Smart',
      histOpen: 'Dokument öffnen',
      histEdit: 'Bearbeiten',
      histBrush: 'Pinsel',
      histErase: 'Radierer',
      histFill: 'Füllen',
      histCrop: 'Zuschneiden',
      histResize: 'Leinwandgröße',
      histAddLayer: 'Neue Ebene',
      histDeleteLayer: 'Ebene löschen',
      histDuplicate: 'Ebene duplizieren',
      histReorder: 'Reihenfolge ändern',
      histMerge: 'Ebenen zusammenführen',
      histFlatten: 'Sichtbare reduzieren',
      histMove: 'Verschieben',
      histRename: 'Umbenennen',
      tabHistory: 'Verlauf',
      historyCurrent: 'aktuell',
      historyClear: 'Verlauf löschen',
      historyCount: '{{n}} Schritte',
      addGroup: 'Neue Gruppe',
      groupFromLayer: 'Gruppe aus Ebene',
      leaveGroup: 'Aus Gruppe verschieben',
      ungroup: 'Gruppe auflösen',
      groupIsolate: 'Als Ganzes zusammenführen',
      groupPassThrough: 'Pass-Through (einzeln mischen)',
      collapse: 'Einklappen',
      expand: 'Ausklappen',
      histGroup: 'Gruppe',
      addAdjustment: 'Neue Einstellungsebene',
      psdExport: 'Als PSD exportieren',
      psdExporting: 'Wird exportiert…',
      psdHint: 'PSD bleibt in Photoshop / Photopea weiterbearbeitbar',
      psdDone: 'PSD exportiert',
      psdDegraded: '{{n}} Element(e) (Einstellungen, Smartobjekte, Text/Formen) wurden gerastert',
      toSmart: 'In Smartobjekt umwandeln',
      rasterize: 'Rastern',
      smartTitle: 'Smartobjekt',
      smartSource: 'Quelle {{w}} × {{h}}: Skalieren und Drehen erfolgt ohne Neuabtastung',
      adjustHint: 'Eine Einstellungsebene wirkt auf alles Darunter und bleibt anpassbar',
      mask: 'Ebenenmaske',
      maskRevealAll: 'Alles anzeigen',
      maskHideAll: 'Alles ausblenden',
      maskFromSelection: 'Aus Auswahl',
      maskRemove: 'Maske löschen',
      maskEnable: 'Aktivieren',
      maskInvert: 'Umkehren',
      maskDensity: 'Dichte',
      maskFeather: 'Weichzeichnen',
      maskEdit: 'Maske bearbeiten',
      maskEditing: 'Maske wird bearbeitet',
      maskHint:
        'Eine Maske steuert die Sichtbarkeit über Graustufen: Beim Bearbeiten malt der Pinsel Weiß (zeigen), der Radierer Schwarz (verbergen)',
      layerText: 'Text {{n}}',
      layerShape: 'Form {{n}}',
      copySuffix: ' Kopie',
      textPlaceholder: 'Doppelklick zum Bearbeiten des Textes',
      blendMode: {
        normal: 'Normal',
        multiply: 'Multiplizieren',
        screen: 'Negativ multiplizieren',
        overlay: 'Ineinanderkopieren',
        darken: 'Abdunkeln',
        lighten: 'Aufhellen',
        'color-dodge': 'Farbig abwedeln',
        difference: 'Differenz',
        exclusion: 'Ausschluss',
        hue: 'Farbton',
        saturation: 'Sättigung',
        color: 'Farbe',
        luminosity: 'Luminanz',
      },
      shape: {
        rect: 'Rechteck',
        roundRect: 'Abgerundetes Rechteck',
        ellipse: 'Ellipse',
        line: 'Linie',
        arrow: 'Pfeil',
        star: 'Stern',
      },
      up: 'Nach oben',
      down: 'Nach unten',
      noLayer: 'Keine Ebenen',

      posX: 'X-Position',
      posY: 'Y-Position',
      rotation: 'Drehung',
      flipH: 'Horizontal spiegeln',
      flipV: 'Vertikal spiegeln',
      fontSize: 'Schriftgröße',
      fontFamily: 'Schriftart',
      bold: 'Fett',
      italic: 'Kursiv',
      underline: 'Unterstrichen',
      alignLeft: 'Linksbündig',
      alignCenter: 'Zentriert',
      alignRight: 'Rechtsbündig',
      fill: 'Füllung',
      stroke: 'Rahmen',
      strokeWidth: 'Rahmenbreite',
      cornerRadius: 'Eckenradius',
      textContent: 'Text',

      brightness: 'Helligkeit',
      contrast: 'Kontrast',
      saturation: 'Sättigung',
      hue: 'Farbton',
      temperature: 'Farbtemperatur',
      exposure: 'Belichtung',
      sharpen: 'Schärfen',
      resetAdjust: 'Anpassungen zurücksetzen',

      filterGrayscale: 'Graustufen',
      filterSepia: 'Sepia',
      filterInvert: 'Invertieren',
      filterBlur: 'Weichzeichnen',
      filterSharpen: 'Schärfen',
      filterEmboss: 'Relief',
      filterEdge: 'Konturen',
      filterNoise: 'Rauschen',
      filterPixelate: 'Pixeln',
      filterPosterize: 'Posterisieren',
      hintGrayscale: 'Alle Farben entfernen und in Schwarzweiß umwandeln',
      hintSepia: 'Warmer Braunton wie bei alten Fotos',
      hintInvert: 'Farben umkehren und ein Negativ erzeugen',
      hintBlur: 'Bild weichzeichnen und Details abschwächen',
      hintSharpen: 'Kantenkontrast erhöhen für ein klareres Bild',
      hintEmboss: 'Konturen hervorheben wie eine Prägung',
      hintEdge: 'Nur die Umrisslinien behalten',
      hintNoise: 'Filmähnliches Korn hinzufügen',
      hintPixelate: 'Mosaik, das Details verbirgt',
      hintPosterize: 'Tonwerte zu Farbflächen reduzieren',

      statusZoom: 'Zoom {{scale}} %',
      statusCursor: 'Cursor {{x}}, {{y}}',
      statusSelection: 'Auswahl {{width}} × {{height}}',
      statusMemory: 'Etwa {{size}} belegt',
      exportTitle: 'Bild exportieren',
      format: 'Format',
      quality: 'Qualität',
      qualityHint: '{{value}} %',
      exportSelectionOnly: 'Nur Auswahl',
      download: 'Herunterladen',

      err: {
        NOT_IMAGE: 'Bitte ein PNG / JPEG / WEBP / GIF / BMP Bild wählen',
        EMPTY: 'Die Datei ist leer',
        TOO_LARGE: 'Die Datei überschreitet das Limit von {{max}} MB',
        IMAGE_DECODE_FAILED: 'Bild konnte nicht dekodiert werden',
        NOT_PROJECT: 'Dies ist keine Projektdatei des Foto-Editors (.photo.json)',
        PARSE_FAILED: 'Projektdatei konnte nicht gelesen werden',
        UNSUPPORTED_VERSION: 'Projektversion zu neu, bitte aktualisieren',
        INVALID_SIZE: 'Die Leinwandgröße muss zwischen {{min}} und {{max}} liegen',
        RUNTIME_FAILED: 'Leinwand konnte nicht initialisiert werden, Seite neu laden',
        EXPORT_FAILED: 'Bildexport fehlgeschlagen',
        PSD_FAILED: 'PSD-Export fehlgeschlagen',
        MERGE_FAILED: 'Nur Rasterebenen können nach unten vereint werden',
        NO_LAYER: 'Bitte zuerst eine Ebene auswählen',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    photo: {
      docTitle: 'Nome della tela',
      present: 'Presenta',
      exitPresent: 'Esci (Esc)',
      presentLoading: 'Preparazione della presentazione…',
      presentFailed: 'Impossibile preparare la presentazione',
      titlePlaceholder: 'Tela senza titolo',
      newCanvas: 'Nuova tela',
      importImage: 'Importa immagine',
      importProject: 'Apri progetto',
      exportImage: 'Esporta immagine',
      exportProject: 'Salva progetto',
      clear: 'Svuota',
      stats: '{{width}} × {{height}} px · {{count}} livelli',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la modifica',
      degraded:
        'Bozza troppo grande: salvata solo la struttura, i pixel dei livelli sono stati rimossi',
      hint: 'Tutto avviene localmente nel browser, nessuna immagine viene caricata; esporta PNG / JPEG / WEBP o salva un progetto modificabile',
      openHint: 'Trascina o scegli un’immagine per aprirla come nuovo livello',
      emptyHint:
        'Nessun livello: importa un’immagine oppure aggiungi un livello vuoto / di testo / forma',
      canvasAria: 'photo canvas',

      dialogNew: 'Nuova tela',
      preset: 'Predefinito',
      widthLabel: 'Larghezza',
      heightLabel: 'Altezza',
      background: 'Sfondo',
      bgTransparent: 'Trasparente',
      bgWhite: 'Bianco',
      bgBlack: 'Nero',
      create: 'Crea',
      cancel: 'Annulla',

      toolMove: 'Sposta',
      toolRectSelect: 'Selezione rettangolare',
      toolEllipseSelect: 'Selezione ellittica',
      toolLasso: 'Lazo',
      toolCrop: 'Ritaglia',
      toolBrush: 'Pennello',
      toolEraser: 'Gomma',
      toolEyedropper: 'Contagocce',
      toolFill: 'Secchiello',
      toolText: 'Testo',
      toolShape: 'Forma',
      toolHand: 'Mano',

      color: 'Colore',
      size: 'Dimensione pennello',
      hardness: 'Durezza',
      opacity: 'Opacità',
      feather: 'Sfumatura',
      shapeKind: 'Forma',
      applyCrop: 'Applica ritaglio',
      cancelCrop: 'Annulla ritaglio',
      zoomIn: 'Ingrandisci',
      zoomOut: 'Riduci',
      zoomFit: 'Adatta alla finestra',
      zoomActual: '100%',
      undo: 'Annulla',
      redo: 'Ripeti',
      deselect: 'Deseleziona',
      canvasMenu: 'Menu contestuale della tela',
      canvasOps: 'Tela',
      selectionOps: 'Selezione',
      ctxFill: 'Riempi selezione (colore primo piano)',
      ctxClear: 'Cancella contenuto selezione',
      ctxLayerViaCopy: 'Livello tramite copia',
      ctxInvert: 'Inverti selezione',
      ctxExportSelection: 'Esporta selezione in PNG',
      ctxSelectAll: 'Seleziona tutto',
      ctxPaste: 'Incolla livello',
      foreground: 'Colore primo piano',
      picked: '{{color}} acquisito',
      pickTransparent: 'Quel pixel è trasparente: colore di primo piano invariato',
      eyedropperHint:
        'Fai clic sulla tela per prelevare un colore (tieni Alt per prelevare con qualsiasi strumento)',

      tabLayers: 'Livelli',
      tabProperty: 'Proprietà',
      tabAdjust: 'Regolazioni',
      tabFilter: 'Filtri',

      addRaster: 'Livello vuoto',
      addText: 'Livello di testo',
      addShape: 'Livello forma',
      duplicate: 'Duplica',
      delete: 'Elimina',
      mergeDown: 'Unisci verso il basso',
      flatten: 'Unisci visibili',
      visible: 'Mostra',
      hidden: 'Nascondi',
      lock: 'Blocca',
      unlock: 'Sblocca',
      blend: 'Modalità di fusione',
      rename: 'Rinomina',
      layerMenu: 'Menu livello',
      newLayer: 'Nuovo livello',
      layerOps: 'Azioni livello',
      layerRaster: 'Livello {{n}}',
      layerGroup: 'Gruppo {{n}}',
      layerAdjust: 'Livello di regolazione {{n}}',
      layerSmart: 'Oggetto avanzato {{n}}',
      kindGroup: 'Gruppo',
      kindAdjust: 'Regolazione',
      kindSmart: 'Smart',
      histOpen: 'Apri documento',
      histEdit: 'Modifica',
      histBrush: 'Pennello',
      histErase: 'Gomma',
      histFill: 'Riempi',
      histCrop: 'Ritaglia',
      histResize: 'Dimensione tela',
      histAddLayer: 'Nuovo livello',
      histDeleteLayer: 'Elimina livello',
      histDuplicate: 'Duplica livello',
      histReorder: 'Riordina',
      histMerge: 'Unisci livelli',
      histFlatten: 'Appiattisci visibili',
      histMove: 'Sposta',
      histRename: 'Rinomina',
      tabHistory: 'Cronologia',
      historyCurrent: 'corrente',
      historyClear: 'Cancella cronologia',
      historyCount: '{{n}} passi',
      addGroup: 'Nuovo gruppo',
      groupFromLayer: 'Raggruppa dal livello',
      leaveGroup: 'Esci dal gruppo',
      ungroup: 'Separa gruppo',
      groupIsolate: 'Unisci il gruppo prima di comporre',
      groupPassThrough: 'Pass-through (mescola singolarmente)',
      collapse: 'Comprimi',
      expand: 'Espandi',
      histGroup: 'Gruppo',
      addAdjustment: 'Nuovo livello di regolazione',
      psdExport: 'Esporta PSD',
      psdExporting: 'Esportazione…',
      psdHint: 'Il PSD resta modificabile in Photoshop / Photopea',
      psdDone: 'PSD esportato',
      psdDegraded:
        '{{n}} elemento/i (regolazioni, oggetti avanzati, testo/forme) sono stati rasterizzati',
      toSmart: 'Converti in oggetto avanzato',
      rasterize: 'Rasterizza',
      smartTitle: 'Oggetto avanzato',
      smartSource: 'Origine {{w}} × {{h}}: scala e rotazione senza ricampionamento',
      adjustHint: 'Agisce su tutto ciò che sta sotto e resta modificabile',
      mask: 'Maschera di livello',
      maskRevealAll: 'Mostra tutto',
      maskHideAll: 'Nascondi tutto',
      maskFromSelection: 'Dalla selezione',
      maskRemove: 'Elimina maschera',
      maskEnable: 'Abilita',
      maskInvert: 'Inverti',
      maskDensity: 'Densità',
      maskFeather: 'Sfumatura',
      maskEdit: 'Modifica maschera',
      maskEditing: 'Modifica maschera in corso',
      maskHint:
        'La maschera controlla la visibilità in scala di grigi: in modifica il pennello dipinge bianco (mostra), la gomma nero (nasconde)',
      layerText: 'Testo {{n}}',
      layerShape: 'Forma {{n}}',
      copySuffix: ' copia',
      textPlaceholder: 'Fai doppio clic per modificare il testo',
      blendMode: {
        normal: 'Normale',
        multiply: 'Moltiplica',
        screen: 'Scherma',
        overlay: 'Sovrapponi',
        darken: 'Scursa',
        lighten: 'Schiarisci',
        'color-dodge': 'Dodge lineare',
        difference: 'Differenza',
        exclusion: 'Esclusione',
        hue: 'Tonalità',
        saturation: 'Saturazione',
        color: 'Colore',
        luminosity: 'Luminosità',
      },
      shape: {
        rect: 'Rettangolo',
        roundRect: 'Rettangolo arrotondato',
        ellipse: 'Ellisse',
        line: 'Linea',
        arrow: 'Freccia',
        star: 'Stella',
      },
      up: 'Sposta su',
      down: 'Sposta giù',
      noLayer: 'Nessun livello',

      posX: 'Posizione X',
      posY: 'Posizione Y',
      rotation: 'Rotazione',
      flipH: 'Specchio orizzontale',
      flipV: 'Specchio verticale',
      fontSize: 'Dimensione carattere',
      fontFamily: 'Carattere',
      bold: 'Grassetto',
      italic: 'Corsivo',
      underline: 'Sottolineato',
      alignLeft: 'Allinea a sinistra',
      alignCenter: 'Centra',
      alignRight: 'Allinea a destra',
      fill: 'Riempimento',
      stroke: 'Contorno',
      strokeWidth: 'Spessore contorno',
      cornerRadius: 'Raggio angoli',
      textContent: 'Testo',

      brightness: 'Luminosità',
      contrast: 'Contrasto',
      saturation: 'Saturazione',
      hue: 'Tonalità',
      temperature: 'Temperatura',
      exposure: 'Esposizione',
      sharpen: 'Nitidezza',
      resetAdjust: 'Ripristina regolazioni',

      filterGrayscale: 'Scala di grigi',
      filterSepia: 'Seppia',
      filterInvert: 'Inverti',
      filterBlur: 'Sfocatura',
      filterSharpen: 'Nitidezza',
      filterEmboss: 'Rilievo',
      filterEdge: 'Contorni',
      filterNoise: 'Rumore',
      filterPixelate: 'Pixelizza',
      filterPosterize: 'Posterizza',
      hintGrayscale: 'Rimuove tutti i colori per un risultato in bianco e nero',
      hintSepia: 'Tono bruno caldo come una vecchia fotografia',
      hintInvert: 'Inverte i colori creando un negativo',
      hintBlur: 'Addolcisce l’immagine e attenua i dettagli',
      hintSharpen: 'Aumenta il contrasto dei bordi per maggiore nitidezza',
      hintEmboss: 'Evidenzia i contorni come un’impronta in rilievo',
      hintEdge: 'Mantiene solo le linee di contorno',
      hintNoise: 'Aggiunge una grana simile alla pellicola',
      hintPixelate: 'Mosaico che nasconde i dettagli',
      hintPosterize: 'Riduce le tonalità a blocchi di colore',

      statusZoom: 'Zoom {{scale}}%',
      statusCursor: 'Cursore {{x}}, {{y}}',
      statusSelection: 'Selezione {{width}} × {{height}}',
      statusMemory: 'Circa {{size}} in uso',
      exportTitle: 'Esporta immagine',
      format: 'Formato',
      quality: 'Qualità',
      qualityHint: '{{value}}%',
      exportSelectionOnly: 'Solo selezione',
      download: 'Scarica',

      err: {
        NOT_IMAGE: 'Scegli un’immagine PNG / JPEG / WEBP / GIF / BMP',
        EMPTY: 'Il file è vuoto',
        TOO_LARGE: 'Il file supera il limite di {{max}} MB',
        IMAGE_DECODE_FAILED: 'Decodifica dell’immagine non riuscita',
        NOT_PROJECT: 'Non è un progetto dell’editor foto (.photo.json)',
        PARSE_FAILED: 'Analisi del progetto non riuscita',
        UNSUPPORTED_VERSION: 'Versione del progetto troppo recente, aggiorna l’app',
        INVALID_SIZE: 'La dimensione della tela deve essere tra {{min}} e {{max}}',
        RUNTIME_FAILED: 'Inizializzazione della tela non riuscita, ricarica la pagina',
        EXPORT_FAILED: 'Esportazione dell’immagine non riuscita',
        PSD_FAILED: 'Esportazione PSD non riuscita',
        MERGE_FAILED: 'Solo i livelli raster possono essere uniti verso il basso',
        NO_LAYER: 'Seleziona prima un livello',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    photo: {
      docTitle: 'Nombre del lienzo',
      present: 'Presentar',
      exitPresent: 'Salir (Esc)',
      presentLoading: 'Preparando la presentación…',
      presentFailed: 'No se pudo preparar la presentación',
      titlePlaceholder: 'Lienzo sin título',
      newCanvas: 'Nuevo lienzo',
      importImage: 'Importar imagen',
      importProject: 'Abrir proyecto',
      exportImage: 'Exportar imagen',
      exportProject: 'Guardar proyecto',
      clear: 'Vaciar',
      stats: '{{width}} × {{height}} px · {{count}} capas',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de editar',
      degraded:
        'Borrador demasiado grande: solo la estructura, se descartaron los píxeles de las capas',
      hint: 'Todo ocurre localmente en el navegador y ninguna imagen se sube; exporta PNG / JPEG / WEBP o guarda un proyecto editable',
      openHint: 'Arrastra o elige una imagen para abrirla como nueva capa',
      emptyHint:
        'Aún no hay capas: importa una imagen o añade una capa vacía / de texto / de forma',
      canvasAria: 'photo canvas',

      dialogNew: 'Nuevo lienzo',
      preset: 'Predefinido',
      widthLabel: 'Ancho',
      heightLabel: 'Alto',
      background: 'Fondo',
      bgTransparent: 'Transparente',
      bgWhite: 'Blanco',
      bgBlack: 'Negro',
      create: 'Crear',
      cancel: 'Cancelar',

      toolMove: 'Mover',
      toolRectSelect: 'Selección rectangular',
      toolEllipseSelect: 'Selección elíptica',
      toolLasso: 'Lazo',
      toolCrop: 'Recortar',
      toolBrush: 'Pincel',
      toolEraser: 'Borrador',
      toolEyedropper: 'Cuentagotas',
      toolFill: 'Bote de pintura',
      toolText: 'Texto',
      toolShape: 'Forma',
      toolHand: 'Mano',

      color: 'Color',
      size: 'Tamaño del pincel',
      hardness: 'Dureza',
      opacity: 'Opacidad',
      feather: 'Difuminado',
      shapeKind: 'Forma',
      applyCrop: 'Aplicar recorte',
      cancelCrop: 'Cancelar recorte',
      zoomIn: 'Acercar',
      zoomOut: 'Alejar',
      zoomFit: 'Ajustar a la ventana',
      zoomActual: '100%',
      undo: 'Deshacer',
      redo: 'Rehacer',
      deselect: 'Quitar selección',
      canvasMenu: 'Menú contextual del lienzo',
      canvasOps: 'Lienzo',
      selectionOps: 'Selección',
      ctxFill: 'Rellenar selección (color frontal)',
      ctxClear: 'Borrar contenido de la selección',
      ctxLayerViaCopy: 'Capa vía copia',
      ctxInvert: 'Invertir selección',
      ctxExportSelection: 'Exportar selección como PNG',
      ctxSelectAll: 'Seleccionar todo',
      ctxPaste: 'Pegar capa',
      foreground: 'Color frontal',
      picked: '{{color}} capturado',
      pickTransparent: 'Ese píxel es transparente; el color frontal no cambió',
      eyedropperHint:
        'Haz clic en el lienzo para capturar un color (mantén Alt para capturar con cualquier herramienta)',

      tabLayers: 'Capas',
      tabProperty: 'Propiedades',
      tabAdjust: 'Ajustes',
      tabFilter: 'Filtros',

      addRaster: 'Capa vacía',
      addText: 'Capa de texto',
      addShape: 'Capa de forma',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      mergeDown: 'Combinar hacia abajo',
      flatten: 'Combinar visibles',
      visible: 'Mostrar',
      hidden: 'Ocultar',
      lock: 'Bloquear',
      unlock: 'Desbloquear',
      blend: 'Modo de fusión',
      rename: 'Renombrar',
      layerMenu: 'Menú de capa',
      newLayer: 'Nueva capa',
      layerOps: 'Acciones de capa',
      layerRaster: 'Capa {{n}}',
      layerGroup: 'Grupo {{n}}',
      layerAdjust: 'Capa de ajuste {{n}}',
      layerSmart: 'Objeto inteligente {{n}}',
      kindGroup: 'Grupo',
      kindAdjust: 'Ajuste',
      kindSmart: 'Inteligente',
      histOpen: 'Abrir documento',
      histEdit: 'Editar',
      histBrush: 'Pincel',
      histErase: 'Borrador',
      histFill: 'Rellenar',
      histCrop: 'Recortar',
      histResize: 'Tamaño del lienzo',
      histAddLayer: 'Nueva capa',
      histDeleteLayer: 'Eliminar capa',
      histDuplicate: 'Duplicar capa',
      histReorder: 'Reordenar',
      histMerge: 'Combinar capas',
      histFlatten: 'Acoplar visibles',
      histMove: 'Mover',
      histRename: 'Renombrar',
      tabHistory: 'Historial',
      historyCurrent: 'actual',
      historyClear: 'Borrar historial',
      historyCount: '{{n}} pasos',
      addGroup: 'Nuevo grupo',
      groupFromLayer: 'Agrupar desde capa',
      leaveGroup: 'Salir del grupo',
      ungroup: 'Desagrupar',
      groupIsolate: 'Componer el grupo como un todo',
      groupPassThrough: 'Pasar a través (mezclar individualmente)',
      collapse: 'Contraer',
      expand: 'Expandir',
      histGroup: 'Grupo',
      addAdjustment: 'Nueva capa de ajuste',
      psdExport: 'Exportar PSD',
      psdExporting: 'Exportando…',
      psdHint: 'El PSD sigue siendo editable en Photoshop / Photopea',
      psdDone: 'PSD exportado',
      psdDegraded:
        '{{n}} elemento(s) (ajustes, objetos inteligentes, texto/formas) se rasterizaron',
      toSmart: 'Convertir en objeto inteligente',
      rasterize: 'Rasterizar',
      smartTitle: 'Objeto inteligente',
      smartSource: 'Origen {{w}} × {{h}}: escalar o girar no remuestrea',
      adjustHint: 'Una capa de ajuste afecta a todo lo que hay debajo y sigue siendo editable',
      mask: 'Máscara de capa',
      maskRevealAll: 'Mostrar todo',
      maskHideAll: 'Ocultar todo',
      maskFromSelection: 'Desde la selección',
      maskRemove: 'Eliminar máscara',
      maskEnable: 'Activar',
      maskInvert: 'Invertir',
      maskDensity: 'Densidad',
      maskFeather: 'Difuminar',
      maskEdit: 'Editar máscara',
      maskEditing: 'Editando máscara',
      maskHint:
        'La máscara controla la visibilidad por escala de grises: al editar, el pincel pinta blanco (mostrar) y el borrador negro (ocultar)',
      layerText: 'Texto {{n}}',
      layerShape: 'Forma {{n}}',
      copySuffix: ' copia',
      textPlaceholder: 'Haz doble clic para editar el texto',
      blendMode: {
        normal: 'Normal',
        multiply: 'Multiplicar',
        screen: 'Trama',
        overlay: 'Superponer',
        darken: 'Oscurecer',
        lighten: 'Aclarar',
        'color-dodge': 'Sobreexponer color',
        difference: 'Diferencia',
        exclusion: 'Exclusión',
        hue: 'Tono',
        saturation: 'Saturación',
        color: 'Color',
        luminosity: 'Luminosidad',
      },
      shape: {
        rect: 'Rectángulo',
        roundRect: 'Rectángulo redondeado',
        ellipse: 'Elipse',
        line: 'Línea',
        arrow: 'Flecha',
        star: 'Estrella',
      },
      up: 'Subir',
      down: 'Bajar',
      noLayer: 'Sin capas',

      posX: 'Posición X',
      posY: 'Posición Y',
      rotation: 'Rotación',
      flipH: 'Voltear horizontal',
      flipV: 'Voltear vertical',
      fontSize: 'Tamaño de fuente',
      fontFamily: 'Fuente',
      bold: 'Negrita',
      italic: 'Cursiva',
      underline: 'Subrayado',
      alignLeft: 'Alinear a la izquierda',
      alignCenter: 'Centrar',
      alignRight: 'Alinear a la derecha',
      fill: 'Relleno',
      stroke: 'Contorno',
      strokeWidth: 'Grosor del contorno',
      cornerRadius: 'Radio de esquina',
      textContent: 'Texto',

      brightness: 'Brillo',
      contrast: 'Contraste',
      saturation: 'Saturación',
      hue: 'Tono',
      temperature: 'Temperatura',
      exposure: 'Exposición',
      sharpen: 'Enfoque',
      resetAdjust: 'Restablecer ajustes',

      filterGrayscale: 'Escala de grises',
      filterSepia: 'Sepia',
      filterInvert: 'Invertir',
      filterBlur: 'Desenfoque',
      filterSharpen: 'Enfoque',
      filterEmboss: 'Relieve',
      filterEdge: 'Contornos',
      filterNoise: 'Ruido',
      filterPixelate: 'Pixelar',
      filterPosterize: 'Posterizar',
      hintGrayscale: 'Elimina todo el color para obtener blanco y negro',
      hintSepia: 'Tono marrón cálido como una foto antigua',
      hintInvert: 'Invierte los colores para crear un negativo',
      hintBlur: 'Suaviza la imagen y atenúa los detalles',
      hintSharpen: 'Aumenta el contraste de los bordes para más nitidez',
      hintEmboss: 'Resalta los contornos como una impronta en relieve',
      hintEdge: 'Conserva solo las líneas de contorno',
      hintNoise: 'Añade grano similar al de una película',
      hintPixelate: 'Mosaico que oculta los detalles',
      hintPosterize: 'Reduce los tonos a bloques de color',

      statusZoom: 'Zoom {{scale}}%',
      statusCursor: 'Cursor {{x}}, {{y}}',
      statusSelection: 'Selección {{width}} × {{height}}',
      statusMemory: 'En uso aprox. {{size}}',
      exportTitle: 'Exportar imagen',
      format: 'Formato',
      quality: 'Calidad',
      qualityHint: '{{value}}%',
      exportSelectionOnly: 'Solo la selección',
      download: 'Descargar',

      err: {
        NOT_IMAGE: 'Elige una imagen PNG / JPEG / WEBP / GIF / BMP',
        EMPTY: 'El archivo está vacío',
        TOO_LARGE: 'El archivo supera el límite de {{max}} MB',
        IMAGE_DECODE_FAILED: 'No se pudo decodificar la imagen',
        NOT_PROJECT: 'No es un proyecto del editor de fotos (.photo.json)',
        PARSE_FAILED: 'No se pudo analizar el proyecto',
        UNSUPPORTED_VERSION: 'La versión del proyecto es demasiado nueva, actualiza la aplicación',
        INVALID_SIZE: 'El tamaño del lienzo debe estar entre {{min}} y {{max}}',
        RUNTIME_FAILED: 'No se pudo inicializar el lienzo, recarga la página',
        EXPORT_FAILED: 'La exportación de la imagen falló',
        PSD_FAILED: 'Error al exportar PSD',
        MERGE_FAILED: 'Solo las capas ráster pueden combinarse hacia abajo',
        NO_LAYER: 'Selecciona primero una capa',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    photo: {
      docTitle: 'Nome da tela',
      present: 'Apresentar',
      exitPresent: 'Sair (Esc)',
      presentLoading: 'A preparar a apresentação…',
      presentFailed: 'Falha ao preparar a apresentação',
      titlePlaceholder: 'Tela sem título',
      newCanvas: 'Nova tela',
      importImage: 'Importar imagem',
      importProject: 'Abrir projeto',
      exportImage: 'Exportar imagem',
      exportProject: 'Guardar projeto',
      clear: 'Limpar',
      stats: '{{width}} × {{height}} px · {{count}} camadas',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de editar',
      degraded:
        'Rascunho demasiado grande: apenas a estrutura, os píxeis das camadas foram descartados',
      hint: 'Tudo corre localmente no navegador, nenhuma imagem é enviada; exporte PNG / JPEG / WEBP ou guarde um projeto editável',
      openHint: 'Arraste ou escolha uma imagem para abri-la como nova camada',
      emptyHint:
        'Ainda sem camadas: importe uma imagem ou adicione uma camada vazia / de texto / de forma',
      canvasAria: 'photo canvas',

      dialogNew: 'Nova tela',
      preset: 'Predefinição',
      widthLabel: 'Largura',
      heightLabel: 'Altura',
      background: 'Fundo',
      bgTransparent: 'Transparente',
      bgWhite: 'Branco',
      bgBlack: 'Preto',
      create: 'Criar',
      cancel: 'Cancelar',

      toolMove: 'Mover',
      toolRectSelect: 'Seleção retangular',
      toolEllipseSelect: 'Seleção elíptica',
      toolLasso: 'Laço',
      toolCrop: 'Recortar',
      toolBrush: 'Pincel',
      toolEraser: 'Borracha',
      toolEyedropper: 'Conta-gotas',
      toolFill: 'Balde de tinta',
      toolText: 'Texto',
      toolShape: 'Forma',
      toolHand: 'Mão',

      color: 'Cor',
      size: 'Tamanho do pincel',
      hardness: 'Dureza',
      opacity: 'Opacidade',
      feather: 'Suavizar',
      shapeKind: 'Forma',
      applyCrop: 'Aplicar recorte',
      cancelCrop: 'Cancelar recorte',
      zoomIn: 'Ampliar',
      zoomOut: 'Reduzir',
      zoomFit: 'Ajustar à janela',
      zoomActual: '100%',
      undo: 'Anular',
      redo: 'Refazer',
      deselect: 'Limpar seleção',
      canvasMenu: 'Menu de contexto da tela',
      canvasOps: 'Tela',
      selectionOps: 'Seleção',
      ctxFill: 'Preencher seleção (cor de primeiro plano)',
      ctxClear: 'Limpar conteúdo da seleção',
      ctxLayerViaCopy: 'Camada por cópia',
      ctxInvert: 'Inverter seleção',
      ctxExportSelection: 'Exportar seleção como PNG',
      ctxSelectAll: 'Selecionar tudo',
      ctxPaste: 'Colar camada',
      foreground: 'Cor de primeiro plano',
      picked: '{{color}} capturada',
      pickTransparent: 'Esse pixel é transparente; a cor de primeiro plano não mudou',
      eyedropperHint:
        'Clique na tela para capturar uma cor (mantenha Alt para capturar com qualquer ferramenta)',

      tabLayers: 'Camadas',
      tabProperty: 'Propriedades',
      tabAdjust: 'Ajustes',
      tabFilter: 'Filtros',

      addRaster: 'Camada vazia',
      addText: 'Camada de texto',
      addShape: 'Camada de forma',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      mergeDown: 'Unir com a de baixo',
      flatten: 'Unir visíveis',
      visible: 'Mostrar',
      hidden: 'Ocultar',
      lock: 'Bloquear',
      unlock: 'Desbloquear',
      blend: 'Modo de mesclagem',
      rename: 'Renomear',
      layerMenu: 'Menu da camada',
      newLayer: 'Nova camada',
      layerOps: 'Ações da camada',
      layerRaster: 'Camada {{n}}',
      layerGroup: 'Grupo {{n}}',
      layerAdjust: 'Camada de ajuste {{n}}',
      layerSmart: 'Objeto inteligente {{n}}',
      kindGroup: 'Grupo',
      kindAdjust: 'Ajuste',
      kindSmart: 'Inteligente',
      histOpen: 'Abrir documento',
      histEdit: 'Editar',
      histBrush: 'Pincel',
      histErase: 'Borracha',
      histFill: 'Preencher',
      histCrop: 'Recortar',
      histResize: 'Tamanho da tela',
      histAddLayer: 'Nova camada',
      histDeleteLayer: 'Excluir camada',
      histDuplicate: 'Duplicar camada',
      histReorder: 'Reordenar',
      histMerge: 'Mesclar camadas',
      histFlatten: 'Achatar visíveis',
      histMove: 'Mover',
      histRename: 'Renomear',
      tabHistory: 'Histórico',
      historyCurrent: 'atual',
      historyClear: 'Limpar histórico',
      historyCount: '{{n}} passos',
      addGroup: 'Novo grupo',
      groupFromLayer: 'Agrupar a partir da camada',
      leaveGroup: 'Sair do grupo',
      ungroup: 'Desagrupar',
      groupIsolate: 'Compor o grupo como um todo',
      groupPassThrough: 'Pass-through (misturar individualmente)',
      collapse: 'Recolher',
      expand: 'Expandir',
      histGroup: 'Grupo',
      addAdjustment: 'Nova camada de ajuste',
      psdExport: 'Exportar PSD',
      psdExporting: 'Exportando…',
      psdHint: 'O PSD permanece editável no Photoshop / Photopea',
      psdDone: 'PSD exportado',
      psdDegraded:
        '{{n}} item(ns) (ajustes, objetos inteligentes, texto/formas) foram rasterizados',
      toSmart: 'Converter em objeto inteligente',
      rasterize: 'Rasterizar',
      smartTitle: 'Objeto inteligente',
      smartSource: 'Origem {{w}} × {{h}}: escalar ou girar não reamostra',
      adjustHint: 'Uma camada de ajuste afeta tudo abaixo dela e permanece editável',
      mask: 'Máscara de camada',
      maskRevealAll: 'Mostrar tudo',
      maskHideAll: 'Ocultar tudo',
      maskFromSelection: 'A partir da seleção',
      maskRemove: 'Excluir máscara',
      maskEnable: 'Ativar',
      maskInvert: 'Inverter',
      maskDensity: 'Densidade',
      maskFeather: 'Suavizar',
      maskEdit: 'Editar máscara',
      maskEditing: 'Editando máscara',
      maskHint:
        'A máscara controla a visibilidade por escala de cinza: ao editar, o pincel pinta branco (mostrar) e a borracha preto (ocultar)',
      layerText: 'Texto {{n}}',
      layerShape: 'Forma {{n}}',
      copySuffix: ' cópia',
      textPlaceholder: 'Clique duas vezes para editar o texto',
      blendMode: {
        normal: 'Normal',
        multiply: 'Multiplicar',
        screen: 'Ecrã',
        overlay: 'Sobrepor',
        darken: 'Escurecer',
        lighten: 'Clarear',
        'color-dodge': 'Sobrepor cor',
        difference: 'Diferença',
        exclusion: 'Exclusão',
        hue: 'Matiz',
        saturation: 'Saturação',
        color: 'Cor',
        luminosity: 'Luminosidade',
      },
      shape: {
        rect: 'Retângulo',
        roundRect: 'Retângulo arredondado',
        ellipse: 'Elipse',
        line: 'Linha',
        arrow: 'Seta',
        star: 'Estrela',
      },
      up: 'Mover para cima',
      down: 'Mover para baixo',
      noLayer: 'Sem camadas',

      posX: 'Posição X',
      posY: 'Posição Y',
      rotation: 'Rotação',
      flipH: 'Espelhar na horizontal',
      flipV: 'Espelhar na vertical',
      fontSize: 'Tamanho da fonte',
      fontFamily: 'Fonte',
      bold: 'Negrito',
      italic: 'Itálico',
      underline: 'Sublinhado',
      alignLeft: 'Alinhar à esquerda',
      alignCenter: 'Centrar',
      alignRight: 'Alinhar à direita',
      fill: 'Preenchimento',
      stroke: 'Contorno',
      strokeWidth: 'Espessura do contorno',
      cornerRadius: 'Raio dos cantos',
      textContent: 'Texto',

      brightness: 'Brilho',
      contrast: 'Contraste',
      saturation: 'Saturação',
      hue: 'Matiz',
      temperature: 'Temperatura',
      exposure: 'Exposição',
      sharpen: 'Nitidez',
      resetAdjust: 'Repor ajustes',

      filterGrayscale: 'Escala de cinzentos',
      filterSepia: 'Sépia',
      filterInvert: 'Inverter',
      filterBlur: 'Desfocar',
      filterSharpen: 'Nitidez',
      filterEmboss: 'Relevo',
      filterEdge: 'Contornos',
      filterNoise: 'Ruído',
      filterPixelate: 'Pixelizar',
      filterPosterize: 'Posterizar',
      hintGrayscale: 'Remove todas as cores para obter preto e branco',
      hintSepia: 'Tom castanho quente como uma fotografia antiga',
      hintInvert: 'Inverte as cores para criar um negativo',
      hintBlur: 'Suaviza a imagem e atenua os detalhes',
      hintSharpen: 'Aumenta o contraste das bordas para maior nitidez',
      hintEmboss: 'Destaca os contornos como uma impressão em relevo',
      hintEdge: 'Mantém apenas as linhas de contorno',
      hintNoise: 'Adiciona grão semelhante ao de película',
      hintPixelate: 'Mosaico que oculta os detalhes',
      hintPosterize: 'Reduz os tons a blocos de cor',

      statusZoom: 'Zoom {{scale}}%',
      statusCursor: 'Cursor {{x}}, {{y}}',
      statusSelection: 'Seleção {{width}} × {{height}}',
      statusMemory: 'Cerca de {{size}} em uso',
      exportTitle: 'Exportar imagem',
      format: 'Formato',
      quality: 'Qualidade',
      qualityHint: '{{value}}%',
      exportSelectionOnly: 'Apenas a seleção',
      download: 'Transferir',

      err: {
        NOT_IMAGE: 'Escolha uma imagem PNG / JPEG / WEBP / GIF / BMP',
        EMPTY: 'O ficheiro está vazio',
        TOO_LARGE: 'O ficheiro excede o limite de {{max}} MB',
        IMAGE_DECODE_FAILED: 'Falha ao descodificar a imagem',
        NOT_PROJECT: 'Este não é um projeto do editor de fotos (.photo.json)',
        PARSE_FAILED: 'Falha ao analisar o projeto',
        UNSUPPORTED_VERSION: 'A versão do projeto é demasiado recente, atualize a aplicação',
        INVALID_SIZE: 'O tamanho da tela deve estar entre {{min}} e {{max}}',
        RUNTIME_FAILED: 'Falha ao inicializar a tela, recarregue a página',
        EXPORT_FAILED: 'Falha ao exportar a imagem',
        PSD_FAILED: 'Falha ao exportar PSD',
        MERGE_FAILED: 'Apenas camadas raster podem ser unidas com a de baixo',
        NO_LAYER: 'Selecione primeiro uma camada',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const photoStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具被懒加载时调用，键路径 tools.photo.*） */
export function registerPhotoStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(photoStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
