/**
 * 代码编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 *
 * 与 rich-text-editor / slide-editor / photo-editor 保持同一套约定：
 * 项目的 zh / en 语言包是首屏同步资源，本工具几十条文案若写进
 * `core/i18n/locales/*` 会直接推高首屏入口体积（预算 210KB，实测已接近上限）。
 * 因此文案放在这里，由 `registerCodeEditorStrings` 在工具被懒加载时合并进 i18next，
 * 键路径 `tools.codeEditor.*`。工具元数据（名称 / 描述）仍写在 locales 的 `toolsMeta` 中。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { codeEditor: StringTree } };

const zh: ResourceTree = {
  tools: {
    codeEditor: {
      language: '语言',
      theme: '风格主题',
      indent: '缩进',
      indent2: '2 空格',
      indent4: '4 空格',
      indentTab: 'Tab',
      lineNumbers: '行号',
      wordWrap: '自动换行',
      wrapHint: '自动换行时行号不显示',
      editor: '编辑器',
      preview: '导出预览',
      import: '导入文件',
      importHint: '拖入或选择源码文件',
      importFormats: '按扩展名自动识别语言（如 .java / .rs / .py）',
      format: '格式化',
      formatting: '格式化中…',
      formatDone: '已格式化',
      formatFallback: 'Prettier 引擎不可用，已使用内置格式化器',
      filename: '文件名',
      finalName: '将导出为 {{name}}',
      exportSource: '导出 {{ext}}',
      exportHtml: '导出 HTML',
      exportPng: '导出 PNG',
      exportJpg: '导出 JPG',
      exportSvg: '导出 SVG',
      exporting: '导出中…',
      copyCode: '复制代码',
      copyHtml: '复制 HTML',
      clear: '清空',
      op: {
        comment: '注释',
        moveUp: '上移行',
        moveDown: '下移行',
        duplicate: '复制行',
        deleteLine: '删除行',
        transpose: '转置行',
        indent: '增加缩进',
        outdent: '减少缩进',
        gotoLine: '跳转行',
        selectOccurrences: '选择同词',
        multiLabel: '统一替换',
        multiHits: '{{ranges}} 处',
        multiApply: '应用',
        multiCancel: '取消',
        multiNoWord: '光标不在可批量替换的词上',
        hint: '快捷键提示',
        unsupported: '当前语言不支持该注释操作',
      },
      find: {
        label: '查找',
        replaceLabel: '替换为',
        caseSensitive: '区分大小写',
        wholeWord: '全词匹配',
        regex: '正则表达式',
        prev: '上一个',
        next: '下一个',
        replaceOne: '替换',
        replaceAll: '全部替换',
        noMatch: '无结果',
        invalid: '正则无效',
        truncated: '命中过多，仅显示前 5000 个',
        tooMany: '命中过多，无法一次性全部替换',
        done: '已全部替换',
        close: '关闭查找栏',
      },
      fold: {
        lines: '{{lines}} 行',
        copy: '复制该段',
        toggle: '折叠范围（{{lines}} 行）',
        clear: '清除折叠范围',
        note: '折叠以范围标记呈现（编辑器不支持隐藏行）',
      },
      card: {
        title: '卡片样式',
        window: '窗口',
        window_mac: '三点窗口',
        window_title: '标题栏',
        window_plain: '纯色面板',
        window_none: '无边框',
        padding: '留白',
        radius: '圆角',
        shadow: '阴影',
        shadow_none: '无',
        shadow_soft: '柔和',
        shadow_medium: '中等',
        shadow_strong: '强烈',
        background: '背景',
        bg_theme: '跟随主题',
        bg_gradient: '渐变',
        bg_grid: '网格',
        bg_transparent: '透明',
        fontSize: '字号',
        highlightLines: '高亮行',
        highlightHint: '如 2-5',
        watermark: '水印',
        watermarkOpacity: '水印透明度',
        scale: '导出倍率',
      },
      copy: {
        markdown: '复制 Markdown',
        richText: '复制富文本',
        image: '复制图片',
        richDone: '已复制富文本',
        plainDone: '剪贴板不支持富文本，已复制纯文本',
        imageDone: '已复制图片',
        imageFallback: '剪贴板不可用，已下载 PNG',
        copyFallback: '剪贴板不可用，已下载 HTML 片段',
      },
      share: {
        tooLongHint: '内容过长，未生成分享链接；可改用导出源码或图片',
      },
      stats: '{{chars}} 字符 · {{lines}} 行 · {{bytes}} 字节',
      saved: '已保存到本地草稿',
      saving: '停止输入后自动保存',
      placeholder: '在此粘贴或编写代码…',
      empty: '输入代码后在此显示导出预览',
      err: {
        EMPTY: '请先输入代码',
        TOO_LARGE: '文件超过 {{max}}MB 限制',
        UNSUPPORTED: '纯文本无需格式化',
        READ_FAILED: '文件读取失败',
        FORMAT_FAILED: '格式化失败，请检查代码语法',
        EXPORT_FAILED: '导出失败，请重试',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Language',
      theme: 'Theme',
      indent: 'Indent',
      indent2: '2 spaces',
      indent4: '4 spaces',
      indentTab: 'Tab',
      lineNumbers: 'Line numbers',
      wordWrap: 'Word wrap',
      wrapHint: 'Line numbers are hidden while word wrap is on',
      editor: 'Editor',
      preview: 'Export preview',
      import: 'Import file',
      importHint: 'Drop or pick a source file',
      importFormats: 'Language is detected from the extension (.java / .rs / .py)',
      format: 'Format',
      formatting: 'Formatting…',
      formatDone: 'Formatted',
      formatFallback: 'Prettier engine unavailable, built-in formatter used',
      filename: 'Filename',
      finalName: 'Exports as {{name}}',
      exportSource: 'Export {{ext}}',
      exportHtml: 'Export HTML',
      exportPng: 'Export PNG',
      exportJpg: 'Export JPG',
      exportSvg: 'Export SVG',
      exporting: 'Exporting…',
      copyCode: 'Copy code',
      copyHtml: 'Copy HTML',
      clear: 'Clear',
      op: {
        comment: 'Comment',
        moveUp: 'Move line up',
        moveDown: 'Move line down',
        duplicate: 'Duplicate line',
        deleteLine: 'Delete line',
        transpose: 'Transpose line',
        indent: 'Indent',
        outdent: 'Outdent',
        gotoLine: 'Go to line',
        selectOccurrences: 'Select occurrences',
        multiLabel: 'Replace in all',
        multiHits: '{{ranges}} places',
        multiApply: 'Apply',
        multiCancel: 'Cancel',
        multiNoWord: 'The caret is not on a word that can be replaced in bulk',
        hint: 'Shortcut hints',
        unsupported: 'This language does not support that comment action',
      },
      find: {
        label: 'Find',
        replaceLabel: 'Replace with',
        caseSensitive: 'Match case',
        wholeWord: 'Whole word',
        regex: 'Regular expression',
        prev: 'Previous match',
        next: 'Next match',
        replaceOne: 'Replace',
        replaceAll: 'Replace all',
        noMatch: 'No results',
        invalid: 'Invalid regex',
        truncated: 'Too many matches, showing the first 5000',
        tooMany: 'Too many matches to replace at once',
        done: 'All replaced',
        close: 'Close find bar',
      },
      fold: {
        lines: '{{lines}} lines',
        copy: 'Copy range',
        toggle: 'Fold range ({{lines}} lines)',
        clear: 'Clear fold range',
        note: 'Folding is shown as a range marker (hiding lines is not supported)',
      },
      card: {
        title: 'Card style',
        window: 'Window',
        window_mac: 'Traffic lights',
        window_title: 'Title bar',
        window_plain: 'Plain panel',
        window_none: 'Borderless',
        padding: 'Padding',
        radius: 'Radius',
        shadow: 'Shadow',
        shadow_none: 'None',
        shadow_soft: 'Soft',
        shadow_medium: 'Medium',
        shadow_strong: 'Strong',
        background: 'Background',
        bg_theme: 'Follow theme',
        bg_gradient: 'Gradient',
        bg_grid: 'Grid',
        bg_transparent: 'Transparent',
        fontSize: 'Font size',
        highlightLines: 'Highlight lines',
        highlightHint: 'e.g. 2-5',
        watermark: 'Watermark',
        watermarkOpacity: 'Watermark opacity',
        scale: 'Export scale',
      },
      copy: {
        markdown: 'Copy Markdown',
        richText: 'Copy rich text',
        image: 'Copy image',
        richDone: 'Rich text copied',
        plainDone: 'Rich text not supported here; plain text copied instead',
        imageDone: 'Image copied',
        imageFallback: 'Clipboard unavailable; PNG downloaded instead',
        copyFallback: 'Clipboard unavailable; HTML snippet downloaded instead',
      },
      share: {
        tooLongHint: 'Too long to share; export the source or an image instead',
      },
      stats: '{{chars}} chars · {{lines}} lines · {{bytes}} bytes',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop typing',
      placeholder: 'Paste or write code here…',
      empty: 'Export preview appears once you type',
      err: {
        EMPTY: 'Please enter some code first',
        TOO_LARGE: 'File exceeds the {{max}}MB limit',
        UNSUPPORTED: 'Plain text has nothing to format',
        READ_FAILED: 'Failed to read the file',
        FORMAT_FAILED: 'Formatting failed, please check the syntax',
        EXPORT_FAILED: 'Export failed, please try again',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    codeEditor: {
      language: '語言',
      theme: '風格主題',
      indent: '縮排',
      indent2: '2 空格',
      indent4: '4 空格',
      indentTab: 'Tab',
      lineNumbers: '行號',
      wordWrap: '自動換行',
      wrapHint: '自動換行時不顯示行號',
      editor: '編輯器',
      preview: '匯出預覽',
      import: '匯入檔案',
      importHint: '拖曳或選擇原始碼檔案',
      importFormats: '依副檔名自動辨識語言（如 .java / .rs / .py）',
      format: '格式化',
      formatting: '格式化中…',
      formatDone: '已格式化',
      formatFallback: 'Prettier 引擎不可用，已改用內建格式化器',
      filename: '檔案名稱',
      finalName: '將匯出為 {{name}}',
      exportSource: '匯出 {{ext}}',
      exportHtml: '匯出 HTML',
      exportPng: '匯出 PNG',
      exportJpg: '匯出 JPG',
      exportSvg: '匯出 SVG',
      exporting: '匯出中…',
      copyCode: '複製程式碼',
      copyHtml: '複製 HTML',
      clear: '清空',
      op: {
        comment: '註解',
        moveUp: '上移行',
        moveDown: '下移行',
        duplicate: '複製行',
        deleteLine: '刪除行',
        transpose: '轉置行',
        indent: '增加縮排',
        outdent: '減少縮排',
        gotoLine: '跳轉行',
        selectOccurrences: '選擇同詞',
        multiLabel: '統一取代',
        multiHits: '{{ranges}} 處',
        multiApply: '套用',
        multiCancel: '取消',
        multiNoWord: '游標不在可批次取代的詞上',
        hint: '快速鍵提示',
        unsupported: '目前語言不支援此註解操作',
      },
      find: {
        label: '尋找',
        replaceLabel: '取代為',
        caseSensitive: '區分大小寫',
        wholeWord: '全字匹配',
        regex: '正規表達式',
        prev: '上一個',
        next: '下一個',
        replaceOne: '取代',
        replaceAll: '全部取代',
        noMatch: '無結果',
        invalid: '正規表達式無效',
        truncated: '命中過多，僅顯示前 5000 個',
        tooMany: '命中過多，無法一次全部取代',
        done: '已全部取代',
        close: '關閉尋找列',
      },
      fold: {
        lines: '{{lines}} 行',
        copy: '複製此段',
        toggle: '摺疊範圍（{{lines}} 行）',
        clear: '清除摺疊範圍',
        note: '摺疊以範圍標記呈現（編輯器不支援隱藏行）',
      },
      card: {
        title: '卡片樣式',
        window: '視窗',
        window_mac: '三點視窗',
        window_title: '標題列',
        window_plain: '純色面板',
        window_none: '無邊框',
        padding: '留白',
        radius: '圓角',
        shadow: '陰影',
        shadow_none: '無',
        shadow_soft: '柔和',
        shadow_medium: '中等',
        shadow_strong: '強烈',
        background: '背景',
        bg_theme: '跟隨主題',
        bg_gradient: '漸層',
        bg_grid: '網格',
        bg_transparent: '透明',
        fontSize: '字級',
        highlightLines: '高亮行',
        highlightHint: '如 2-5',
        watermark: '浮水印',
        watermarkOpacity: '浮水印透明度',
        scale: '匯出倍率',
      },
      copy: {
        markdown: '複製 Markdown',
        richText: '複製富文字',
        image: '複製圖片',
        richDone: '已複製富文字',
        plainDone: '剪貼簿不支援富文字，已複製純文字',
        imageDone: '已複製圖片',
        imageFallback: '剪貼簿不可用，已下載 PNG',
        copyFallback: '剪貼簿不可用，已下載 HTML 片段',
      },
      share: {
        tooLongHint: '內容過長，未產生分享連結；可改用匯出原始碼或圖片',
      },
      stats: '{{chars}} 字元 · {{lines}} 行 · {{bytes}} 位元組',
      saved: '已儲存至本機草稿',
      saving: '停止輸入後自動儲存',
      placeholder: '在此貼上或撰寫程式碼…',
      empty: '輸入程式碼後於此顯示匯出預覽',
      err: {
        EMPTY: '請先輸入程式碼',
        TOO_LARGE: '檔案超過 {{max}}MB 限制',
        UNSUPPORTED: '純文字無需格式化',
        READ_FAILED: '檔案讀取失敗',
        FORMAT_FAILED: '格式化失敗，請檢查語法',
        EXPORT_FAILED: '匯出失敗，請重試',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    codeEditor: {
      language: '言語',
      theme: 'テーマ',
      indent: 'インデント',
      indent2: '2 スペース',
      indent4: '4 スペース',
      indentTab: 'タブ',
      lineNumbers: '行番号',
      wordWrap: '折り返し',
      wrapHint: '折り返し時は行番号を非表示',
      editor: 'エディター',
      preview: '書き出しプレビュー',
      import: 'ファイルを読み込む',
      importHint: 'ソースファイルをドロップまたは選択',
      importFormats: '拡張子から言語を自動判定（.java / .rs / .py など）',
      format: '整形',
      formatting: '整形中…',
      formatDone: '整形しました',
      formatFallback: 'Prettier を利用できないため内蔵整形を使用しました',
      filename: 'ファイル名',
      finalName: '{{name}} として書き出し',
      exportSource: '{{ext}} を書き出し',
      exportHtml: 'HTML を書き出し',
      exportPng: 'PNG を書き出し',
      exportJpg: 'JPG を書き出し',
      exportSvg: 'SVG を書き出し',
      exporting: '書き出し中…',
      copyCode: 'コードをコピー',
      copyHtml: 'HTML をコピー',
      clear: 'クリア',
      op: {
        comment: 'コメント',
        moveUp: '行を上へ',
        moveDown: '行を下へ',
        duplicate: '行を複製',
        deleteLine: '行を削除',
        transpose: '行を入れ替え',
        indent: 'インデント追加',
        outdent: 'インデント解除',
        gotoLine: '行へ移動',
        selectOccurrences: '同じ語を選択',
        multiLabel: '一括置換',
        multiHits: '{{ranges}} か所',
        multiApply: '適用',
        multiCancel: 'キャンセル',
        multiNoWord: 'カーソルが一括置換できる語の上にありません',
        hint: 'ショートカットのヒント',
        unsupported: 'この言語ではこのコメント操作を利用できません',
      },
      find: {
        label: '検索',
        replaceLabel: '置換後',
        caseSensitive: '大文字と小文字を区別',
        wholeWord: '単語単位',
        regex: '正規表現',
        prev: '前を検索',
        next: '次を検索',
        replaceOne: '置換',
        replaceAll: 'すべて置換',
        noMatch: '該当なし',
        invalid: '正規表現が無効です',
        truncated: '一致が多すぎます。先頭 5000 件のみ表示',
        tooMany: '一致が多すぎるため一括置換できません',
        done: 'すべて置換しました',
        close: '検索バーを閉じる',
      },
      fold: {
        lines: '{{lines}} 行',
        copy: '範囲をコピー',
        toggle: '折りたたみ範囲（{{lines}} 行）',
        clear: '折りたたみ範囲を解除',
        note: '折りたたみは範囲マーカーで表示されます（行の非表示には未対応）',
      },
      card: {
        title: 'カードスタイル',
        window: 'ウィンドウ',
        window_mac: '3 色の丸',
        window_title: 'タイトルバー',
        window_plain: '単色パネル',
        window_none: '枠なし',
        padding: '余白',
        radius: '角丸',
        shadow: '影',
        shadow_none: 'なし',
        shadow_soft: '弱',
        shadow_medium: '中',
        shadow_strong: '強',
        background: '背景',
        bg_theme: 'テーマに従う',
        bg_gradient: 'グラデーション',
        bg_grid: 'グリッド',
        bg_transparent: '透明',
        fontSize: '文字サイズ',
        highlightLines: 'ハイライト行',
        highlightHint: '例 2-5',
        watermark: '透かし',
        watermarkOpacity: '透かしの不透明度',
        scale: '書き出し倍率',
      },
      copy: {
        markdown: 'Markdown をコピー',
        richText: 'リッチテキストをコピー',
        image: '画像をコピー',
        richDone: 'リッチテキストをコピーしました',
        plainDone: 'リッチテキスト未対応のためプレーンテキストをコピーしました',
        imageDone: '画像をコピーしました',
        imageFallback: 'クリップボードを使えないため PNG を保存しました',
        copyFallback: 'クリップボードを使えないため HTML 断片を保存しました',
      },
      share: {
        tooLongHint: '長すぎて共有リンクを作成できません。書き出しをご利用ください',
      },
      stats: '{{chars}} 文字 · {{lines}} 行 · {{bytes}} バイト',
      saved: 'ローカル下書きに保存しました',
      saving: '入力を止めると自動保存します',
      placeholder: 'ここにコードを貼り付け、または記述…',
      empty: 'コードを入力すると書き出しプレビューが表示されます',
      err: {
        EMPTY: '先にコードを入力してください',
        TOO_LARGE: 'ファイルが {{max}}MB の上限を超えています',
        UNSUPPORTED: 'プレーンテキストは整形できません',
        READ_FAILED: 'ファイルの読み込みに失敗しました',
        FORMAT_FAILED: '整形に失敗しました。構文を確認してください',
        EXPORT_FAILED: '書き出しに失敗しました。もう一度お試しください',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Langage',
      theme: 'Thème',
      indent: 'Indentation',
      indent2: '2 espaces',
      indent4: '4 espaces',
      indentTab: 'Tabulation',
      lineNumbers: 'Numéros de ligne',
      wordWrap: 'Retour à la ligne',
      wrapHint: 'Les numéros de ligne sont masqués avec le retour à la ligne',
      editor: 'Éditeur',
      preview: 'Aperçu d’export',
      import: 'Importer un fichier',
      importHint: 'Déposez ou choisissez un fichier source',
      importFormats: 'Langage détecté depuis l’extension (.java / .rs / .py)',
      format: 'Formater',
      formatting: 'Formatage…',
      formatDone: 'Formaté',
      formatFallback: 'Moteur Prettier indisponible, formateur intégré utilisé',
      filename: 'Nom du fichier',
      finalName: 'Sera exporté en {{name}}',
      exportSource: 'Exporter {{ext}}',
      exportHtml: 'Exporter HTML',
      exportPng: 'Exporter PNG',
      exportJpg: 'Exporter JPG',
      exportSvg: 'Exporter SVG',
      exporting: 'Export…',
      copyCode: 'Copier le code',
      copyHtml: 'Copier le HTML',
      clear: 'Effacer',
      op: {
        comment: 'Commenter',
        moveUp: 'Déplacer la ligne vers le haut',
        moveDown: 'Déplacer la ligne vers le bas',
        duplicate: 'Dupliquer la ligne',
        deleteLine: 'Supprimer la ligne',
        transpose: 'Transposer la ligne',
        indent: 'Indenter',
        outdent: 'Désindenter',
        gotoLine: 'Aller à la ligne',
        selectOccurrences: 'Sélectionner les occurrences',
        multiLabel: 'Remplacer partout',
        multiHits: '{{ranges}} emplacements',
        multiApply: 'Appliquer',
        multiCancel: 'Annuler',
        multiNoWord: 'Le curseur n’est pas sur un mot remplaçable en masse',
        hint: 'Raccourcis',
        unsupported: 'Ce langage ne prend pas en charge cette action de commentaire',
      },
      find: {
        label: 'Rechercher',
        replaceLabel: 'Remplacer par',
        caseSensitive: 'Respecter la casse',
        wholeWord: 'Mot entier',
        regex: 'Expression régulière',
        prev: 'Occurrence précédente',
        next: 'Occurrence suivante',
        replaceOne: 'Remplacer',
        replaceAll: 'Tout remplacer',
        noMatch: 'Aucun résultat',
        invalid: 'Expression régulière invalide',
        truncated: 'Trop d’occurrences : les 5000 premières sont affichées',
        tooMany: 'Trop d’occurrences pour tout remplacer',
        done: 'Tout remplacé',
        close: 'Fermer la barre de recherche',
      },
      fold: {
        lines: '{{lines}} lignes',
        copy: 'Copier la plage',
        toggle: 'Plage repliable ({{lines}} lignes)',
        clear: 'Effacer la plage repliable',
        note: 'Le repli est affiché comme repère de plage (masquage des lignes non pris en charge)',
      },
      card: {
        title: 'Style de carte',
        window: 'Fenêtre',
        window_mac: 'Feux tricolores',
        window_title: 'Barre de titre',
        window_plain: 'Panneau uni',
        window_none: 'Sans bordure',
        padding: 'Marge',
        radius: 'Arrondi',
        shadow: 'Ombre',
        shadow_none: 'Aucune',
        shadow_soft: 'Douce',
        shadow_medium: 'Moyenne',
        shadow_strong: 'Forte',
        background: 'Arrière-plan',
        bg_theme: 'Suivre le thème',
        bg_gradient: 'Dégradé',
        bg_grid: 'Grille',
        bg_transparent: 'Transparent',
        fontSize: 'Taille de police',
        highlightLines: 'Lignes en surbrillance',
        highlightHint: 'ex. 2-5',
        watermark: 'Filigrane',
        watermarkOpacity: 'Opacité du filigrane',
        scale: 'Échelle d’export',
      },
      copy: {
        markdown: 'Copier en Markdown',
        richText: 'Copier le texte riche',
        image: 'Copier l’image',
        richDone: 'Texte riche copié',
        plainDone: 'Texte riche non pris en charge ; texte brut copié',
        imageDone: 'Image copiée',
        imageFallback: 'Presse-papiers indisponible ; PNG téléchargé',
        copyFallback: 'Presse-papiers indisponible ; fragment HTML téléchargé',
      },
      share: {
        tooLongHint: 'Trop long pour partager ; exportez le code ou une image',
      },
      stats: '{{chars}} caractères · {{lines}} lignes · {{bytes}} octets',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement automatique après la saisie',
      placeholder: 'Collez ou écrivez du code ici…',
      empty: 'L’aperçu d’export s’affiche après la saisie',
      err: {
        EMPTY: 'Veuillez d’abord saisir du code',
        TOO_LARGE: 'Le fichier dépasse la limite de {{max}} Mo',
        UNSUPPORTED: 'Le texte brut n’a rien à formater',
        READ_FAILED: 'Échec de la lecture du fichier',
        FORMAT_FAILED: 'Formatage impossible, vérifiez la syntaxe',
        EXPORT_FAILED: 'Échec de l’export, réessayez',
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Sprache',
      theme: 'Farbschema',
      indent: 'Einrückung',
      indent2: '2 Leerzeichen',
      indent4: '4 Leerzeichen',
      indentTab: 'Tab',
      lineNumbers: 'Zeilennummern',
      wordWrap: 'Zeilenumbruch',
      wrapHint: 'Bei Zeilenumbruch werden Zeilennummern ausgeblendet',
      editor: 'Editor',
      preview: 'Exportvorschau',
      import: 'Datei importieren',
      importHint: 'Quelldatei hierher ziehen oder auswählen',
      importFormats: 'Sprache wird an der Endung erkannt (.java / .rs / .py)',
      format: 'Formatieren',
      formatting: 'Formatiere…',
      formatDone: 'Formatiert',
      formatFallback: 'Prettier nicht verfügbar, integrierter Formatter verwendet',
      filename: 'Dateiname',
      finalName: 'Wird als {{name}} exportiert',
      exportSource: '{{ext}} exportieren',
      exportHtml: 'HTML exportieren',
      exportPng: 'PNG exportieren',
      exportJpg: 'JPG exportieren',
      exportSvg: 'SVG exportieren',
      exporting: 'Exportiere…',
      copyCode: 'Code kopieren',
      copyHtml: 'HTML kopieren',
      clear: 'Leeren',
      op: {
        comment: 'Kommentieren',
        moveUp: 'Zeile nach oben',
        moveDown: 'Zeile nach unten',
        duplicate: 'Zeile duplizieren',
        deleteLine: 'Zeile löschen',
        transpose: 'Zeile tauschen',
        indent: 'Einrücken',
        outdent: 'Ausrücken',
        gotoLine: 'Gehe zu Zeile',
        selectOccurrences: 'Vorkommen auswählen',
        multiLabel: 'Überall ersetzen',
        multiHits: '{{ranges}} Stellen',
        multiApply: 'Anwenden',
        multiCancel: 'Abbrechen',
        multiNoWord: 'Der Cursor steht nicht auf einem massenweise ersetzbaren Wort',
        hint: 'Tastenkürzel',
        unsupported: 'Diese Sprache unterstützt diese Kommentaraktion nicht',
      },
      find: {
        label: 'Suchen',
        replaceLabel: 'Ersetzen durch',
        caseSensitive: 'Groß-/Kleinschreibung beachten',
        wholeWord: 'Ganzes Wort',
        regex: 'Regulärer Ausdruck',
        prev: 'Vorheriger Treffer',
        next: 'Nächster Treffer',
        replaceOne: 'Ersetzen',
        replaceAll: 'Alle ersetzen',
        noMatch: 'Keine Treffer',
        invalid: 'Ungültiger regulärer Ausdruck',
        truncated: 'Zu viele Treffer, es werden die ersten 5000 angezeigt',
        tooMany: 'Zu viele Treffer für ein einmaliges Ersetzen',
        done: 'Alle ersetzt',
        close: 'Suchleiste schließen',
      },
      fold: {
        lines: '{{lines}} Zeilen',
        copy: 'Bereich kopieren',
        toggle: 'Faltbereich ({{lines}} Zeilen)',
        clear: 'Faltbereich aufheben',
        note: 'Falten wird als Bereichsmarkierung dargestellt (Zeilenausblenden wird nicht unterstützt)',
      },
      card: {
        title: 'Kartenstil',
        window: 'Fenster',
        window_mac: 'Ampel-Punkte',
        window_title: 'Titelleiste',
        window_plain: 'Einfarbige Fläche',
        window_none: 'Ohne Rahmen',
        padding: 'Innenabstand',
        radius: 'Radius',
        shadow: 'Schatten',
        shadow_none: 'Keiner',
        shadow_soft: 'Weich',
        shadow_medium: 'Mittel',
        shadow_strong: 'Stark',
        background: 'Hintergrund',
        bg_theme: 'Theme folgen',
        bg_gradient: 'Verlauf',
        bg_grid: 'Raster',
        bg_transparent: 'Transparent',
        fontSize: 'Schriftgröße',
        highlightLines: 'Zeilen hervorheben',
        highlightHint: 'z. B. 2-5',
        watermark: 'Wasserzeichen',
        watermarkOpacity: 'Deckkraft des Wasserzeichens',
        scale: 'Export-Skalierung',
      },
      copy: {
        markdown: 'Markdown kopieren',
        richText: 'Rich-Text kopieren',
        image: 'Bild kopieren',
        richDone: 'Rich-Text kopiert',
        plainDone: 'Rich-Text nicht unterstützt; Text kopiert',
        imageDone: 'Bild kopiert',
        imageFallback: 'Zwischenablage nicht verfügbar; PNG heruntergeladen',
        copyFallback: 'Zwischenablage nicht verfügbar; HTML-Schnipsel heruntergeladen',
      },
      share: {
        tooLongHint: 'Zu lang zum Teilen; bitte Code oder Bild exportieren',
      },
      stats: '{{chars}} Zeichen · {{lines}} Zeilen · {{bytes}} Bytes',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Eingabe',
      placeholder: 'Code hier einfügen oder schreiben…',
      empty: 'Die Exportvorschau erscheint nach der Eingabe',
      err: {
        EMPTY: 'Bitte zuerst Code eingeben',
        TOO_LARGE: 'Datei überschreitet das Limit von {{max}} MB',
        UNSUPPORTED: 'Klartext muss nicht formatiert werden',
        READ_FAILED: 'Datei konnte nicht gelesen werden',
        FORMAT_FAILED: 'Formatierung fehlgeschlagen, Syntax prüfen',
        EXPORT_FAILED: 'Export fehlgeschlagen, bitte erneut versuchen',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Linguaggio',
      theme: 'Tema',
      indent: 'Rientro',
      indent2: '2 spazi',
      indent4: '4 spazi',
      indentTab: 'Tabulazione',
      lineNumbers: 'Numeri di riga',
      wordWrap: 'Ritorno a capo',
      wrapHint: 'Con il ritorno a capo i numeri di riga sono nascosti',
      editor: 'Editor',
      preview: 'Anteprima di esportazione',
      import: 'Importa file',
      importHint: 'Trascina o scegli un file sorgente',
      importFormats: 'Linguaggio rilevato dall’estensione (.java / .rs / .py)',
      format: 'Formatta',
      formatting: 'Formattazione…',
      formatDone: 'Formattato',
      formatFallback: 'Motore Prettier non disponibile, usato il formattatore integrato',
      filename: 'Nome file',
      finalName: 'Verrà esportato come {{name}}',
      exportSource: 'Esporta {{ext}}',
      exportHtml: 'Esporta HTML',
      exportPng: 'Esporta PNG',
      exportJpg: 'Esporta JPG',
      exportSvg: 'Esporta SVG',
      exporting: 'Esportazione…',
      copyCode: 'Copia codice',
      copyHtml: 'Copia HTML',
      clear: 'Svuota',
      op: {
        comment: 'Commenta',
        moveUp: 'Sposta riga su',
        moveDown: 'Sposta riga giù',
        duplicate: 'Duplica riga',
        deleteLine: 'Elimina riga',
        transpose: 'Inverti riga',
        indent: 'Aumenta rientro',
        outdent: 'Riduci rientro',
        gotoLine: 'Vai alla riga',
        selectOccurrences: 'Seleziona occorrenze',
        multiLabel: 'Sostituisci ovunque',
        multiHits: '{{ranges}} occorrenze',
        multiApply: 'Applica',
        multiCancel: 'Annulla',
        multiNoWord: 'Il cursore non è su una parola sostituibile in blocco',
        hint: 'Scorciatoie',
        unsupported: 'Questo linguaggio non supporta questa azione di commento',
      },
      find: {
        label: 'Trova',
        replaceLabel: 'Sostituisci con',
        caseSensitive: 'Distinzione maiuscole',
        wholeWord: 'Parola intera',
        regex: 'Espressione regolare',
        prev: 'Occorrenza precedente',
        next: 'Occorrenza successiva',
        replaceOne: 'Sostituisci',
        replaceAll: 'Sostituisci tutto',
        noMatch: 'Nessun risultato',
        invalid: 'Espressione regolare non valida',
        truncated: 'Troppe occorrenze: mostrate le prime 5000',
        tooMany: 'Troppe occorrenze per sostituirle tutte insieme',
        done: 'Sostituite tutte',
        close: 'Chiudi la barra di ricerca',
      },
      fold: {
        lines: '{{lines}} righe',
        copy: 'Copia intervallo',
        toggle: 'Intervallo comprimibile ({{lines}} righe)',
        clear: 'Rimuovi intervallo comprimibile',
        note: 'La compressione è mostrata come indicatore di intervallo (l’occultamento delle righe non è supportato)',
      },
      card: {
        title: 'Stile scheda',
        window: 'Finestra',
        window_mac: 'Semaforo',
        window_title: 'Barra del titolo',
        window_plain: 'Pannello tinta unita',
        window_none: 'Senza bordo',
        padding: 'Margine',
        radius: 'Raggio',
        shadow: 'Ombra',
        shadow_none: 'Nessuna',
        shadow_soft: 'Morbida',
        shadow_medium: 'Media',
        shadow_strong: 'Forte',
        background: 'Sfondo',
        bg_theme: 'Segui il tema',
        bg_gradient: 'Sfumatura',
        bg_grid: 'Griglia',
        bg_transparent: 'Trasparente',
        fontSize: 'Dimensione carattere',
        highlightLines: 'Righe evidenziate',
        highlightHint: 'es. 2-5',
        watermark: 'Filigrana',
        watermarkOpacity: 'Opacità filigrana',
        scale: 'Scala di esportazione',
      },
      copy: {
        markdown: 'Copia Markdown',
        richText: 'Copia testo formattato',
        image: 'Copia immagine',
        richDone: 'Testo formattato copiato',
        plainDone: 'Testo formattato non supportato; copiato testo semplice',
        imageDone: 'Immagine copiata',
        imageFallback: 'Appunti non disponibili; PNG scaricato',
        copyFallback: 'Appunti non disponibili; frammento HTML scaricato',
      },
      share: {
        tooLongHint: 'Troppo lungo da condividere; esporta il codice o un’immagine',
      },
      stats: '{{chars}} caratteri · {{lines}} righe · {{bytes}} byte',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la digitazione',
      placeholder: 'Incolla o scrivi il codice qui…',
      empty: 'L’anteprima appare dopo aver scritto il codice',
      err: {
        EMPTY: 'Inserisci prima del codice',
        TOO_LARGE: 'Il file supera il limite di {{max}} MB',
        UNSUPPORTED: 'Il testo semplice non va formattato',
        READ_FAILED: 'Lettura del file non riuscita',
        FORMAT_FAILED: 'Formattazione non riuscita, controlla la sintassi',
        EXPORT_FAILED: 'Esportazione non riuscita, riprova',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Lenguaje',
      theme: 'Tema',
      indent: 'Sangría',
      indent2: '2 espacios',
      indent4: '4 espacios',
      indentTab: 'Tabulación',
      lineNumbers: 'Números de línea',
      wordWrap: 'Ajuste de línea',
      wrapHint: 'Los números de línea se ocultan con el ajuste de línea',
      editor: 'Editor',
      preview: 'Vista previa de exportación',
      import: 'Importar archivo',
      importHint: 'Arrastra o elige un archivo de código',
      importFormats: 'El idioma se detecta por la extensión (.java / .rs / .py)',
      format: 'Formatear',
      formatting: 'Formateando…',
      formatDone: 'Formateado',
      formatFallback: 'Prettier no disponible, se usó el formateador integrado',
      filename: 'Nombre del archivo',
      finalName: 'Se exportará como {{name}}',
      exportSource: 'Exportar {{ext}}',
      exportHtml: 'Exportar HTML',
      exportPng: 'Exportar PNG',
      exportJpg: 'Exportar JPG',
      exportSvg: 'Exportar SVG',
      exporting: 'Exportando…',
      copyCode: 'Copiar código',
      copyHtml: 'Copiar HTML',
      clear: 'Vaciar',
      op: {
        comment: 'Comentar',
        moveUp: 'Subir línea',
        moveDown: 'Bajar línea',
        duplicate: 'Duplicar línea',
        deleteLine: 'Eliminar línea',
        transpose: 'Transponer línea',
        indent: 'Aumentar sangría',
        outdent: 'Reducir sangría',
        gotoLine: 'Ir a la línea',
        selectOccurrences: 'Seleccionar coincidencias',
        multiLabel: 'Reemplazar en todas',
        multiHits: '{{ranges}} apariciones',
        multiApply: 'Aplicar',
        multiCancel: 'Cancelar',
        multiNoWord: 'El cursor no está sobre una palabra reemplazable en bloque',
        hint: 'Atajos',
        unsupported: 'Este lenguaje no admite esa acción de comentario',
      },
      find: {
        label: 'Buscar',
        replaceLabel: 'Reemplazar por',
        caseSensitive: 'Distinguir mayúsculas',
        wholeWord: 'Palabra completa',
        regex: 'Expresión regular',
        prev: 'Coincidencia anterior',
        next: 'Coincidencia siguiente',
        replaceOne: 'Reemplazar',
        replaceAll: 'Reemplazar todo',
        noMatch: 'Sin resultados',
        invalid: 'Expresión regular no válida',
        truncated: 'Demasiadas coincidencias: se muestran las primeras 5000',
        tooMany: 'Demasiadas coincidencias para reemplazar de una vez',
        done: 'Reemplazadas todas',
        close: 'Cerrar la barra de búsqueda',
      },
      fold: {
        lines: '{{lines}} líneas',
        copy: 'Copiar el rango',
        toggle: 'Rango plegable ({{lines}} líneas)',
        clear: 'Quitar el rango plegable',
        note: 'El plegado se muestra como marca de rango (no se admite ocultar líneas)',
      },
      card: {
        title: 'Estilo de tarjeta',
        window: 'Ventana',
        window_mac: 'Semáforo',
        window_title: 'Barra de título',
        window_plain: 'Panel liso',
        window_none: 'Sin borde',
        padding: 'Margen',
        radius: 'Radio',
        shadow: 'Sombra',
        shadow_none: 'Ninguna',
        shadow_soft: 'Suave',
        shadow_medium: 'Media',
        shadow_strong: 'Fuerte',
        background: 'Fondo',
        bg_theme: 'Seguir el tema',
        bg_gradient: 'Degradado',
        bg_grid: 'Cuadrícula',
        bg_transparent: 'Transparente',
        fontSize: 'Tamaño de fuente',
        highlightLines: 'Líneas resaltadas',
        highlightHint: 'p. ej. 2-5',
        watermark: 'Marca de agua',
        watermarkOpacity: 'Opacidad de la marca',
        scale: 'Escala de exportación',
      },
      copy: {
        markdown: 'Copiar Markdown',
        richText: 'Copiar texto enriquecido',
        image: 'Copiar imagen',
        richDone: 'Texto enriquecido copiado',
        plainDone: 'Texto enriquecido no admitido; se copió texto sin formato',
        imageDone: 'Imagen copiada',
        imageFallback: 'Portapapeles no disponible; se descargó el PNG',
        copyFallback: 'Portapapeles no disponible; se descargó el fragmento HTML',
      },
      share: {
        tooLongHint: 'Demasiado largo para compartir; exporta el código o una imagen',
      },
      stats: '{{chars}} caracteres · {{lines}} líneas · {{bytes}} bytes',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de escribir',
      placeholder: 'Pega o escribe código aquí…',
      empty: 'La vista previa aparece al escribir código',
      err: {
        EMPTY: 'Introduce código primero',
        TOO_LARGE: 'El archivo supera el límite de {{max}} MB',
        UNSUPPORTED: 'El texto plano no necesita formato',
        READ_FAILED: 'No se pudo leer el archivo',
        FORMAT_FAILED: 'Formato fallido, revisa la sintaxis',
        EXPORT_FAILED: 'Exportación fallida, inténtalo de nuevo',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Linguagem',
      theme: 'Tema',
      indent: 'Indentação',
      indent2: '2 espaços',
      indent4: '4 espaços',
      indentTab: 'Tabulação',
      lineNumbers: 'Números de linha',
      wordWrap: 'Quebra de linha',
      wrapHint: 'Os números de linha são ocultados com a quebra de linha',
      editor: 'Editor',
      preview: 'Pré-visualização da exportação',
      import: 'Importar ficheiro',
      importHint: 'Arraste ou escolha um ficheiro de código',
      importFormats: 'O idioma é detetado pela extensão (.java / .rs / .py)',
      format: 'Formatar',
      formatting: 'A formatar…',
      formatDone: 'Formatado',
      formatFallback: 'Motor Prettier indisponível, usado o formatador integrado',
      filename: 'Nome do ficheiro',
      finalName: 'Será exportado como {{name}}',
      exportSource: 'Exportar {{ext}}',
      exportHtml: 'Exportar HTML',
      exportPng: 'Exportar PNG',
      exportJpg: 'Exportar JPG',
      exportSvg: 'Exportar SVG',
      exporting: 'A exportar…',
      copyCode: 'Copiar código',
      copyHtml: 'Copiar HTML',
      clear: 'Limpar',
      op: {
        comment: 'Comentar',
        moveUp: 'Mover linha para cima',
        moveDown: 'Mover linha para baixo',
        duplicate: 'Duplicar linha',
        deleteLine: 'Eliminar linha',
        transpose: 'Transpor linha',
        indent: 'Aumentar indentação',
        outdent: 'Reduzir indentação',
        gotoLine: 'Ir para a linha',
        selectOccurrences: 'Selecionar ocorrências',
        multiLabel: 'Substituir em todas',
        multiHits: '{{ranges}} ocorrências',
        multiApply: 'Aplicar',
        multiCancel: 'Cancelar',
        multiNoWord: 'O cursor não está sobre uma palavra substituível em bloco',
        hint: 'Atalhos',
        unsupported: 'Esta linguagem não suporta esta ação de comentário',
      },
      find: {
        label: 'Localizar',
        replaceLabel: 'Substituir por',
        caseSensitive: 'Distinguir maiúsculas',
        wholeWord: 'Palavra inteira',
        regex: 'Expressão regular',
        prev: 'Ocorrência anterior',
        next: 'Ocorrência seguinte',
        replaceOne: 'Substituir',
        replaceAll: 'Substituir tudo',
        noMatch: 'Sem resultados',
        invalid: 'Expressão regular inválida',
        truncated: 'Demasiadas ocorrências: são mostradas as primeiras 5000',
        tooMany: 'Demasiadas ocorrências para substituir de uma vez',
        done: 'Tudo substituído',
        close: 'Fechar a barra de pesquisa',
      },
      fold: {
        lines: '{{lines}} linhas',
        copy: 'Copiar o intervalo',
        toggle: 'Intervalo recolhível ({{lines}} linhas)',
        clear: 'Limpar o intervalo recolhível',
        note: 'A recolha é apresentada como marca de intervalo (ocultar linhas não é suportado)',
      },
      card: {
        title: 'Estilo do cartão',
        window: 'Janela',
        window_mac: 'Semáforo',
        window_title: 'Barra de título',
        window_plain: 'Painel liso',
        window_none: 'Sem moldura',
        padding: 'Margem',
        radius: 'Raio',
        shadow: 'Sombra',
        shadow_none: 'Nenhuma',
        shadow_soft: 'Suave',
        shadow_medium: 'Média',
        shadow_strong: 'Forte',
        background: 'Fundo',
        bg_theme: 'Seguir o tema',
        bg_gradient: 'Gradiente',
        bg_grid: 'Grelha',
        bg_transparent: 'Transparente',
        fontSize: 'Tamanho da letra',
        highlightLines: 'Linhas destacadas',
        highlightHint: 'ex. 2-5',
        watermark: 'Marca de água',
        watermarkOpacity: 'Opacidade da marca de água',
        scale: 'Escala de exportação',
      },
      copy: {
        markdown: 'Copiar Markdown',
        richText: 'Copiar texto formatado',
        image: 'Copiar imagem',
        richDone: 'Texto formatado copiado',
        plainDone: 'Texto formatado não suportado; copiado texto simples',
        imageDone: 'Imagem copiada',
        imageFallback: 'Área de transferência indisponível; PNG descarregado',
        copyFallback: 'Área de transferência indisponível; fragmento HTML descarregado',
      },
      share: {
        tooLongHint: 'Longo demais para partilhar; exporte o código ou uma imagem',
      },
      stats: '{{chars}} caracteres · {{lines}} linhas · {{bytes}} bytes',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de escrever',
      placeholder: 'Cole ou escreva código aqui…',
      empty: 'A pré-visualização aparece após escrever código',
      err: {
        EMPTY: 'Introduza código primeiro',
        TOO_LARGE: 'O ficheiro excede o limite de {{max}} MB',
        UNSUPPORTED: 'Texto simples não precisa de formatação',
        READ_FAILED: 'Falha ao ler o ficheiro',
        FORMAT_FAILED: 'Formatação falhou, verifique a sintaxe',
        EXPORT_FAILED: 'Exportação falhou, tente novamente',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const codeEditorStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具懒加载时调用，键路径 tools.codeEditor.*） */
export function registerCodeEditorStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(codeEditorStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
