/**
 * 代码编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 *
 * 与 rich-text-editor / slide-editor / photo-editor 保持同一套约定：
 * 项目的 zh / en 语言包是首屏同步资源，本工具几十条文案若写进
 * `core/i18n/locales/*` 会直接推高首屏入口体积（预算 210KB，实测已接近上限）。
 * 因此文案放在这里，由 `registerCodeEditorStrings` 在工具被懒加载时合并进 i18next，
 * 键路径 `tools.codeEditor.*`。工具元数据（名称 / 描述）仍写在 locales 的 `toolsMeta` 中。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { codeEditor: StringTree } };

const zh: ResourceTree = {
  tools: {
    codeEditor: {
      language: '语言',
      theme: '风格主题',
      indent: '缩进',
      indent2: '2 空格',
      indent4: '4 空格',
      indentTab: 'Tab',
      lineNumbers: '行号',
      wordWrap: '自动换行',
      wrapHint: '自动换行时行号不显示',
      editor: '编辑器',
      preview: '导出预览',
      import: '导入文件',
      importHint: '拖入或选择源码文件',
      importFormats: '按扩展名自动识别语言（如 .java / .rs / .py）',
      format: '格式化',
      formatting: '格式化中…',
      formatDone: '已格式化',
      formatFallback: 'Prettier 引擎不可用，已使用内置格式化器',
      filename: '文件名',
      finalName: '将导出为 {{name}}',
      exportSource: '导出 {{ext}}',
      exportHtml: '导出 HTML',
      exportPng: '导出 PNG',
      exportJpg: '导出 JPG',
      exportSvg: '导出 SVG',
      exporting: '导出中…',
      copyCode: '复制代码',
      copyHtml: '复制 HTML',
      clear: '清空',
      stats: '{{chars}} 字符 · {{lines}} 行 · {{bytes}} 字节',
      saved: '已保存到本地草稿',
      saving: '停止输入后自动保存',
      placeholder: '在此粘贴或编写代码…',
      empty: '输入代码后在此显示导出预览',
      err: {
        EMPTY: '请先输入代码',
        TOO_LARGE: '文件超过 {{max}}MB 限制',
        UNSUPPORTED: '纯文本无需格式化',
        READ_FAILED: '文件读取失败',
        FORMAT_FAILED: '格式化失败，请检查代码语法',
        EXPORT_FAILED: '导出失败，请重试',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Language',
      theme: 'Theme',
      indent: 'Indent',
      indent2: '2 spaces',
      indent4: '4 spaces',
      indentTab: 'Tab',
      lineNumbers: 'Line numbers',
      wordWrap: 'Word wrap',
      wrapHint: 'Line numbers are hidden while word wrap is on',
      editor: 'Editor',
      preview: 'Export preview',
      import: 'Import file',
      importHint: 'Drop or pick a source file',
      importFormats: 'Language is detected from the extension (.java / .rs / .py)',
      format: 'Format',
      formatting: 'Formatting…',
      formatDone: 'Formatted',
      formatFallback: 'Prettier engine unavailable, built-in formatter used',
      filename: 'Filename',
      finalName: 'Exports as {{name}}',
      exportSource: 'Export {{ext}}',
      exportHtml: 'Export HTML',
      exportPng: 'Export PNG',
      exportJpg: 'Export JPG',
      exportSvg: 'Export SVG',
      exporting: 'Exporting…',
      copyCode: 'Copy code',
      copyHtml: 'Copy HTML',
      clear: 'Clear',
      stats: '{{chars}} chars · {{lines}} lines · {{bytes}} bytes',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop typing',
      placeholder: 'Paste or write code here…',
      empty: 'Export preview appears once you type',
      err: {
        EMPTY: 'Please enter some code first',
        TOO_LARGE: 'File exceeds the {{max}}MB limit',
        UNSUPPORTED: 'Plain text has nothing to format',
        READ_FAILED: 'Failed to read the file',
        FORMAT_FAILED: 'Formatting failed, please check the syntax',
        EXPORT_FAILED: 'Export failed, please try again',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    codeEditor: {
      language: '語言',
      theme: '風格主題',
      indent: '縮排',
      indent2: '2 空格',
      indent4: '4 空格',
      indentTab: 'Tab',
      lineNumbers: '行號',
      wordWrap: '自動換行',
      wrapHint: '自動換行時不顯示行號',
      editor: '編輯器',
      preview: '匯出預覽',
      import: '匯入檔案',
      importHint: '拖曳或選擇原始碼檔案',
      importFormats: '依副檔名自動辨識語言（如 .java / .rs / .py）',
      format: '格式化',
      formatting: '格式化中…',
      formatDone: '已格式化',
      formatFallback: 'Prettier 引擎不可用，已改用內建格式化器',
      filename: '檔案名稱',
      finalName: '將匯出為 {{name}}',
      exportSource: '匯出 {{ext}}',
      exportHtml: '匯出 HTML',
      exportPng: '匯出 PNG',
      exportJpg: '匯出 JPG',
      exportSvg: '匯出 SVG',
      exporting: '匯出中…',
      copyCode: '複製程式碼',
      copyHtml: '複製 HTML',
      clear: '清空',
      stats: '{{chars}} 字元 · {{lines}} 行 · {{bytes}} 位元組',
      saved: '已儲存至本機草稿',
      saving: '停止輸入後自動儲存',
      placeholder: '在此貼上或撰寫程式碼…',
      empty: '輸入程式碼後於此顯示匯出預覽',
      err: {
        EMPTY: '請先輸入程式碼',
        TOO_LARGE: '檔案超過 {{max}}MB 限制',
        UNSUPPORTED: '純文字無需格式化',
        READ_FAILED: '檔案讀取失敗',
        FORMAT_FAILED: '格式化失敗，請檢查語法',
        EXPORT_FAILED: '匯出失敗，請重試',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    codeEditor: {
      language: '言語',
      theme: 'テーマ',
      indent: 'インデント',
      indent2: '2 スペース',
      indent4: '4 スペース',
      indentTab: 'タブ',
      lineNumbers: '行番号',
      wordWrap: '折り返し',
      wrapHint: '折り返し時は行番号を非表示',
      editor: 'エディター',
      preview: '書き出しプレビュー',
      import: 'ファイルを読み込む',
      importHint: 'ソースファイルをドロップまたは選択',
      importFormats: '拡張子から言語を自動判定（.java / .rs / .py など）',
      format: '整形',
      formatting: '整形中…',
      formatDone: '整形しました',
      formatFallback: 'Prettier を利用できないため内蔵整形を使用しました',
      filename: 'ファイル名',
      finalName: '{{name}} として書き出し',
      exportSource: '{{ext}} を書き出し',
      exportHtml: 'HTML を書き出し',
      exportPng: 'PNG を書き出し',
      exportJpg: 'JPG を書き出し',
      exportSvg: 'SVG を書き出し',
      exporting: '書き出し中…',
      copyCode: 'コードをコピー',
      copyHtml: 'HTML をコピー',
      clear: 'クリア',
      stats: '{{chars}} 文字 · {{lines}} 行 · {{bytes}} バイト',
      saved: 'ローカル下書きに保存しました',
      saving: '入力を止めると自動保存します',
      placeholder: 'ここにコードを貼り付け、または記述…',
      empty: 'コードを入力すると書き出しプレビューが表示されます',
      err: {
        EMPTY: '先にコードを入力してください',
        TOO_LARGE: 'ファイルが {{max}}MB の上限を超えています',
        UNSUPPORTED: 'プレーンテキストは整形できません',
        READ_FAILED: 'ファイルの読み込みに失敗しました',
        FORMAT_FAILED: '整形に失敗しました。構文を確認してください',
        EXPORT_FAILED: '書き出しに失敗しました。もう一度お試しください',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Langage',
      theme: 'Thème',
      indent: 'Indentation',
      indent2: '2 espaces',
      indent4: '4 espaces',
      indentTab: 'Tabulation',
      lineNumbers: 'Numéros de ligne',
      wordWrap: 'Retour à la ligne',
      wrapHint: 'Les numéros de ligne sont masqués avec le retour à la ligne',
      editor: 'Éditeur',
      preview: 'Aperçu d’export',
      import: 'Importer un fichier',
      importHint: 'Déposez ou choisissez un fichier source',
      importFormats: 'Langage détecté depuis l’extension (.java / .rs / .py)',
      format: 'Formater',
      formatting: 'Formatage…',
      formatDone: 'Formaté',
      formatFallback: 'Moteur Prettier indisponible, formateur intégré utilisé',
      filename: 'Nom du fichier',
      finalName: 'Sera exporté en {{name}}',
      exportSource: 'Exporter {{ext}}',
      exportHtml: 'Exporter HTML',
      exportPng: 'Exporter PNG',
      exportJpg: 'Exporter JPG',
      exportSvg: 'Exporter SVG',
      exporting: 'Export…',
      copyCode: 'Copier le code',
      copyHtml: 'Copier le HTML',
      clear: 'Effacer',
      stats: '{{chars}} caractères · {{lines}} lignes · {{bytes}} octets',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement automatique après la saisie',
      placeholder: 'Collez ou écrivez du code ici…',
      empty: 'L’aperçu d’export s’affiche après la saisie',
      err: {
        EMPTY: 'Veuillez d’abord saisir du code',
        TOO_LARGE: 'Le fichier dépasse la limite de {{max}} Mo',
        UNSUPPORTED: 'Le texte brut n’a rien à formater',
        READ_FAILED: 'Échec de la lecture du fichier',
        FORMAT_FAILED: 'Formatage impossible, vérifiez la syntaxe',
        EXPORT_FAILED: 'Échec de l’export, réessayez',
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Sprache',
      theme: 'Farbschema',
      indent: 'Einrückung',
      indent2: '2 Leerzeichen',
      indent4: '4 Leerzeichen',
      indentTab: 'Tab',
      lineNumbers: 'Zeilennummern',
      wordWrap: 'Zeilenumbruch',
      wrapHint: 'Bei Zeilenumbruch werden Zeilennummern ausgeblendet',
      editor: 'Editor',
      preview: 'Exportvorschau',
      import: 'Datei importieren',
      importHint: 'Quelldatei hierher ziehen oder auswählen',
      importFormats: 'Sprache wird an der Endung erkannt (.java / .rs / .py)',
      format: 'Formatieren',
      formatting: 'Formatiere…',
      formatDone: 'Formatiert',
      formatFallback: 'Prettier nicht verfügbar, integrierter Formatter verwendet',
      filename: 'Dateiname',
      finalName: 'Wird als {{name}} exportiert',
      exportSource: '{{ext}} exportieren',
      exportHtml: 'HTML exportieren',
      exportPng: 'PNG exportieren',
      exportJpg: 'JPG exportieren',
      exportSvg: 'SVG exportieren',
      exporting: 'Exportiere…',
      copyCode: 'Code kopieren',
      copyHtml: 'HTML kopieren',
      clear: 'Leeren',
      stats: '{{chars}} Zeichen · {{lines}} Zeilen · {{bytes}} Bytes',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Eingabe',
      placeholder: 'Code hier einfügen oder schreiben…',
      empty: 'Die Exportvorschau erscheint nach der Eingabe',
      err: {
        EMPTY: 'Bitte zuerst Code eingeben',
        TOO_LARGE: 'Datei überschreitet das Limit von {{max}} MB',
        UNSUPPORTED: 'Klartext muss nicht formatiert werden',
        READ_FAILED: 'Datei konnte nicht gelesen werden',
        FORMAT_FAILED: 'Formatierung fehlgeschlagen, Syntax prüfen',
        EXPORT_FAILED: 'Export fehlgeschlagen, bitte erneut versuchen',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Linguaggio',
      theme: 'Tema',
      indent: 'Rientro',
      indent2: '2 spazi',
      indent4: '4 spazi',
      indentTab: 'Tabulazione',
      lineNumbers: 'Numeri di riga',
      wordWrap: 'Ritorno a capo',
      wrapHint: 'Con il ritorno a capo i numeri di riga sono nascosti',
      editor: 'Editor',
      preview: 'Anteprima di esportazione',
      import: 'Importa file',
      importHint: 'Trascina o scegli un file sorgente',
      importFormats: 'Linguaggio rilevato dall’estensione (.java / .rs / .py)',
      format: 'Formatta',
      formatting: 'Formattazione…',
      formatDone: 'Formattato',
      formatFallback: 'Motore Prettier non disponibile, usato il formattatore integrato',
      filename: 'Nome file',
      finalName: 'Verrà esportato come {{name}}',
      exportSource: 'Esporta {{ext}}',
      exportHtml: 'Esporta HTML',
      exportPng: 'Esporta PNG',
      exportJpg: 'Esporta JPG',
      exportSvg: 'Esporta SVG',
      exporting: 'Esportazione…',
      copyCode: 'Copia codice',
      copyHtml: 'Copia HTML',
      clear: 'Svuota',
      stats: '{{chars}} caratteri · {{lines}} righe · {{bytes}} byte',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la digitazione',
      placeholder: 'Incolla o scrivi il codice qui…',
      empty: 'L’anteprima appare dopo aver scritto il codice',
      err: {
        EMPTY: 'Inserisci prima del codice',
        TOO_LARGE: 'Il file supera il limite di {{max}} MB',
        UNSUPPORTED: 'Il testo semplice non va formattato',
        READ_FAILED: 'Lettura del file non riuscita',
        FORMAT_FAILED: 'Formattazione non riuscita, controlla la sintassi',
        EXPORT_FAILED: 'Esportazione non riuscita, riprova',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Lenguaje',
      theme: 'Tema',
      indent: 'Sangría',
      indent2: '2 espacios',
      indent4: '4 espacios',
      indentTab: 'Tabulación',
      lineNumbers: 'Números de línea',
      wordWrap: 'Ajuste de línea',
      wrapHint: 'Los números de línea se ocultan con el ajuste de línea',
      editor: 'Editor',
      preview: 'Vista previa de exportación',
      import: 'Importar archivo',
      importHint: 'Arrastra o elige un archivo de código',
      importFormats: 'El idioma se detecta por la extensión (.java / .rs / .py)',
      format: 'Formatear',
      formatting: 'Formateando…',
      formatDone: 'Formateado',
      formatFallback: 'Prettier no disponible, se usó el formateador integrado',
      filename: 'Nombre del archivo',
      finalName: 'Se exportará como {{name}}',
      exportSource: 'Exportar {{ext}}',
      exportHtml: 'Exportar HTML',
      exportPng: 'Exportar PNG',
      exportJpg: 'Exportar JPG',
      exportSvg: 'Exportar SVG',
      exporting: 'Exportando…',
      copyCode: 'Copiar código',
      copyHtml: 'Copiar HTML',
      clear: 'Vaciar',
      stats: '{{chars}} caracteres · {{lines}} líneas · {{bytes}} bytes',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de escribir',
      placeholder: 'Pega o escribe código aquí…',
      empty: 'La vista previa aparece al escribir código',
      err: {
        EMPTY: 'Introduce código primero',
        TOO_LARGE: 'El archivo supera el límite de {{max}} MB',
        UNSUPPORTED: 'El texto plano no necesita formato',
        READ_FAILED: 'No se pudo leer el archivo',
        FORMAT_FAILED: 'Formato fallido, revisa la sintaxis',
        EXPORT_FAILED: 'Exportación fallida, inténtalo de nuevo',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    codeEditor: {
      language: 'Linguagem',
      theme: 'Tema',
      indent: 'Indentação',
      indent2: '2 espaços',
      indent4: '4 espaços',
      indentTab: 'Tabulação',
      lineNumbers: 'Números de linha',
      wordWrap: 'Quebra de linha',
      wrapHint: 'Os números de linha são ocultados com a quebra de linha',
      editor: 'Editor',
      preview: 'Pré-visualização da exportação',
      import: 'Importar ficheiro',
      importHint: 'Arraste ou escolha um ficheiro de código',
      importFormats: 'O idioma é detetado pela extensão (.java / .rs / .py)',
      format: 'Formatar',
      formatting: 'A formatar…',
      formatDone: 'Formatado',
      formatFallback: 'Motor Prettier indisponível, usado o formatador integrado',
      filename: 'Nome do ficheiro',
      finalName: 'Será exportado como {{name}}',
      exportSource: 'Exportar {{ext}}',
      exportHtml: 'Exportar HTML',
      exportPng: 'Exportar PNG',
      exportJpg: 'Exportar JPG',
      exportSvg: 'Exportar SVG',
      exporting: 'A exportar…',
      copyCode: 'Copiar código',
      copyHtml: 'Copiar HTML',
      clear: 'Limpar',
      stats: '{{chars}} caracteres · {{lines}} linhas · {{bytes}} bytes',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de escrever',
      placeholder: 'Cole ou escreva código aqui…',
      empty: 'A pré-visualização aparece após escrever código',
      err: {
        EMPTY: 'Introduza código primeiro',
        TOO_LARGE: 'O ficheiro excede o limite de {{max}} MB',
        UNSUPPORTED: 'Texto simples não precisa de formatação',
        READ_FAILED: 'Falha ao ler o ficheiro',
        FORMAT_FAILED: 'Formatação falhou, verifique a sintaxe',
        EXPORT_FAILED: 'Exportação falhou, tente novamente',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const codeEditorStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具懒加载时调用，键路径 tools.codeEditor.*） */
export function registerCodeEditorStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(codeEditorStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
