/**
 * 富文本编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 *
 * 背景：项目的语言包 zh / en 是首屏同步资源（`SYNC_LANGS`），
 * 单个工具几十条 UI 文案若全部写进 `core/i18n/locales/*`，会直接推高首屏入口体积
 * （本项目预算：首屏 gzip ≤ 180KB，实测已接近上限）。
 * 因此本工具的界面文案放在这里，在工具被懒加载时由 `registerRichTextStrings` 合并进 i18next，
 * 键路径保持不变（`tools.richText.*`），且保留 10 种语言。
 *
 * 注意：工具元数据（名称/描述）仍写在 `core/i18n/locales/*` 的 `toolsMeta` 中，
 * 因为首页卡片、侧边栏与 ⌘K 搜索在工具加载前就要用到。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { richText: StringTree } };

const zh: ResourceTree = {
  tools: {
    richText: {
      docTitle: '文档标题',
      titlePlaceholder: '未命名文档',
      importHint: '拖入或选择 .docx 文件导入 Word 内容',
      placeholder: '开始撰写正文…（支持 Word 导入与 PDF 导出）',
      chars: '字符',
      words: '词数',
      paragraphs: '段落',
      saved: '已保存到本地草稿',
      saving: '停止输入后自动保存',
      undo: '撤销',
      redo: '重做',
      paragraph: '正文段落',
      h1: '一级标题',
      h2: '二级标题',
      h3: '三级标题',
      bold: '加粗',
      italic: '斜体',
      underline: '下划线',
      strike: '删除线',
      code: '行内代码',
      color: '字体颜色',
      highlight: '荧光笔',
      bulletList: '无序列表',
      orderedList: '有序列表',
      taskList: '任务清单',
      quote: '引用',
      codeBlock: '代码块',
      link: '链接',
      linkPrompt: '输入链接地址（留空则移除）',
      image: '插入图片',
      divider: '分割线',
      table: '插入表格',
      alignLeft: '左对齐',
      alignCenter: '居中对齐',
      alignRight: '右对齐',
      alignJustify: '两端对齐',
      pdfMode: 'PDF 模式',
      modeText: '文字版（可选可搜索）',
      modeSnapshot: '截图版（样式高保真）',
      modeTextHint: '经浏览器打印导出：文字可选中检索，中文不会乱码',
      modeSnapshotHint: '按 A4 分页截图后合成，视觉效果与编辑器一致',
      exportDocx: '导出 Word (.docx)',
      exportPdf: '导出 PDF',
      exporting: '导出中…',
      err: {
        EMPTY: '文档内容为空',
        UNSUPPORTED_LEGACY_DOC: '暂不支持旧版 .doc / .wps / .rtf 格式，请另存为 .docx 后重试',
        NOT_DOCX: '仅支持 .docx 文件',
        TOO_LARGE: '内容超出 {{max}}MB 限制',
        IMPORT_FAILED: '文档解析失败',
        EXPORT_FAILED: 'Word 导出失败',
        RENDER_FAILED: '排版渲染失败',
        SNAPSHOT_FAILED: 'PDF 截图生成失败',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Title',
      titlePlaceholder: 'Untitled document',
      importHint: 'Drop or pick a .docx file to import Word content',
      placeholder: 'Start writing… (Word import and PDF export supported)',
      chars: 'Characters',
      words: 'Words',
      paragraphs: 'Paragraphs',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop typing',
      undo: 'Undo',
      redo: 'Redo',
      paragraph: 'Body text',
      h1: 'Heading 1',
      h2: 'Heading 2',
      h3: 'Heading 3',
      bold: 'Bold',
      italic: 'Italic',
      underline: 'Underline',
      strike: 'Strikethrough',
      code: 'Inline code',
      color: 'Text color',
      highlight: 'Highlight',
      bulletList: 'Bulleted list',
      orderedList: 'Numbered list',
      taskList: 'Task list',
      quote: 'Quote',
      codeBlock: 'Code block',
      link: 'Link',
      linkPrompt: 'Enter link URL (empty to remove)',
      image: 'Insert image',
      divider: 'Divider',
      table: 'Insert table',
      alignLeft: 'Align left',
      alignCenter: 'Align center',
      alignRight: 'Align right',
      alignJustify: 'Justify',
      pdfMode: 'PDF mode',
      modeText: 'Text (selectable & searchable)',
      modeSnapshot: 'Snapshot (pixel-perfect)',
      modeTextHint: 'Exported via browser print: text stays selectable and CJK renders correctly',
      modeSnapshotHint: 'Rasterized page by page at A4 size, identical to the editor',
      exportDocx: 'Export Word (.docx)',
      exportPdf: 'Export PDF',
      exporting: 'Exporting…',
      err: {
        EMPTY: 'The document is empty',
        UNSUPPORTED_LEGACY_DOC:
          'Legacy .doc / .wps / .rtf files are not supported, please save as .docx',
        NOT_DOCX: 'Only .docx files are supported',
        TOO_LARGE: 'Content exceeds the {{max}}MB limit',
        IMPORT_FAILED: 'Failed to parse the document',
        EXPORT_FAILED: 'Word export failed',
        RENDER_FAILED: 'Rendering failed',
        SNAPSHOT_FAILED: 'Failed to generate the PDF snapshot',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    richText: {
      docTitle: '文檔標題',
      titlePlaceholder: '未命名文檔',
      importHint: '拖曳或選擇 .docx 檔案匯入 Word 內容',
      placeholder: '開始撰寫正文…（支援 Word 匯入與 PDF 匯出）',
      chars: '字元',
      words: '字數',
      paragraphs: '段落',
      saved: '已儲存至本機草稿',
      saving: '停止輸入後自動儲存',
      undo: '復原',
      redo: '重做',
      paragraph: '本文段落',
      h1: '一級標題',
      h2: '二級標題',
      h3: '三級標題',
      bold: '粗體',
      italic: '斜體',
      underline: '底線',
      strike: '刪除線',
      code: '行內程式碼',
      color: '文字顏色',
      highlight: '螢光筆',
      bulletList: '項目符號清單',
      orderedList: '編號清單',
      taskList: '任務清單',
      quote: '引用',
      codeBlock: '程式碼區塊',
      link: '連結',
      linkPrompt: '輸入連結網址（留空則移除）',
      image: '插入圖片',
      divider: '分隔線',
      table: '插入表格',
      alignLeft: '靠左對齊',
      alignCenter: '置中對齊',
      alignRight: '靠右對齊',
      alignJustify: '左右對齊',
      pdfMode: 'PDF 模式',
      modeText: '文字版（可選可取並可搜尋）',
      modeSnapshot: '截圖版（樣式高保真）',
      modeTextHint: '透過瀏覽器列印匯出，文字可選取，中文不會亂碼',
      modeSnapshotHint: '依 A4 分頁截圖後合成，視覺與編輯器一致',
      exportDocx: '匯出 Word (.docx)',
      exportPdf: '匯出 PDF',
      exporting: '匯出中…',
      err: {
        EMPTY: '文檔內容為空',
        UNSUPPORTED_LEGACY_DOC: '不支援舊版 .doc / .wps / .rtf，請另存為 .docx 後再試',
        NOT_DOCX: '僅支援 .docx 檔案',
        TOO_LARGE: '內容超過 {{max}}MB 限制',
        IMPORT_FAILED: '文檔解析失敗',
        EXPORT_FAILED: 'Word 匯出失敗',
        RENDER_FAILED: '排版失敗',
        SNAPSHOT_FAILED: 'PDF 截圖產生失敗',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'タイトル',
      titlePlaceholder: '無題の文書',
      importHint: '.docx ファイルをドロップまたは選択して Word の内容を読み込む',
      placeholder: '本文を書き始めましょう…（Word 読み込みと PDF 書き出しに対応）',
      chars: '文字数',
      words: '単語数',
      paragraphs: '段落数',
      saved: 'ローカル下書きに保存しました',
      saving: '入力を止めると自動保存します',
      undo: '元に戻す',
      redo: 'やり直す',
      paragraph: '本文',
      h1: '見出し 1',
      h2: '見出し 2',
      h3: '見出し 3',
      bold: '太字',
      italic: '斜体',
      underline: '下線',
      strike: '取り消し線',
      code: 'インラインコード',
      color: '文字色',
      highlight: 'ハイライト',
      bulletList: '箇条書き',
      orderedList: '番号付きリスト',
      taskList: 'タスクリスト',
      quote: '引用',
      codeBlock: 'コードブロック',
      link: 'リンク',
      linkPrompt: 'リンク先 URL を入力（空欄で解除）',
      image: '画像を挿入',
      divider: '区切り線',
      table: '表を挿入',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      alignJustify: '両端揃え',
      pdfMode: 'PDF モード',
      modeText: 'テキスト版（選択・検索可）',
      modeSnapshot: 'スナップショット版（見た目をそのまま保持）',
      modeTextHint: 'ブラウザの印刷から書き出すため、文字は選択でき、日本語も文字化けしません',
      modeSnapshotHint:
        'A4 サイズでページごとに画像化して合成するため、エディターと同じ見た目になります',
      exportDocx: 'Word (.docx) を書き出し',
      exportPdf: 'PDF を書き出し',
      exporting: '書き出し中…',
      err: {
        EMPTY: '文書が空です',
        UNSUPPORTED_LEGACY_DOC:
          '旧形式の .doc / .wps / .rtf には対応していません。.docx で保存し直してください',
        NOT_DOCX: '.docx ファイルのみ対応しています',
        TOO_LARGE: '内容が {{max}}MB の上限を超えています',
        IMPORT_FAILED: '文書の解析に失敗しました',
        EXPORT_FAILED: 'Word 書き出しに失敗しました',
        RENDER_FAILED: 'レイアウトの描画に失敗しました',
        SNAPSHOT_FAILED: 'PDF スナップショットの生成に失敗しました',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Titre',
      titlePlaceholder: 'Document sans titre',
      importHint: 'Déposez ou choisissez un fichier .docx pour importer le contenu Word',
      placeholder: 'Commencez à écrire… (import Word et export PDF pris en charge)',
      chars: 'Caractères',
      words: 'Mots',
      paragraphs: 'Paragraphes',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement automatique après la saisie',
      undo: 'Annuler',
      redo: 'Rétablir',
      paragraph: 'Corps du texte',
      h1: 'Titre 1',
      h2: 'Titre 2',
      h3: 'Titre 3',
      bold: 'Gras',
      italic: 'Italique',
      underline: 'Souligné',
      strike: 'Barré',
      code: 'Code en ligne',
      color: 'Couleur du texte',
      highlight: 'Surligner',
      bulletList: 'Liste à puces',
      orderedList: 'Liste numérotée',
      taskList: 'Liste de tâches',
      quote: 'Citation',
      codeBlock: 'Bloc de code',
      link: 'Lien',
      linkPrompt: "Saisissez l'URL du lien (vide pour supprimer)",
      image: 'Insérer une image',
      divider: 'Séparateur',
      table: 'Insérer un tableau',
      alignLeft: 'Aligné à gauche',
      alignCenter: 'Centré',
      alignRight: 'Aligné à droite',
      alignJustify: 'Justifié',
      pdfMode: 'Mode PDF',
      modeText: 'Texte (sélectionnable et recherchable)',
      modeSnapshot: 'Capture (rendu fidèle)',
      modeTextHint:
        "Exporté via l'impression du navigateur : le texte reste sélectionnable et le CJK s'affiche correctement",
      modeSnapshotHint: "Rastérisé page par page au format A4, identique à l'éditeur",
      exportDocx: 'Exporter Word (.docx)',
      exportPdf: 'Exporter PDF',
      exporting: 'Export en cours…',
      err: {
        EMPTY: 'Le document est vide',
        UNSUPPORTED_LEGACY_DOC:
          'Les anciens formats .doc / .wps / .rtf ne sont pas pris en charge, enregistrez en .docx',
        NOT_DOCX: 'Seuls les fichiers .docx sont pris en charge',
        TOO_LARGE: 'Le contenu dépasse la limite de {{max}} Mo',
        IMPORT_FAILED: "Échec de l'analyse du document",
        EXPORT_FAILED: "Échec de l'export Word",
        RENDER_FAILED: 'Échec de la mise en page',
        SNAPSHOT_FAILED: 'Échec de la génération de la capture PDF',
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Titel',
      titlePlaceholder: 'Unbenanntes Dokument',
      importHint: '.docx-Datei hierher ziehen oder auswählen, um Word-Inhalte zu importieren',
      placeholder: 'Beginnen Sie zu schreiben… (Word-Import und PDF-Export möglich)',
      chars: 'Zeichen',
      words: 'Wörter',
      paragraphs: 'Absätze',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatische Speicherung nach der Eingabe',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      paragraph: 'Fließtext',
      h1: 'Überschrift 1',
      h2: 'Überschrift 2',
      h3: 'Überschrift 3',
      bold: 'Fett',
      italic: 'Kursiv',
      underline: 'Unterstrichen',
      strike: 'Durchgestrichen',
      code: 'Inline-Code',
      color: 'Textfarbe',
      highlight: 'Markieren',
      bulletList: 'Unsortierte Liste',
      orderedList: 'Sortierte Liste',
      taskList: 'Aufgabenliste',
      quote: 'Zitat',
      codeBlock: 'Codeblock',
      link: 'Link',
      linkPrompt: 'Link-URL eingeben (leer zum Entfernen)',
      image: 'Bild einfügen',
      divider: 'Trennlinie',
      table: 'Tabelle einfügen',
      alignLeft: 'Linksbündig',
      alignCenter: 'Zentriert',
      alignRight: 'Rechtsbündig',
      alignJustify: 'Blocksatz',
      pdfMode: 'PDF-Modus',
      modeText: 'Text (auswählbar und durchsuchbar)',
      modeSnapshot: 'Bild (originalgetreu)',
      modeTextHint:
        'Über den Browserdruck exportiert: Text bleibt auswählbar, CJK korrekt dargestellt',
      modeSnapshotHint: 'Seite für Seite im A4-Format gerastert, identisch mit dem Editor',
      exportDocx: 'Word exportieren (.docx)',
      exportPdf: 'PDF exportieren',
      exporting: 'Wird exportiert…',
      err: {
        EMPTY: 'Das Dokument ist leer',
        UNSUPPORTED_LEGACY_DOC:
          'Alte .doc- / .wps- / .rtf-Dateien werden nicht unterstützt, bitte als .docx speichern',
        NOT_DOCX: 'Nur .docx-Dateien werden unterstützt',
        TOO_LARGE: 'Der Inhalt überschreitet das Limit von {{max}} MB',
        IMPORT_FAILED: 'Dokument konnte nicht gelesen werden',
        EXPORT_FAILED: 'Word-Export fehlgeschlagen',
        RENDER_FAILED: 'Layout konnte nicht gerendert werden',
        SNAPSHOT_FAILED: 'PDF-Bild konnte nicht erstellt werden',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Titolo',
      titlePlaceholder: 'Documento senza titolo',
      importHint: 'Trascina o scegli un file .docx per importare il contenuto di Word',
      placeholder: 'Inizia a scrivere… (import Word ed export PDF supportati)',
      chars: 'Caratteri',
      words: 'Parole',
      paragraphs: 'Paragrafi',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la digitazione',
      undo: 'Annulla',
      redo: 'Ripeti',
      paragraph: 'Testo normale',
      h1: 'Titolo 1',
      h2: 'Titolo 2',
      h3: 'Titolo 3',
      bold: 'Grassetto',
      italic: 'Corsivo',
      underline: 'Sottolineato',
      strike: 'Barrato',
      code: 'Codice in linea',
      color: 'Colore del testo',
      highlight: 'Evidenzia',
      bulletList: 'Elenco puntato',
      orderedList: 'Elenco numerato',
      taskList: 'Elenco di attività',
      quote: 'Citazione',
      codeBlock: 'Blocco di codice',
      link: 'Link',
      linkPrompt: "Inserisci l'URL del link (vuoto per rimuoverlo)",
      image: 'Inserisci immagine',
      divider: 'Riga divisoria',
      table: 'Inserisci tabella',
      alignLeft: 'Allinea a sinistra',
      alignCenter: 'Centra',
      alignRight: 'Allinea a destra',
      alignJustify: 'Giustifica',
      pdfMode: 'Modalità PDF',
      modeText: 'Testo (selezionabile e ricercabile)',
      modeSnapshot: 'Immagine (fedeltà visiva)',
      modeTextHint:
        'Esportato tramite la stampa del browser: il testo resta selezionabile e il CJK appare correttamente',
      modeSnapshotHint: "Rasterizzato pagina per pagina in formato A4, identico all'editor",
      exportDocx: 'Esporta Word (.docx)',
      exportPdf: 'Esporta PDF',
      exporting: 'Esportazione…',
      err: {
        EMPTY: 'Il documento è vuoto',
        UNSUPPORTED_LEGACY_DOC:
          'I formati .doc / .wps / .rtf precedenti non sono supportati, salva come .docx',
        NOT_DOCX: 'Sono supportati solo i file .docx',
        TOO_LARGE: 'Il contenuto supera il limite di {{max}} MB',
        IMPORT_FAILED: 'Analisi del documento non riuscita',
        EXPORT_FAILED: 'Esportazione Word non riuscita',
        RENDER_FAILED: 'Composizione del documento non riuscita',
        SNAPSHOT_FAILED: 'Generazione della cattura PDF non riuscita',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Título',
      titlePlaceholder: 'Documento sin título',
      importHint: 'Arrastra o elige un archivo .docx para importar el contenido de Word',
      placeholder: 'Empieza a escribir… (importación de Word y exportación a PDF compatibles)',
      chars: 'Caracteres',
      words: 'Palabras',
      paragraphs: 'Párrafos',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de escribir',
      undo: 'Deshacer',
      redo: 'Rehacer',
      paragraph: 'Texto normal',
      h1: 'Título 1',
      h2: 'Título 2',
      h3: 'Título 3',
      bold: 'Negrita',
      italic: 'Cursiva',
      underline: 'Subrayado',
      strike: 'Tachado',
      code: 'Código en línea',
      color: 'Color del texto',
      highlight: 'Resaltar',
      bulletList: 'Lista con viñetas',
      orderedList: 'Lista numerada',
      taskList: 'Lista de tareas',
      quote: 'Cita',
      codeBlock: 'Bloque de código',
      link: 'Enlace',
      linkPrompt: 'Introduce la URL del enlace (vacío para eliminarlo)',
      image: 'Insertar imagen',
      divider: 'Separador',
      table: 'Insertar tabla',
      alignLeft: 'Alinear a la izquierda',
      alignCenter: 'Centrar',
      alignRight: 'Alinear a la derecha',
      alignJustify: 'Justificar',
      pdfMode: 'Modo PDF',
      modeText: 'Texto (seleccionable y con posibilidad de búsqueda)',
      modeSnapshot: 'Captura (fiel al diseño)',
      modeTextHint:
        'Se exporta con la impresión del navegador: el texto sigue siendo seleccionable y los caracteres chinos se muestran bien',
      modeSnapshotHint: 'Se rasteriza página a página en tamaño A4, idéntico al editor',
      exportDocx: 'Exportar Word (.docx)',
      exportPdf: 'Exportar PDF',
      exporting: 'Exportando…',
      err: {
        EMPTY: 'El documento está vacío',
        UNSUPPORTED_LEGACY_DOC:
          'Los formatos antiguos .doc / .wps / .rtf no son compatibles, guarda como .docx',
        NOT_DOCX: 'Solo se admiten archivos .docx',
        TOO_LARGE: 'El contenido supera el límite de {{max}} MB',
        IMPORT_FAILED: 'No se pudo analizar el documento',
        EXPORT_FAILED: 'La exportación a Word falló',
        RENDER_FAILED: 'No se pudo componer el documento',
        SNAPSHOT_FAILED: 'No se pudo generar la captura en PDF',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Título',
      titlePlaceholder: 'Documento sem título',
      importHint: 'Arraste ou escolha um ficheiro .docx para importar o conteúdo do Word',
      placeholder: 'Comece a escrever… (importação Word e exportação PDF suportadas)',
      chars: 'Caracteres',
      words: 'Palavras',
      paragraphs: 'Parágrafos',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de escrever',
      undo: 'Anular',
      redo: 'Refazer',
      paragraph: 'Texto normal',
      h1: 'Título 1',
      h2: 'Título 2',
      h3: 'Título 3',
      bold: 'Negrito',
      italic: 'Itálico',
      underline: 'Sublinhado',
      strike: 'Rasurado',
      code: 'Código em linha',
      color: 'Cor do texto',
      highlight: 'Realçar',
      bulletList: 'Lista com marcadores',
      orderedList: 'Lista numerada',
      taskList: 'Lista de tarefas',
      quote: 'Citação',
      codeBlock: 'Bloco de código',
      link: 'Ligação',
      linkPrompt: 'Introduza o URL da ligação (vazio para remover)',
      image: 'Inserir imagem',
      divider: 'Separador',
      table: 'Inserir tabela',
      alignLeft: 'Alinhar à esquerda',
      alignCenter: 'Centrar',
      alignRight: 'Alinhar à direita',
      alignJustify: 'Justificar',
      pdfMode: 'Modo PDF',
      modeText: 'Texto (selecionável e pesquisável)',
      modeSnapshot: 'Captura (fidelidade visual)',
      modeTextHint:
        'Exportado pela impressão do navegador: o texto mantém-se selecionável e o CJK é apresentado corretamente',
      modeSnapshotHint: 'Rasterizado página a página em formato A4, idêntico ao editor',
      exportDocx: 'Exportar Word (.docx)',
      exportPdf: 'Exportar PDF',
      exporting: 'A exportar…',
      err: {
        EMPTY: 'O documento está vazio',
        UNSUPPORTED_LEGACY_DOC:
          'Os formatos antigos .doc / .wps / .rtf não são suportados, guarde como .docx',
        NOT_DOCX: 'Apenas são suportados ficheiros .docx',
        TOO_LARGE: 'O conteúdo excede o limite de {{max}} MB',
        IMPORT_FAILED: 'Falha ao analisar o documento',
        EXPORT_FAILED: 'Falha ao exportar para Word',
        RENDER_FAILED: 'Falha ao compor o documento',
        SNAPSHOT_FAILED: 'Falha ao gerar a captura em PDF',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const richTextStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具被懒加载时调用，键路径 tools.richText.*） */
export function registerRichTextStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(richTextStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
