/**
 * 富文本编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 *
 * 背景：项目的语言包 zh / en 是首屏同步资源（`SYNC_LANGS`），
 * 单个工具几十条 UI 文案若全部写进 `core/i18n/locales/*`，会直接推高首屏入口体积
 * （本项目预算：首屏 gzip ≤ 180KB，实测已接近上限）。
 * 因此本工具的界面文案放在这里，在工具被懒加载时由 `registerRichTextStrings` 合并进 i18next，
 * 键路径保持不变（`tools.richText.*`），且保留 10 种语言。
 *
 * 注意：工具元数据（名称/描述）仍写在 `core/i18n/locales/*` 的 `toolsMeta` 中，
 * 因为首页卡片、侧边栏与 ⌘K 搜索在工具加载前就要用到。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { richText: StringTree } };

const zh: ResourceTree = {
  tools: {
    richText: {
      docTitle: '文档标题',
      present: '放映',
      exitPresent: '退出放映（Esc）',
      presentLoading: '正在生成放映画面…',
      presentFailed: '放映画面生成失败',
      titlePlaceholder: '未命名文档',
      importHint: '拖入或选择 .docx 文件导入 Word 内容',
      importDocx: '导入 Word (.docx)',
      placeholder: '开始撰写正文…（支持 Word 导入与 PDF 导出）',
      chars: '字符',
      words: '词数',
      paragraphs: '段落',
      saved: '已保存到本地草稿',
      saving: '停止输入后自动保存',
      undo: '撤销',
      redo: '重做',
      paragraph: '正文段落',
      h1: '一级标题',
      h2: '二级标题',
      h3: '三级标题',
      h4: '四级标题',
      h5: '五级标题',
      h6: '六级标题',
      headingSelect: '标题样式',
      fontFamily: '字体',
      fontDefault: '默认字体',
      fontSans: '无衬线',
      fontSerif: '衬线',
      fontMono: '等宽',
      fontSong: '宋体',
      fontKai: '楷体',
      fontSize: '字号',
      sizeDefault: '默认字号',
      lineHeight: '行距',
      spacingDefault: '默认行距',
      findReplace: '查找替换（Ctrl/⌘+F）',
      find: '查找',
      replace: '替换为',
      replaceOne: '替换',
      replaceAll: '全部替换',
      matchCase: '区分大小写',
      prevMatch: '上一个',
      nextMatch: '下一个',
      noMatch: '无结果',
      closeFind: '关闭查找替换',
      outline: '文档大纲',
      viewMode: '视图模式',
      viewFlow: '流式视图',
      viewPaged: '页面视图',
      pageBadge: '第 {{page}} 页',
      bold: '加粗',
      italic: '斜体',
      underline: '下划线',
      strike: '删除线',
      code: '行内代码',
      color: '字体颜色',
      highlight: '荧光笔',
      bulletList: '无序列表',
      orderedList: '有序列表',
      taskList: '任务清单',
      quote: '引用',
      codeBlock: '代码块',
      link: '链接',
      linkPrompt: '输入链接地址（留空则移除）',
      image: '插入图片',
      divider: '分割线',
      pageBreak: '插入分页符',
      lossExternalImages: '{{count}} 张外链图片未写入 Word（仅支持内嵌图片）。',
      lossWebpImages: '{{count}} 张 WebP 图片未写入 Word（请改用 PNG/JPEG）。',
      lossDeepLists: '{{count}} 处列表嵌套超过 8 层，已并入最深层级。',
      library: '文档库',
      libraryNew: '新建',
      libraryClose: '关闭',
      libraryEmpty: '暂无本地文档',
      untitledDoc: '未命名文档',
      updatedAt: '更新于',
      duplicateDoc: '创建副本',
      deleteDoc: '删除',
      deleteDocConfirm: '确定删除「{{title}}」？该操作不可撤销。',
      versionHistory: '历史版本',
      noVersions: '暂无历史版本',
      restoreVersion: '恢复',
      restoreConfirm: '用该版本覆盖当前内容？',
      versionChars: '{{count}} 字符',
      draftDegraded: '草稿过大，已剥离图片后保存到本地。',
      draftSaveFailed: '本地草稿保存失败，请导出文件以保留内容。',
      printFallback: '当前环境不支持打印对话框，已改用快照模式导出 PDF。',
      pageSetup: '页面设置',
      pageSetupClose: '关闭页面设置',
      paperSize: '纸张',
      orientation: '方向',
      portrait: '纵向',
      landscape: '横向',
      marginPreset: '页边距',
      margin_normal: '普通',
      margin_narrow: '窄',
      margin_wide: '宽',
      margin_top: '上',
      margin_right: '右',
      margin_bottom: '下',
      margin_left: '左',
      headerText: '页眉',
      footerText: '页脚',
      headerPlaceholder: '页眉内容（留空则不显示）',
      footerPlaceholder: '页脚内容（留空则不显示）',
      showPageNumber: '显示页码',
      zoom: '缩放',
      docSection: '文档',
      indentIncrease: '增加缩进',
      indentDecrease: '减少缩进',
      paragraphSpacing: '段间距',
      spacingPresetDefault: '默认',
      spacingPresetCompact: '紧凑',
      spacingPresetRelaxed: '宽松',
      spacingPresetLoose: '很宽松',
      spacingCompact: '紧凑',
      spacingRelaxed: '宽松',
      spacingLoose: '很宽松',
      imageWidth: '图片宽度',
      imageWidthAuto: '自动',
      imageWidthCustom: '自定义（{{px}} px）',
      imageAlign_left: '图片左对齐',
      imageAlign_center: '图片居中',
      imageAlign_right: '图片右对齐',
      imageLayer: '环绕方式',
      imageLayerInline: '嵌入型',
      imageLayerFront: '浮于文字上方',
      imageLayerBehind: '衬于文字下方',
      tableBorders: '表格边框',
      tableZebra: '斑马纹',
      insertToc: '插入目录',
      tocTitle: '目录',
      styles: '样式',
      stylesClose: '关闭',
      styleBody: '正文',
      styleTitle: '标题',
      styleHeading2: '标题 2',
      styleHeading3: '标题 3',
      styleQuote: '引用',
      styleCode: '代码',
      review: '批注与修订',
      reviewClose: '关闭批注与修订',
      addComment: '新建批注',
      removeComment: '删除批注',
      noComments: '暂无批注',
      commentPrompt: '请输入批注内容',
      commentAuthor: '本地用户',
      trackedChanges: '修订',
      acceptAll: '全部接受',
      rejectAll: '全部拒绝',
      markInsert: '标记为插入',
      markDelete: '标记为删除',
      markHint: '先选中文本，再标记修订',
      exportMarkdown: '导出 Markdown',
      exportHtml: '导出 HTML',
      table: '插入表格',
      rowAbove: '上方插入行',
      rowBelow: '下方插入行',
      columnLeft: '左侧插入列',
      columnRight: '右侧插入列',
      deleteRow: '删除行',
      deleteColumn: '删除列',
      headerRow: '表头行',
      mergeCells: '合并单元格',
      splitCell: '拆分单元格',
      deleteTable: '删除表格',
      alignLeft: '左对齐',
      alignCenter: '居中对齐',
      alignRight: '右对齐',
      alignJustify: '两端对齐',
      pdfMode: 'PDF 模式',
      modeText: '文字版（可选可搜索）',
      modeSnapshot: '截图版（样式高保真）',
      modeTextHint: '经浏览器打印导出：文字可选中检索，中文不会乱码',
      modeSnapshotHint: '按 A4 分页截图后合成，视觉效果与编辑器一致',
      pdfDialogTitle: '导出 PDF',
      pdfDialogDesc: '选择导出方式（记住上次选择）',
      pdfDialogCancel: '取消',
      exportDocx: '导出 Word (.docx)',
      exportPdf: '导出 PDF',
      exporting: '导出中…',
      err: {
        EMPTY: '文档内容为空',
        UNSUPPORTED_LEGACY_DOC: '暂不支持旧版 .doc / .wps / .rtf 格式，请另存为 .docx 后重试',
        NOT_DOCX: '仅支持 .docx 文件',
        TOO_LARGE: '内容超出 {{max}}MB 限制',
        IMPORT_FAILED: '文档解析失败',
        EXPORT_FAILED: 'Word 导出失败',
        RENDER_FAILED: '排版渲染失败',
        SNAPSHOT_FAILED: 'PDF 截图生成失败',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Title',
      present: 'Present',
      exitPresent: 'Exit (Esc)',
      presentLoading: 'Preparing the slideshow…',
      presentFailed: 'Failed to build the slideshow',
      titlePlaceholder: 'Untitled document',
      importHint: 'Drop or pick a .docx file to import Word content',
      importDocx: 'Import Word (.docx)',
      placeholder: 'Start writing… (Word import and PDF export supported)',
      chars: 'Characters',
      words: 'Words',
      paragraphs: 'Paragraphs',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop typing',
      undo: 'Undo',
      redo: 'Redo',
      paragraph: 'Body text',
      h1: 'Heading 1',
      h2: 'Heading 2',
      h3: 'Heading 3',
      h4: 'Heading 4',
      h5: 'Heading 5',
      h6: 'Heading 6',
      headingSelect: 'Heading style',
      fontFamily: 'Font',
      fontDefault: 'Default font',
      fontSans: 'Sans-serif',
      fontSerif: 'Serif',
      fontMono: 'Monospace',
      fontSong: 'Songti',
      fontKai: 'Kaiti',
      fontSize: 'Font size',
      sizeDefault: 'Default size',
      lineHeight: 'Line height',
      spacingDefault: 'Default spacing',
      findReplace: 'Find & replace (Ctrl/⌘+F)',
      find: 'Find',
      replace: 'Replace with',
      replaceOne: 'Replace',
      replaceAll: 'Replace all',
      matchCase: 'Match case',
      prevMatch: 'Previous match',
      nextMatch: 'Next match',
      noMatch: 'No matches',
      closeFind: 'Close find & replace',
      outline: 'Document outline',
      viewMode: 'View mode',
      viewFlow: 'Flow view',
      viewPaged: 'Page view',
      pageBadge: 'Page {{page}}',
      bold: 'Bold',
      italic: 'Italic',
      underline: 'Underline',
      strike: 'Strikethrough',
      code: 'Inline code',
      color: 'Text color',
      highlight: 'Highlight',
      bulletList: 'Bulleted list',
      orderedList: 'Numbered list',
      taskList: 'Task list',
      quote: 'Quote',
      codeBlock: 'Code block',
      link: 'Link',
      linkPrompt: 'Enter link URL (empty to remove)',
      image: 'Insert image',
      divider: 'Divider',
      pageBreak: 'Insert page break',
      lossExternalImages: '{{count}} linked image(s) were not embedded in the Word file.',
      lossWebpImages: '{{count}} WebP image(s) were skipped (use PNG/JPEG instead).',
      lossDeepLists: '{{count}} list(s) nested deeper than 8 levels were flattened.',
      library: 'Library',
      libraryNew: 'New',
      libraryClose: 'Close',
      libraryEmpty: 'No local documents yet',
      untitledDoc: 'Untitled document',
      updatedAt: 'Updated',
      duplicateDoc: 'Duplicate',
      deleteDoc: 'Delete',
      deleteDocConfirm: 'Delete "{{title}}"? This cannot be undone.',
      versionHistory: 'Version history',
      noVersions: 'No versions yet',
      restoreVersion: 'Restore',
      restoreConfirm: 'Overwrite the current content with this version?',
      versionChars: '{{count}} chars',
      draftDegraded: 'Draft too large: images were stripped to keep the local draft.',
      draftSaveFailed: 'Failed to save the local draft. Export a file to keep your content.',
      printFallback: 'Print dialog is unavailable here; exported as snapshot PDF instead.',
      pageSetup: 'Page setup',
      pageSetupClose: 'Close page setup',
      paperSize: 'Paper size',
      orientation: 'Orientation',
      portrait: 'Portrait',
      landscape: 'Landscape',
      marginPreset: 'Margins',
      margin_normal: 'Normal',
      margin_narrow: 'Narrow',
      margin_wide: 'Wide',
      margin_top: 'Top',
      margin_right: 'Right',
      margin_bottom: 'Bottom',
      margin_left: 'Left',
      headerText: 'Header',
      footerText: 'Footer',
      headerPlaceholder: 'Header text (empty to hide)',
      footerPlaceholder: 'Footer text (empty to hide)',
      showPageNumber: 'Page numbers',
      zoom: 'Zoom',
      docSection: 'Document',
      indentIncrease: 'Increase indent',
      indentDecrease: 'Decrease indent',
      paragraphSpacing: 'Paragraph spacing',
      spacingPresetDefault: 'Default',
      spacingPresetCompact: 'Compact',
      spacingPresetRelaxed: 'Relaxed',
      spacingPresetLoose: 'Loose',
      imageWidth: 'Image width',
      imageWidthAuto: 'Auto',
      imageWidthCustom: 'Custom ({{px}} px)',
      imageAlign_left: 'Align image left',
      imageAlign_center: 'Center image',
      imageAlign_right: 'Align image right',
      imageLayer: 'Wrapping',
      imageLayerInline: 'In line',
      imageLayerFront: 'In front of text',
      imageLayerBehind: 'Behind text',
      tableBorders: 'Table borders',
      tableZebra: 'Zebra stripes',
      insertToc: 'Insert TOC',
      tocTitle: 'Table of Contents',
      styles: 'Styles',
      stylesClose: 'Close',
      styleBody: 'Body',
      styleTitle: 'Title',
      styleHeading2: 'Heading 2',
      styleHeading3: 'Heading 3',
      styleQuote: 'Quote',
      styleCode: 'Code',
      review: 'Comments & changes',
      reviewClose: 'Close review',
      addComment: 'New comment',
      removeComment: 'Delete comment',
      noComments: 'No comments yet',
      commentPrompt: 'Enter your comment',
      commentAuthor: 'Local user',
      trackedChanges: 'Changes',
      acceptAll: 'Accept all',
      rejectAll: 'Reject all',
      markInsert: 'Mark as insert',
      markDelete: 'Mark as delete',
      markHint: 'Select text first, then mark the change',
      exportMarkdown: 'Export Markdown',
      exportHtml: 'Export HTML',
      table: 'Insert table',
      rowAbove: 'Insert row above',
      rowBelow: 'Insert row below',
      columnLeft: 'Insert column left',
      columnRight: 'Insert column right',
      deleteRow: 'Delete row',
      deleteColumn: 'Delete column',
      headerRow: 'Header row',
      mergeCells: 'Merge cells',
      splitCell: 'Split cell',
      deleteTable: 'Delete table',
      alignLeft: 'Align left',
      alignCenter: 'Align center',
      alignRight: 'Align right',
      alignJustify: 'Justify',
      pdfMode: 'PDF mode',
      modeText: 'Text (selectable & searchable)',
      modeSnapshot: 'Snapshot (pixel-perfect)',
      modeTextHint: 'Exported via browser print: text stays selectable and CJK renders correctly',
      modeSnapshotHint: 'Rasterized page by page at A4 size, identical to the editor',
      pdfDialogTitle: 'Export PDF',
      pdfDialogDesc: 'Choose an export mode (your last choice is remembered)',
      pdfDialogCancel: 'Cancel',
      exportDocx: 'Export Word (.docx)',
      exportPdf: 'Export PDF',
      exporting: 'Exporting…',
      err: {
        EMPTY: 'The document is empty',
        UNSUPPORTED_LEGACY_DOC:
          'Legacy .doc / .wps / .rtf files are not supported, please save as .docx',
        NOT_DOCX: 'Only .docx files are supported',
        TOO_LARGE: 'Content exceeds the {{max}}MB limit',
        IMPORT_FAILED: 'Failed to parse the document',
        EXPORT_FAILED: 'Word export failed',
        RENDER_FAILED: 'Rendering failed',
        SNAPSHOT_FAILED: 'Failed to generate the PDF snapshot',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    richText: {
      docTitle: '文檔標題',
      present: '放映',
      exitPresent: '結束放映（Esc）',
      presentLoading: '正在產生放映畫面…',
      presentFailed: '放映畫面產生失敗',
      titlePlaceholder: '未命名文檔',
      importHint: '拖曳或選擇 .docx 檔案匯入 Word 內容',
      importDocx: '匯入 Word (.docx)',
      placeholder: '開始撰寫正文…（支援 Word 匯入與 PDF 匯出）',
      chars: '字元',
      words: '字數',
      paragraphs: '段落',
      saved: '已儲存至本機草稿',
      saving: '停止輸入後自動儲存',
      undo: '復原',
      redo: '重做',
      paragraph: '本文段落',
      h1: '一級標題',
      h2: '二級標題',
      h3: '三級標題',
      h4: '四級標題',
      h5: '五級標題',
      h6: '六級標題',
      headingSelect: '標題樣式',
      fontFamily: '字型',
      fontDefault: '預設字型',
      fontSans: '無襯線',
      fontSerif: '襯線',
      fontMono: '等寬',
      fontSong: '宋體',
      fontKai: '楷體',
      fontSize: '字號',
      sizeDefault: '預設字號',
      lineHeight: '行距',
      spacingDefault: '預設行距',
      findReplace: '尋找取代（Ctrl/⌘+F）',
      find: '尋找',
      replace: '取代為',
      replaceOne: '取代',
      replaceAll: '全部取代',
      matchCase: '區分大小寫',
      prevMatch: '上一個',
      nextMatch: '下一個',
      noMatch: '無結果',
      closeFind: '關閉尋找取代',
      outline: '文檔大綱',
      viewMode: '檢視模式',
      viewFlow: '流式檢視',
      viewPaged: '頁面檢視',
      pageBadge: '第 {{page}} 頁',
      bold: '粗體',
      italic: '斜體',
      underline: '底線',
      strike: '刪除線',
      code: '行內程式碼',
      color: '文字顏色',
      highlight: '螢光筆',
      bulletList: '項目符號清單',
      orderedList: '編號清單',
      taskList: '任務清單',
      quote: '引用',
      codeBlock: '程式碼區塊',
      link: '連結',
      linkPrompt: '輸入連結網址（留空則移除）',
      image: '插入圖片',
      divider: '分隔線',
      pageBreak: '插入分頁符',
      lossExternalImages: '{{count}} 張外鏈圖片未寫入 Word（僅支援內嵌圖片）。',
      lossWebpImages: '{{count}} 張 WebP 圖片未寫入 Word（請改用 PNG/JPEG）。',
      lossDeepLists: '{{count}} 處清單巢狀超過 8 層，已併入最深層級。',
      library: '文檔庫',
      libraryNew: '新建',
      libraryClose: '關閉',
      libraryEmpty: '暫無本機文檔',
      untitledDoc: '未命名文檔',
      updatedAt: '更新於',
      duplicateDoc: '建立副本',
      deleteDoc: '刪除',
      deleteDocConfirm: '確定刪除「{{title}}」？該操作不可撤銷。',
      versionHistory: '歷史版本',
      noVersions: '暫無歷史版本',
      restoreVersion: '恢復',
      restoreConfirm: '以該版本覆蓋目前內容？',
      versionChars: '{{count}} 字元',
      draftDegraded: '草稿過大，已剝離圖片後儲存到本機。',
      draftSaveFailed: '本機草稿儲存失敗，請匯出檔案以保留內容。',
      printFallback: '目前環境不支援列印對話框，已改用快照模式匯出 PDF。',
      pageSetup: '版面設定',
      pageSetupClose: '關閉版面設定',
      paperSize: '紙張',
      orientation: '方向',
      portrait: '直向',
      landscape: '橫向',
      marginPreset: '邊界',
      margin_normal: '一般',
      margin_narrow: '窄',
      margin_wide: '寬',
      margin_top: '上',
      margin_right: '右',
      margin_bottom: '下',
      margin_left: '左',
      headerText: '頁首',
      footerText: '頁尾',
      headerPlaceholder: '頁首內容（留空則不顯示）',
      footerPlaceholder: '頁尾內容（留空則不顯示）',
      showPageNumber: '顯示頁碼',
      zoom: '縮放',
      docSection: '文檔',
      indentIncrease: '增加縮排',
      indentDecrease: '減少縮排',
      paragraphSpacing: '段落間距',
      spacingPresetDefault: '預設',
      spacingPresetCompact: '緊湊',
      spacingPresetRelaxed: '寬鬆',
      spacingPresetLoose: '很寬鬆',
      imageWidth: '圖片寬度',
      imageWidthAuto: '自動',
      imageWidthCustom: '自訂（{{px}} px）',
      imageAlign_left: '圖片靠左',
      imageAlign_center: '圖片置中',
      imageAlign_right: '圖片靠右',
      imageLayer: '環繞方式',
      imageLayerInline: '嵌入型',
      imageLayerFront: '浮於文字上方',
      imageLayerBehind: '襯於文字下方',
      tableBorders: '表格框線',
      tableZebra: '斑馬紋',
      insertToc: '插入目錄',
      tocTitle: '目錄',
      styles: '樣式',
      stylesClose: '關閉',
      styleBody: '正文',
      styleTitle: '標題',
      styleHeading2: '標題 2',
      styleHeading3: '標題 3',
      styleQuote: '引用',
      styleCode: '程式碼',
      review: '批註與修訂',
      reviewClose: '關閉批註與修訂',
      addComment: '新增批註',
      removeComment: '刪除批註',
      noComments: '暫無批註',
      commentPrompt: '請輸入批註內容',
      commentAuthor: '本機使用者',
      trackedChanges: '修訂',
      acceptAll: '全部接受',
      rejectAll: '全部拒絕',
      markInsert: '標記為插入',
      markDelete: '標記為刪除',
      markHint: '請先選取文字，再標記修訂',
      exportMarkdown: '匯出 Markdown',
      exportHtml: '匯出 HTML',
      table: '插入表格',
      rowAbove: '上方插入列',
      rowBelow: '下方插入列',
      columnLeft: '左側插入欄',
      columnRight: '右側插入欄',
      deleteRow: '刪除列',
      deleteColumn: '刪除欄',
      headerRow: '表頭列',
      mergeCells: '合併儲存格',
      splitCell: '分割儲存格',
      deleteTable: '刪除表格',
      alignLeft: '靠左對齊',
      alignCenter: '置中對齊',
      alignRight: '靠右對齊',
      alignJustify: '左右對齊',
      pdfMode: 'PDF 模式',
      modeText: '文字版（可選可取並可搜尋）',
      modeSnapshot: '截圖版（樣式高保真）',
      modeTextHint: '透過瀏覽器列印匯出，文字可選取，中文不會亂碼',
      modeSnapshotHint: '依 A4 分頁截圖後合成，視覺與編輯器一致',
      pdfDialogTitle: '匯出 PDF',
      pdfDialogDesc: '選擇匯出方式（會記住上次選擇）',
      pdfDialogCancel: '取消',
      exportDocx: '匯出 Word (.docx)',
      exportPdf: '匯出 PDF',
      exporting: '匯出中…',
      err: {
        EMPTY: '文檔內容為空',
        UNSUPPORTED_LEGACY_DOC: '不支援舊版 .doc / .wps / .rtf，請另存為 .docx 後再試',
        NOT_DOCX: '僅支援 .docx 檔案',
        TOO_LARGE: '內容超過 {{max}}MB 限制',
        IMPORT_FAILED: '文檔解析失敗',
        EXPORT_FAILED: 'Word 匯出失敗',
        RENDER_FAILED: '排版失敗',
        SNAPSHOT_FAILED: 'PDF 截圖產生失敗',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'タイトル',
      present: 'スライドショー',
      exitPresent: '終了（Esc）',
      presentLoading: '表示用の画像を生成中…',
      presentFailed: '表示用の画像の生成に失敗しました',
      titlePlaceholder: '無題の文書',
      importHint: '.docx ファイルをドロップまたは選択して Word の内容を読み込む',
      importDocx: 'Word (.docx) を読み込む',
      placeholder: '本文を書き始めましょう…（Word 読み込みと PDF 書き出しに対応）',
      chars: '文字数',
      words: '単語数',
      paragraphs: '段落数',
      saved: 'ローカル下書きに保存しました',
      saving: '入力を止めると自動保存します',
      undo: '元に戻す',
      redo: 'やり直す',
      paragraph: '本文',
      h1: '見出し 1',
      h2: '見出し 2',
      h3: '見出し 3',
      h4: '見出し 4',
      h5: '見出し 5',
      h6: '見出し 6',
      headingSelect: '見出しスタイル',
      fontFamily: 'フォント',
      fontDefault: 'デフォルト',
      fontSans: 'サンセリフ',
      fontSerif: 'セリフ',
      fontMono: '等幅',
      fontSong: '宋体',
      fontKai: '楷体',
      fontSize: '文字サイズ',
      sizeDefault: 'デフォルト',
      lineHeight: '行間',
      spacingDefault: 'デフォルト',
      findReplace: '検索と置換（Ctrl/⌘+F）',
      find: '検索',
      replace: '置換後',
      replaceOne: '置換',
      replaceAll: 'すべて置換',
      matchCase: '大文字と小文字を区別',
      prevMatch: '前へ',
      nextMatch: '次へ',
      noMatch: '該当なし',
      closeFind: '検索と置換を閉じる',
      outline: '文書アウトライン',
      viewMode: '表示モード',
      viewFlow: 'フロー表示',
      viewPaged: 'ページ表示',
      pageBadge: '{{page}} ページ目',
      bold: '太字',
      italic: '斜体',
      underline: '下線',
      strike: '取り消し線',
      code: 'インラインコード',
      color: '文字色',
      highlight: 'ハイライト',
      bulletList: '箇条書き',
      orderedList: '番号付きリスト',
      taskList: 'タスクリスト',
      quote: '引用',
      codeBlock: 'コードブロック',
      link: 'リンク',
      linkPrompt: 'リンク先 URL を入力（空欄で解除）',
      image: '画像を挿入',
      divider: '区切り線',
      pageBreak: '改ページを挿入',
      lossExternalImages: 'リンク画像 {{count}} 枚は Word に埋め込めませんでした。',
      lossWebpImages: 'WebP 画像 {{count}} 枚をスキップしました（PNG/JPEG をご利用ください）。',
      lossDeepLists: '8 階層を超えるリストの {{count}} か所を最深階層に統合しました。',
      library: 'ドキュメントライブラリ',
      libraryNew: '新規作成',
      libraryClose: '閉じる',
      libraryEmpty: 'ローカル文書はまだありません',
      untitledDoc: '無題の文書',
      updatedAt: '更新',
      duplicateDoc: '複製',
      deleteDoc: '削除',
      deleteDocConfirm: '「{{title}}」を削除しますか？元に戻せません。',
      versionHistory: 'バージョン履歴',
      noVersions: '履歴はまだありません',
      restoreVersion: '復元',
      restoreConfirm: '現在の内容をこのバージョンで上書きしますか？',
      versionChars: '{{count}} 文字',
      draftDegraded: '下書きが大きすぎるため、画像を取り除いて保存しました。',
      draftSaveFailed: 'ローカル下書きの保存に失敗しました。内容を残すには書き出してください。',
      printFallback:
        'この環境では印刷ダイアログを使用できないため、スナップショットで書き出しました。',
      pageSetup: 'ページ設定',
      pageSetupClose: 'ページ設定を閉じる',
      paperSize: '用紙',
      orientation: '方向',
      portrait: '縦',
      landscape: '横',
      marginPreset: '余白',
      margin_normal: '標準',
      margin_narrow: '狭い',
      margin_wide: '広い',
      margin_top: '上',
      margin_right: '右',
      margin_bottom: '下',
      margin_left: '左',
      headerText: 'ヘッダー',
      footerText: 'フッター',
      headerPlaceholder: 'ヘッダー（空欄で非表示）',
      footerPlaceholder: 'フッター（空欄で非表示）',
      showPageNumber: 'ページ番号',
      zoom: '表示倍率',
      docSection: '文書',
      indentIncrease: 'インデントを増やす',
      indentDecrease: 'インデントを減らす',
      paragraphSpacing: '段落間隔',
      spacingPresetDefault: '既定',
      spacingPresetCompact: '狭い',
      spacingPresetRelaxed: '広い',
      spacingPresetLoose: 'とても広い',
      imageWidth: '画像の幅',
      imageWidthAuto: '自動',
      imageWidthCustom: 'カスタム（{{px}} px）',
      imageAlign_left: '画像を左寄せ',
      imageAlign_center: '画像を中央',
      imageAlign_right: '画像を右寄せ',
      imageLayer: '文字列の折り返し',
      imageLayerInline: '行内',
      imageLayerFront: '文字列の前面',
      imageLayerBehind: '文字列の背面',
      tableBorders: '表の罫線',
      tableZebra: '縞模様',
      insertToc: '目次を挿入',
      tocTitle: '目次',
      styles: 'スタイル',
      stylesClose: '閉じる',
      styleBody: '本文',
      styleTitle: 'タイトル',
      styleHeading2: '見出し 2',
      styleHeading3: '見出し 3',
      styleQuote: '引用',
      styleCode: 'コード',
      review: 'コメントと変更',
      reviewClose: 'レビューを閉じる',
      addComment: 'コメントを追加',
      removeComment: 'コメントを削除',
      noComments: 'コメントはありません',
      commentPrompt: 'コメントを入力してください',
      commentAuthor: 'ローカルユーザー',
      trackedChanges: '変更履歴',
      acceptAll: 'すべて承認',
      rejectAll: 'すべて拒否',
      markInsert: '挿入として記録',
      markDelete: '削除として記録',
      markHint: '先にテキストを選択してください',
      exportMarkdown: 'Markdown を書き出し',
      exportHtml: 'HTML を書き出し',
      table: '表を挿入',
      rowAbove: '上に行を追加',
      rowBelow: '下に行を追加',
      columnLeft: '左に列を追加',
      columnRight: '右に列を追加',
      deleteRow: '行を削除',
      deleteColumn: '列を削除',
      headerRow: 'ヘッダー行',
      mergeCells: 'セルを結合',
      splitCell: 'セルを分割',
      deleteTable: '表を削除',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      alignJustify: '両端揃え',
      pdfMode: 'PDF モード',
      modeText: 'テキスト版（選択・検索可）',
      modeSnapshot: 'スナップショット版（見た目をそのまま保持）',
      modeTextHint: 'ブラウザの印刷から書き出すため、文字は選択でき、日本語も文字化けしません',
      modeSnapshotHint:
        'A4 サイズでページごとに画像化して合成するため、エディターと同じ見た目になります',
      pdfDialogTitle: 'PDF を書き出し',
      pdfDialogDesc: '書き出し方法を選択（前回の選択を記憶します）',
      pdfDialogCancel: 'キャンセル',
      exportDocx: 'Word (.docx) を書き出し',
      exportPdf: 'PDF を書き出し',
      exporting: '書き出し中…',
      err: {
        EMPTY: '文書が空です',
        UNSUPPORTED_LEGACY_DOC:
          '旧形式の .doc / .wps / .rtf には対応していません。.docx で保存し直してください',
        NOT_DOCX: '.docx ファイルのみ対応しています',
        TOO_LARGE: '内容が {{max}}MB の上限を超えています',
        IMPORT_FAILED: '文書の解析に失敗しました',
        EXPORT_FAILED: 'Word 書き出しに失敗しました',
        RENDER_FAILED: 'レイアウトの描画に失敗しました',
        SNAPSHOT_FAILED: 'PDF スナップショットの生成に失敗しました',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Titre',
      present: 'Présenter',
      exitPresent: 'Quitter (Échap)',
      presentLoading: 'Préparation du diaporama…',
      presentFailed: 'Échec de la préparation du diaporama',
      titlePlaceholder: 'Document sans titre',
      importHint: 'Déposez ou choisissez un fichier .docx pour importer le contenu Word',
      importDocx: 'Importer Word (.docx)',
      placeholder: 'Commencez à écrire… (import Word et export PDF pris en charge)',
      chars: 'Caractères',
      words: 'Mots',
      paragraphs: 'Paragraphes',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement automatique après la saisie',
      undo: 'Annuler',
      redo: 'Rétablir',
      paragraph: 'Corps du texte',
      h1: 'Titre 1',
      h2: 'Titre 2',
      h3: 'Titre 3',
      h4: 'Titre 4',
      h5: 'Titre 5',
      h6: 'Titre 6',
      headingSelect: 'Style de titre',
      fontFamily: 'Police',
      fontDefault: 'Par défaut',
      fontSans: 'Sans-serif',
      fontSerif: 'Serif',
      fontMono: 'Monospace',
      fontSong: 'Songti',
      fontKai: 'Kaiti',
      fontSize: 'Taille',
      sizeDefault: 'Par défaut',
      lineHeight: 'Interligne',
      spacingDefault: 'Par défaut',
      findReplace: 'Rechercher et remplacer (Ctrl/⌘+F)',
      find: 'Rechercher',
      replace: 'Remplacer par',
      replaceOne: 'Remplacer',
      replaceAll: 'Tout remplacer',
      matchCase: 'Respecter la casse',
      prevMatch: 'Précédent',
      nextMatch: 'Suivant',
      noMatch: 'Aucun résultat',
      closeFind: 'Fermer la recherche',
      outline: 'Plan du document',
      viewMode: "Mode d'affichage",
      viewFlow: 'Vue continue',
      viewPaged: 'Vue paginée',
      pageBadge: 'Page {{page}}',
      bold: 'Gras',
      italic: 'Italique',
      underline: 'Souligné',
      strike: 'Barré',
      code: 'Code en ligne',
      color: 'Couleur du texte',
      highlight: 'Surligner',
      bulletList: 'Liste à puces',
      orderedList: 'Liste numérotée',
      taskList: 'Liste de tâches',
      quote: 'Citation',
      codeBlock: 'Bloc de code',
      link: 'Lien',
      linkPrompt: "Saisissez l'URL du lien (vide pour supprimer)",
      image: 'Insérer une image',
      divider: 'Séparateur',
      pageBreak: 'Insérer un saut de page',
      lossExternalImages: "{{count}} image(s) liée(s) n'ont pas été intégrées au fichier Word.",
      lossWebpImages: '{{count}} image(s) WebP ignorée(s) (utilisez PNG/JPEG).',
      lossDeepLists: '{{count}} liste(s) imbriquée(s) au-delà de 8 niveaux ont été aplanies.',
      library: 'Bibliothèque',
      libraryNew: 'Nouveau',
      libraryClose: 'Fermer',
      libraryEmpty: 'Aucun document local',
      untitledDoc: 'Document sans titre',
      updatedAt: 'Mis à jour',
      duplicateDoc: 'Dupliquer',
      deleteDoc: 'Supprimer',
      deleteDocConfirm: 'Supprimer «\u00a0{{title}}\u00a0»\u00a0? Action irréversible.',
      versionHistory: 'Historique',
      noVersions: 'Aucune version',
      restoreVersion: 'Restaurer',
      restoreConfirm: 'Remplacer le contenu actuel par cette version\u00a0?',
      versionChars: '{{count}} caractères',
      draftDegraded: "Brouillon trop volumineux : images retirées pour l'enregistrement local.",
      draftSaveFailed:
        "Échec de l'enregistrement local. Exportez un fichier pour conserver le contenu.",
      printFallback:
        "La boîte de dialogue d'impression est indisponible ; export en PDF snapshot effectué.",
      pageSetup: 'Mise en page',
      pageSetupClose: 'Fermer la mise en page',
      paperSize: 'Format',
      orientation: 'Orientation',
      portrait: 'Portrait',
      landscape: 'Paysage',
      marginPreset: 'Marges',
      margin_normal: 'Normales',
      margin_narrow: 'Étroites',
      margin_wide: 'Larges',
      margin_top: 'Haut',
      margin_right: 'Droite',
      margin_bottom: 'Bas',
      margin_left: 'Gauche',
      headerText: 'En-tête',
      footerText: 'Pied de page',
      headerPlaceholder: "Texte d'en-tête (vide pour masquer)",
      footerPlaceholder: 'Texte de pied de page (vide pour masquer)',
      showPageNumber: 'Numéros de page',
      zoom: 'Zoom',
      docSection: 'Document',
      indentIncrease: 'Augmenter le retrait',
      indentDecrease: 'Diminuer le retrait',
      paragraphSpacing: 'Interligne de paragraphe',
      spacingPresetDefault: 'Par défaut',
      spacingPresetCompact: 'Compact',
      spacingPresetRelaxed: 'Large',
      spacingPresetLoose: 'Très large',
      imageWidth: "Largeur de l'image",
      imageWidthAuto: 'Auto',
      imageWidthCustom: 'Personnalisée ({{px}} px)',
      imageAlign_left: 'Image à gauche',
      imageAlign_center: 'Image centrée',
      imageAlign_right: 'Image à droite',
      imageLayer: 'Habillage',
      imageLayerInline: 'Aligné sur le texte',
      imageLayerFront: 'Devant le texte',
      imageLayerBehind: 'Derrière le texte',
      tableBorders: 'Bordures du tableau',
      tableZebra: 'Lignes alternées',
      insertToc: 'Insérer la table des matières',
      tocTitle: 'Table des matières',
      styles: 'Styles',
      stylesClose: 'Fermer',
      styleBody: 'Corps',
      styleTitle: 'Titre',
      styleHeading2: 'Titre 2',
      styleHeading3: 'Titre 3',
      styleQuote: 'Citation',
      styleCode: 'Code',
      review: 'Commentaires et révisions',
      reviewClose: 'Fermer la révision',
      addComment: 'Nouveau commentaire',
      removeComment: 'Supprimer le commentaire',
      noComments: 'Aucun commentaire',
      commentPrompt: 'Saisissez votre commentaire',
      commentAuthor: 'Utilisateur local',
      trackedChanges: 'Révisions',
      acceptAll: 'Tout accepter',
      rejectAll: 'Tout refuser',
      markInsert: 'Marquer comme insertion',
      markDelete: 'Marquer comme suppression',
      markHint: 'Sélectionnez du texte avant de marquer',
      exportMarkdown: 'Exporter en Markdown',
      exportHtml: 'Exporter en HTML',
      table: 'Insérer un tableau',
      rowAbove: 'Insérer une ligne au-dessus',
      rowBelow: 'Insérer une ligne en dessous',
      columnLeft: 'Insérer une colonne à gauche',
      columnRight: 'Insérer une colonne à droite',
      deleteRow: 'Supprimer la ligne',
      deleteColumn: 'Supprimer la colonne',
      headerRow: "Ligne d'en-tête",
      mergeCells: 'Fusionner les cellules',
      splitCell: 'Scinder la cellule',
      deleteTable: 'Supprimer le tableau',
      alignLeft: 'Aligné à gauche',
      alignCenter: 'Centré',
      alignRight: 'Aligné à droite',
      alignJustify: 'Justifié',
      pdfMode: 'Mode PDF',
      modeText: 'Texte (sélectionnable et recherchable)',
      modeSnapshot: 'Capture (rendu fidèle)',
      modeTextHint:
        "Exporté via l'impression du navigateur : le texte reste sélectionnable et le CJK s'affiche correctement",
      modeSnapshotHint: "Rastérisé page par page au format A4, identique à l'éditeur",
      pdfDialogTitle: 'Exporter en PDF',
      pdfDialogDesc: 'Choisissez un mode d’export (le dernier choix est mémorisé)',
      pdfDialogCancel: 'Annuler',
      exportDocx: 'Exporter Word (.docx)',
      exportPdf: 'Exporter PDF',
      exporting: 'Export en cours…',
      err: {
        EMPTY: 'Le document est vide',
        UNSUPPORTED_LEGACY_DOC:
          'Les anciens formats .doc / .wps / .rtf ne sont pas pris en charge, enregistrez en .docx',
        NOT_DOCX: 'Seuls les fichiers .docx sont pris en charge',
        TOO_LARGE: 'Le contenu dépasse la limite de {{max}} Mo',
        IMPORT_FAILED: "Échec de l'analyse du document",
        EXPORT_FAILED: "Échec de l'export Word",
        RENDER_FAILED: 'Échec de la mise en page',
        SNAPSHOT_FAILED: 'Échec de la génération de la capture PDF',
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Titel',
      present: 'Präsentieren',
      exitPresent: 'Beenden (Esc)',
      presentLoading: 'Präsentationsansicht wird erstellt…',
      presentFailed: 'Präsentationsansicht fehlgeschlagen',
      titlePlaceholder: 'Unbenanntes Dokument',
      importHint: '.docx-Datei hierher ziehen oder auswählen, um Word-Inhalte zu importieren',
      importDocx: 'Word importieren (.docx)',
      placeholder: 'Beginnen Sie zu schreiben… (Word-Import und PDF-Export möglich)',
      chars: 'Zeichen',
      words: 'Wörter',
      paragraphs: 'Absätze',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatische Speicherung nach der Eingabe',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      paragraph: 'Fließtext',
      h1: 'Überschrift 1',
      h2: 'Überschrift 2',
      h3: 'Überschrift 3',
      h4: 'Überschrift 4',
      h5: 'Überschrift 5',
      h6: 'Überschrift 6',
      headingSelect: 'Überschriftenstil',
      fontFamily: 'Schriftart',
      fontDefault: 'Standard',
      fontSans: 'Serifenlos',
      fontSerif: 'Serif',
      fontMono: 'Monospace',
      fontSong: 'Songti',
      fontKai: 'Kaiti',
      fontSize: 'Schriftgröße',
      sizeDefault: 'Standard',
      lineHeight: 'Zeilenhöhe',
      spacingDefault: 'Standard',
      findReplace: 'Suchen und Ersetzen (Ctrl/⌘+F)',
      find: 'Suchen',
      replace: 'Ersetzen durch',
      replaceOne: 'Ersetzen',
      replaceAll: 'Alle ersetzen',
      matchCase: 'Groß-/Kleinschreibung',
      prevMatch: 'Zurück',
      nextMatch: 'Weiter',
      noMatch: 'Keine Treffer',
      closeFind: 'Suche schließen',
      outline: 'Dokumentgliederung',
      viewMode: 'Ansichtsmodus',
      viewFlow: 'Fortlaufend',
      viewPaged: 'Seitenumbruch',
      pageBadge: 'Seite {{page}}',
      bold: 'Fett',
      italic: 'Kursiv',
      underline: 'Unterstrichen',
      strike: 'Durchgestrichen',
      code: 'Inline-Code',
      color: 'Textfarbe',
      highlight: 'Markieren',
      bulletList: 'Unsortierte Liste',
      orderedList: 'Sortierte Liste',
      taskList: 'Aufgabenliste',
      quote: 'Zitat',
      codeBlock: 'Codeblock',
      link: 'Link',
      linkPrompt: 'Link-URL eingeben (leer zum Entfernen)',
      image: 'Bild einfügen',
      divider: 'Trennlinie',
      pageBreak: 'Seitenumbruch einfügen',
      lossExternalImages:
        '{{count}} verlinkte(s) Bild(er) wurden nicht in die Word-Datei eingebettet.',
      lossWebpImages: '{{count}} WebP-Bild(er) übersprungen (bitte PNG/JPEG verwenden).',
      lossDeepLists: '{{count}} Liste(n) tiefer als 8 Ebenen wurden vereinfacht.',
      library: 'Bibliothek',
      libraryNew: 'Neu',
      libraryClose: 'Schließen',
      libraryEmpty: 'Noch keine lokalen Dokumente',
      untitledDoc: 'Unbenanntes Dokument',
      updatedAt: 'Aktualisiert',
      duplicateDoc: 'Duplizieren',
      deleteDoc: 'Löschen',
      deleteDocConfirm: '„{{title}}" löschen? Dies kann nicht rückgängig gemacht werden.',
      versionHistory: 'Versionsverlauf',
      noVersions: 'Noch keine Versionen',
      restoreVersion: 'Wiederherstellen',
      restoreConfirm: 'Aktuellen Inhalt mit dieser Version überschreiben?',
      versionChars: '{{count}} Zeichen',
      draftDegraded: 'Entwurf zu groß: Bilder wurden für die lokale Speicherung entfernt.',
      draftSaveFailed:
        'Lokaler Entwurf konnte nicht gespeichert werden. Exportieren Sie eine Datei.',
      printFallback: 'Druckdialog hier nicht verfügbar; PDF wurde als Snapshot exportiert.',
      pageSetup: 'Seite einrichten',
      pageSetupClose: 'Seiteneinrichtung schließen',
      paperSize: 'Papierformat',
      orientation: 'Ausrichtung',
      portrait: 'Hochformat',
      landscape: 'Querformat',
      marginPreset: 'Ränder',
      margin_normal: 'Normal',
      margin_narrow: 'Schmal',
      margin_wide: 'Breit',
      margin_top: 'Oben',
      margin_right: 'Rechts',
      margin_bottom: 'Unten',
      margin_left: 'Links',
      headerText: 'Kopfzeile',
      footerText: 'Fußzeile',
      headerPlaceholder: 'Kopfzeilentext (leer = ausblenden)',
      footerPlaceholder: 'Fußzeilentext (leer = ausblenden)',
      showPageNumber: 'Seitenzahlen',
      zoom: 'Zoom',
      docSection: 'Dokument',
      indentIncrease: 'Einzug vergrößern',
      indentDecrease: 'Einzug verkleinern',
      paragraphSpacing: 'Absatzabstand',
      spacingPresetDefault: 'Standard',
      spacingPresetCompact: 'Kompakt',
      spacingPresetRelaxed: 'Weit',
      spacingPresetLoose: 'Sehr weit',
      imageWidth: 'Bildbreite',
      imageWidthAuto: 'Auto',
      imageWidthCustom: 'Benutzerdefiniert ({{px}} px)',
      imageAlign_left: 'Bild links',
      imageAlign_center: 'Bild zentriert',
      imageAlign_right: 'Bild rechts',
      imageLayer: 'Textumbruch',
      imageLayerInline: 'Mit Text in Zeile',
      imageLayerFront: 'Vor dem Text',
      imageLayerBehind: 'Hinter dem Text',
      tableBorders: 'Tabellenrahmen',
      tableZebra: 'Zebrastreifen',
      insertToc: 'Inhaltsverzeichnis einfügen',
      tocTitle: 'Inhaltsverzeichnis',
      styles: 'Formatvorlagen',
      stylesClose: 'Schließen',
      styleBody: 'Standard',
      styleTitle: 'Titel',
      styleHeading2: 'Überschrift 2',
      styleHeading3: 'Überschrift 3',
      styleQuote: 'Zitat',
      styleCode: 'Code',
      review: 'Kommentare & Änderungen',
      reviewClose: 'Überprüfung schließen',
      addComment: 'Neuer Kommentar',
      removeComment: 'Kommentar löschen',
      noComments: 'Keine Kommentare',
      commentPrompt: 'Kommentar eingeben',
      commentAuthor: 'Lokaler Benutzer',
      trackedChanges: 'Änderungen',
      acceptAll: 'Alle übernehmen',
      rejectAll: 'Alle ablehnen',
      markInsert: 'Als Einfügung markieren',
      markDelete: 'Als Löschung markieren',
      markHint: 'Text auswählen, dann Änderung markieren',
      exportMarkdown: 'Als Markdown exportieren',
      exportHtml: 'Als HTML exportieren',
      table: 'Tabelle einfügen',
      rowAbove: 'Zeile darüber einfügen',
      rowBelow: 'Zeile darunter einfügen',
      columnLeft: 'Spalte links einfügen',
      columnRight: 'Spalte rechts einfügen',
      deleteRow: 'Zeile löschen',
      deleteColumn: 'Spalte löschen',
      headerRow: 'Kopfzeile',
      mergeCells: 'Zellen verbinden',
      splitCell: 'Zelle teilen',
      deleteTable: 'Tabelle löschen',
      alignLeft: 'Linksbündig',
      alignCenter: 'Zentriert',
      alignRight: 'Rechtsbündig',
      alignJustify: 'Blocksatz',
      pdfMode: 'PDF-Modus',
      modeText: 'Text (auswählbar und durchsuchbar)',
      modeSnapshot: 'Bild (originalgetreu)',
      modeTextHint:
        'Über den Browserdruck exportiert: Text bleibt auswählbar, CJK korrekt dargestellt',
      modeSnapshotHint: 'Seite für Seite im A4-Format gerastert, identisch mit dem Editor',
      pdfDialogTitle: 'Als PDF exportieren',
      pdfDialogDesc: 'Exportmodus wählen (letzte Auswahl wird gemerkt)',
      pdfDialogCancel: 'Abbrechen',
      exportDocx: 'Word exportieren (.docx)',
      exportPdf: 'PDF exportieren',
      exporting: 'Wird exportiert…',
      err: {
        EMPTY: 'Das Dokument ist leer',
        UNSUPPORTED_LEGACY_DOC:
          'Alte .doc- / .wps- / .rtf-Dateien werden nicht unterstützt, bitte als .docx speichern',
        NOT_DOCX: 'Nur .docx-Dateien werden unterstützt',
        TOO_LARGE: 'Der Inhalt überschreitet das Limit von {{max}} MB',
        IMPORT_FAILED: 'Dokument konnte nicht gelesen werden',
        EXPORT_FAILED: 'Word-Export fehlgeschlagen',
        RENDER_FAILED: 'Layout konnte nicht gerendert werden',
        SNAPSHOT_FAILED: 'PDF-Bild konnte nicht erstellt werden',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Titolo',
      present: 'Presenta',
      exitPresent: 'Esci (Esc)',
      presentLoading: 'Preparazione della presentazione…',
      presentFailed: 'Impossibile preparare la presentazione',
      titlePlaceholder: 'Documento senza titolo',
      importHint: 'Trascina o scegli un file .docx per importare il contenuto di Word',
      importDocx: 'Importa Word (.docx)',
      placeholder: 'Inizia a scrivere… (import Word ed export PDF supportati)',
      chars: 'Caratteri',
      words: 'Parole',
      paragraphs: 'Paragrafi',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la digitazione',
      undo: 'Annulla',
      redo: 'Ripeti',
      paragraph: 'Testo normale',
      h1: 'Titolo 1',
      h2: 'Titolo 2',
      h3: 'Titolo 3',
      h4: 'Titolo 4',
      h5: 'Titolo 5',
      h6: 'Titolo 6',
      headingSelect: 'Stile del titolo',
      fontFamily: 'Carattere',
      fontDefault: 'Predefinito',
      fontSans: 'Sans-serif',
      fontSerif: 'Serif',
      fontMono: 'Monospace',
      fontSong: 'Songti',
      fontKai: 'Kaiti',
      fontSize: 'Dimensione',
      sizeDefault: 'Predefinita',
      lineHeight: 'Interlinea',
      spacingDefault: 'Predefinita',
      findReplace: 'Trova e sostituisci (Ctrl/⌘+F)',
      find: 'Trova',
      replace: 'Sostituisci con',
      replaceOne: 'Sostituisci',
      replaceAll: 'Sostituisci tutto',
      matchCase: 'Maiuscole/minuscole',
      prevMatch: 'Precedente',
      nextMatch: 'Successivo',
      noMatch: 'Nessun risultato',
      closeFind: 'Chiudi ricerca',
      outline: 'Struttura del documento',
      viewMode: 'Modalità vista',
      viewFlow: 'Vista continua',
      viewPaged: 'Vista paginata',
      pageBadge: 'Pagina {{page}}',
      bold: 'Grassetto',
      italic: 'Corsivo',
      underline: 'Sottolineato',
      strike: 'Barrato',
      code: 'Codice in linea',
      color: 'Colore del testo',
      highlight: 'Evidenzia',
      bulletList: 'Elenco puntato',
      orderedList: 'Elenco numerato',
      taskList: 'Elenco di attività',
      quote: 'Citazione',
      codeBlock: 'Blocco di codice',
      link: 'Link',
      linkPrompt: "Inserisci l'URL del link (vuoto per rimuoverlo)",
      image: 'Inserisci immagine',
      divider: 'Riga divisoria',
      pageBreak: 'Inserisci interruzione di pagina',
      lossExternalImages: '{{count}} immagine/i collegate non incorporate nel file Word.',
      lossWebpImages: '{{count}} immagine/i WebP ignorate (usa PNG/JPEG).',
      lossDeepLists: '{{count}} elenco/hi annidati oltre 8 livelli sono stati appiattiti.',
      library: 'Libreria',
      libraryNew: 'Nuovo',
      libraryClose: 'Chiudi',
      libraryEmpty: 'Nessun documento locale',
      untitledDoc: 'Documento senza titolo',
      updatedAt: 'Aggiornato',
      duplicateDoc: 'Duplica',
      deleteDoc: 'Elimina',
      deleteDocConfirm: 'Eliminare «{{title}}»? Operazione irreversibile.',
      versionHistory: 'Cronologia versioni',
      noVersions: 'Nessuna versione',
      restoreVersion: 'Ripristina',
      restoreConfirm: 'Sovrascrivere il contenuto attuale con questa versione?',
      versionChars: '{{count}} caratteri',
      draftDegraded: 'Bozza troppo grande: immagini rimosse per il salvataggio locale.',
      draftSaveFailed:
        'Salvataggio locale non riuscito. Esporta un file per conservare il contenuto.',
      printFallback: 'Finestra di stampa non disponibile; esportato come PDF snapshot.',
      pageSetup: 'Impostazioni pagina',
      pageSetupClose: 'Chiudi impostazioni pagina',
      paperSize: 'Formato',
      orientation: 'Orientamento',
      portrait: 'Verticale',
      landscape: 'Orizzontale',
      marginPreset: 'Margini',
      margin_normal: 'Normali',
      margin_narrow: 'Stretti',
      margin_wide: 'Larghi',
      margin_top: 'Alto',
      margin_right: 'Destro',
      margin_bottom: 'Basso',
      margin_left: 'Sinistro',
      headerText: 'Intestazione',
      footerText: 'Piè di pagina',
      headerPlaceholder: 'Testo intestazione (vuoto per nascondere)',
      footerPlaceholder: 'Testo piè di pagina (vuoto per nascondere)',
      showPageNumber: 'Numeri di pagina',
      zoom: 'Zoom',
      docSection: 'Documento',
      indentIncrease: 'Aumenta rientro',
      indentDecrease: 'Riduci rientro',
      paragraphSpacing: 'Spaziatura paragrafo',
      spacingPresetDefault: 'Predefinita',
      spacingPresetCompact: 'Compatta',
      spacingPresetRelaxed: 'Ampia',
      spacingPresetLoose: 'Molto ampia',
      imageWidth: 'Larghezza immagine',
      imageWidthAuto: 'Auto',
      imageWidthCustom: 'Personalizzata ({{px}} px)',
      imageAlign_left: 'Immagine a sinistra',
      imageAlign_center: 'Immagine centrata',
      imageAlign_right: 'Immagine a destra',
      imageLayer: 'Disposizione',
      imageLayerInline: 'In linea con il testo',
      imageLayerFront: 'Davanti al testo',
      imageLayerBehind: 'Dietro il testo',
      tableBorders: 'Bordi tabella',
      tableZebra: 'Righe alternate',
      insertToc: 'Inserisci indice',
      tocTitle: 'Indice',
      styles: 'Stili',
      stylesClose: 'Chiudi',
      styleBody: 'Corpo',
      styleTitle: 'Titolo',
      styleHeading2: 'Titolo 2',
      styleHeading3: 'Titolo 3',
      styleQuote: 'Citazione',
      styleCode: 'Codice',
      review: 'Commenti e revisioni',
      reviewClose: 'Chiudi revisione',
      addComment: 'Nuovo commento',
      removeComment: 'Elimina commento',
      noComments: 'Nessun commento',
      commentPrompt: 'Inserisci il commento',
      commentAuthor: 'Utente locale',
      trackedChanges: 'Revisioni',
      acceptAll: 'Accetta tutto',
      rejectAll: 'Rifiuta tutto',
      markInsert: 'Segna come inserimento',
      markDelete: 'Segna come eliminazione',
      markHint: 'Seleziona il testo prima di segnare',
      exportMarkdown: 'Esporta Markdown',
      exportHtml: 'Esporta HTML',
      table: 'Inserisci tabella',
      rowAbove: 'Inserisci riga sopra',
      rowBelow: 'Inserisci riga sotto',
      columnLeft: 'Inserisci colonna a sinistra',
      columnRight: 'Inserisci colonna a destra',
      deleteRow: 'Elimina riga',
      deleteColumn: 'Elimina colonna',
      headerRow: 'Riga di intestazione',
      mergeCells: 'Unisci celle',
      splitCell: 'Dividi cella',
      deleteTable: 'Elimina tabella',
      alignLeft: 'Allinea a sinistra',
      alignCenter: 'Centra',
      alignRight: 'Allinea a destra',
      alignJustify: 'Giustifica',
      pdfMode: 'Modalità PDF',
      modeText: 'Testo (selezionabile e ricercabile)',
      modeSnapshot: 'Immagine (fedeltà visiva)',
      modeTextHint:
        'Esportato tramite la stampa del browser: il testo resta selezionabile e il CJK appare correttamente',
      modeSnapshotHint: "Rasterizzato pagina per pagina in formato A4, identico all'editor",
      pdfDialogTitle: 'Esporta PDF',
      pdfDialogDesc: "Scegli una modalità di esportazione (l'ultima scelta viene ricordata)",
      pdfDialogCancel: 'Annulla',
      exportDocx: 'Esporta Word (.docx)',
      exportPdf: 'Esporta PDF',
      exporting: 'Esportazione…',
      err: {
        EMPTY: 'Il documento è vuoto',
        UNSUPPORTED_LEGACY_DOC:
          'I formati .doc / .wps / .rtf precedenti non sono supportati, salva come .docx',
        NOT_DOCX: 'Sono supportati solo i file .docx',
        TOO_LARGE: 'Il contenuto supera il limite di {{max}} MB',
        IMPORT_FAILED: 'Analisi del documento non riuscita',
        EXPORT_FAILED: 'Esportazione Word non riuscita',
        RENDER_FAILED: 'Composizione del documento non riuscita',
        SNAPSHOT_FAILED: 'Generazione della cattura PDF non riuscita',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Título',
      present: 'Presentar',
      exitPresent: 'Salir (Esc)',
      presentLoading: 'Preparando la presentación…',
      presentFailed: 'No se pudo preparar la presentación',
      titlePlaceholder: 'Documento sin título',
      importHint: 'Arrastra o elige un archivo .docx para importar el contenido de Word',
      importDocx: 'Importar Word (.docx)',
      placeholder: 'Empieza a escribir… (importación de Word y exportación a PDF compatibles)',
      chars: 'Caracteres',
      words: 'Palabras',
      paragraphs: 'Párrafos',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de escribir',
      undo: 'Deshacer',
      redo: 'Rehacer',
      paragraph: 'Texto normal',
      h1: 'Título 1',
      h2: 'Título 2',
      h3: 'Título 3',
      h4: 'Título 4',
      h5: 'Título 5',
      h6: 'Título 6',
      headingSelect: 'Estilo de título',
      fontFamily: 'Fuente',
      fontDefault: 'Predeterminada',
      fontSans: 'Sans-serif',
      fontSerif: 'Serif',
      fontMono: 'Monospace',
      fontSong: 'Songti',
      fontKai: 'Kaiti',
      fontSize: 'Tamaño',
      sizeDefault: 'Predeterminado',
      lineHeight: 'Interlineado',
      spacingDefault: 'Predeterminado',
      findReplace: 'Buscar y reemplazar (Ctrl/⌘+F)',
      find: 'Buscar',
      replace: 'Reemplazar con',
      replaceOne: 'Reemplazar',
      replaceAll: 'Reemplazar todo',
      matchCase: 'Distinguir mayúsculas',
      prevMatch: 'Anterior',
      nextMatch: 'Siguiente',
      noMatch: 'Sin resultados',
      closeFind: 'Cerrar búsqueda',
      outline: 'Esquema del documento',
      viewMode: 'Modo de vista',
      viewFlow: 'Vista continua',
      viewPaged: 'Vista paginada',
      pageBadge: 'Página {{page}}',
      bold: 'Negrita',
      italic: 'Cursiva',
      underline: 'Subrayado',
      strike: 'Tachado',
      code: 'Código en línea',
      color: 'Color del texto',
      highlight: 'Resaltar',
      bulletList: 'Lista con viñetas',
      orderedList: 'Lista numerada',
      taskList: 'Lista de tareas',
      quote: 'Cita',
      codeBlock: 'Bloque de código',
      link: 'Enlace',
      linkPrompt: 'Introduce la URL del enlace (vacío para eliminarlo)',
      image: 'Insertar imagen',
      divider: 'Separador',
      pageBreak: 'Insertar salto de página',
      lossExternalImages:
        '{{count}} imagen/imagenes vinculadas no se incrustaron en el archivo Word.',
      lossWebpImages: '{{count}} imagen/imagenes WebP omitidas (usa PNG/JPEG).',
      lossDeepLists: '{{count}} lista/s con más de 8 niveles se aplanaron.',
      library: 'Biblioteca',
      libraryNew: 'Nuevo',
      libraryClose: 'Cerrar',
      libraryEmpty: 'Aún no hay documentos locales',
      untitledDoc: 'Documento sin título',
      updatedAt: 'Actualizado',
      duplicateDoc: 'Duplicar',
      deleteDoc: 'Eliminar',
      deleteDocConfirm: '¿Eliminar «{{title}}»? Esta acción no se puede deshacer.',
      versionHistory: 'Historial de versiones',
      noVersions: 'Aún no hay versiones',
      restoreVersion: 'Restaurar',
      restoreConfirm: '¿Sobrescribir el contenido actual con esta versión?',
      versionChars: '{{count}} caracteres',
      draftDegraded: 'Borrador demasiado grande: se quitaron las imágenes para guardarlo.',
      draftSaveFailed:
        'No se pudo guardar el borrador local. Exporta un archivo para conservar el contenido.',
      printFallback:
        'El diálogo de impresión no está disponible; se exportó como PDF de instantánea.',
      pageSetup: 'Configuración de página',
      pageSetupClose: 'Cerrar configuración de página',
      paperSize: 'Tamaño',
      orientation: 'Orientación',
      portrait: 'Vertical',
      landscape: 'Horizontal',
      marginPreset: 'Márgenes',
      margin_normal: 'Normales',
      margin_narrow: 'Estrechos',
      margin_wide: 'Amplios',
      margin_top: 'Superior',
      margin_right: 'Derecho',
      margin_bottom: 'Inferior',
      margin_left: 'Izquierdo',
      headerText: 'Encabezado',
      footerText: 'Pie de página',
      headerPlaceholder: 'Texto del encabezado (vacío para ocultar)',
      footerPlaceholder: 'Texto del pie (vacío para ocultar)',
      showPageNumber: 'Números de página',
      zoom: 'Zoom',
      docSection: 'Documento',
      indentIncrease: 'Aumentar sangría',
      indentDecrease: 'Reducir sangría',
      paragraphSpacing: 'Espaciado de párrafo',
      spacingPresetDefault: 'Predeterminado',
      spacingPresetCompact: 'Compacto',
      spacingPresetRelaxed: 'Amplio',
      spacingPresetLoose: 'Muy amplio',
      imageWidth: 'Ancho de imagen',
      imageWidthAuto: 'Auto',
      imageWidthCustom: 'Personalizado ({{px}} px)',
      imageAlign_left: 'Imagen a la izquierda',
      imageAlign_center: 'Imagen centrada',
      imageAlign_right: 'Imagen a la derecha',
      imageLayer: 'Ajuste de texto',
      imageLayerInline: 'En línea con el texto',
      imageLayerFront: 'Delante del texto',
      imageLayerBehind: 'Detrás del texto',
      tableBorders: 'Bordes de tabla',
      tableZebra: 'Filas alternas',
      insertToc: 'Insertar índice',
      tocTitle: 'Índice',
      styles: 'Estilos',
      stylesClose: 'Cerrar',
      styleBody: 'Cuerpo',
      styleTitle: 'Título',
      styleHeading2: 'Título 2',
      styleHeading3: 'Título 3',
      styleQuote: 'Cita',
      styleCode: 'Código',
      review: 'Comentarios y cambios',
      reviewClose: 'Cerrar revisión',
      addComment: 'Nuevo comentario',
      removeComment: 'Eliminar comentario',
      noComments: 'Sin comentarios',
      commentPrompt: 'Introduce tu comentario',
      commentAuthor: 'Usuario local',
      trackedChanges: 'Cambios',
      acceptAll: 'Aceptar todo',
      rejectAll: 'Rechazar todo',
      markInsert: 'Marcar como inserción',
      markDelete: 'Marcar como eliminación',
      markHint: 'Selecciona el texto antes de marcar',
      exportMarkdown: 'Exportar Markdown',
      exportHtml: 'Exportar HTML',
      table: 'Insertar tabla',
      rowAbove: 'Insertar fila arriba',
      rowBelow: 'Insertar fila abajo',
      columnLeft: 'Insertar columna a la izquierda',
      columnRight: 'Insertar columna a la derecha',
      deleteRow: 'Eliminar fila',
      deleteColumn: 'Eliminar columna',
      headerRow: 'Fila de encabezado',
      mergeCells: 'Combinar celdas',
      splitCell: 'Dividir celda',
      deleteTable: 'Eliminar tabla',
      alignLeft: 'Alinear a la izquierda',
      alignCenter: 'Centrar',
      alignRight: 'Alinear a la derecha',
      alignJustify: 'Justificar',
      pdfMode: 'Modo PDF',
      modeText: 'Texto (seleccionable y con posibilidad de búsqueda)',
      modeSnapshot: 'Captura (fiel al diseño)',
      modeTextHint:
        'Se exporta con la impresión del navegador: el texto sigue siendo seleccionable y los caracteres chinos se muestran bien',
      modeSnapshotHint: 'Se rasteriza página a página en tamaño A4, idéntico al editor',
      pdfDialogTitle: 'Exportar PDF',
      pdfDialogDesc: 'Elige un modo de exportación (se recuerda la última opción)',
      pdfDialogCancel: 'Cancelar',
      exportDocx: 'Exportar Word (.docx)',
      exportPdf: 'Exportar PDF',
      exporting: 'Exportando…',
      err: {
        EMPTY: 'El documento está vacío',
        UNSUPPORTED_LEGACY_DOC:
          'Los formatos antiguos .doc / .wps / .rtf no son compatibles, guarda como .docx',
        NOT_DOCX: 'Solo se admiten archivos .docx',
        TOO_LARGE: 'El contenido supera el límite de {{max}} MB',
        IMPORT_FAILED: 'No se pudo analizar el documento',
        EXPORT_FAILED: 'La exportación a Word falló',
        RENDER_FAILED: 'No se pudo componer el documento',
        SNAPSHOT_FAILED: 'No se pudo generar la captura en PDF',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    richText: {
      docTitle: 'Título',
      present: 'Apresentar',
      exitPresent: 'Sair (Esc)',
      presentLoading: 'A preparar a apresentação…',
      presentFailed: 'Falha ao preparar a apresentação',
      titlePlaceholder: 'Documento sem título',
      importHint: 'Arraste ou escolha um ficheiro .docx para importar o conteúdo do Word',
      importDocx: 'Importar Word (.docx)',
      placeholder: 'Comece a escrever… (importação Word e exportação PDF suportadas)',
      chars: 'Caracteres',
      words: 'Palavras',
      paragraphs: 'Parágrafos',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de escrever',
      undo: 'Anular',
      redo: 'Refazer',
      paragraph: 'Texto normal',
      h1: 'Título 1',
      h2: 'Título 2',
      h3: 'Título 3',
      h4: 'Título 4',
      h5: 'Título 5',
      h6: 'Título 6',
      headingSelect: 'Estilo de título',
      fontFamily: 'Tipo de letra',
      fontDefault: 'Predefinida',
      fontSans: 'Sans-serif',
      fontSerif: 'Serif',
      fontMono: 'Monospace',
      fontSong: 'Songti',
      fontKai: 'Kaiti',
      fontSize: 'Tamanho',
      sizeDefault: 'Predefinido',
      lineHeight: 'Altura da linha',
      spacingDefault: 'Predefinido',
      findReplace: 'Localizar e substituir (Ctrl/⌘+F)',
      find: 'Localizar',
      replace: 'Substituir por',
      replaceOne: 'Substituir',
      replaceAll: 'Substituir tudo',
      matchCase: 'Diferenciar maiúsculas',
      prevMatch: 'Anterior',
      nextMatch: 'Seguinte',
      noMatch: 'Sem resultados',
      closeFind: 'Fechar localizar',
      outline: 'Estrutura do documento',
      viewMode: 'Modo de vista',
      viewFlow: 'Vista contínua',
      viewPaged: 'Vista paginada',
      pageBadge: 'Página {{page}}',
      bold: 'Negrito',
      italic: 'Itálico',
      underline: 'Sublinhado',
      strike: 'Rasurado',
      code: 'Código em linha',
      color: 'Cor do texto',
      highlight: 'Realçar',
      bulletList: 'Lista com marcadores',
      orderedList: 'Lista numerada',
      taskList: 'Lista de tarefas',
      quote: 'Citação',
      codeBlock: 'Bloco de código',
      link: 'Ligação',
      linkPrompt: 'Introduza o URL da ligação (vazio para remover)',
      image: 'Inserir imagem',
      divider: 'Separador',
      pageBreak: 'Inserir quebra de página',
      lossExternalImages:
        '{{count}} imagem/imagens ligadas não foram incorporadas no ficheiro Word.',
      lossWebpImages: '{{count}} imagem/imagens WebP ignoradas (use PNG/JPEG).',
      lossDeepLists: '{{count}} lista(s) com mais de 8 níveis foram achatadas.',
      library: 'Biblioteca',
      libraryNew: 'Novo',
      libraryClose: 'Fechar',
      libraryEmpty: 'Ainda não há documentos locais',
      untitledDoc: 'Documento sem título',
      updatedAt: 'Atualizado',
      duplicateDoc: 'Duplicar',
      deleteDoc: 'Eliminar',
      deleteDocConfirm: 'Eliminar «{{title}}»? Esta ação não pode ser desfeita.',
      versionHistory: 'Histórico de versões',
      noVersions: 'Ainda não há versões',
      restoreVersion: 'Restaurar',
      restoreConfirm: 'Substituir o conteúdo atual por esta versão?',
      versionChars: '{{count}} caracteres',
      draftDegraded: 'Rascunho grande demais: as imagens foram removidas para guardar localmente.',
      draftSaveFailed:
        'Falha ao guardar o rascunho local. Exporte um ficheiro para manter o conteúdo.',
      printFallback: 'Diálogo de impressão indisponível; exportado como PDF de instantâneo.',
      pageSetup: 'Configuração da página',
      pageSetupClose: 'Fechar configuração da página',
      paperSize: 'Tamanho',
      orientation: 'Orientação',
      portrait: 'Retrato',
      landscape: 'Paisagem',
      marginPreset: 'Margens',
      margin_normal: 'Normais',
      margin_narrow: 'Estreitas',
      margin_wide: 'Largas',
      margin_top: 'Superior',
      margin_right: 'Direita',
      margin_bottom: 'Inferior',
      margin_left: 'Esquerda',
      headerText: 'Cabeçalho',
      footerText: 'Rodapé',
      headerPlaceholder: 'Texto do cabeçalho (vazio para ocultar)',
      footerPlaceholder: 'Texto do rodapé (vazio para ocultar)',
      showPageNumber: 'Números de página',
      zoom: 'Ampliação',
      docSection: 'Documento',
      indentIncrease: 'Aumentar avanço',
      indentDecrease: 'Reduzir avanço',
      paragraphSpacing: 'Espaçamento do parágrafo',
      spacingPresetDefault: 'Predefinido',
      spacingPresetCompact: 'Compacto',
      spacingPresetRelaxed: 'Amplo',
      spacingPresetLoose: 'Muito amplo',
      imageWidth: 'Largura da imagem',
      imageWidthAuto: 'Auto',
      imageWidthCustom: 'Personalizado ({{px}} px)',
      imageAlign_left: 'Imagem à esquerda',
      imageAlign_center: 'Imagem centrada',
      imageAlign_right: 'Imagem à direita',
      imageLayer: 'Quebra de texto',
      imageLayerInline: 'Alinhado ao texto',
      imageLayerFront: 'À frente do texto',
      imageLayerBehind: 'Atrás do texto',
      tableBorders: 'Contornos da tabela',
      tableZebra: 'Linhas alternadas',
      insertToc: 'Inserir índice',
      tocTitle: 'Índice',
      styles: 'Estilos',
      stylesClose: 'Fechar',
      styleBody: 'Corpo',
      styleTitle: 'Título',
      styleHeading2: 'Título 2',
      styleHeading3: 'Título 3',
      styleQuote: 'Citação',
      styleCode: 'Código',
      review: 'Comentários e alterações',
      reviewClose: 'Fechar revisão',
      addComment: 'Novo comentário',
      removeComment: 'Eliminar comentário',
      noComments: 'Sem comentários',
      commentPrompt: 'Introduza o comentário',
      commentAuthor: 'Utilizador local',
      trackedChanges: 'Alterações',
      acceptAll: 'Aceitar tudo',
      rejectAll: 'Rejeitar tudo',
      markInsert: 'Marcar como inserção',
      markDelete: 'Marcar como eliminação',
      markHint: 'Selecione o texto antes de marcar',
      exportMarkdown: 'Exportar Markdown',
      exportHtml: 'Exportar HTML',
      table: 'Inserir tabela',
      rowAbove: 'Inserir linha acima',
      rowBelow: 'Inserir linha abaixo',
      columnLeft: 'Inserir coluna à esquerda',
      columnRight: 'Inserir coluna à direita',
      deleteRow: 'Eliminar linha',
      deleteColumn: 'Eliminar coluna',
      headerRow: 'Linha de cabeçalho',
      mergeCells: 'Unir células',
      splitCell: 'Dividir célula',
      deleteTable: 'Eliminar tabela',
      alignLeft: 'Alinhar à esquerda',
      alignCenter: 'Centrar',
      alignRight: 'Alinhar à direita',
      alignJustify: 'Justificar',
      pdfMode: 'Modo PDF',
      modeText: 'Texto (selecionável e pesquisável)',
      modeSnapshot: 'Captura (fidelidade visual)',
      modeTextHint:
        'Exportado pela impressão do navegador: o texto mantém-se selecionável e o CJK é apresentado corretamente',
      modeSnapshotHint: 'Rasterizado página a página em formato A4, idêntico ao editor',
      pdfDialogTitle: 'Exportar PDF',
      pdfDialogDesc: 'Escolha um modo de exportação (a última escolha é memorizada)',
      pdfDialogCancel: 'Cancelar',
      exportDocx: 'Exportar Word (.docx)',
      exportPdf: 'Exportar PDF',
      exporting: 'A exportar…',
      err: {
        EMPTY: 'O documento está vazio',
        UNSUPPORTED_LEGACY_DOC:
          'Os formatos antigos .doc / .wps / .rtf não são suportados, guarde como .docx',
        NOT_DOCX: 'Apenas são suportados ficheiros .docx',
        TOO_LARGE: 'O conteúdo excede o limite de {{max}} MB',
        IMPORT_FAILED: 'Falha ao analisar o documento',
        EXPORT_FAILED: 'Falha ao exportar para Word',
        RENDER_FAILED: 'Falha ao compor o documento',
        SNAPSHOT_FAILED: 'Falha ao gerar a captura em PDF',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const richTextStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具被懒加载时调用，键路径 tools.richText.*） */
export function registerRichTextStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(richTextStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
