/**
 * 九语言图形名（侧边栏与属性面板显示用）。
 * 集中在此管理，避免 strings.ts 随形状数量增长而膨胀；
 * 注册时按 `shape_<kind>` 键合并进 `tools.flowchart` 命名空间。
 */

import { SHAPE_LABELS, type ShapeKind } from './types';

export type ShapeLabelMap = Record<ShapeKind, string>;

export const SHAPE_LABELS_I18N: Record<string, ShapeLabelMap> = {
  // 中文名已在 types.ts 的 SHAPE_LABELS 中定义（同时作为 i18n 缺失时的回退）
  zh: SHAPE_LABELS,

  en: {
    rect: 'Process',
    roundRect: 'Rounded rectangle',
    ellipse: 'Ellipse',
    diamond: 'Diamond',
    parallelogram: 'Parallelogram',
    trapezoid: 'Trapezoid',
    hexagon: 'Hexagon',
    cylinder: 'Cylinder',
    note: 'Note',
    startEnd: 'Start / End',
    decision: 'Decision',
    data: 'Data',
    document: 'Document',
    predefined: 'Predefined process',
    manualInput: 'Manual input',
    manualOperation: 'Manual operation',
    preparation: 'Preparation',
    database: 'Database',
    display: 'Display',
    onPageConnector: 'On-page connector',
    offPageConnector: 'Off-page connector',
    terminator: 'Terminator',
    parallelMode: 'Parallel mode',
    loopLimit: 'Loop limit',
    umlActor: 'Actor',
    umlUseCase: 'Use case',
    umlClass: 'Class',
    umlInterface: 'Interface',
    umlPackage: 'Package',
    umlNote: 'Note',
    umlLifeline: 'Lifeline',
    umlState: 'State',
    umlStateInitial: 'Initial state',
    umlStateFinal: 'Final state',
    umlForkJoin: 'Fork / Join',
    bpmnEventStart: 'Start event',
    bpmnEventIntermediate: 'Intermediate event',
    bpmnEventEnd: 'End event',
    bpmnGatewayExclusive: 'Exclusive gateway',
    bpmnGatewayParallel: 'Parallel gateway',
    bpmnGatewayInclusive: 'Inclusive gateway',
    bpmnTask: 'Task',
    bpmnSubProcess: 'Sub-process',
    bpmnCallActivity: 'Call activity',
    bpmnDataObject: 'Data object',
    bpmnDataStore: 'Data store',
    bpmnTextAnnotation: 'Text annotation',
    netServer: 'Server',
    netClient: 'Client',
    netRouter: 'Router',
    netSwitch: 'Switch',
    netFirewall: 'Firewall',
    netLoadBalancer: 'Load balancer',
    netCloud: 'Cloud',
    netCdn: 'CDN',
    netDatabase: 'Database',
    netStorage: 'Storage',
    orgUnit: 'Unit',
    orgAssistant: 'Assistant',
    orgTeam: 'Team',
    mindCenter: 'Central topic',
    mindTopic: 'Topic',
    mindSub: 'Subtopic',
    erEntity: 'Entity',
    erAttribute: 'Attribute',
    erRelationship: 'Relationship',
    erWeakEntity: 'Weak entity',
    swimlane: 'Horizontal lane',
    swimlaneV: 'Vertical lane',
    group: 'Group',
    triangle: 'Triangle',
    star: 'Star',
    pentagon: 'Pentagon',
    octagon: 'Octagon',
    chevron: 'Chevron',
    card: 'Card',
    callout: 'Callout',
    cloud: 'Cloud',
    cross: 'Cross',
    plus: 'Plus',
    flag: 'Flag',
    lightning: 'Lightning',
    arrow: 'Arrow',
    bracket: 'Bracket',
  },

  'zh-TW': {
    rect: '過程',
    roundRect: '圓角矩形',
    ellipse: '橢圓',
    diamond: '菱形',
    parallelogram: '平行四邊形',
    trapezoid: '梯形',
    hexagon: '六邊形',
    cylinder: '圓柱',
    note: '便簽',
    startEnd: '開始/結束',
    decision: '判斷',
    data: '資料',
    document: '文件',
    predefined: '預定義過程',
    manualInput: '手動輸入',
    manualOperation: '人工操作',
    preparation: '準備',
    database: '資料庫',
    display: '顯示',
    onPageConnector: '同頁連接符',
    offPageConnector: '離頁連接符',
    terminator: '終止',
    parallelMode: '並行模式',
    loopLimit: '迴圈上限',
    umlActor: '角色',
    umlUseCase: '使用案例',
    umlClass: '類別',
    umlInterface: '介面',
    umlPackage: '套件',
    umlNote: '註釋',
    umlLifeline: '生命線',
    umlState: '狀態',
    umlStateInitial: '初始狀態',
    umlStateFinal: '終止狀態',
    umlForkJoin: '分岔/會合',
    bpmnEventStart: '開始事件',
    bpmnEventIntermediate: '中間事件',
    bpmnEventEnd: '結束事件',
    bpmnGatewayExclusive: '排他閘道',
    bpmnGatewayParallel: '平行閘道',
    bpmnGatewayInclusive: '包容閘道',
    bpmnTask: '任務',
    bpmnSubProcess: '子流程',
    bpmnCallActivity: '呼叫活動',
    bpmnDataObject: '資料物件',
    bpmnDataStore: '資料儲存',
    bpmnTextAnnotation: '文字註解',
    netServer: '伺服器',
    netClient: '用戶端',
    netRouter: '路由器',
    netSwitch: '交換器',
    netFirewall: '防火牆',
    netLoadBalancer: '負載平衡',
    netCloud: '雲端',
    netCdn: 'CDN',
    netDatabase: '資料庫',
    netStorage: '儲存',
    orgUnit: '組織單位',
    orgAssistant: '助理',
    orgTeam: '團隊',
    mindCenter: '中心主題',
    mindTopic: '子主題',
    mindSub: '次主題',
    erEntity: '實體',
    erAttribute: '屬性',
    erRelationship: '關聯',
    erWeakEntity: '弱實體',
    swimlane: '橫向泳道',
    swimlaneV: '縱向泳道',
    group: '群組',
    triangle: '三角形',
    star: '星形',
    pentagon: '五邊形',
    octagon: '八邊形',
    chevron: '箭頭',
    card: '卡片',
    callout: '標註',
    cloud: '雲',
    cross: '叉號',
    plus: '加號',
    flag: '旗幟',
    lightning: '閃電',
    arrow: '箭頭圖形',
    bracket: '方括號',
  },

  ja: {
    rect: '処理',
    roundRect: '角丸め長方形',
    ellipse: '楕円',
    diamond: '菱形',
    parallelogram: '平行四辺形',
    trapezoid: '台形',
    hexagon: '六角形',
    cylinder: '円柱',
    note: '付箋',
    startEnd: '開始/終了',
    decision: '判断',
    data: 'データ',
    document: '文書',
    predefined: '定義済み処理',
    manualInput: '手動入力',
    manualOperation: '手作業',
    preparation: '準備',
    database: 'データベース',
    display: '表示',
    onPageConnector: 'ページ内接続子',
    offPageConnector: 'ページ外接続子',
    terminator: '端子',
    parallelMode: '並行モード',
    loopLimit: 'ループ上限',
    umlActor: 'アクター',
    umlUseCase: 'ユースケース',
    umlClass: 'クラス',
    umlInterface: 'インターフェース',
    umlPackage: 'パッケージ',
    umlNote: 'ノート',
    umlLifeline: 'ライフライン',
    umlState: '状態',
    umlStateInitial: '初期状態',
    umlStateFinal: '終了状態',
    umlForkJoin: '分岐/合流',
    bpmnEventStart: '開始イベント',
    bpmnEventIntermediate: '中間イベント',
    bpmnEventEnd: '終了イベント',
    bpmnGatewayExclusive: '排他ゲートウェイ',
    bpmnGatewayParallel: '並列ゲートウェイ',
    bpmnGatewayInclusive: '包含ゲートウェイ',
    bpmnTask: 'タスク',
    bpmnSubProcess: 'サブプロセス',
    bpmnCallActivity: '呼び出しアクティビティ',
    bpmnDataObject: 'データオブジェクト',
    bpmnDataStore: 'データストア',
    bpmnTextAnnotation: 'テキスト注釈',
    netServer: 'サーバー',
    netClient: 'クライアント',
    netRouter: 'ルーター',
    netSwitch: 'スイッチ',
    netFirewall: 'ファイアウォール',
    netLoadBalancer: 'ロードバランサー',
    netCloud: 'クラウド',
    netCdn: 'CDN',
    netDatabase: 'データベース',
    netStorage: 'ストレージ',
    orgUnit: '組織単位',
    orgAssistant: '補佐',
    orgTeam: 'チーム',
    mindCenter: '中心トピック',
    mindTopic: 'トピック',
    mindSub: 'サブトピック',
    erEntity: 'エンティティ',
    erAttribute: '属性',
    erRelationship: 'リレーションシップ',
    erWeakEntity: '弱エンティティ',
    swimlane: '横スイムレーン',
    swimlaneV: '縦スイムレーン',
    group: 'グループ',
    triangle: '三角形',
    star: '星',
    pentagon: '五角形',
    octagon: '八角形',
    chevron: '矢印',
    card: 'カード',
    callout: '吹き出し',
    cloud: '雲',
    cross: 'バツ',
    plus: 'プラス',
    flag: '旗',
    lightning: '雷',
    arrow: '矢印図形',
    bracket: '大括弧',
  },

  fr: {
    rect: 'Processus',
    roundRect: 'Rectangle arrondi',
    ellipse: 'Ellipse',
    diamond: 'Losange',
    parallelogram: 'Parallélogramme',
    trapezoid: 'Trapèze',
    hexagon: 'Hexagone',
    cylinder: 'Cylindre',
    note: 'Note',
    startEnd: 'Début / Fin',
    decision: 'Décision',
    data: 'Données',
    document: 'Document',
    predefined: 'Processus prédéfini',
    manualInput: 'Saisie manuelle',
    manualOperation: 'Opération manuelle',
    preparation: 'Préparation',
    database: 'Base de données',
    display: 'Affichage',
    onPageConnector: 'Connecteur même page',
    offPageConnector: 'Connecteur hors page',
    terminator: 'Terminateur',
    parallelMode: 'Mode parallèle',
    loopLimit: 'Limite de boucle',
    umlActor: 'Acteur',
    umlUseCase: "Cas d'utilisation",
    umlClass: 'Classe',
    umlInterface: 'Interface',
    umlPackage: 'Paquet',
    umlNote: 'Note',
    umlLifeline: 'Ligne de vie',
    umlState: 'État',
    umlStateInitial: 'État initial',
    umlStateFinal: 'État final',
    umlForkJoin: 'Embranchement / Jonction',
    bpmnEventStart: 'Événement de début',
    bpmnEventIntermediate: 'Événement intermédiaire',
    bpmnEventEnd: 'Événement de fin',
    bpmnGatewayExclusive: 'Passerelle exclusive',
    bpmnGatewayParallel: 'Passerelle parallèle',
    bpmnGatewayInclusive: 'Passerelle inclusive',
    bpmnTask: 'Tâche',
    bpmnSubProcess: 'Sous-processus',
    bpmnCallActivity: 'Activité appelante',
    bpmnDataObject: 'Objet de données',
    bpmnDataStore: 'Magasin de données',
    bpmnTextAnnotation: 'Annotation de texte',
    netServer: 'Serveur',
    netClient: 'Client',
    netRouter: 'Routeur',
    netSwitch: 'Commutateur',
    netFirewall: 'Pare-feu',
    netLoadBalancer: 'Répartiteur de charge',
    netCloud: 'Cloud',
    netCdn: 'CDN',
    netDatabase: 'Base de données',
    netStorage: 'Stockage',
    orgUnit: 'Unité',
    orgAssistant: 'Assistant',
    orgTeam: 'Équipe',
    mindCenter: 'Sujet central',
    mindTopic: 'Sujet',
    mindSub: 'Sous-sujet',
    erEntity: 'Entité',
    erAttribute: 'Attribut',
    erRelationship: 'Relation',
    erWeakEntity: 'Entité faible',
    swimlane: 'Ligne horizontale',
    swimlaneV: 'Ligne verticale',
    group: 'Groupe',
    triangle: 'Triangle',
    star: 'Étoile',
    pentagon: 'Pentagone',
    octagon: 'Octogone',
    chevron: 'Chevron',
    card: 'Carte',
    callout: 'Annotation',
    cloud: 'Nuage',
    cross: 'Croix',
    plus: 'Plus',
    flag: 'Drapeau',
    lightning: 'Éclair',
    arrow: 'Flèche',
    bracket: 'Crochet',
  },

  de: {
    rect: 'Prozess',
    roundRect: 'Abgerundetes Rechteck',
    ellipse: 'Ellipse',
    diamond: 'Raute',
    parallelogram: 'Parallelogramm',
    trapezoid: 'Trapez',
    hexagon: 'Sechseck',
    cylinder: 'Zylinder',
    note: 'Notiz',
    startEnd: 'Start / Ende',
    decision: 'Entscheidung',
    data: 'Daten',
    document: 'Dokument',
    predefined: 'Vordefinierter Prozess',
    manualInput: 'Manuelle Eingabe',
    manualOperation: 'Manueller Vorgang',
    preparation: 'Vorbereitung',
    database: 'Datenbank',
    display: 'Anzeige',
    onPageConnector: 'Verbinder gleiche Seite',
    offPageConnector: 'Verbinder andere Seite',
    terminator: 'Abschluss',
    parallelMode: 'Parallelmodus',
    loopLimit: 'Schleifengrenze',
    umlActor: 'Akteur',
    umlUseCase: 'Anwendungsfall',
    umlClass: 'Klasse',
    umlInterface: 'Schnittstelle',
    umlPackage: 'Paket',
    umlNote: 'Notiz',
    umlLifeline: 'Lebenslinie',
    umlState: 'Zustand',
    umlStateInitial: 'Anfangszustand',
    umlStateFinal: 'Endzustand',
    umlForkJoin: 'Gabelung / Zusammenführung',
    bpmnEventStart: 'Startereignis',
    bpmnEventIntermediate: 'Zwischenereignis',
    bpmnEventEnd: 'Endereignis',
    bpmnGatewayExclusive: 'Exklusives Gateway',
    bpmnGatewayParallel: 'Paralleles Gateway',
    bpmnGatewayInclusive: 'Inklusives Gateway',
    bpmnTask: 'Aufgabe',
    bpmnSubProcess: 'Teilprozess',
    bpmnCallActivity: 'Aufrufende Aktivität',
    bpmnDataObject: 'Datenobjekt',
    bpmnDataStore: 'Datenspeicher',
    bpmnTextAnnotation: 'Textanmerkung',
    netServer: 'Server',
    netClient: 'Client',
    netRouter: 'Router',
    netSwitch: 'Switch',
    netFirewall: 'Firewall',
    netLoadBalancer: 'Lastverteiler',
    netCloud: 'Cloud',
    netCdn: 'CDN',
    netDatabase: 'Datenbank',
    netStorage: 'Speicher',
    orgUnit: 'Einheit',
    orgAssistant: 'Assistenz',
    orgTeam: 'Team',
    mindCenter: 'Hauptthema',
    mindTopic: 'Thema',
    mindSub: 'Unterthema',
    erEntity: 'Entität',
    erAttribute: 'Attribut',
    erRelationship: 'Beziehung',
    erWeakEntity: 'Schwache Entität',
    swimlane: 'Horizontale Spur',
    swimlaneV: 'Vertikale Spur',
    group: 'Gruppe',
    triangle: 'Dreieck',
    star: 'Stern',
    pentagon: 'Fünfeck',
    octagon: 'Achteck',
    chevron: 'Pfeil',
    card: 'Karte',
    callout: 'Sprechblase',
    cloud: 'Wolke',
    cross: 'Kreuz',
    plus: 'Plus',
    flag: 'Fahne',
    lightning: 'Blitz',
    arrow: 'Pfeil',
    bracket: 'Klammer',
  },

  it: {
    rect: 'Processo',
    roundRect: 'Rettangolo arrotondato',
    ellipse: 'Ellisse',
    diamond: 'Diamante',
    parallelogram: 'Parallelogramma',
    trapezoid: 'Trapezio',
    hexagon: 'Esagono',
    cylinder: 'Cilindro',
    note: 'Nota',
    startEnd: 'Inizio / Fine',
    decision: 'Decisione',
    data: 'Dati',
    document: 'Documento',
    predefined: 'Processo predefinito',
    manualInput: 'Inserimento manuale',
    manualOperation: 'Operazione manuale',
    preparation: 'Preparazione',
    database: 'Database',
    display: 'Visualizzazione',
    onPageConnector: 'Connettore stessa pagina',
    offPageConnector: 'Connettore altra pagina',
    terminator: 'Terminatore',
    parallelMode: 'Modalità parallela',
    loopLimit: 'Limite ciclo',
    umlActor: 'Attore',
    umlUseCase: "Caso d'uso",
    umlClass: 'Classe',
    umlInterface: 'Interfaccia',
    umlPackage: 'Pacchetto',
    umlNote: 'Nota',
    umlLifeline: 'Linea di vita',
    umlState: 'Stato',
    umlStateInitial: 'Stato iniziale',
    umlStateFinal: 'Stato finale',
    umlForkJoin: 'Biforcazione / Unione',
    bpmnEventStart: 'Evento di inizio',
    bpmnEventIntermediate: 'Evento intermedio',
    bpmnEventEnd: 'Evento di fine',
    bpmnGatewayExclusive: 'Gateway esclusivo',
    bpmnGatewayParallel: 'Gateway parallelo',
    bpmnGatewayInclusive: 'Gateway inclusivo',
    bpmnTask: 'Attività',
    bpmnSubProcess: 'Sottoprocesso',
    bpmnCallActivity: 'Attività di chiamata',
    bpmnDataObject: 'Oggetto dati',
    bpmnDataStore: 'Archivio dati',
    bpmnTextAnnotation: 'Annotazione di testo',
    netServer: 'Server',
    netClient: 'Client',
    netRouter: 'Router',
    netSwitch: 'Switch',
    netFirewall: 'Firewall',
    netLoadBalancer: 'Bilanciatore di carico',
    netCloud: 'Cloud',
    netCdn: 'CDN',
    netDatabase: 'Database',
    netStorage: 'Archiviazione',
    orgUnit: 'Unità',
    orgAssistant: 'Assistente',
    orgTeam: 'Team',
    mindCenter: 'Argomento centrale',
    mindTopic: 'Argomento',
    mindSub: 'Sotto-argomento',
    erEntity: 'Entità',
    erAttribute: 'Attributo',
    erRelationship: 'Relazione',
    erWeakEntity: 'Entità debole',
    swimlane: 'Corsia orizzontale',
    swimlaneV: 'Corsia verticale',
    group: 'Gruppo',
    triangle: 'Triangolo',
    star: 'Stella',
    pentagon: 'Pentagono',
    octagon: 'Ottagono',
    chevron: 'Chevron',
    card: 'Scheda',
    callout: 'Fumetto',
    cloud: 'Nuvola',
    cross: 'Croce',
    plus: 'Più',
    flag: 'Bandiera',
    lightning: 'Fulmine',
    arrow: 'Freccia',
    bracket: 'Parentesi',
  },

  es: {
    rect: 'Proceso',
    roundRect: 'Rectángulo redondeado',
    ellipse: 'Elipse',
    diamond: 'Rombo',
    parallelogram: 'Paralelogramo',
    trapezoid: 'Trapecio',
    hexagon: 'Hexágono',
    cylinder: 'Cilindro',
    note: 'Nota',
    startEnd: 'Inicio / Fin',
    decision: 'Decisión',
    data: 'Datos',
    document: 'Documento',
    predefined: 'Proceso predefinido',
    manualInput: 'Entrada manual',
    manualOperation: 'Operación manual',
    preparation: 'Preparación',
    database: 'Base de datos',
    display: 'Visualización',
    onPageConnector: 'Conector misma página',
    offPageConnector: 'Conector otra página',
    terminator: 'Terminador',
    parallelMode: 'Modo paralelo',
    loopLimit: 'Límite de bucle',
    umlActor: 'Actor',
    umlUseCase: 'Caso de uso',
    umlClass: 'Clase',
    umlInterface: 'Interfaz',
    umlPackage: 'Paquete',
    umlNote: 'Nota',
    umlLifeline: 'Línea de vida',
    umlState: 'Estado',
    umlStateInitial: 'Estado inicial',
    umlStateFinal: 'Estado final',
    umlForkJoin: 'Bifurcación / Unión',
    bpmnEventStart: 'Evento de inicio',
    bpmnEventIntermediate: 'Evento intermedio',
    bpmnEventEnd: 'Evento final',
    bpmnGatewayExclusive: 'Compuerta exclusiva',
    bpmnGatewayParallel: 'Compuerta paralela',
    bpmnGatewayInclusive: 'Compuerta inclusiva',
    bpmnTask: 'Tarea',
    bpmnSubProcess: 'Subproceso',
    bpmnCallActivity: 'Actividad de llamada',
    bpmnDataObject: 'Objeto de datos',
    bpmnDataStore: 'Almacén de datos',
    bpmnTextAnnotation: 'Anotación de texto',
    netServer: 'Servidor',
    netClient: 'Cliente',
    netRouter: 'Enrutador',
    netSwitch: 'Conmutador',
    netFirewall: 'Cortafuegos',
    netLoadBalancer: 'Balanceador de carga',
    netCloud: 'Nube',
    netCdn: 'CDN',
    netDatabase: 'Base de datos',
    netStorage: 'Almacenamiento',
    orgUnit: 'Unidad',
    orgAssistant: 'Asistente',
    orgTeam: 'Equipo',
    mindCenter: 'Tema central',
    mindTopic: 'Tema',
    mindSub: 'Subtema',
    erEntity: 'Entidad',
    erAttribute: 'Atributo',
    erRelationship: 'Relación',
    erWeakEntity: 'Entidad débil',
    swimlane: 'Carril horizontal',
    swimlaneV: 'Carril vertical',
    group: 'Grupo',
    triangle: 'Triángulo',
    star: 'Estrella',
    pentagon: 'Pentágono',
    octagon: 'Octágono',
    chevron: 'Cheurón',
    card: 'Tarjeta',
    callout: 'Globo',
    cloud: 'Nube',
    cross: 'Cruz',
    plus: 'Más',
    flag: 'Bandera',
    lightning: 'Rayo',
    arrow: 'Flecha',
    bracket: 'Corchete',
  },

  pt: {
    rect: 'Processo',
    roundRect: 'Retângulo arredondado',
    ellipse: 'Elipse',
    diamond: 'Losango',
    parallelogram: 'Paralelograma',
    trapezoid: 'Trapézio',
    hexagon: 'Hexágono',
    cylinder: 'Cilindro',
    note: 'Nota',
    startEnd: 'Início / Fim',
    decision: 'Decisão',
    data: 'Dados',
    document: 'Documento',
    predefined: 'Processo predefinido',
    manualInput: 'Entrada manual',
    manualOperation: 'Operação manual',
    preparation: 'Preparação',
    database: 'Base de dados',
    display: 'Exibição',
    onPageConnector: 'Conector mesma página',
    offPageConnector: 'Conector outra página',
    terminator: 'Terminador',
    parallelMode: 'Modo paralelo',
    loopLimit: 'Limite de loop',
    umlActor: 'Ator',
    umlUseCase: 'Caso de uso',
    umlClass: 'Classe',
    umlInterface: 'Interface',
    umlPackage: 'Pacote',
    umlNote: 'Nota',
    umlLifeline: 'Linha de vida',
    umlState: 'Estado',
    umlStateInitial: 'Estado inicial',
    umlStateFinal: 'Estado final',
    umlForkJoin: 'Bifurcação / União',
    bpmnEventStart: 'Evento de início',
    bpmnEventIntermediate: 'Evento intermediário',
    bpmnEventEnd: 'Evento final',
    bpmnGatewayExclusive: 'Gateway exclusivo',
    bpmnGatewayParallel: 'Gateway paralelo',
    bpmnGatewayInclusive: 'Gateway inclusivo',
    bpmnTask: 'Tarefa',
    bpmnSubProcess: 'Subprocesso',
    bpmnCallActivity: 'Atividade de chamada',
    bpmnDataObject: 'Objeto de dados',
    bpmnDataStore: 'Armazém de dados',
    bpmnTextAnnotation: 'Anotação de texto',
    netServer: 'Servidor',
    netClient: 'Cliente',
    netRouter: 'Roteador',
    netSwitch: 'Switch',
    netFirewall: 'Firewall',
    netLoadBalancer: 'Balanceador de carga',
    netCloud: 'Nuvem',
    netCdn: 'CDN',
    netDatabase: 'Base de dados',
    netStorage: 'Armazenamento',
    orgUnit: 'Unidade',
    orgAssistant: 'Assistente',
    orgTeam: 'Equipe',
    mindCenter: 'Tópico central',
    mindTopic: 'Tópico',
    mindSub: 'Subtópico',
    erEntity: 'Entidade',
    erAttribute: 'Atributo',
    erRelationship: 'Relacionamento',
    erWeakEntity: 'Entidade fraca',
    swimlane: 'Raia horizontal',
    swimlaneV: 'Raia vertical',
    group: 'Grupo',
    triangle: 'Triângulo',
    star: 'Estrela',
    pentagon: 'Pentágono',
    octagon: 'Octágono',
    chevron: 'Chevron',
    card: 'Cartão',
    callout: 'Balão',
    cloud: 'Nuvem',
    cross: 'Cruz',
    plus: 'Mais',
    flag: 'Bandeira',
    lightning: 'Raio',
    arrow: 'Seta',
    bracket: 'Colchete',
  },
};
