/**
 * 模板内节点/连线文案（占位内容，用户可自由改写）。
 *
 * 模板内容是「起始素材」而非 UI 文案，因此不放进 strings.ts 的 9 语种大表：
 * - zh / en / zh-TW 在此完整维护（键集合必须与 en 保持一致，见 templates.test.ts）；
 * - 其余语种缺键时回退英文（`bundleToResource` 按 `TEMPLATE_LABELS_I18N[lng] ?? en` 注册），
 *   后续补齐只需在此追加同名 token 的整表（键名前缀统一为 `tpl_`）。
 */

/** 模板文案 token → 文案；键与模板中的占位内容一一对应 */
export const TEMPLATE_LABELS_I18N: Record<string, Record<string, string>> = {
  zh: {
    start: '开始',
    end: '结束',
    step: '处理步骤',
    step1: '步骤 1',
    step2: '步骤 2',
    condition: '条件成立？',
    branchA: '分支 A',
    branchB: '分支 B',
    yes: '是',
    no: '否',
    pass: '通过',
    laneH: '横向泳道',
    laneV: '纵向泳道',
    user: '用户',
    service: '服务',
    login: '登录系统',
    report: '查看报表',
    order: '订单',
    orderItem: '订单明细',
    request: '请求',
    query: '查询',
    result: '结果',
    submit: '提交申请',
    approved: '审核通过？',
    archive: '归档',
    pendingPay: '待支付',
    paid: '已支付',
    paySuccess: '支付成功',
    startEvent: '开始事件',
    endEvent: '结束事件',
    userTask: '用户任务',
    serviceTask: '服务任务',
    autoPass: '自动通过',
    manualReview: '人工审核',
    amountSmall: '金额 < 1k',
    amountLarge: '金额 ≥ 1k',
    publicNet: '公网',
    edgeRouter: '边界路由',
    firewall: '防火墙',
    coreSwitch: '核心交换',
    appServer: '应用服务器',
    database: '数据库',
    gm: '总经理',
    techDept: '技术部',
    marketDept: '市场部',
    devTeam: '开发组',
    salesTeam: '销售组',
    topic: '主题',
    topic1: '分支一',
    topic2: '分支二',
    topic3: '分支三',
    point: '要点',
    placeOrder: '下单',
    userId: '用户ID',
    orderTime: '下单时间',
    draft: '拟稿',
    review: '审批',
    reject: '驳回',
    onboard: '入职报到',
    training: '培训',
    probation: '试用期',
    confirm: '转正',
    laneSales: '销售部',
    laneFinance: '财务部',
    component: '组件',
    pool: '协作池',
    message: '消息',
    subnet: '子网',
    gateway: '网关',
  },

  en: {
    start: 'Start',
    end: 'End',
    step: 'Process step',
    step1: 'Step 1',
    step2: 'Step 2',
    condition: 'Condition met?',
    branchA: 'Branch A',
    branchB: 'Branch B',
    yes: 'Yes',
    no: 'No',
    pass: 'Pass',
    laneH: 'Horizontal lane',
    laneV: 'Vertical lane',
    user: 'User',
    service: 'Service',
    login: 'Sign in',
    report: 'View reports',
    order: 'Order',
    orderItem: 'Order item',
    request: 'Request',
    query: 'Query',
    result: 'Result',
    submit: 'Submit request',
    approved: 'Approved?',
    archive: 'Archive',
    pendingPay: 'Pending payment',
    paid: 'Paid',
    paySuccess: 'Payment succeeded',
    startEvent: 'Start event',
    endEvent: 'End event',
    userTask: 'User task',
    serviceTask: 'Service task',
    autoPass: 'Auto approve',
    manualReview: 'Manual review',
    amountSmall: 'Amount < 1k',
    amountLarge: 'Amount ≥ 1k',
    publicNet: 'Internet',
    edgeRouter: 'Edge router',
    firewall: 'Firewall',
    coreSwitch: 'Core switch',
    appServer: 'App server',
    database: 'Database',
    gm: 'General manager',
    techDept: 'Engineering',
    marketDept: 'Marketing',
    devTeam: 'Dev team',
    salesTeam: 'Sales team',
    topic: 'Topic',
    topic1: 'Branch 1',
    topic2: 'Branch 2',
    topic3: 'Branch 3',
    point: 'Key point',
    placeOrder: 'Place order',
    userId: 'User ID',
    orderTime: 'Ordered at',
    draft: 'Draft',
    review: 'Review',
    reject: 'Reject',
    onboard: 'Onboarding',
    training: 'Training',
    probation: 'Probation',
    confirm: 'Confirmation',
    laneSales: 'Sales',
    laneFinance: 'Finance',
    component: 'Component',
    pool: 'Collaboration pool',
    message: 'Message',
    subnet: 'Subnet',
    gateway: 'Gateway',
  },

  'zh-TW': {
    start: '開始',
    end: '結束',
    step: '處理步驟',
    step1: '步驟 1',
    step2: '步驟 2',
    condition: '條件成立？',
    branchA: '分支 A',
    branchB: '分支 B',
    yes: '是',
    no: '否',
    pass: '通過',
    laneH: '橫向泳道',
    laneV: '縱向泳道',
    user: '使用者',
    service: '服務',
    login: '登入系統',
    report: '檢視報表',
    order: '訂單',
    orderItem: '訂單明細',
    request: '請求',
    query: '查詢',
    result: '結果',
    submit: '提交申請',
    approved: '審核通過？',
    archive: '歸檔',
    pendingPay: '待支付',
    paid: '已支付',
    paySuccess: '支付成功',
    startEvent: '開始事件',
    endEvent: '結束事件',
    userTask: '使用者任務',
    serviceTask: '服務任務',
    autoPass: '自動通過',
    manualReview: '人工審核',
    amountSmall: '金額 < 1k',
    amountLarge: '金額 ≥ 1k',
    publicNet: '公網',
    edgeRouter: '邊界路由',
    firewall: '防火牆',
    coreSwitch: '核心交換',
    appServer: '應用伺服器',
    database: '資料庫',
    gm: '總經理',
    techDept: '技術部',
    marketDept: '市場部',
    devTeam: '開發組',
    salesTeam: '銷售組',
    topic: '主題',
    topic1: '分支一',
    topic2: '分支二',
    topic3: '分支三',
    point: '要點',
    placeOrder: '下單',
    userId: '使用者ID',
    orderTime: '下單時間',
    draft: '擬稿',
    review: '審批',
    reject: '駁回',
    onboard: '入職報到',
    training: '培訓',
    probation: '試用期',
    confirm: '轉正',
    laneSales: '銷售部',
    laneFinance: '財務部',
    component: '組件',
    pool: '協作池',
    message: '訊息',
    subnet: '子網',
    gateway: '閘道',
  },
};

/** 模板文案 token（以 en 表为基准，保证 zh/en 键集合一致） */
export type TemplateLabelKey = keyof (typeof TEMPLATE_LABELS_I18N)['en'];

/** 与 i18next 注册时的键前缀保持一致 */
export const TEMPLATE_LABEL_PREFIX = 'tpl_';
