/**
 * 脑图编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 * 与 flowchart-editor 保持同一套约定：UI 文案不进首屏语言包，工具被懒加载时由
 * `registerMindmapStrings` 合并进 i18next，键路径 `tools.mindmap.*`。
 * 工具元数据（名称/描述）仍写在 `core/i18n/locales/*` 的 `toolsMeta` 中。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { mindmap: StringTree } };

const zh: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: '新建脑图',
      addSheet: '新建画布',
      prevPage: '上一张',
      nextPage: '下一张',
      pageOverview: '画布总览',
      openPageOverview: '打开画布总览',
      closeOverview: '关闭总览',
      removePage: '删除画布',
      emptyPage: '空白画布',
      movePageLeft: '左移',
      movePageRight: '右移',
      pageCounter: '第 {{current}} / {{total}} 张',
      renameHint: '双击可重命名',
      docTitle: '脑图标题',
      present: '放映',
      exitPresent: '退出放映（Esc）',
      presentLoading: '正在生成放映画面…',
      presentFailed: '放映画面生成失败',
      titlePlaceholder: '未命名脑图',
      templates: '模板',
      undo: '撤销',
      redo: '重做',
      duplicate: '复制分支',
      delete: '删除',
      addChild: '子主题',
      addSibling: '同级主题',
      indent: '降级',
      outdent: '升级',
      moveUp: '上移',
      moveDown: '下移',
      collapseAll: '全部折叠',
      expandAll: '全部展开',
      fitView: '适应画布',
      dir_right: '向右',
      dir_both: '左右分布',
      dir_down: '向下',
      theme: '配色主题',
      theme_classic: '经典蓝',
      theme_forest: '森林绿',
      theme_sunset: '暖阳橙',
      theme_grape: '葡萄紫',
      theme_slate: '石墨灰',
      theme_candy: '糖果粉',
      theme_mono: '极简黑白',
      theme_neon: '霓虹夜',
      themes: '配色',
      themeHint: '点击主题即可一键切换整张脑图配色',
      outlineTitle: '结构大纲',
      outlineHint: '点击节点定位到画布，双击可重命名',
      panelTitle: '属性',
      noSelection: '未选中节点',
      untitled: '未命名',
      text: '文本',
      note: '备注',
      shape: '形状',
      shape_rounded: '圆角矩形',
      shape_pill: '胶囊',
      shape_underline: '下划线',
      shape_rect: '矩形',
      shape_ellipse: '椭圆',
      branchColor: '分支颜色',
      fill: '填充色',
      fontSize: '字号',
      textColor: '文字颜色',
      align: '对齐',
      alignLeft: '左对齐',
      alignCenter: '居中',
      alignRight: '右对齐',
      bold: '加粗',
      italic: '斜体',
      side: '分支所在侧',
      sideLeft: '左侧',
      sideRight: '右侧',
      collapse: '折叠',
      expand: '展开',
      exportPanel: '导出',
      importFile: '导入',
      scale: '分辨率',
      transparentBg: '透明背景',
      nodesLabel: '节点',
      branchesLabel: '分支',
      selectedOne: '已选中 1 个节点',
      saved: '已保存到本地草稿',
      saving: '停止编辑后自动保存',
      emptyHint: '按 Tab 添加子主题，按 Enter 添加同级主题',
      templateTitle: '选择模板',
      templateHint: '载入模板将替换当前脑图内容',
      templateProject: '项目规划',
      templateMeeting: '会议纪要',
      templateReading: '读书笔记',
      templateProduct: '产品结构',
      templateWeekly: '本周计划',
      err: {
        EMPTY: '脑图为空，无法导出',
        EXPORT_FAILED: '导出失败',
        IMPORT_FAILED: '导入失败：无法识别该文件格式',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: 'New map',
      addSheet: 'New canvas',
      prevPage: 'Previous canvas',
      nextPage: 'Next canvas',
      pageOverview: 'Canvas overview',
      openPageOverview: 'Open canvas overview',
      closeOverview: 'Close overview',
      removePage: 'Delete canvas',
      emptyPage: 'Blank canvas',
      movePageLeft: 'Move left',
      movePageRight: 'Move right',
      pageCounter: 'Canvas {{current}} of {{total}}',
      renameHint: 'Double-click to rename',
      docTitle: 'Mind map title',
      present: 'Present',
      exitPresent: 'Exit (Esc)',
      presentLoading: 'Preparing the slideshow…',
      presentFailed: 'Failed to build the slideshow',
      titlePlaceholder: 'Untitled mind map',
      templates: 'Templates',
      undo: 'Undo',
      redo: 'Redo',
      duplicate: 'Duplicate branch',
      delete: 'Delete',
      addChild: 'Subtopic',
      addSibling: 'Sibling',
      indent: 'Indent',
      outdent: 'Outdent',
      moveUp: 'Move up',
      moveDown: 'Move down',
      collapseAll: 'Collapse all',
      expandAll: 'Expand all',
      fitView: 'Fit view',
      dir_right: 'Right',
      dir_both: 'Both sides',
      dir_down: 'Down',
      theme: 'Color theme',
      theme_classic: 'Classic blue',
      theme_forest: 'Forest green',
      theme_sunset: 'Sunset orange',
      theme_grape: 'Grape purple',
      theme_slate: 'Slate gray',
      theme_candy: 'Candy pink',
      theme_mono: 'Minimal mono',
      theme_neon: 'Neon night',
      themes: 'Themes',
      themeHint: 'Click a theme to recolor the whole map',
      outlineTitle: 'Outline',
      outlineHint: 'Click a node to focus it; double-click to rename',
      panelTitle: 'Properties',
      noSelection: 'No node selected',
      untitled: 'Untitled',
      text: 'Text',
      note: 'Note',
      shape: 'Shape',
      shape_rounded: 'Rounded',
      shape_pill: 'Pill',
      shape_underline: 'Underline',
      shape_rect: 'Rectangle',
      shape_ellipse: 'Ellipse',
      branchColor: 'Branch color',
      fill: 'Fill',
      fontSize: 'Font size',
      textColor: 'Text color',
      align: 'Align',
      alignLeft: 'Left',
      alignCenter: 'Center',
      alignRight: 'Right',
      bold: 'Bold',
      italic: 'Italic',
      side: 'Branch side',
      sideLeft: 'Left',
      sideRight: 'Right',
      collapse: 'Collapse',
      expand: 'Expand',
      exportPanel: 'Export',
      importFile: 'Import',
      scale: 'Scale',
      transparentBg: 'Transparent',
      nodesLabel: 'Nodes',
      branchesLabel: 'Branches',
      selectedOne: '1 node selected',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop editing',
      emptyHint: 'Press Tab for a subtopic, Enter for a sibling',
      templateTitle: 'Choose a template',
      templateHint: 'Loading a template replaces the current map',
      templateProject: 'Project plan',
      templateMeeting: 'Meeting notes',
      templateReading: 'Reading notes',
      templateProduct: 'Product structure',
      templateWeekly: 'Weekly plan',
      err: {
        EMPTY: 'The map is empty, nothing to export',
        EXPORT_FAILED: 'Export failed',
        IMPORT_FAILED: 'Import failed: unsupported file format',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: '新增心智圖',
      addSheet: '新增畫布',
      prevPage: '上一張',
      nextPage: '下一張',
      pageOverview: '畫布總覽',
      openPageOverview: '開啟畫布總覽',
      closeOverview: '關閉總覽',
      removePage: '刪除畫布',
      emptyPage: '空白畫布',
      movePageLeft: '左移',
      movePageRight: '右移',
      pageCounter: '第 {{current}} / {{total}} 張',
      renameHint: '雙擊可重新命名',
      docTitle: '心智圖標題',
      present: '放映',
      exitPresent: '結束放映（Esc）',
      presentLoading: '正在產生放映畫面…',
      presentFailed: '放映畫面產生失敗',
      titlePlaceholder: '未命名心智圖',
      templates: '模板',
      undo: '復原',
      redo: '重做',
      duplicate: '複製分支',
      delete: '刪除',
      addChild: '子主題',
      addSibling: '同級主題',
      indent: '降級',
      outdent: '升級',
      moveUp: '上移',
      moveDown: '下移',
      collapseAll: '全部摺疊',
      expandAll: '全部展開',
      fitView: '符合畫布',
      dir_right: '向右',
      dir_both: '左右分布',
      dir_down: '向下',
      theme: '配色主題',
      theme_classic: '經典藍',
      theme_forest: '森林綠',
      theme_sunset: '暖陽橘',
      theme_grape: '葡萄紫',
      theme_slate: '石墨灰',
      theme_candy: '糖果粉',
      theme_mono: '極簡黑白',
      theme_neon: '霓虹夜',
      themes: '配色',
      themeHint: '點擊主題即可一鍵切換整張心智圖配色',
      outlineTitle: '結構大綱',
      outlineHint: '點擊節點定位到畫布，雙擊可重新命名',
      panelTitle: '屬性',
      noSelection: '未選取節點',
      untitled: '未命名',
      text: '文字',
      note: '備註',
      shape: '形狀',
      shape_rounded: '圓角矩形',
      shape_pill: '膠囊',
      shape_underline: '底線',
      shape_rect: '矩形',
      shape_ellipse: '橢圓',
      branchColor: '分支色彩',
      fill: '填滿色彩',
      fontSize: '字級',
      textColor: '文字色彩',
      align: '對齊',
      alignLeft: '靠左',
      alignCenter: '置中',
      alignRight: '靠右',
      bold: '粗體',
      italic: '斜體',
      side: '分支所在側',
      sideLeft: '左側',
      sideRight: '右側',
      collapse: '摺疊',
      expand: '展開',
      exportPanel: '匯出',
      importFile: '匯入',
      scale: '解析度',
      transparentBg: '透明背景',
      nodesLabel: '節點',
      branchesLabel: '分支',
      selectedOne: '已選取 1 個節點',
      saved: '已儲存至本機草稿',
      saving: '停止編輯後自動儲存',
      emptyHint: '按 Tab 新增子主題，按 Enter 新增同級主題',
      templateTitle: '選擇模板',
      templateHint: '載入模板將取代目前心智圖內容',
      templateProject: '專案規劃',
      templateMeeting: '會議記錄',
      templateReading: '讀書筆記',
      templateProduct: '產品結構',
      templateWeekly: '本週計畫',
      err: {
        EMPTY: '心智圖為空，無法匯出',
        EXPORT_FAILED: '匯出失敗',
        IMPORT_FAILED: '匯入失敗：無法識別該檔案格式',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: '新規マインドマップ',
      addSheet: '新規キャンバス',
      prevPage: '前のキャンバス',
      nextPage: '次のキャンバス',
      pageOverview: 'キャンバス一覧',
      openPageOverview: 'キャンバス一覧を開く',
      closeOverview: '一覧を閉じる',
      removePage: 'キャンバスを削除',
      emptyPage: '空白のキャンバス',
      movePageLeft: '左へ移動',
      movePageRight: '右へ移動',
      pageCounter: '{{current}} / {{total}} キャンバス',
      renameHint: 'ダブルクリックで名前変更',
      docTitle: 'マインドマップのタイトル',
      present: 'スライドショー',
      exitPresent: '終了（Esc）',
      presentLoading: '表示用の画像を生成中…',
      presentFailed: '表示用の画像の生成に失敗しました',
      titlePlaceholder: '無題のマインドマップ',
      templates: 'テンプレート',
      undo: '元に戻す',
      redo: 'やり直し',
      duplicate: 'ブランチを複製',
      delete: '削除',
      addChild: 'サブトピック',
      addSibling: '同階層',
      indent: '下げる',
      outdent: '上げる',
      moveUp: '上へ',
      moveDown: '下へ',
      collapseAll: 'すべて折りたたむ',
      expandAll: 'すべて展開',
      fitView: '画面に合わせる',
      dir_right: '右方向',
      dir_both: '左右配置',
      dir_down: '下方向',
      theme: 'カラーテーマ',
      theme_classic: 'クラシックブルー',
      theme_forest: 'フォレストグリーン',
      theme_sunset: 'サンセットオレンジ',
      theme_grape: 'グレープパープル',
      theme_slate: 'スレートグレー',
      theme_candy: 'キャンディピンク',
      theme_mono: 'モノクロ',
      theme_neon: 'ネオン',
      themes: 'テーマ',
      themeHint: 'テーマをクリックするとマップ全体の配色が切り替わります',
      outlineTitle: 'アウトライン',
      outlineHint: 'ノードをクリックで選択、ダブルクリックで名前変更',
      panelTitle: 'プロパティ',
      noSelection: 'ノードが未選択です',
      untitled: '無題',
      text: 'テキスト',
      note: 'メモ',
      shape: '形',
      shape_rounded: '角丸',
      shape_pill: 'カプセル',
      shape_underline: '下線',
      shape_rect: '長方形',
      shape_ellipse: '楕円',
      branchColor: 'ブランチの色',
      fill: '塗りつぶし',
      fontSize: '文字サイズ',
      textColor: '文字色',
      align: '配置',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      bold: '太字',
      italic: '斜体',
      side: 'ブランチの位置',
      sideLeft: '左',
      sideRight: '右',
      collapse: '折りたたむ',
      expand: '展開',
      exportPanel: '書き出し',
      importFile: '読み込み',
      scale: '倍率',
      transparentBg: '透明背景',
      nodesLabel: 'ノード',
      branchesLabel: 'ブランチ',
      selectedOne: '1 個のノードを選択中',
      saved: 'ローカル下書きに保存しました',
      saving: '編集を止めると自動保存します',
      emptyHint: 'Tab でサブトピック、Enter で同階層を追加',
      templateTitle: 'テンプレートを選択',
      templateHint: 'テンプレートを読み込むと現在のマップを置き換えます',
      templateProject: 'プロジェクト計画',
      templateMeeting: '議事録',
      templateReading: '読書メモ',
      templateProduct: 'プロダクト構成',
      templateWeekly: '今週の計画',
      err: {
        EMPTY: 'マップが空です',
        EXPORT_FAILED: '書き出しに失敗しました',
        IMPORT_FAILED: '読み込みに失敗しました：ファイル形式を認識できません',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: 'Nouvelle carte',
      addSheet: 'Nouveau canevas',
      prevPage: 'Canevas précédent',
      nextPage: 'Canevas suivant',
      pageOverview: 'Aperçu des canevas',
      openPageOverview: 'Ouvrir l’aperçu des canevas',
      closeOverview: 'Fermer l’aperçu',
      removePage: 'Supprimer le canevas',
      emptyPage: 'Canevas vide',
      movePageLeft: 'Déplacer à gauche',
      movePageRight: 'Déplacer à droite',
      pageCounter: 'Canevas {{current}} sur {{total}}',
      renameHint: 'Double-cliquez pour renommer',
      docTitle: 'Titre de la carte',
      present: 'Présenter',
      exitPresent: 'Quitter (Échap)',
      presentLoading: 'Préparation du diaporama…',
      presentFailed: 'Échec de la préparation du diaporama',
      titlePlaceholder: 'Carte sans titre',
      templates: 'Modèles',
      undo: 'Annuler',
      redo: 'Rétablir',
      duplicate: 'Dupliquer la branche',
      delete: 'Supprimer',
      addChild: 'Sous-thème',
      addSibling: 'Thème frère',
      indent: 'Indenter',
      outdent: 'Désindenter',
      moveUp: 'Monter',
      moveDown: 'Descendre',
      collapseAll: 'Tout replier',
      expandAll: 'Tout déplier',
      fitView: 'Ajuster',
      dir_right: 'Vers la droite',
      dir_both: 'Des deux côtés',
      dir_down: 'Vers le bas',
      theme: 'Palette',
      theme_classic: 'Bleu classique',
      theme_forest: 'Vert forêt',
      theme_sunset: 'Orange couchant',
      theme_grape: 'Violet raisin',
      theme_slate: 'Gris ardoise',
      theme_candy: 'Rose bonbon',
      theme_mono: 'Mono minimal',
      theme_neon: 'Néon',
      themes: 'Thèmes',
      themeHint: 'Cliquez un thème pour recolorier toute la carte',
      outlineTitle: 'Plan',
      outlineHint: 'Cliquez un nœud pour le cibler, double-cliquez pour renommer',
      panelTitle: 'Propriétés',
      noSelection: 'Aucun nœud sélectionné',
      untitled: 'Sans titre',
      text: 'Texte',
      note: 'Note',
      shape: 'Forme',
      shape_rounded: 'Arrondi',
      shape_pill: 'Pastille',
      shape_underline: 'Souligné',
      shape_rect: 'Rectangle',
      shape_ellipse: 'Ellipse',
      branchColor: 'Couleur de branche',
      fill: 'Remplissage',
      fontSize: 'Taille',
      textColor: 'Couleur du texte',
      align: 'Alignement',
      alignLeft: 'Gauche',
      alignCenter: 'Centre',
      alignRight: 'Droite',
      bold: 'Gras',
      italic: 'Italique',
      side: 'Côté de la branche',
      sideLeft: 'Gauche',
      sideRight: 'Droite',
      collapse: 'Replier',
      expand: 'Déplier',
      exportPanel: 'Exporter',
      importFile: 'Importer',
      scale: 'Échelle',
      transparentBg: 'Transparent',
      nodesLabel: 'Nœuds',
      branchesLabel: 'Branches',
      selectedOne: '1 nœud sélectionné',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement auto après la saisie',
      emptyHint: 'Tab pour un sous-thème, Entrée pour un thème frère',
      templateTitle: 'Choisir un modèle',
      templateHint: 'Charger un modèle remplace la carte actuelle',
      templateProject: 'Plan de projet',
      templateMeeting: 'Compte rendu',
      templateReading: 'Notes de lecture',
      templateProduct: 'Structure produit',
      templateWeekly: 'Plan hebdo',
      err: {
        EMPTY: 'La carte est vide',
        EXPORT_FAILED: "Échec de l'export",
        IMPORT_FAILED: 'Échec de l’import : format de fichier non reconnu',
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: 'Neue Map',
      addSheet: 'Neue Fläche',
      prevPage: 'Vorherige Fläche',
      nextPage: 'Nächste Fläche',
      pageOverview: 'Flächenübersicht',
      openPageOverview: 'Flächenübersicht öffnen',
      closeOverview: 'Übersicht schließen',
      removePage: 'Fläche löschen',
      emptyPage: 'Leere Fläche',
      movePageLeft: 'Nach links',
      movePageRight: 'Nach rechts',
      pageCounter: 'Fläche {{current}} von {{total}}',
      renameHint: 'Doppelklick zum Umbenennen',
      docTitle: 'Map-Titel',
      present: 'Präsentieren',
      exitPresent: 'Beenden (Esc)',
      presentLoading: 'Präsentationsansicht wird erstellt…',
      presentFailed: 'Präsentationsansicht fehlgeschlagen',
      titlePlaceholder: 'Unbenannte Map',
      templates: 'Vorlagen',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      duplicate: 'Zweig duplizieren',
      delete: 'Löschen',
      addChild: 'Unterthema',
      addSibling: 'Gleichrangig',
      indent: 'Einrücken',
      outdent: 'Ausrücken',
      moveUp: 'Nach oben',
      moveDown: 'Nach unten',
      collapseAll: 'Alle einklappen',
      expandAll: 'Alle ausklappen',
      fitView: 'Einpassen',
      dir_right: 'Nach rechts',
      dir_both: 'Beidseitig',
      dir_down: 'Nach unten',
      theme: 'Farbthema',
      theme_classic: 'Klassisches Blau',
      theme_forest: 'Waldgrün',
      theme_sunset: 'Sonnenorange',
      theme_grape: 'Traubenlila',
      theme_slate: 'Schiefergrau',
      theme_candy: 'Bonbonrosa',
      theme_mono: 'Minimal Mono',
      theme_neon: 'Neon',
      themes: 'Themen',
      themeHint: 'Klicken Sie ein Thema an, um die ganze Map umzufärben',
      outlineTitle: 'Gliederung',
      outlineHint: 'Knoten anklicken zum Fokussieren, Doppelklick zum Umbenennen',
      panelTitle: 'Eigenschaften',
      noSelection: 'Kein Knoten ausgewählt',
      untitled: 'Unbenannt',
      text: 'Text',
      note: 'Notiz',
      shape: 'Form',
      shape_rounded: 'Abgerundet',
      shape_pill: 'Kapsel',
      shape_underline: 'Unterstrichen',
      shape_rect: 'Rechteck',
      shape_ellipse: 'Ellipse',
      branchColor: 'Zweigfarbe',
      fill: 'Füllung',
      fontSize: 'Schriftgröße',
      textColor: 'Textfarbe',
      align: 'Ausrichtung',
      alignLeft: 'Links',
      alignCenter: 'Mitte',
      alignRight: 'Rechts',
      bold: 'Fett',
      italic: 'Kursiv',
      side: 'Zweigseite',
      sideLeft: 'Links',
      sideRight: 'Rechts',
      collapse: 'Einklappen',
      expand: 'Ausklappen',
      exportPanel: 'Exportieren',
      importFile: 'Importieren',
      scale: 'Maßstab',
      transparentBg: 'Transparent',
      nodesLabel: 'Knoten',
      branchesLabel: 'Zweige',
      selectedOne: '1 Knoten ausgewählt',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Bearbeitung',
      emptyHint: 'Tab für Unterthema, Enter für gleichrangiges Thema',
      templateTitle: 'Vorlage wählen',
      templateHint: 'Laden einer Vorlage ersetzt die aktuelle Map',
      templateProject: 'Projektplan',
      templateMeeting: 'Besprechungsnotizen',
      templateReading: 'Lesenotizen',
      templateProduct: 'Produktstruktur',
      templateWeekly: 'Wochenplan',
      err: {
        EMPTY: 'Die Map ist leer',
        EXPORT_FAILED: 'Export fehlgeschlagen',
        IMPORT_FAILED: 'Import fehlgeschlagen: Dateiformat nicht erkannt',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: 'Nuova mappa',
      addSheet: 'Nuova tela',
      prevPage: 'Tela precedente',
      nextPage: 'Tela successiva',
      pageOverview: 'Panoramica tele',
      openPageOverview: 'Apri la panoramica',
      closeOverview: 'Chiudi la panoramica',
      removePage: 'Elimina tela',
      emptyPage: 'Tela vuota',
      movePageLeft: 'Sposta a sinistra',
      movePageRight: 'Sposta a destra',
      pageCounter: 'Tela {{current}} di {{total}}',
      renameHint: 'Doppio clic per rinominare',
      docTitle: 'Titolo della mappa',
      present: 'Presenta',
      exitPresent: 'Esci (Esc)',
      presentLoading: 'Preparazione della presentazione…',
      presentFailed: 'Impossibile preparare la presentazione',
      titlePlaceholder: 'Mappa senza titolo',
      templates: 'Modelli',
      undo: 'Annulla',
      redo: 'Ripeti',
      duplicate: 'Duplica ramo',
      delete: 'Elimina',
      addChild: 'Sottotema',
      addSibling: 'Tema gemello',
      indent: 'Aumenta livello',
      outdent: 'Riduci livello',
      moveUp: 'Sposta su',
      moveDown: 'Sposta giù',
      collapseAll: 'Comprimi tutto',
      expandAll: 'Espandi tutto',
      fitView: 'Adatta',
      dir_right: 'Verso destra',
      dir_both: 'Due lati',
      dir_down: 'Verso il basso',
      theme: 'Tema colore',
      theme_classic: 'Blu classico',
      theme_forest: 'Verde foresta',
      theme_sunset: 'Arancio tramonto',
      theme_grape: 'Viola uva',
      theme_slate: 'Grigio ardesia',
      theme_candy: 'Rosa caramella',
      theme_mono: 'Mono minimale',
      theme_neon: 'Neon',
      themes: 'Temi',
      themeHint: 'Clicca un tema per ricolorare l’intera mappa',
      outlineTitle: 'Struttura',
      outlineHint: 'Clicca un nodo per selezionarlo, doppio clic per rinominare',
      panelTitle: 'Proprietà',
      noSelection: 'Nessun nodo selezionato',
      untitled: 'Senza titolo',
      text: 'Testo',
      note: 'Nota',
      shape: 'Forma',
      shape_rounded: 'Arrotondato',
      shape_pill: 'Capsula',
      shape_underline: 'Sottolineato',
      shape_rect: 'Rettangolo',
      shape_ellipse: 'Ellisse',
      branchColor: 'Colore ramo',
      fill: 'Riempimento',
      fontSize: 'Dimensione',
      textColor: 'Colore testo',
      align: 'Allineamento',
      alignLeft: 'Sinistra',
      alignCenter: 'Centro',
      alignRight: 'Destra',
      bold: 'Grassetto',
      italic: 'Corsivo',
      side: 'Lato del ramo',
      sideLeft: 'Sinistra',
      sideRight: 'Destra',
      collapse: 'Comprimi',
      expand: 'Espandi',
      exportPanel: 'Esporta',
      importFile: 'Importa',
      scale: 'Scala',
      transparentBg: 'Trasparente',
      nodesLabel: 'Nodi',
      branchesLabel: 'Rami',
      selectedOne: '1 nodo selezionato',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la modifica',
      emptyHint: 'Tab per un sottotema, Invio per un tema gemello',
      templateTitle: 'Scegli un modello',
      templateHint: 'Caricare un modello sostituisce la mappa corrente',
      templateProject: 'Piano di progetto',
      templateMeeting: 'Verbale riunione',
      templateReading: 'Note di lettura',
      templateProduct: 'Struttura prodotto',
      templateWeekly: 'Piano settimanale',
      err: {
        EMPTY: 'La mappa è vuota',
        EXPORT_FAILED: 'Esportazione non riuscita',
        IMPORT_FAILED: 'Importazione non riuscita: formato file non riconosciuto',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: 'Nuevo mapa',
      addSheet: 'Nuevo lienzo',
      prevPage: 'Lienzo anterior',
      nextPage: 'Lienzo siguiente',
      pageOverview: 'Vista de lienzos',
      openPageOverview: 'Abrir la vista de lienzos',
      closeOverview: 'Cerrar la vista',
      removePage: 'Eliminar lienzo',
      emptyPage: 'Lienzo vacío',
      movePageLeft: 'Mover a la izquierda',
      movePageRight: 'Mover a la derecha',
      pageCounter: 'Lienzo {{current}} de {{total}}',
      renameHint: 'Doble clic para renombrar',
      docTitle: 'Título del mapa',
      present: 'Presentar',
      exitPresent: 'Salir (Esc)',
      presentLoading: 'Preparando la presentación…',
      presentFailed: 'No se pudo preparar la presentación',
      titlePlaceholder: 'Mapa sin título',
      templates: 'Plantillas',
      undo: 'Deshacer',
      redo: 'Rehacer',
      duplicate: 'Duplicar rama',
      delete: 'Eliminar',
      addChild: 'Subtema',
      addSibling: 'Tema hermano',
      indent: 'Aumentar nivel',
      outdent: 'Reducir nivel',
      moveUp: 'Subir',
      moveDown: 'Bajar',
      collapseAll: 'Plegar todo',
      expandAll: 'Desplegar todo',
      fitView: 'Ajustar',
      dir_right: 'Hacia la derecha',
      dir_both: 'Ambos lados',
      dir_down: 'Hacia abajo',
      theme: 'Tema de color',
      theme_classic: 'Azul clásico',
      theme_forest: 'Verde bosque',
      theme_sunset: 'Naranja atardecer',
      theme_grape: 'Morado uva',
      theme_slate: 'Gris pizarra',
      theme_candy: 'Rosa caramelo',
      theme_mono: 'Mono minimal',
      theme_neon: 'Neón',
      themes: 'Temas',
      themeHint: 'Haz clic en un tema para recolorear todo el mapa',
      outlineTitle: 'Esquema',
      outlineHint: 'Haz clic en un nodo para enfocarlo, doble clic para renombrar',
      panelTitle: 'Propiedades',
      noSelection: 'Ningún nodo seleccionado',
      untitled: 'Sin título',
      text: 'Texto',
      note: 'Nota',
      shape: 'Forma',
      shape_rounded: 'Redondeado',
      shape_pill: 'Cápsula',
      shape_underline: 'Subrayado',
      shape_rect: 'Rectángulo',
      shape_ellipse: 'Elipse',
      branchColor: 'Color de rama',
      fill: 'Relleno',
      fontSize: 'Tamaño',
      textColor: 'Color de texto',
      align: 'Alineación',
      alignLeft: 'Izquierda',
      alignCenter: 'Centro',
      alignRight: 'Derecha',
      bold: 'Negrita',
      italic: 'Cursiva',
      side: 'Lado de la rama',
      sideLeft: 'Izquierda',
      sideRight: 'Derecha',
      collapse: 'Plegar',
      expand: 'Desplegar',
      exportPanel: 'Exportar',
      importFile: 'Importar',
      scale: 'Escala',
      transparentBg: 'Transparente',
      nodesLabel: 'Nodos',
      branchesLabel: 'Ramas',
      selectedOne: '1 nodo seleccionado',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de editar',
      emptyHint: 'Tab para subtema, Enter para tema hermano',
      templateTitle: 'Elegir plantilla',
      templateHint: 'Cargar una plantilla reemplaza el mapa actual',
      templateProject: 'Plan de proyecto',
      templateMeeting: 'Acta de reunión',
      templateReading: 'Notas de lectura',
      templateProduct: 'Estructura de producto',
      templateWeekly: 'Plan semanal',
      err: {
        EMPTY: 'El mapa está vacío',
        EXPORT_FAILED: 'Error al exportar',
        IMPORT_FAILED: 'Error al importar: formato de archivo no reconocido',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    mindmap: {
      newDoc: 'Novo mapa',
      addSheet: 'Nova tela',
      prevPage: 'Tela anterior',
      nextPage: 'Tela seguinte',
      pageOverview: 'Visão geral das telas',
      openPageOverview: 'Abrir a visão geral',
      closeOverview: 'Fechar a visão geral',
      removePage: 'Excluir tela',
      emptyPage: 'Tela vazia',
      movePageLeft: 'Mover para a esquerda',
      movePageRight: 'Mover para a direita',
      pageCounter: 'Tela {{current}} de {{total}}',
      renameHint: 'Duplo clique para renomear',
      docTitle: 'Título do mapa',
      present: 'Apresentar',
      exitPresent: 'Sair (Esc)',
      presentLoading: 'A preparar a apresentação…',
      presentFailed: 'Falha ao preparar a apresentação',
      titlePlaceholder: 'Mapa sem título',
      templates: 'Modelos',
      undo: 'Desfazer',
      redo: 'Refazer',
      duplicate: 'Duplicar ramo',
      delete: 'Eliminar',
      addChild: 'Subtema',
      addSibling: 'Tema irmão',
      indent: 'Aumentar nível',
      outdent: 'Reduzir nível',
      moveUp: 'Mover para cima',
      moveDown: 'Mover para baixo',
      collapseAll: 'Recolher tudo',
      expandAll: 'Expandir tudo',
      fitView: 'Ajustar',
      dir_right: 'Para a direita',
      dir_both: 'Ambos os lados',
      dir_down: 'Para baixo',
      theme: 'Tema de cores',
      theme_classic: 'Azul clássico',
      theme_forest: 'Verde floresta',
      theme_sunset: 'Laranja pôr do sol',
      theme_grape: 'Roxo uva',
      theme_slate: 'Cinza ardósia',
      theme_candy: 'Rosa doce',
      theme_mono: 'Mono minimalista',
      theme_neon: 'Neon',
      themes: 'Temas',
      themeHint: 'Clique num tema para recolorir o mapa inteiro',
      outlineTitle: 'Estrutura',
      outlineHint: 'Clique num nó para focá-lo, duplo clique para renomear',
      panelTitle: 'Propriedades',
      noSelection: 'Nenhum nó selecionado',
      untitled: 'Sem título',
      text: 'Texto',
      note: 'Nota',
      shape: 'Forma',
      shape_rounded: 'Arredondado',
      shape_pill: 'Cápsula',
      shape_underline: 'Sublinhado',
      shape_rect: 'Retângulo',
      shape_ellipse: 'Elipse',
      branchColor: 'Cor do ramo',
      fill: 'Preenchimento',
      fontSize: 'Tamanho',
      textColor: 'Cor do texto',
      align: 'Alinhamento',
      alignLeft: 'Esquerda',
      alignCenter: 'Centro',
      alignRight: 'Direita',
      bold: 'Negrito',
      italic: 'Itálico',
      side: 'Lado do ramo',
      sideLeft: 'Esquerda',
      sideRight: 'Direita',
      collapse: 'Recolher',
      expand: 'Expandir',
      exportPanel: 'Exportar',
      importFile: 'Importar',
      scale: 'Escala',
      transparentBg: 'Transparente',
      nodesLabel: 'Nós',
      branchesLabel: 'Ramos',
      selectedOne: '1 nó selecionado',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de editar',
      emptyHint: 'Tab para subtema, Enter para tema irmão',
      templateTitle: 'Escolher modelo',
      templateHint: 'Carregar um modelo substitui o mapa atual',
      templateProject: 'Plano de projeto',
      templateMeeting: 'Ata de reunião',
      templateReading: 'Notas de leitura',
      templateProduct: 'Estrutura do produto',
      templateWeekly: 'Plano semanal',
      err: {
        EMPTY: 'O mapa está vazio',
        EXPORT_FAILED: 'Falha ao exportar',
        IMPORT_FAILED: 'Falha ao importar: formato de arquivo não reconhecido',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const mindmapStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具被懒加载时调用，键路径 tools.mindmap.*） */
export function registerMindmapStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(mindmapStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
