import type { ShapeDef } from './index';

/** 通用图形：各类型图表都会用到的基础外形，置于分类首位 */
export const GENERAL_SHAPES: ShapeDef[] = [
  { kind: 'rect', category: 'general', draw: 'rect', size: { width: 150, height: 64 } },
  { kind: 'roundRect', category: 'general', draw: 'roundRect', size: { width: 150, height: 64 } },
  { kind: 'ellipse', category: 'general', draw: 'ellipse', size: { width: 140, height: 90 } },
  { kind: 'diamond', category: 'general', draw: 'diamond', size: { width: 140, height: 90 } },
  {
    kind: 'parallelogram',
    category: 'general',
    draw: 'parallelogram',
    size: { width: 150, height: 64 },
  },
  { kind: 'trapezoid', category: 'general', draw: 'trapezoid', size: { width: 150, height: 64 } },
  { kind: 'hexagon', category: 'general', draw: 'hexagon', size: { width: 170, height: 64 } },
  { kind: 'cylinder', category: 'general', draw: 'cylinder', size: { width: 130, height: 80 } },
  { kind: 'note', category: 'general', draw: 'note', size: { width: 150, height: 90 } },
  { kind: 'triangle', category: 'general', draw: 'triangle', size: { width: 150, height: 120 } },
  {
    kind: 'star',
    category: 'general',
    draw: 'star',
    size: { width: 150, height: 140 },
    defaultStyle: { fill: '#FEF3C7', stroke: '#D97706' },
  },
  { kind: 'pentagon', category: 'general', draw: 'pentagon', size: { width: 150, height: 130 } },
  { kind: 'octagon', category: 'general', draw: 'octagon', size: { width: 150, height: 130 } },
  {
    kind: 'chevron',
    category: 'general',
    draw: 'chevron',
    size: { width: 150, height: 90 },
    defaultStyle: { fill: '#DBEAFE', stroke: '#2563EB' },
  },
  { kind: 'card', category: 'general', draw: 'card', size: { width: 160, height: 100 } },
  { kind: 'callout', category: 'general', draw: 'callout', size: { width: 170, height: 110 } },
  {
    kind: 'cloud',
    category: 'general',
    draw: 'cloud',
    size: { width: 170, height: 110 },
    defaultStyle: { fill: '#E0F2FE', stroke: '#0284C7' },
  },
  {
    kind: 'cross',
    category: 'general',
    draw: 'cross',
    size: { width: 120, height: 120 },
    defaultStyle: { fill: '#FEE2E2', stroke: '#DC2626' },
  },
  {
    kind: 'plus',
    category: 'general',
    draw: 'plus',
    size: { width: 120, height: 120 },
    defaultStyle: { fill: '#DCFCE7', stroke: '#16A34A' },
  },
  {
    kind: 'flag',
    category: 'general',
    draw: 'flag',
    size: { width: 120, height: 150 },
    defaultStyle: { fill: '#FEE2E2', stroke: '#DC2626' },
  },
  {
    kind: 'lightning',
    category: 'general',
    draw: 'lightning',
    size: { width: 110, height: 140 },
    defaultStyle: { fill: '#FEF9C3', stroke: '#CA8A04' },
  },
  {
    kind: 'arrow',
    category: 'general',
    draw: 'arrow',
    size: { width: 170, height: 80 },
    defaultStyle: { fill: '#E2E8F0', stroke: '#475569' },
  },
  { kind: 'bracket', category: 'general', draw: 'bracket', size: { width: 90, height: 140 } },
];
