/**
 * de 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Neue Fläche',
      docTitle: 'Diagrammtitel',
      present: 'Präsentieren',
      exitPresent: 'Beenden (Esc)',
      presentLoading: 'Präsentationsansicht wird erstellt…',
      presentFailed: 'Präsentationsansicht fehlgeschlagen',
      titlePlaceholder: 'Unbenanntes Diagramm',
      clear: 'Leeren',
      exportPng: 'PNG exportieren',
      exportSvg: 'SVG exportieren',
      templates: 'Vorlagen',
      autoLayout: 'Auto-Layout',
      fitView: 'An Bildschirm anpassen',
      zoomActual: 'Tatsächliche Größe',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      duplicate: 'Duplizieren',
      delete: 'Löschen',
      panelTitle: 'Eigenschaften',
      paletteTitle: 'Formen',
      searchShape: 'Form suchen',
      noShape: 'Keine passende Form',
      resizeSidebar: 'Ziehen zum Ändern der Breite',
      cat_general: 'Allgemein',
      cat_flow: 'Flussdiagramm',
      cat_uml: 'UML',
      cat_umlCommon: 'UML Allgemein',
      cat_umlUseCase: 'UML Anwendungsfalldiagramm',
      cat_umlClass: 'UML Klassendiagramm',
      cat_umlObject: 'UML Objekt-/Paketdiagramm',
      cat_umlSequence: 'UML Sequenzdiagramm',
      cat_umlActivity: 'UML Aktivitätsdiagramm',
      cat_umlState: 'UML Zustandsdiagramm',
      cat_umlComponent: 'UML Komponentendiagramm',
      cat_umlDeployment: 'UML Bereitstellungsdiagramm',
      cat_bpmn: 'BPMN',
      cat_network: 'Netzwerk & Cloud',
      cat_org: 'Organisation',
      cat_mind: 'Mindmap',
      cat_er: 'ER-Diagramm',
      groupBasic: 'Basisformen',
      groupFlow: 'Flusssymbole',
      groupBpmn: 'Swimlanes & BPMN',
      shape_rect: 'Prozess',
      shape_startEnd: 'Start / Ende',
      shape_decision: 'Entscheidung',
      shape_data: 'Daten',
      shape_swimlane: 'Horizontale Swimlane',
      shape_swimlaneV: 'Vertikale Swimlane',
      shape_bpmnTask: 'BPMN-Aufgabe',
      canvasAria: 'Flussdiagramm-Fläche',
      emptyHint: 'Form von links ziehen oder Vorlage wählen',
      nodesLabel: 'Knoten',
      edgesLabel: 'Kanten',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Bearbeitung',
      noSelection: 'Kein Element ausgewählt',
      selected: '{{count}} Elemente ausgewählt',
      fill: 'Füllung',
      stroke: 'Rahmen',
      strokeWidth: 'Linienstärke',
      fontSize: 'Schriftgröße',
      bold: 'Fett',
      italic: 'Kursiv',
      align: 'Ausrichtung',
      alignLeft: 'Links',
      alignCenter: 'Mitte',
      alignRight: 'Rechts',
      label: 'Text',
      edgeLabel: 'Kantenbeschriftung',
      templateTitle: 'Vorlage wählen',
      templateBasic: 'Basisfluss',
      templateDecision: 'Entscheidungsfluss',
      templateSwimlane: 'Horizontaler Swimlane-Fluss',
      templateSwimlaneV: 'Vertikaler Swimlane-Fluss',
      templateBpmn: 'BPMN-Gerüst',
      templateHint: 'Laden einer Vorlage ersetzt die aktuelle Fläche',
      exportPanel: 'Exportieren',
      importFile: 'Importieren',
      scale: 'Maßstab',
      transparentBg: 'Transparent',
      onlySelected: 'Nur Auswahl',
      padding: 'Rand',
      exportRange: 'Bereich',
      rangeCurrent: 'Aktuelle Seite',
      rangeAll: 'Alle Seiten',
      exporting: 'Wird exportiert…',
      snapToGrid: 'Am Raster ausrichten',
      gridSize: 'Raster',
      layoutDirection: 'Layout-Richtung',
      layoutDensity: 'Layout-Abstand',
      densityCompact: 'Kompakt',
      densityNormal: 'Normal',
      densityLoose: 'Weit',
      alignTolerance: 'Ausrichten-Schwelle',
      dirTB: 'Oben nach unten',
      dirBT: 'Unten nach oben',
      dirLR: 'Links nach rechts',
      dirRL: 'Rechts nach links',
      mixed: 'Gemischt',
      nodesSelected: '{{count}} Knoten ausgewählt',
      importHint: 'Unterstützt .flow.json / .drawio / .mmd',
      waypoints: 'Wegpunkte',
      waypoint: 'Wegpunkt',
      waypointCount: '{{count}}',
      waypointHint:
        'Orange Quadrate ziehen, um einen Wegpunkt zu verschieben, Doppelklick zum Löschen; blauen Punkt anklicken zum Einfügen.',
      autoRoute: 'Orthogonales Routing',
      clearWaypoints: 'Wegpunkte löschen',
      addWaypoint: 'Wegpunkt einfügen',
      removeWaypoint: 'Wegpunkt löschen',
      searchLayer: 'Ebenen suchen',
      moveOut: 'Aus Container entfernen',
      dropToRoot: 'Zum Entfernen aus dem Container hier ablegen',
      insertImage: 'Bild einfügen',
      insertIcon: 'Symbol einfügen',
      insertFormula: 'Formel einfügen',
      formula: 'Formel',
      imageFailed: 'Bild konnte nicht gelesen werden',
      draftTooLarge:
        'Entwurf zu groß: Bilder wurden nicht gespeichert. Bitte „Projektdatei exportieren“ verwenden.',
      iconGroup_general: 'Allgemein',
      iconGroup_office: 'Büro',
      iconGroup_tech: 'Technik',
      iconGroup_people: 'Team',
      quickConnect: 'Schnellverbindung',
      reconnectSource: 'Startpunkt neu verbinden',
      reconnectTarget: 'Endpunkt neu verbinden',
      defaultPageName: 'Seite {{n}}',
      layers: 'Ebenen',
      history: 'Verlauf',
      addPage: 'Neue Seite',
      prevPage: 'Vorherige Seite',
      nextPage: 'Nächste Seite',
      pageOverview: 'Seitenübersicht',
      openPageOverview: 'Seitenübersicht öffnen',
      closeOverview: 'Übersicht schließen',
      removePage: 'Seite löschen',
      emptyPage: 'Leere Seite',
      movePageLeft: 'Nach links',
      movePageRight: 'Nach rechts',
      pageCounter: 'Seite {{current}} von {{total}}',
      noLayer: 'Keine Elemente auf der Fläche',
      noSnapshot: 'Noch keine Snapshots gespeichert',
      saveSnapshot: 'Speichern',
      snapshotName: 'Snapshot-Name',
      restore: 'Wiederherstellen',
      toggleVisible: 'Ein- / Ausblenden',
      toggleLock: 'Sperren / Entsperren',
      renameHint: 'Doppelklick zum Umbenennen',
      alignTop: 'Oben ausrichten',
      alignMiddle: 'Mitte ausrichten',
      alignBottom: 'Unten ausrichten',
      distributeH: 'Horizontal verteilen',
      distributeV: 'Vertikal verteilen',
      uniformSize: 'Gleiche Größe',
      snapSelectionToGrid: 'Am Raster ausrichten',
      closeDialog: 'Schließen',
      contextMenu: 'Kontextmenü',
      switchShape: 'Form ändern',
      paste: 'Einfügen',
      selectAll: 'Alles auswählen',
      deselect: 'Auswahl aufheben',
      geometry: 'Geometrie',
      posX: 'X',
      posY: 'Y',
      geoWidth: 'Breite',
      geoHeight: 'Höhe',
      layerFront: 'Nach vorne',
      layerForward: 'Eine Ebene vor',
      layerBackward: 'Eine Ebene zurück',
      layerBack: 'Nach hinten',
      group: 'Gruppieren',
      ungroup: 'Gruppe auflösen',
      edgeStyle: 'Kantenstil',
      edgeType: 'Linientyp',
      edgeDash: 'Linie',
      edgeStartArrow: 'Start',
      edgeEndArrow: 'Ende',
      straight: 'Gerade',
      bezier: 'Bézier',
      smoothstep: 'Abgerundete Ecke',
      step: 'Rechteckige Ecke',
      solid: 'Durchgezogen',
      dashed: 'Gestrichelt',
      dotted: 'Gepunktet',
      arrowNone: 'Keine',
      arrowArrow: 'Pfeil',
      arrowCircle: 'Kreis',
      arrowTriangle: 'Leeres Dreieck',
      arrowDiamondHollow: 'Leere Raute',
      templateUmlUseCase: 'Anwendungsfalldiagramm',
      templateUmlClass: 'Klassendiagramm',
      templateUmlSequence: 'Sequenzdiagramm',
      templateUmlActivity: 'Aktivitätsdiagramm',
      templateUmlState: 'Zustandsdiagramm',
      templateBpmnProcess: 'Geschäftsprozess',
      templateNetTopology: 'Netzwerktopologie',
      templateOrgChart: 'Organigramm',
      templateMindMap: 'Mindmap',
      templateErDiagram: 'ER-Diagramm',
      templateApproval: 'Genehmigungsprozess',
      templateOnboarding: 'Onboarding-Prozess',
      templateSwimlane2: 'Zwei-Spur-Prozess',
      templateUmlComponent: 'Komponentendiagramm',
      templateBpmnCollab: 'Kollaborationsprozess',
      templateNetSubnet: 'Subnetz-Topologie',
      theme: 'Design',
      themeDefault: 'Standard',
      themeBusiness: 'Business',
      themeMinimal: 'Minimal',
      themeDark: 'Dunkel',
      applyThemeAll: 'Auf alle anwenden',
      applyThemeSelection: 'Auf Auswahl anwenden',
      formatBrush: 'Stil kopieren',
      applyStyle: 'Stil einfügen',
      exportPrintPdf: 'PDF mit Seitenumbruch drucken',
      printLandscape: 'Querformat drucken',
      err: {
        EMPTY: 'Fläche ist leer',
        EXPORT_FAILED: 'Export fehlgeschlagen',
        IMPORT_FAILED: 'Import fehlgeschlagen: Dateiformat nicht erkannt',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: 'Prozess',
  roundRect: 'Abgerundetes Rechteck',
  ellipse: 'Ellipse',
  diamond: 'Raute',
  parallelogram: 'Parallelogramm',
  trapezoid: 'Trapez',
  hexagon: 'Sechseck',
  cylinder: 'Zylinder',
  note: 'Notiz',
  startEnd: 'Start / Ende',
  decision: 'Entscheidung',
  data: 'Daten',
  document: 'Dokument',
  predefined: 'Vordefinierter Prozess',
  manualInput: 'Manuelle Eingabe',
  manualOperation: 'Manueller Vorgang',
  preparation: 'Vorbereitung',
  database: 'Datenbank',
  display: 'Anzeige',
  onPageConnector: 'Verbinder gleiche Seite',
  offPageConnector: 'Verbinder andere Seite',
  terminator: 'Abschluss',
  parallelMode: 'Parallelmodus',
  loopLimit: 'Schleifengrenze',
  umlActor: 'Akteur',
  umlNote: 'Notiz',
  umlBoundary: 'Grenze',
  umlControl: 'Steuerung',
  umlEntity: 'Entität',
  umlFrame: 'Rahmen',
  umlUseCase: 'Anwendungsfall',
  umlSubject: 'Subjekt',
  umlInclude: 'Include',
  umlExtend: 'Extend',
  umlExtensionPoint: 'Erweiterungspunkt',
  umlClass: 'Klasse',
  umlInterface: 'Schnittstelle',
  umlEnumeration: 'Aufzählung',
  umlDataType: 'Datentyp',
  umlAbstractClass: 'Abstrakte Klasse',
  umlActiveClass: 'Aktive Klasse',
  umlTemplateClass: 'Template-Klasse',
  umlAssociationClass: 'Assoziationsklasse',
  umlPackage: 'Paket',
  umlObject: 'Objekt',
  umlObjectSlot: 'Objekt (Slots)',
  umlModel: 'Modell',
  umlProfile: 'Profil',
  umlLifeline: 'Lebenslinie',
  umlActivation: 'Aktivierung',
  umlDestroy: 'Zerstörung',
  umlCombinedFragment: 'Kombiniertes Fragment',
  umlInteractionUse: 'Interaktionsverwendung',
  umlStateInvariant: 'Zustandsinvariante',
  umlGate: 'Tor',
  umlForkJoin: 'Gabelung / Zusammenführung',
  umlAction: 'Aktion',
  umlActivity: 'Aktivität',
  umlDecisionMerge: 'Entscheidung / Zusammenführung',
  umlInitialNode: 'Startknoten',
  umlActivityFinal: 'Aktivitätsende',
  umlFlowFinal: 'Flussende',
  umlObjectNode: 'Objektknoten',
  umlSendSignal: 'Signal senden',
  umlReceiveSignal: 'Signal empfangen',
  umlActivityPartition: 'Aktivitätspartition',
  umlState: 'Zustand',
  umlStateInitial: 'Anfangszustand',
  umlStateFinal: 'Endzustand',
  umlChoice: 'Auswahl',
  umlJunction: 'Verbindung',
  umlTerminate: 'Abbruch',
  umlEntryPoint: 'Eintrittspunkt',
  umlExitPoint: 'Austrittspunkt',
  umlHistory: 'Flache Historie',
  umlHistoryDeep: 'Tiefe Historie',
  umlCompositeState: 'Zusammengesetzter Zustand',
  umlComponent: 'Komponente',
  umlProvidedInterface: 'Angebotene Schnittstelle',
  umlRequiredInterface: 'Benötigte Schnittstelle',
  umlPort: 'Port',
  umlSubsystem: 'Teilsystem',
  umlNode: 'Knoten',
  umlDevice: 'Gerät',
  umlExecutionEnvironment: 'Ausführungsumgebung',
  umlArtifact: 'Artefakt',
  umlDeploymentSpec: 'Bereitstellungsspezifikation',
  bpmnEventStart: 'Startereignis',
  bpmnEventIntermediate: 'Zwischenereignis',
  bpmnEventEnd: 'Endereignis',
  bpmnGatewayExclusive: 'Exklusives Gateway',
  bpmnGatewayParallel: 'Paralleles Gateway',
  bpmnGatewayInclusive: 'Inklusives Gateway',
  bpmnTask: 'Aufgabe',
  bpmnSubProcess: 'Teilprozess',
  bpmnCallActivity: 'Aufrufende Aktivität',
  bpmnDataObject: 'Datenobjekt',
  bpmnDataStore: 'Datenspeicher',
  bpmnTextAnnotation: 'Textanmerkung',
  netServer: 'Server',
  netClient: 'Client',
  netRouter: 'Router',
  netSwitch: 'Switch',
  netFirewall: 'Firewall',
  netLoadBalancer: 'Lastverteiler',
  netCloud: 'Cloud',
  netCdn: 'CDN',
  netDatabase: 'Datenbank',
  netStorage: 'Speicher',
  orgUnit: 'Einheit',
  orgAssistant: 'Assistenz',
  orgTeam: 'Team',
  mindCenter: 'Hauptthema',
  mindTopic: 'Thema',
  mindSub: 'Unterthema',
  erEntity: 'Entität',
  erAttribute: 'Attribut',
  erRelationship: 'Beziehung',
  erWeakEntity: 'Schwache Entität',
  swimlane: 'Horizontale Spur',
  swimlaneV: 'Vertikale Spur',
  group: 'Gruppe',
  triangle: 'Dreieck',
  star: 'Stern',
  pentagon: 'Fünfeck',
  octagon: 'Achteck',
  chevron: 'Pfeil',
  card: 'Karte',
  callout: 'Sprechblase',
  cloud: 'Wolke',
  cross: 'Kreuz',
  plus: 'Plus',
  flag: 'Fahne',
  lightning: 'Blitz',
  arrow: 'Pfeil',
  bracket: 'Klammer',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
