/**
 * en 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'New canvas',
      docTitle: 'Diagram title',
      present: 'Present',
      exitPresent: 'Exit (Esc)',
      presentLoading: 'Preparing the slideshow…',
      presentFailed: 'Failed to build the slideshow',
      titlePlaceholder: 'Untitled diagram',
      clear: 'Clear',
      exportPng: 'Export PNG',
      exportSvg: 'Export SVG',
      templates: 'Templates',
      autoLayout: 'Auto layout',
      fitView: 'Fit to screen',
      zoomActual: 'Actual size',
      undo: 'Undo',
      redo: 'Redo',
      duplicate: 'Duplicate',
      delete: 'Delete',
      panelTitle: 'Properties',
      paletteTitle: 'Shapes',
      searchShape: 'Search shapes',
      noShape: 'No matching shape',
      resizeSidebar: 'Drag to resize sidebar',
      exportPanel: 'Export',
      importFile: 'Import',
      scale: 'Scale',
      transparentBg: 'Transparent',
      onlySelected: 'Selection only',
      padding: 'Margin',
      exportRange: 'Range',
      rangeCurrent: 'Current page',
      rangeAll: 'All pages',
      exporting: 'Exporting…',
      snapToGrid: 'Snap to grid',
      gridSize: 'Grid',
      layoutDirection: 'Layout direction',
      layoutDensity: 'Layout spacing',
      densityCompact: 'Compact',
      densityNormal: 'Normal',
      densityLoose: 'Loose',
      alignTolerance: 'Align threshold',
      dirTB: 'Top to bottom',
      dirBT: 'Bottom to top',
      dirLR: 'Left to right',
      dirRL: 'Right to left',
      mixed: 'Mixed',
      nodesSelected: '{{count}} nodes selected',
      importHint: 'Supports .flow.json / .drawio / .mmd',
      waypoints: 'Waypoints',
      waypoint: 'Waypoint',
      waypointCount: '{{count}}',
      waypointHint:
        'Drag the orange squares to move a waypoint, double-click to delete; click a blue dot to insert one.',
      autoRoute: 'Orthogonal routing',
      clearWaypoints: 'Clear waypoints',
      addWaypoint: 'Insert waypoint',
      removeWaypoint: 'Delete waypoint',
      searchLayer: 'Search layers',
      moveOut: 'Move out of container',
      dropToRoot: 'Drop here to move out of a container',
      insertImage: 'Insert image',
      insertIcon: 'Insert icon',
      insertFormula: 'Insert formula',
      formula: 'Formula',
      imageFailed: 'Failed to read the image',
      draftTooLarge:
        'Draft is too large: images were not saved locally. Use "Export project file" instead.',
      iconGroup_general: 'General',
      iconGroup_office: 'Office',
      iconGroup_tech: 'Tech',
      iconGroup_people: 'People',
      quickConnect: 'Quick connect',
      reconnectSource: 'Reconnect start',
      reconnectTarget: 'Reconnect end',
      defaultPageName: 'Page {{n}}',
      layers: 'Layers',
      history: 'History',
      addPage: 'New page',
      prevPage: 'Previous page',
      nextPage: 'Next page',
      pageOverview: 'Page overview',
      openPageOverview: 'Open page overview',
      closeOverview: 'Close overview',
      removePage: 'Delete page',
      emptyPage: 'Blank page',
      movePageLeft: 'Move left',
      movePageRight: 'Move right',
      pageCounter: 'Page {{current}} of {{total}}',
      noLayer: 'No elements on the canvas',
      noSnapshot: 'No snapshots saved yet',
      saveSnapshot: 'Save',
      snapshotName: 'Snapshot name',
      restore: 'Restore',
      toggleVisible: 'Show / Hide',
      toggleLock: 'Lock / Unlock',
      renameHint: 'Double-click to rename',
      cat_general: 'General',
      cat_flow: 'Flowchart',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Network & Cloud',
      cat_org: 'Organization',
      cat_mind: 'Mind map',
      cat_er: 'ER diagram',
      groupBasic: 'Basic shapes',
      groupFlow: 'Flow symbols',
      groupBpmn: 'Swimlanes & BPMN',
      shape_rect: 'Process',
      shape_startEnd: 'Start / End',
      shape_decision: 'Decision',
      shape_data: 'Data',
      shape_swimlane: 'Horizontal lane',
      shape_swimlaneV: 'Vertical lane',
      shape_bpmnTask: 'BPMN task',
      canvasAria: 'Flowchart canvas',
      emptyHint: 'Drag a shape from the left, or pick a template to start',
      nodesLabel: 'Nodes',
      edgesLabel: 'Edges',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop editing',
      noSelection: 'No element selected',
      selected: '{{count}} elements selected',
      fill: 'Fill',
      stroke: 'Stroke',
      strokeWidth: 'Stroke width',
      fontSize: 'Font size',
      bold: 'Bold',
      italic: 'Italic',
      align: 'Align',
      alignLeft: 'Left',
      alignCenter: 'Center',
      alignRight: 'Right',
      alignTop: 'Align top',
      alignMiddle: 'Align middle',
      alignBottom: 'Align bottom',
      distributeH: 'Distribute horizontally',
      distributeV: 'Distribute vertically',
      uniformSize: 'Same size',
      snapSelectionToGrid: 'Snap selection to grid',
      closeDialog: 'Close',
      contextMenu: 'Context menu',
      switchShape: 'Change shape',
      paste: 'Paste',
      selectAll: 'Select all',
      deselect: 'Clear selection',
      geometry: 'Geometry',
      posX: 'X',
      posY: 'Y',
      geoWidth: 'Width',
      geoHeight: 'Height',
      layerFront: 'Bring to front',
      layerForward: 'Bring forward',
      layerBackward: 'Send backward',
      layerBack: 'Send to back',
      group: 'Group',
      ungroup: 'Ungroup',
      edgeStyle: 'Edge style',
      edgeType: 'Line type',
      edgeDash: 'Stroke',
      edgeStartArrow: 'Arrow at start',
      edgeEndArrow: 'Arrow at end',
      edgeSourceNode: 'Source node',
      edgeTargetNode: 'Target node',
      straight: 'Straight',
      bezier: 'Bezier',
      smoothstep: 'Rounded step',
      step: 'Right-angle step',
      solid: 'Solid',
      dashed: 'Dashed',
      dotted: 'Dotted',
      arrowNone: 'None',
      arrowArrow: 'Arrow',
      arrowCircle: 'Circle',
      label: 'Text',
      edgeLabel: 'Edge label',
      templateTitle: 'Choose a template',
      templateBasic: 'Basic flow',
      templateDecision: 'Decision flow',
      templateSwimlane: 'Horizontal lane flow',
      templateSwimlaneV: 'Vertical lane flow',
      templateUmlUseCase: 'Use case diagram',
      templateUmlClass: 'Class diagram',
      templateUmlSequence: 'Sequence diagram',
      templateUmlActivity: 'Activity diagram',
      templateUmlState: 'State diagram',
      templateBpmnProcess: 'Business process',
      templateNetTopology: 'Network topology',
      templateOrgChart: 'Organization chart',
      templateMindMap: 'Mind map',
      templateErDiagram: 'ER diagram',
      templateApproval: 'Approval flow',
      templateOnboarding: 'Onboarding flow',
      templateSwimlane2: 'Two-lane flow',
      templateUmlComponent: 'Component diagram',
      templateBpmnCollab: 'Collaboration flow',
      templateNetSubnet: 'Subnet topology',
      theme: 'Theme',
      themeDefault: 'Default',
      themeBusiness: 'Business',
      themeMinimal: 'Minimal',
      themeDark: 'Dark',
      applyThemeAll: 'Apply to all',
      applyThemeSelection: 'Apply to selection',
      formatBrush: 'Copy style',
      applyStyle: 'Paste style',
      exportPrintPdf: 'Print paged PDF',
      printLandscape: 'Landscape print',
      templateBpmn: 'BPMN skeleton',
      templateHint: 'Loading a template replaces the current canvas',
      edgeStyleLabel: 'Edge style',
      startArrowLabel: 'Start arrow',
      endArrowLabel: 'End arrow',
      dashdot: 'Dash-dot',
      sketch: 'Sketch',
      sketchDashed: 'Sketch dashed',
      arrowSolid: 'Solid arrow',
      arrowOpen: 'Open arrow',
      arrowDiamond: 'Diamond',
      arrowSquare: 'Square',
      arrowBar: 'Bar',
      appearance: 'Appearance',
      opacity: 'Opacity',
      shadow: 'Shadow',
      textColor: 'Text color',
      cornerRadius: 'Corner radius',
      foldSize: 'Fold size',
      fontFamily: 'Font',
      err: {
        EMPTY: 'Canvas is empty, nothing to export',
        EXPORT_FAILED: 'Export failed',
        IMPORT_FAILED: 'Import failed: unsupported file format',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: 'Process',
  roundRect: 'Rounded rectangle',
  ellipse: 'Ellipse',
  diamond: 'Diamond',
  parallelogram: 'Parallelogram',
  trapezoid: 'Trapezoid',
  hexagon: 'Hexagon',
  cylinder: 'Cylinder',
  note: 'Note',
  startEnd: 'Start / End',
  decision: 'Decision',
  data: 'Data',
  document: 'Document',
  predefined: 'Predefined process',
  manualInput: 'Manual input',
  manualOperation: 'Manual operation',
  preparation: 'Preparation',
  database: 'Database',
  display: 'Display',
  onPageConnector: 'On-page connector',
  offPageConnector: 'Off-page connector',
  terminator: 'Terminator',
  parallelMode: 'Parallel mode',
  loopLimit: 'Loop limit',
  umlActor: 'Actor',
  umlUseCase: 'Use case',
  umlClass: 'Class',
  umlInterface: 'Interface',
  umlPackage: 'Package',
  umlNote: 'Note',
  umlLifeline: 'Lifeline',
  umlState: 'State',
  umlStateInitial: 'Initial state',
  umlStateFinal: 'Final state',
  umlForkJoin: 'Fork / Join',
  bpmnEventStart: 'Start event',
  bpmnEventIntermediate: 'Intermediate event',
  bpmnEventEnd: 'End event',
  bpmnGatewayExclusive: 'Exclusive gateway',
  bpmnGatewayParallel: 'Parallel gateway',
  bpmnGatewayInclusive: 'Inclusive gateway',
  bpmnTask: 'Task',
  bpmnSubProcess: 'Sub-process',
  bpmnCallActivity: 'Call activity',
  bpmnDataObject: 'Data object',
  bpmnDataStore: 'Data store',
  bpmnTextAnnotation: 'Text annotation',
  netServer: 'Server',
  netClient: 'Client',
  netRouter: 'Router',
  netSwitch: 'Switch',
  netFirewall: 'Firewall',
  netLoadBalancer: 'Load balancer',
  netCloud: 'Cloud',
  netCdn: 'CDN',
  netDatabase: 'Database',
  netStorage: 'Storage',
  orgUnit: 'Unit',
  orgAssistant: 'Assistant',
  orgTeam: 'Team',
  mindCenter: 'Central topic',
  mindTopic: 'Topic',
  mindSub: 'Subtopic',
  erEntity: 'Entity',
  erAttribute: 'Attribute',
  erRelationship: 'Relationship',
  erWeakEntity: 'Weak entity',
  swimlane: 'Horizontal lane',
  swimlaneV: 'Vertical lane',
  group: 'Group',
  triangle: 'Triangle',
  star: 'Star',
  pentagon: 'Pentagon',
  octagon: 'Octagon',
  chevron: 'Chevron',
  card: 'Card',
  callout: 'Callout',
  cloud: 'Cloud',
  cross: 'Cross',
  plus: 'Plus',
  flag: 'Flag',
  lightning: 'Lightning',
  arrow: 'Arrow',
  bracket: 'Bracket',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
