/**
 * es 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nuevo lienzo',
      docTitle: 'Título del diagrama',
      present: 'Presentar',
      exitPresent: 'Salir (Esc)',
      presentLoading: 'Preparando la presentación…',
      presentFailed: 'No se pudo preparar la presentación',
      titlePlaceholder: 'Diagrama sin título',
      clear: 'Vaciar',
      exportPng: 'Exportar PNG',
      exportSvg: 'Exportar SVG',
      templates: 'Plantillas',
      autoLayout: 'Auto diseño',
      fitView: 'Ajustar a la pantalla',
      zoomActual: 'Tamaño real',
      undo: 'Deshacer',
      redo: 'Rehacer',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      panelTitle: 'Propiedades',
      paletteTitle: 'Formas',
      searchShape: 'Buscar formas',
      noShape: 'Sin formas coincidentes',
      resizeSidebar: 'Arrastra para ajustar el ancho',
      cat_general: 'General',
      cat_flow: 'Diagrama de flujo',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Red y nube',
      cat_org: 'Organización',
      cat_mind: 'Mapa mental',
      cat_er: 'Diagrama ER',
      groupBasic: 'Formas básicas',
      groupFlow: 'Símbolos de flujo',
      groupBpmn: 'Carriles y BPMN',
      shape_rect: 'Proceso',
      shape_startEnd: 'Inicio / Fin',
      shape_decision: 'Decisión',
      shape_data: 'Datos',
      shape_swimlane: 'Carril horizontal',
      shape_swimlaneV: 'Carril vertical',
      shape_bpmnTask: 'Tarea BPMN',
      canvasAria: 'Lienzo de diagrama',
      emptyHint: 'Arrastra una forma desde la izquierda o elige una plantilla',
      nodesLabel: 'Nodos',
      edgesLabel: 'Enlaces',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de editar',
      noSelection: 'Ningún elemento seleccionado',
      selected: '{{count}} elementos seleccionados',
      fill: 'Relleno',
      stroke: 'Contorno',
      strokeWidth: 'Grosor',
      fontSize: 'Tamaño',
      bold: 'Negrita',
      italic: 'Cursiva',
      align: 'Alineación',
      alignLeft: 'Izquierda',
      alignCenter: 'Centro',
      alignRight: 'Derecha',
      label: 'Texto',
      edgeLabel: 'Etiqueta de enlace',
      templateTitle: 'Elegir plantilla',
      templateBasic: 'Flujo básico',
      templateDecision: 'Flujo de decisión',
      templateSwimlane: 'Flujo de carril horizontal',
      templateSwimlaneV: 'Flujo de carril vertical',
      templateBpmn: 'Esqueleto BPMN',
      templateHint: 'Cargar una plantilla reemplaza el lienzo actual',
      exportPanel: 'Exportar',
      importFile: 'Importar',
      scale: 'Escala',
      transparentBg: 'Transparente',
      onlySelected: 'Solo selección',
      padding: 'Margen',
      exportRange: 'Rango',
      rangeCurrent: 'Página actual',
      rangeAll: 'Todas las páginas',
      exporting: 'Exportando…',
      snapToGrid: 'Ajustar a la cuadrícula',
      gridSize: 'Cuadrícula',
      layoutDirection: 'Dirección del diseño',
      layoutDensity: 'Espaciado',
      densityCompact: 'Compacto',
      densityNormal: 'Normal',
      densityLoose: 'Amplio',
      alignTolerance: 'Umbral de alineación',
      dirTB: 'De arriba abajo',
      dirBT: 'De abajo arriba',
      dirLR: 'De izquierda a derecha',
      dirRL: 'De derecha a izquierda',
      mixed: 'Mixto',
      nodesSelected: '{{count}} nodos seleccionados',
      importHint: 'Compatible con .flow.json / .drawio / .mmd',
      waypoints: 'Puntos de paso',
      waypoint: 'Punto de paso',
      waypointCount: '{{count}}',
      waypointHint:
        'Arrastra los cuadrados naranjas para mover un punto, doble clic para eliminarlo; haz clic en un punto azul para insertar uno.',
      autoRoute: 'Enrutado ortogonal',
      clearWaypoints: 'Borrar puntos',
      addWaypoint: 'Insertar punto',
      removeWaypoint: 'Eliminar punto',
      searchLayer: 'Buscar capas',
      moveOut: 'Sacar del contenedor',
      dropToRoot: 'Suelta aquí para salir del contenedor',
      insertImage: 'Insertar imagen',
      insertIcon: 'Insertar icono',
      insertFormula: 'Insertar fórmula',
      formula: 'Fórmula',
      imageFailed: 'No se pudo leer la imagen',
      draftTooLarge:
        'Borrador demasiado grande: las imágenes no se guardaron. Usa «Exportar proyecto».',
      iconGroup_general: 'General',
      iconGroup_office: 'Oficina',
      iconGroup_tech: 'Tecnología',
      iconGroup_people: 'Personas',
      quickConnect: 'Conexión rápida',
      reconnectSource: 'Reconectar inicio',
      reconnectTarget: 'Reconectar fin',
      defaultPageName: 'Página {{n}}',
      layers: 'Capas',
      history: 'Historial',
      addPage: 'Nueva página',
      prevPage: 'Página anterior',
      nextPage: 'Página siguiente',
      pageOverview: 'Vista de páginas',
      openPageOverview: 'Abrir la vista de páginas',
      closeOverview: 'Cerrar la vista',
      removePage: 'Eliminar página',
      emptyPage: 'Página vacía',
      movePageLeft: 'Mover a la izquierda',
      movePageRight: 'Mover a la derecha',
      pageCounter: 'Página {{current}} de {{total}}',
      noLayer: 'No hay elementos en el lienzo',
      noSnapshot: 'Aún no hay instantáneas guardadas',
      saveSnapshot: 'Guardar',
      snapshotName: 'Nombre de instantánea',
      restore: 'Restaurar',
      toggleVisible: 'Mostrar / Ocultar',
      toggleLock: 'Bloquear / Desbloquear',
      renameHint: 'Doble clic para renombrar',
      alignTop: 'Alinear arriba',
      alignMiddle: 'Alinear al centro',
      alignBottom: 'Alinear abajo',
      distributeH: 'Distribuir horizontalmente',
      distributeV: 'Distribuir verticalmente',
      layerFront: 'Traer al frente',
      layerForward: 'Acercar',
      layerBackward: 'Alejar',
      layerBack: 'Enviar atrás',
      group: 'Agrupar',
      ungroup: 'Desagrupar',
      edgeStyle: 'Estilo de enlace',
      edgeType: 'Tipo de línea',
      edgeDash: 'Trazo',
      edgeStartArrow: 'Inicio',
      edgeEndArrow: 'Fin',
      straight: 'Línea recta',
      bezier: 'Bézier',
      smoothstep: 'Esquina redondeada',
      step: 'Esquina recta',
      solid: 'Sólida',
      dashed: 'Guionada',
      dotted: 'Punteada',
      arrowNone: 'Ninguna',
      arrowArrow: 'Flecha',
      arrowCircle: 'Círculo',
      templateUmlUseCase: 'Diagrama de casos de uso',
      templateUmlClass: 'Diagrama de clases',
      templateUmlSequence: 'Diagrama de secuencia',
      templateUmlActivity: 'Diagrama de actividad',
      templateUmlState: 'Diagrama de estados',
      templateBpmnProcess: 'Proceso de negocio',
      templateNetTopology: 'Topología de red',
      templateOrgChart: 'Organigrama',
      templateMindMap: 'Mapa mental',
      templateErDiagram: 'Diagrama ER',
      templateApproval: 'Flujo de aprobación',
      templateOnboarding: 'Proceso de incorporación',
      templateSwimlane2: 'Flujo de dos carriles',
      templateUmlComponent: 'Diagrama de componentes',
      templateBpmnCollab: 'Flujo colaborativo',
      templateNetSubnet: 'Topología de subred',
      theme: 'Tema',
      themeDefault: 'Predeterminado',
      themeBusiness: 'Empresa',
      themeMinimal: 'Minimalista',
      themeDark: 'Oscuro',
      applyThemeAll: 'Aplicar a todo',
      applyThemeSelection: 'Aplicar a la selección',
      formatBrush: 'Copiar estilo',
      applyStyle: 'Pegar estilo',
      exportPrintPdf: 'Imprimir PDF paginado',
      printLandscape: 'Impresión horizontal',
      err: {
        EMPTY: 'El lienzo está vacío',
        EXPORT_FAILED: 'Error al exportar',
        IMPORT_FAILED: 'Error al importar: formato de archivo no reconocido',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: 'Proceso',
  roundRect: 'Rectángulo redondeado',
  ellipse: 'Elipse',
  diamond: 'Rombo',
  parallelogram: 'Paralelogramo',
  trapezoid: 'Trapecio',
  hexagon: 'Hexágono',
  cylinder: 'Cilindro',
  note: 'Nota',
  startEnd: 'Inicio / Fin',
  decision: 'Decisión',
  data: 'Datos',
  document: 'Documento',
  predefined: 'Proceso predefinido',
  manualInput: 'Entrada manual',
  manualOperation: 'Operación manual',
  preparation: 'Preparación',
  database: 'Base de datos',
  display: 'Visualización',
  onPageConnector: 'Conector misma página',
  offPageConnector: 'Conector otra página',
  terminator: 'Terminador',
  parallelMode: 'Modo paralelo',
  loopLimit: 'Límite de bucle',
  umlActor: 'Actor',
  umlUseCase: 'Caso de uso',
  umlClass: 'Clase',
  umlInterface: 'Interfaz',
  umlPackage: 'Paquete',
  umlNote: 'Nota',
  umlLifeline: 'Línea de vida',
  umlState: 'Estado',
  umlStateInitial: 'Estado inicial',
  umlStateFinal: 'Estado final',
  umlForkJoin: 'Bifurcación / Unión',
  bpmnEventStart: 'Evento de inicio',
  bpmnEventIntermediate: 'Evento intermedio',
  bpmnEventEnd: 'Evento final',
  bpmnGatewayExclusive: 'Compuerta exclusiva',
  bpmnGatewayParallel: 'Compuerta paralela',
  bpmnGatewayInclusive: 'Compuerta inclusiva',
  bpmnTask: 'Tarea',
  bpmnSubProcess: 'Subproceso',
  bpmnCallActivity: 'Actividad de llamada',
  bpmnDataObject: 'Objeto de datos',
  bpmnDataStore: 'Almacén de datos',
  bpmnTextAnnotation: 'Anotación de texto',
  netServer: 'Servidor',
  netClient: 'Cliente',
  netRouter: 'Enrutador',
  netSwitch: 'Conmutador',
  netFirewall: 'Cortafuegos',
  netLoadBalancer: 'Balanceador de carga',
  netCloud: 'Nube',
  netCdn: 'CDN',
  netDatabase: 'Base de datos',
  netStorage: 'Almacenamiento',
  orgUnit: 'Unidad',
  orgAssistant: 'Asistente',
  orgTeam: 'Equipo',
  mindCenter: 'Tema central',
  mindTopic: 'Tema',
  mindSub: 'Subtema',
  erEntity: 'Entidad',
  erAttribute: 'Atributo',
  erRelationship: 'Relación',
  erWeakEntity: 'Entidad débil',
  swimlane: 'Carril horizontal',
  swimlaneV: 'Carril vertical',
  group: 'Grupo',
  triangle: 'Triángulo',
  star: 'Estrella',
  pentagon: 'Pentágono',
  octagon: 'Octágono',
  chevron: 'Cheurón',
  card: 'Tarjeta',
  callout: 'Globo',
  cloud: 'Nube',
  cross: 'Cruz',
  plus: 'Más',
  flag: 'Bandera',
  lightning: 'Rayo',
  arrow: 'Flecha',
  bracket: 'Corchete',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
