/**
 * es 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nuevo lienzo',
      docTitle: 'Título del diagrama',
      present: 'Presentar',
      exitPresent: 'Salir (Esc)',
      presentLoading: 'Preparando la presentación…',
      presentFailed: 'No se pudo preparar la presentación',
      titlePlaceholder: 'Diagrama sin título',
      clear: 'Vaciar',
      exportPng: 'Exportar PNG',
      exportSvg: 'Exportar SVG',
      templates: 'Plantillas',
      autoLayout: 'Auto diseño',
      fitView: 'Ajustar a la pantalla',
      zoomActual: 'Tamaño real',
      undo: 'Deshacer',
      redo: 'Rehacer',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      panelTitle: 'Propiedades',
      paletteTitle: 'Formas',
      searchShape: 'Buscar formas',
      noShape: 'Sin formas coincidentes',
      resizeSidebar: 'Arrastra para ajustar el ancho',
      cat_general: 'General',
      cat_flow: 'Diagrama de flujo',
      cat_uml: 'UML',
      cat_umlCommon: 'UML común',
      cat_umlUseCase: 'UML casos de uso',
      cat_umlClass: 'UML clases',
      cat_umlObject: 'UML objetos/paquetes',
      cat_umlSequence: 'UML secuencia',
      cat_umlActivity: 'UML actividad',
      cat_umlState: 'UML estados',
      cat_umlComponent: 'UML componentes',
      cat_umlDeployment: 'UML despliegue',
      cat_bpmn: 'BPMN',
      cat_network: 'Red y nube',
      cat_org: 'Organización',
      cat_mind: 'Mapa mental',
      cat_er: 'Diagrama ER',
      groupBasic: 'Formas básicas',
      groupFlow: 'Símbolos de flujo',
      groupBpmn: 'Carriles y BPMN',
      shape_rect: 'Proceso',
      shape_startEnd: 'Inicio / Fin',
      shape_decision: 'Decisión',
      shape_data: 'Datos',
      shape_swimlane: 'Carril horizontal',
      shape_swimlaneV: 'Carril vertical',
      shape_bpmnTask: 'Tarea BPMN',
      canvasAria: 'Lienzo de diagrama',
      emptyHint: 'Arrastra una forma desde la izquierda o elige una plantilla',
      showGuide: 'Guía rápida',
      onboardingTitle: 'Guía rápida',
      onboardingStepPalette:
        'Haz clic o arrastra una forma desde la biblioteca de la izquierda; también puedes insertar imágenes, iconos, fórmulas y tablas.',
      onboardingStepConnect:
        'Pasa el puntero por el borde de un nodo y arrastra un ancla azul o la flecha de conexión rápida para crear un conector.',
      onboardingStepArrange:
        'Selecciona varios elementos y usa el panel Organizar de la derecha para alinear, distribuir y unificar tamaños.',
      onboardingStepExport:
        'La exportación admite PNG / SVG (vectorial) / PDF / Draw.io / Mermaid e impresión paginada.',
      onboardingSkip: 'Omitir',
      onboardingNext: 'Siguiente',
      onboardingDone: 'Empezar',
      nodesLabel: 'Nodos',
      edgesLabel: 'Enlaces',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de editar',
      noSelection: 'Ningún elemento seleccionado',
      selected: '{{count}} elementos seleccionados',
      fill: 'Relleno',
      stroke: 'Contorno',
      strokeWidth: 'Grosor',
      fontSize: 'Tamaño',
      bold: 'Negrita',
      italic: 'Cursiva',
      align: 'Alineación',
      alignLeft: 'Izquierda',
      alignCenter: 'Centro',
      alignRight: 'Derecha',
      label: 'Texto',
      edgeLabel: 'Etiqueta de enlace',
      templateTitle: 'Elegir plantilla',
      templateBasic: 'Flujo básico',
      templateDecision: 'Flujo de decisión',
      templateSwimlane: 'Flujo de carril horizontal',
      templateSwimlaneV: 'Flujo de carril vertical',
      templateBpmn: 'Esqueleto BPMN',
      templateHint: 'Cargar una plantilla reemplaza el lienzo actual',
      exportPanel: 'Exportar',
      importFile: 'Importar',
      scale: 'Escala',
      transparentBg: 'Transparente',
      onlySelected: 'Solo selección',
      padding: 'Margen',
      exportRange: 'Rango',
      rangeCurrent: 'Página actual',
      rangeAll: 'Todas las páginas',
      exporting: 'Exportando…',
      snapToGrid: 'Ajustar a la cuadrícula',
      gridSize: 'Cuadrícula',
      layoutDirection: 'Dirección del diseño',
      layoutDensity: 'Espaciado',
      densityCompact: 'Compacto',
      densityNormal: 'Normal',
      densityLoose: 'Amplio',
      alignTolerance: 'Umbral de alineación',
      dirTB: 'De arriba abajo',
      dirBT: 'De abajo arriba',
      dirLR: 'De izquierda a derecha',
      dirRL: 'De derecha a izquierda',
      mixed: 'Mixto',
      nodesSelected: '{{count}} nodos seleccionados',
      importHint: 'Compatible con .flow.json / .drawio / .mmd',
      waypoints: 'Puntos de paso',
      waypoint: 'Punto de paso',
      waypointCount: '{{count}}',
      waypointHint:
        'Arrastra los cuadrados naranjas para mover un punto, doble clic para eliminarlo; haz clic en un punto azul para insertar uno.',
      autoRoute: 'Enrutado ortogonal',
      routeAll: 'Enrutar todos los conectores',
      clearWaypoints: 'Borrar puntos',
      addWaypoint: 'Insertar punto',
      removeWaypoint: 'Eliminar punto',
      searchLayer: 'Buscar capas',
      moveOut: 'Sacar del contenedor',
      dropToRoot: 'Suelta aquí para salir del contenedor',
      insertImage: 'Insertar imagen',
      insertIcon: 'Insertar icono',
      insertFormula: 'Insertar fórmula',
      insertTable: 'Insertar tabla',
      tableInsertRow: 'Insertar fila debajo',
      tableInsertCol: 'Insertar columna a la derecha',
      tableRemoveRow: 'Eliminar fila',
      tableRemoveCol: 'Eliminar columna',
      tableMerge: 'Combinar con la celda de la derecha',
      tableSplit: 'Dividir celda',
      tableSection: 'Tabla',
      tableRows: 'Filas',
      tableColumns: 'Columnas',
      tableHint:
        'Haz doble clic en una celda para editarla; selecciona una celda y usa la barra superior para añadir o quitar filas/columnas, o combinar/dividir.',
      textFormat: 'Formato de texto',
      textFormatPlain: 'Texto sin formato',
      textFormatMarkdown: 'Markdown',
      formula: 'Fórmula',
      imageFailed: 'No se pudo leer la imagen',
      draftTooLarge:
        'Borrador demasiado grande: las imágenes no se guardaron. Usa «Exportar proyecto».',
      iconGroup_general: 'General',
      iconGroup_office: 'Oficina',
      iconGroup_tech: 'Tecnología',
      iconGroup_people: 'Personas',
      quickConnect: 'Conexión rápida',
      reconnectSource: 'Reconectar inicio',
      reconnectTarget: 'Reconectar fin',
      defaultPageName: 'Página {{n}}',
      layers: 'Capas',
      history: 'Historial',
      addPage: 'Nueva página',
      prevPage: 'Página anterior',
      nextPage: 'Página siguiente',
      pageOverview: 'Vista de páginas',
      openPageOverview: 'Abrir la vista de páginas',
      closeOverview: 'Cerrar la vista',
      removePage: 'Eliminar página',
      emptyPage: 'Página vacía',
      movePageLeft: 'Mover a la izquierda',
      movePageRight: 'Mover a la derecha',
      pageCounter: 'Página {{current}} de {{total}}',
      noLayer: 'No hay elementos en el lienzo',
      noSnapshot: 'Aún no hay instantáneas guardadas',
      saveSnapshot: 'Guardar',
      snapshotName: 'Nombre de instantánea',
      restore: 'Restaurar',
      toggleVisible: 'Mostrar / Ocultar',
      toggleLock: 'Bloquear / Desbloquear',
      renameHint: 'Doble clic para renombrar',
      alignTop: 'Alinear arriba',
      alignMiddle: 'Alinear al centro',
      alignBottom: 'Alinear abajo',
      distributeH: 'Distribuir horizontalmente',
      distributeV: 'Distribuir verticalmente',
      uniformSize: 'Mismo tamaño',
      arrangePanel: 'Organizar',
      arrangeScope: 'Alinear a',
      scopeSelection: 'Selección',
      scopeCanvas: 'Lienzo',
      scopePage: 'Página',
      distributeSpacing: 'Espaciado igual',
      distributeEdges: 'Ajustar a los bordes',
      snapSelectionToGrid: 'Alinear a la cuadrícula',
      closeDialog: 'Cerrar',
      contextMenu: 'Menú contextual',
      switchShape: 'Cambiar forma',
      paste: 'Pegar',
      selectAll: 'Seleccionar todo',
      deselect: 'Anular selección',
      geometry: 'Geometría',
      posX: 'X',
      posY: 'Y',
      geoWidth: 'Ancho',
      geoHeight: 'Alto',
      layerFront: 'Traer al frente',
      layerForward: 'Acercar',
      layerBackward: 'Alejar',
      layerBack: 'Enviar atrás',
      group: 'Agrupar',
      ungroup: 'Desagrupar',
      edgeStyle: 'Estilo de enlace',
      edgeType: 'Tipo de línea',
      edgeDash: 'Trazo',
      edgeStartArrow: 'Inicio',
      edgeEndArrow: 'Fin',
      straight: 'Línea recta',
      bezier: 'Bézier',
      smoothstep: 'Esquina redondeada',
      step: 'Esquina recta',
      solid: 'Sólida',
      dashed: 'Guionada',
      dotted: 'Punteada',
      arrowNone: 'Ninguna',
      arrowArrow: 'Flecha',
      arrowCircle: 'Círculo',
      arrowTriangle: 'Triángulo hueco',
      arrowDiamondHollow: 'Rombo hueco',
      templateUmlUseCase: 'Diagrama de casos de uso',
      templateUmlClass: 'Diagrama de clases',
      templateUmlSequence: 'Diagrama de secuencia',
      templateUmlActivity: 'Diagrama de actividad',
      templateUmlState: 'Diagrama de estados',
      templateBpmnProcess: 'Proceso de negocio',
      templateNetTopology: 'Topología de red',
      templateOrgChart: 'Organigrama',
      templateMindMap: 'Mapa mental',
      templateErDiagram: 'Diagrama ER',
      templateApproval: 'Flujo de aprobación',
      templateOnboarding: 'Proceso de incorporación',
      templateSwimlane2: 'Flujo de dos carriles',
      templateUmlComponent: 'Diagrama de componentes',
      templateBpmnCollab: 'Flujo colaborativo',
      templateNetSubnet: 'Topología de subred',
      theme: 'Tema',
      themeDefault: 'Predeterminado',
      themeBusiness: 'Empresa',
      themeMinimal: 'Minimalista',
      themeDark: 'Oscuro',
      applyThemeAll: 'Aplicar a todo',
      applyThemeSelection: 'Aplicar a la selección',
      formatBrush: 'Copiar estilo',
      applyStyle: 'Pegar estilo',
      exportPrintPdf: 'Imprimir PDF paginado',
      printLandscape: 'Impresión horizontal',
      shapeParams: 'Parámetros de forma',
      shapeParamHint: 'Arrastra el tirador ámbar o ajusta con el control / campo',
      reset: 'Restablecer',
      shapeParam: {
        cornerRadius: 'Radio de esquina',
        foldSize: 'Tamaño del pliegue',
        skew: 'Inclinación',
        inset: 'Sangría',
        capHeight: 'Altura de tapa',
        waveHeight: 'Altura de onda',
        chevronDepth: 'Profundidad de flecha',
        barWidth: 'Ancho de barras',
        roofHeight: 'Altura del techo',
        loopNotch: 'Muesca',
        lifelineHeader: 'Altura del encabezado',
        tabHeight: 'Altura de pestaña',
        componentTab: 'Ancho de pestaña',
        partitionHeader: 'Ancho de columna',
        cubeDepth: 'Profundidad',
        starInner: 'Radio interior',
        plusArm: 'Grosor del brazo',
        calloutTail: 'Altura de cola',
        arrowHead: 'Longitud de punta',
        bracketArm: 'Grosor del corchete',
        annotationBracket: 'Ancho del corchete',
        dividerTop: 'Divisor superior',
        dividerBottom: 'Divisor inferior',
        laneHeader: 'Grosor del encabezado',
        activeClassInset: 'Separación de líneas',
        templateTab: 'Altura de pestaña',
      },
      transform: 'Transformación',
      rotation: 'Rotación',
      rotationValue: 'Ángulo',
      rotateHint: 'Arrastra para rotar (15° con imán, Shift 45°, Alt libre)',
      rotateCw: 'Rotar 90° en sentido horario',
      rotateCcw: 'Rotar 90° en sentido antihorario',
      flipH: 'Voltear horizontal',
      flipV: 'Voltear vertical',
      collapseContainer: 'Contraer contenedor',
      expandContainer: 'Expandir contenedor',
      textLayout: 'Diseño del texto',
      verticalAlign: 'Alineación vertical',
      lineHeight: 'Altura de línea',
      autoShrink: 'Ajustar el texto automáticamente',
      labelBackground: 'Fondo de la etiqueta',
      link: 'Hipervínculo',
      linkInvalid: 'Solo se permiten http / https / mailto',
      edgeSourceLabel: 'Etiqueta de origen',
      edgeTargetLabel: 'Etiqueta de destino',
      edgeLabelPosition: 'Posición de la etiqueta',
      labelPos_center: 'Centrada',
      labelPos_nearSource: 'Cerca del origen',
      labelPos_nearTarget: 'Cerca del destino',
      relationPreset: 'Relación predefinida',
      relationAssociation: 'Asociación',
      relationGeneralization: 'Generalización',
      relationRealization: 'Realización',
      relationDependency: 'Dependencia',
      relationAggregation: 'Agregación',
      relationComposition: 'Composición',
      edgeJump: 'Salto de línea',
      jump_none: 'Sin salto',
      jump_arc: 'Salto en arco',
      pasteFailed: 'No se reconoce el contenido draw.io del portapapeles',
      cut: 'Cortar',
      copy: 'Copiar',
      editText: 'Editar texto',
      container: 'Contenedor',
      duplicatePage: 'Duplicar página',
      pageCopySuffix: 'copia',
      paperSize: 'Papel',
      paper_none: 'Sin borde',
      paper_a4l: 'A4 horizontal',
      paper_a4p: 'A4 vertical',
      paper_a3l: 'A3 horizontal',
      paper_letterl: 'Letter horizontal',
      paper_letterp: 'Letter vertical',
      paper_custom: 'Personalizado',
      wheelMode: 'Rueda',
      wheel_pan: 'La rueda desplaza',
      wheel_zoom: 'La rueda amplía',
      gridStyle: 'Cuadrícula',
      grid_dots: 'Puntos',
      grid_lines: 'Líneas',
      grid_cross: 'Cruces',
      grid_none: 'Sin cuadrícula',
      canvasBackground: 'Fondo',
      bgTransparent: 'Transparente',
      rulers: 'Reglas',
      shortcutHelp: 'Atajos de teclado',
      searchNodes: 'Buscar',
      searchNodesPlaceholder: 'Buscar nodos por texto…',
      searchNoResult: 'Sin nodos coincidentes',
      scGroupEdit: 'Edición',
      scGroupArrange: 'Alinear y transformar',
      scGroupCanvas: 'Lienzo y ayuda',
      scUndo: 'Deshacer',
      scRedo: 'Rehacer',
      scClipboard: 'Cortar / copiar / pegar',
      scDuplicate: 'Duplicar',
      scSelectAll: 'Seleccionar todo',
      scDelete: 'Eliminar selección',
      scSave: 'Guardar borrador',
      scTextNewline: 'Nueva línea al editar texto',
      scTextCommit: 'Confirmar edición de texto',
      scRotateCw: 'Rotar 90° horario',
      scRotateCcw: 'Rotar 90° antihorario',
      scFlipH: 'Voltear horizontal',
      scFlipV: 'Voltear vertical',
      scGroup: 'Agrupar / desagrupar',
      scNudge: 'Mover poco a poco (⇧ para 10px)',
      scSpawnRight: 'Crear nodo conectado a la derecha',
      scSpawnDown: 'Crear nodo conectado debajo',
      scRename: 'Renombrar selección',
      scDeselect: 'Deseleccionar',
      scSwitchPage: 'Página anterior / siguiente',
      scPan: 'Desplazar el lienzo',
      scZoom: 'Ampliar el lienzo',
      scHandles: 'Ajustar forma / rotar',
      scEditLabel: 'Editar etiqueta en el sitio',
      scHelp: 'Abrir esta ayuda',
      err: {
        EMPTY: 'El lienzo está vacío',
        EXPORT_FAILED: 'Error al exportar',
        IMPORT_FAILED: 'Error al importar: formato de archivo no reconocido',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: 'Proceso',
  roundRect: 'Rectángulo redondeado',
  ellipse: 'Elipse',
  diamond: 'Rombo',
  parallelogram: 'Paralelogramo',
  trapezoid: 'Trapecio',
  hexagon: 'Hexágono',
  cylinder: 'Cilindro',
  note: 'Nota',
  startEnd: 'Inicio / Fin',
  decision: 'Decisión',
  data: 'Datos',
  document: 'Documento',
  predefined: 'Proceso predefinido',
  manualInput: 'Entrada manual',
  manualOperation: 'Operación manual',
  preparation: 'Preparación',
  database: 'Base de datos',
  display: 'Visualización',
  onPageConnector: 'Conector misma página',
  offPageConnector: 'Conector otra página',
  terminator: 'Terminador',
  parallelMode: 'Modo paralelo',
  loopLimit: 'Límite de bucle',
  umlActor: 'Actor',
  umlNote: 'Nota',
  umlBoundary: 'Frontera',
  umlControl: 'Control',
  umlEntity: 'Entidad',
  umlFrame: 'Marco',
  umlUseCase: 'Caso de uso',
  umlSubject: 'Sujeto',
  umlInclude: 'Inclusión',
  umlExtend: 'Extensión',
  umlExtensionPoint: 'Punto de extensión',
  umlClass: 'Clase',
  umlInterface: 'Interfaz',
  umlEnumeration: 'Enumeración',
  umlDataType: 'Tipo de dato',
  umlAbstractClass: 'Clase abstracta',
  umlActiveClass: 'Clase activa',
  umlTemplateClass: 'Clase plantilla',
  umlAssociationClass: 'Clase de asociación',
  umlPackage: 'Paquete',
  umlObject: 'Objeto',
  umlObjectSlot: 'Objeto (ranuras)',
  umlModel: 'Modelo',
  umlProfile: 'Perfil',
  umlLifeline: 'Línea de vida',
  umlActivation: 'Activación',
  umlDestroy: 'Destrucción',
  umlCombinedFragment: 'Fragmento combinado',
  umlInteractionUse: 'Uso de interacción',
  umlStateInvariant: 'Invariante de estado',
  umlGate: 'Puerta',
  umlForkJoin: 'Bifurcación / Unión',
  umlAction: 'Acción',
  umlActivity: 'Actividad',
  umlDecisionMerge: 'Decisión / Fusión',
  umlInitialNode: 'Nodo inicial',
  umlActivityFinal: 'Fin de actividad',
  umlFlowFinal: 'Fin de flujo',
  umlObjectNode: 'Nodo de objeto',
  umlSendSignal: 'Enviar señal',
  umlReceiveSignal: 'Recibir señal',
  umlActivityPartition: 'Partición de actividad',
  umlState: 'Estado',
  umlStateInitial: 'Estado inicial',
  umlStateFinal: 'Estado final',
  umlChoice: 'Elección',
  umlJunction: 'Unión',
  umlTerminate: 'Terminar',
  umlEntryPoint: 'Punto de entrada',
  umlExitPoint: 'Punto de salida',
  umlHistory: 'Historial superficial',
  umlHistoryDeep: 'Historial profundo',
  umlCompositeState: 'Estado compuesto',
  umlComponent: 'Componente',
  umlProvidedInterface: 'Interfaz provista',
  umlRequiredInterface: 'Interfaz requerida',
  umlPort: 'Puerto',
  umlSubsystem: 'Subsistema',
  umlNode: 'Nodo',
  umlDevice: 'Dispositivo',
  umlExecutionEnvironment: 'Entorno de ejecución',
  umlArtifact: 'Artefacto',
  umlDeploymentSpec: 'Especificación de despliegue',
  bpmnEventStart: 'Evento de inicio',
  bpmnEventIntermediate: 'Evento intermedio',
  bpmnEventEnd: 'Evento final',
  bpmnGatewayExclusive: 'Compuerta exclusiva',
  bpmnGatewayParallel: 'Compuerta paralela',
  bpmnGatewayInclusive: 'Compuerta inclusiva',
  bpmnTask: 'Tarea',
  bpmnSubProcess: 'Subproceso',
  bpmnCallActivity: 'Actividad de llamada',
  bpmnDataObject: 'Objeto de datos',
  bpmnDataStore: 'Almacén de datos',
  bpmnTextAnnotation: 'Anotación de texto',
  netServer: 'Servidor',
  netClient: 'Cliente',
  netRouter: 'Enrutador',
  netSwitch: 'Conmutador',
  netFirewall: 'Cortafuegos',
  netLoadBalancer: 'Balanceador de carga',
  netCloud: 'Nube',
  netCdn: 'CDN',
  netDatabase: 'Base de datos',
  netStorage: 'Almacenamiento',
  orgUnit: 'Unidad',
  orgAssistant: 'Asistente',
  orgTeam: 'Equipo',
  mindCenter: 'Tema central',
  mindTopic: 'Tema',
  mindSub: 'Subtema',
  erEntity: 'Entidad',
  erAttribute: 'Atributo',
  erRelationship: 'Relación',
  erWeakEntity: 'Entidad débil',
  swimlane: 'Carril horizontal',
  swimlaneV: 'Carril vertical',
  group: 'Grupo',
  triangle: 'Triángulo',
  star: 'Estrella',
  pentagon: 'Pentágono',
  octagon: 'Octágono',
  chevron: 'Cheurón',
  card: 'Tarjeta',
  callout: 'Globo',
  cloud: 'Nube',
  cross: 'Cruz',
  plus: 'Más',
  flag: 'Bandera',
  lightning: 'Rayo',
  arrow: 'Flecha',
  bracket: 'Corchete',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
