/**
 * fr 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nouveau canevas',
      docTitle: 'Titre du diagramme',
      present: 'Présenter',
      exitPresent: 'Quitter (Échap)',
      presentLoading: 'Préparation du diaporama…',
      presentFailed: 'Échec de la préparation du diaporama',
      titlePlaceholder: 'Diagramme sans titre',
      clear: 'Effacer',
      exportPng: 'Exporter PNG',
      exportSvg: 'Exporter SVG',
      templates: 'Modèles',
      autoLayout: 'Disposition auto',
      fitView: 'Ajuster à l’écran',
      zoomActual: 'Taille réelle',
      undo: 'Annuler',
      redo: 'Rétablir',
      duplicate: 'Dupliquer',
      delete: 'Supprimer',
      panelTitle: 'Propriétés',
      paletteTitle: 'Formes',
      searchShape: 'Rechercher une forme',
      noShape: 'Aucune forme correspondante',
      resizeSidebar: 'Glissez pour redimensionner le panneau',
      cat_general: 'Général',
      cat_flow: 'Diagramme',
      cat_uml: 'UML',
      cat_umlCommon: 'UML commun',
      cat_umlUseCase: "UML cas d'utilisation",
      cat_umlClass: 'UML classes',
      cat_umlObject: 'UML objets/paquetages',
      cat_umlSequence: 'UML séquence',
      cat_umlActivity: 'UML activité',
      cat_umlState: 'UML états',
      cat_umlComponent: 'UML composants',
      cat_umlDeployment: 'UML déploiement',
      cat_bpmn: 'BPMN',
      cat_network: 'Réseau & Cloud',
      cat_org: 'Organisation',
      cat_mind: 'Carte mentale',
      cat_er: 'Diagramme ER',
      groupBasic: 'Formes de base',
      groupFlow: 'Symboles de flux',
      groupBpmn: 'Lignes de nage et BPMN',
      shape_rect: 'Processus',
      shape_startEnd: 'Début / Fin',
      shape_decision: 'Décision',
      shape_data: 'Données',
      shape_swimlane: 'Ligne de nage horizontale',
      shape_swimlaneV: 'Ligne de nage verticale',
      shape_bpmnTask: 'Tâche BPMN',
      canvasAria: 'Canevas de diagramme',
      emptyHint: 'Glissez une forme depuis la gauche ou choisissez un modèle',
      nodesLabel: 'Nœuds',
      edgesLabel: 'Liens',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement auto après la saisie',
      noSelection: 'Aucun élément sélectionné',
      selected: '{{count}} éléments sélectionnés',
      fill: 'Remplissage',
      stroke: 'Contour',
      strokeWidth: 'Épaisseur',
      fontSize: 'Taille',
      bold: 'Gras',
      italic: 'Italique',
      align: 'Alignement',
      alignLeft: 'Gauche',
      alignCenter: 'Centre',
      alignRight: 'Droite',
      label: 'Texte',
      edgeLabel: 'Libellé du lien',
      templateTitle: 'Choisir un modèle',
      templateBasic: 'Flux de base',
      templateDecision: 'Flux conditionnel',
      templateSwimlane: 'Flux en lignes horizontales',
      templateSwimlaneV: 'Flux en lignes verticales',
      templateBpmn: 'Squelette BPMN',
      templateHint: 'Charger un modèle remplace le canevas actuel',
      exportPanel: 'Exporter',
      importFile: 'Importer',
      scale: 'Échelle',
      transparentBg: 'Transparent',
      onlySelected: 'Sélection uniquement',
      padding: 'Marge',
      exportRange: 'Étendue',
      rangeCurrent: 'Page actuelle',
      rangeAll: 'Toutes les pages',
      exporting: 'Export en cours…',
      snapToGrid: 'Aligner sur la grille',
      gridSize: 'Grille',
      layoutDirection: 'Direction de disposition',
      layoutDensity: 'Espacement',
      densityCompact: 'Compact',
      densityNormal: 'Normal',
      densityLoose: 'Ample',
      alignTolerance: 'Seuil d’alignement',
      dirTB: 'De haut en bas',
      dirBT: 'De bas en haut',
      dirLR: 'De gauche à droite',
      dirRL: 'De droite à gauche',
      mixed: 'Mixte',
      nodesSelected: '{{count}} nœuds sélectionnés',
      importHint: 'Prend en charge .flow.json / .drawio / .mmd',
      waypoints: 'Points de passage',
      waypoint: 'Point de passage',
      waypointCount: '{{count}}',
      waypointHint:
        'Faites glisser les carrés orange pour déplacer un point, double-cliquez pour le supprimer ; cliquez un point bleu pour en insérer un.',
      autoRoute: 'Routage orthogonal',
      clearWaypoints: 'Supprimer les points',
      addWaypoint: 'Insérer un point',
      removeWaypoint: 'Supprimer le point',
      searchLayer: 'Rechercher des calques',
      moveOut: 'Retirer du conteneur',
      dropToRoot: 'Déposer ici pour sortir du conteneur',
      insertImage: 'Insérer une image',
      insertIcon: 'Insérer une icône',
      insertFormula: 'Insérer une formule',
      formula: 'Formule',
      imageFailed: 'Échec de lecture de l’image',
      draftTooLarge:
        'Brouillon trop volumineux : les images n’ont pas été enregistrées. Utilisez « Exporter le projet ».',
      iconGroup_general: 'Général',
      iconGroup_office: 'Bureautique',
      iconGroup_tech: 'Technique',
      iconGroup_people: 'Équipe',
      quickConnect: 'Connexion rapide',
      reconnectSource: 'Reconnecter le début',
      reconnectTarget: 'Reconnecter la fin',
      defaultPageName: 'Page {{n}}',
      layers: 'Calques',
      history: 'Historique',
      addPage: 'Nouvelle page',
      prevPage: 'Page précédente',
      nextPage: 'Page suivante',
      pageOverview: 'Aperçu des pages',
      openPageOverview: 'Ouvrir l’aperçu des pages',
      closeOverview: 'Fermer l’aperçu',
      removePage: 'Supprimer la page',
      emptyPage: 'Page vide',
      movePageLeft: 'Déplacer à gauche',
      movePageRight: 'Déplacer à droite',
      pageCounter: 'Page {{current}} sur {{total}}',
      noLayer: 'Aucun élément sur le canevas',
      noSnapshot: 'Aucun instantané enregistré',
      saveSnapshot: 'Enregistrer',
      snapshotName: "Nom de l'instantané",
      restore: 'Restaurer',
      toggleVisible: 'Afficher / Masquer',
      toggleLock: 'Verrouiller / Déverrouiller',
      renameHint: 'Double-cliquez pour renommer',
      alignTop: 'Aligner en haut',
      alignMiddle: 'Aligner au centre',
      alignBottom: 'Aligner en bas',
      distributeH: 'Distribuer horizontalement',
      distributeV: 'Distribuer verticalement',
      uniformSize: 'Même taille',
      snapSelectionToGrid: 'Aligner sur la grille',
      closeDialog: 'Fermer',
      contextMenu: 'Menu contextuel',
      switchShape: 'Changer la forme',
      paste: 'Coller',
      selectAll: 'Tout sélectionner',
      deselect: 'Annuler la sélection',
      geometry: 'Géométrie',
      posX: 'X',
      posY: 'Y',
      geoWidth: 'Largeur',
      geoHeight: 'Hauteur',
      layerFront: 'Mettre au premier plan',
      layerForward: 'Avancer',
      layerBackward: 'Reculer',
      layerBack: 'Mettre en arrière-plan',
      group: 'Grouper',
      ungroup: 'Dissocier',
      edgeStyle: 'Style du lien',
      edgeType: 'Type de ligne',
      edgeDash: 'Trait',
      edgeStartArrow: 'Début',
      edgeEndArrow: 'Fin',
      straight: 'Ligne droite',
      bezier: 'Bézier',
      smoothstep: 'Ligne brisée arrondie',
      step: 'Ligne brisée à angle droit',
      solid: 'Pleine',
      dashed: 'Tirets',
      dotted: 'Pointillés',
      arrowNone: 'Aucune',
      arrowArrow: 'Flèche',
      arrowCircle: 'Rond',
      arrowTriangle: 'Triangle vide',
      arrowDiamondHollow: 'Losange vide',
      templateUmlUseCase: 'Diagramme de cas d’usage',
      templateUmlClass: 'Diagramme de classes',
      templateUmlSequence: 'Diagramme de séquence',
      templateUmlActivity: 'Diagramme d’activité',
      templateUmlState: 'Diagramme d’états',
      templateBpmnProcess: 'Processus métier',
      templateNetTopology: 'Topologie réseau',
      templateOrgChart: 'Organigramme',
      templateMindMap: 'Carte mentale',
      templateErDiagram: 'Diagramme ER',
      templateApproval: 'Processus d’approbation',
      templateOnboarding: 'Parcours d’intégration',
      templateSwimlane2: 'Processus à deux couloirs',
      templateUmlComponent: 'Diagramme de composants',
      templateBpmnCollab: 'Processus collaboratif',
      templateNetSubnet: 'Topologie de sous-réseau',
      theme: 'Thème',
      themeDefault: 'Par défaut',
      themeBusiness: 'Business',
      themeMinimal: 'Minimal',
      themeDark: 'Sombre',
      applyThemeAll: 'Appliquer à tout',
      applyThemeSelection: 'Appliquer à la sélection',
      formatBrush: 'Copier le style',
      applyStyle: 'Coller le style',
      exportPrintPdf: 'Impression paginée PDF',
      printLandscape: 'Impression paysage',
      shapeParams: 'Paramètres de forme',
      shapeParamHint: 'Faites glisser la poignée ambre ou réglez avec le curseur / le champ',
      reset: 'Réinitialiser',
      shapeParam: {
        cornerRadius: 'Rayon des coins',
        foldSize: 'Taille du pli',
        skew: 'Inclinaison',
        inset: 'Retrait',
        capHeight: 'Hauteur du chapeau',
        waveHeight: 'Hauteur de vague',
        chevronDepth: 'Profondeur du chevron',
        barWidth: 'Largeur des barres',
        roofHeight: 'Hauteur du toit',
        loopNotch: 'Encoche',
        lifelineHeader: 'Hauteur de l’en-tête',
        tabHeight: 'Hauteur de l’onglet',
        componentTab: 'Largeur de l’onglet',
        partitionHeader: 'Largeur de colonne',
        cubeDepth: 'Profondeur',
        starInner: 'Rayon interne',
        plusArm: 'Épaisseur du bras',
        calloutTail: 'Hauteur de la queue',
        arrowHead: 'Longueur de la pointe',
        bracketArm: 'Épaisseur du crochet',
        annotationBracket: 'Largeur du crochet',
        dividerTop: 'Séparateur haut',
        dividerBottom: 'Séparateur bas',
        laneHeader: 'Épaisseur de l’en-tête',
        activeClassInset: 'Écart des doubles lignes',
        templateTab: 'Hauteur de l’onglet',
      },
      err: {
        EMPTY: 'Le canevas est vide',
        EXPORT_FAILED: "Échec de l'export",
        IMPORT_FAILED: 'Échec de l’import : format de fichier non reconnu',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: 'Processus',
  roundRect: 'Rectangle arrondi',
  ellipse: 'Ellipse',
  diamond: 'Losange',
  parallelogram: 'Parallélogramme',
  trapezoid: 'Trapèze',
  hexagon: 'Hexagone',
  cylinder: 'Cylindre',
  note: 'Note',
  startEnd: 'Début / Fin',
  decision: 'Décision',
  data: 'Données',
  document: 'Document',
  predefined: 'Processus prédéfini',
  manualInput: 'Saisie manuelle',
  manualOperation: 'Opération manuelle',
  preparation: 'Préparation',
  database: 'Base de données',
  display: 'Affichage',
  onPageConnector: 'Connecteur même page',
  offPageConnector: 'Connecteur hors page',
  terminator: 'Terminateur',
  parallelMode: 'Mode parallèle',
  loopLimit: 'Limite de boucle',
  umlActor: 'Acteur',
  umlNote: 'Note',
  umlBoundary: 'Frontière',
  umlControl: 'Contrôle',
  umlEntity: 'Entité',
  umlFrame: 'Cadre',
  umlUseCase: "Cas d'utilisation",
  umlSubject: 'Sujet',
  umlInclude: 'Inclusion',
  umlExtend: 'Extension',
  umlExtensionPoint: "Point d'extension",
  umlClass: 'Classe',
  umlInterface: 'Interface',
  umlEnumeration: 'Énumération',
  umlDataType: 'Type de données',
  umlAbstractClass: 'Classe abstraite',
  umlActiveClass: 'Classe active',
  umlTemplateClass: 'Classe de modèle',
  umlAssociationClass: "Classe d'association",
  umlPackage: 'Paquet',
  umlObject: 'Objet',
  umlObjectSlot: 'Objet (emplacements)',
  umlModel: 'Modèle',
  umlProfile: 'Profil',
  umlLifeline: 'Ligne de vie',
  umlActivation: 'Activation',
  umlDestroy: 'Destruction',
  umlCombinedFragment: 'Fragment combiné',
  umlInteractionUse: "Utilisation d'interaction",
  umlStateInvariant: "Invariant d'état",
  umlGate: 'Porte',
  umlForkJoin: 'Embranchement / Jonction',
  umlAction: 'Action',
  umlActivity: 'Activité',
  umlDecisionMerge: 'Décision / Fusion',
  umlInitialNode: 'Nœud initial',
  umlActivityFinal: "Fin d'activité",
  umlFlowFinal: 'Fin de flux',
  umlObjectNode: "Nœud d'objet",
  umlSendSignal: 'Envoi de signal',
  umlReceiveSignal: 'Réception de signal',
  umlActivityPartition: "Partition d'activité",
  umlState: 'État',
  umlStateInitial: 'État initial',
  umlStateFinal: 'État final',
  umlChoice: 'Choix',
  umlJunction: 'Jonction',
  umlTerminate: 'Terminer',
  umlEntryPoint: "Point d'entrée",
  umlExitPoint: 'Point de sortie',
  umlHistory: 'Historique superficiel',
  umlHistoryDeep: 'Historique profond',
  umlCompositeState: 'État composite',
  umlComponent: 'Composant',
  umlProvidedInterface: 'Interface fournie',
  umlRequiredInterface: 'Interface requise',
  umlPort: 'Port',
  umlSubsystem: 'Sous-système',
  umlNode: 'Nœud',
  umlDevice: 'Dispositif',
  umlExecutionEnvironment: "Environnement d'exécution",
  umlArtifact: 'Artefact',
  umlDeploymentSpec: 'Spécification de déploiement',
  bpmnEventStart: 'Événement de début',
  bpmnEventIntermediate: 'Événement intermédiaire',
  bpmnEventEnd: 'Événement de fin',
  bpmnGatewayExclusive: 'Passerelle exclusive',
  bpmnGatewayParallel: 'Passerelle parallèle',
  bpmnGatewayInclusive: 'Passerelle inclusive',
  bpmnTask: 'Tâche',
  bpmnSubProcess: 'Sous-processus',
  bpmnCallActivity: 'Activité appelante',
  bpmnDataObject: 'Objet de données',
  bpmnDataStore: 'Magasin de données',
  bpmnTextAnnotation: 'Annotation de texte',
  netServer: 'Serveur',
  netClient: 'Client',
  netRouter: 'Routeur',
  netSwitch: 'Commutateur',
  netFirewall: 'Pare-feu',
  netLoadBalancer: 'Répartiteur de charge',
  netCloud: 'Cloud',
  netCdn: 'CDN',
  netDatabase: 'Base de données',
  netStorage: 'Stockage',
  orgUnit: 'Unité',
  orgAssistant: 'Assistant',
  orgTeam: 'Équipe',
  mindCenter: 'Sujet central',
  mindTopic: 'Sujet',
  mindSub: 'Sous-sujet',
  erEntity: 'Entité',
  erAttribute: 'Attribut',
  erRelationship: 'Relation',
  erWeakEntity: 'Entité faible',
  swimlane: 'Ligne horizontale',
  swimlaneV: 'Ligne verticale',
  group: 'Groupe',
  triangle: 'Triangle',
  star: 'Étoile',
  pentagon: 'Pentagone',
  octagon: 'Octogone',
  chevron: 'Chevron',
  card: 'Carte',
  callout: 'Annotation',
  cloud: 'Nuage',
  cross: 'Croix',
  plus: 'Plus',
  flag: 'Drapeau',
  lightning: 'Éclair',
  arrow: 'Flèche',
  bracket: 'Crochet',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
