/**
 * it 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nuova tela',
      docTitle: 'Titolo del diagramma',
      present: 'Presenta',
      exitPresent: 'Esci (Esc)',
      presentLoading: 'Preparazione della presentazione…',
      presentFailed: 'Impossibile preparare la presentazione',
      titlePlaceholder: 'Diagramma senza titolo',
      clear: 'Pulisci',
      exportPng: 'Esporta PNG',
      exportSvg: 'Esporta SVG',
      templates: 'Modelli',
      autoLayout: 'Disposizione auto',
      fitView: 'Adatta alla schermo',
      zoomActual: 'Dimensione reale',
      undo: 'Annulla',
      redo: 'Ripeti',
      duplicate: 'Duplica',
      delete: 'Elimina',
      panelTitle: 'Proprietà',
      paletteTitle: 'Forme',
      searchShape: 'Cerca forma',
      noShape: 'Nessuna forma corrispondente',
      resizeSidebar: 'Trascina per ridimensionare il pannello',
      cat_general: 'Generale',
      cat_flow: 'Diagramma di flusso',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Rete & Cloud',
      cat_org: 'Organizzazione',
      cat_mind: 'Mappa mentale',
      cat_er: 'Diagramma ER',
      groupBasic: 'Forme base',
      groupFlow: 'Simboli di flusso',
      groupBpmn: 'Swimlane e BPMN',
      shape_rect: 'Processo',
      shape_startEnd: 'Inizio / Fine',
      shape_decision: 'Decisione',
      shape_data: 'Dati',
      shape_swimlane: 'Swimlane orizzontale',
      shape_swimlaneV: 'Swimlane verticale',
      shape_bpmnTask: 'Attività BPMN',
      canvasAria: 'Tela del diagramma',
      emptyHint: 'Trascina una forma da sinistra o scegli un modello',
      nodesLabel: 'Nodi',
      edgesLabel: 'Collegamenti',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la modifica',
      noSelection: 'Nessun elemento selezionato',
      selected: '{{count}} elementi selezionati',
      fill: 'Riempimento',
      stroke: 'Contorno',
      strokeWidth: 'Spessore',
      fontSize: 'Dimensione',
      bold: 'Grassetto',
      italic: 'Corsivo',
      align: 'Allineamento',
      alignLeft: 'Sinistra',
      alignCenter: 'Centro',
      alignRight: 'Destra',
      label: 'Testo',
      edgeLabel: 'Etichetta collegamento',
      templateTitle: 'Scegli un modello',
      templateBasic: 'Flusso base',
      templateDecision: 'Flusso decisionale',
      templateSwimlane: 'Flusso swimlane orizzontale',
      templateSwimlaneV: 'Flusso swimlane verticale',
      templateBpmn: 'Scheletro BPMN',
      templateHint: 'Caricare un modello sostituisce la tela corrente',
      exportPanel: 'Esporta',
      importFile: 'Importa',
      scale: 'Scala',
      transparentBg: 'Trasparente',
      onlySelected: 'Solo selezione',
      padding: 'Margine',
      exportRange: 'Intervallo',
      rangeCurrent: 'Pagina corrente',
      rangeAll: 'Tutte le pagine',
      exporting: 'Esportazione…',
      snapToGrid: 'Aggancia alla griglia',
      gridSize: 'Griglia',
      layoutDirection: 'Direzione layout',
      layoutDensity: 'Spaziatura',
      densityCompact: 'Compatto',
      densityNormal: 'Normale',
      densityLoose: 'Ampio',
      alignTolerance: 'Soglia di allineamento',
      dirTB: 'Dall’alto verso il basso',
      dirBT: 'Dal basso verso l’alto',
      dirLR: 'Da sinistra a destra',
      dirRL: 'Da destra a sinistra',
      mixed: 'Misto',
      nodesSelected: '{{count}} nodi selezionati',
      importHint: 'Supporta .flow.json / .drawio / .mmd',
      waypoints: 'Punti di passaggio',
      waypoint: 'Punto di passaggio',
      waypointCount: '{{count}}',
      waypointHint:
        'Trascina i quadrati arancioni per spostare un punto, doppio clic per eliminarlo; clicca un punto blu per inserirne uno.',
      autoRoute: 'Instradamento ortogonale',
      clearWaypoints: 'Rimuovi punti',
      addWaypoint: 'Inserisci punto',
      removeWaypoint: 'Elimina punto',
      searchLayer: 'Cerca livelli',
      moveOut: 'Rimuovi dal contenitore',
      dropToRoot: 'Rilascia qui per uscire dal contenitore',
      insertImage: 'Inserisci immagine',
      insertIcon: 'Inserisci icona',
      insertFormula: 'Inserisci formula',
      formula: 'Formula',
      imageFailed: 'Impossibile leggere l’immagine',
      draftTooLarge:
        'Bozza troppo grande: le immagini non sono state salvate. Usa «Esporta progetto».',
      iconGroup_general: 'Generale',
      iconGroup_office: 'Ufficio',
      iconGroup_tech: 'Tecnologia',
      iconGroup_people: 'Persone',
      quickConnect: 'Connessione rapida',
      reconnectSource: 'Ricollega inizio',
      reconnectTarget: 'Ricollega fine',
      defaultPageName: 'Pagina {{n}}',
      layers: 'Livelli',
      history: 'Cronologia',
      addPage: 'Nuova pagina',
      prevPage: 'Pagina precedente',
      nextPage: 'Pagina successiva',
      pageOverview: 'Panoramica pagine',
      openPageOverview: 'Apri la panoramica',
      closeOverview: 'Chiudi la panoramica',
      removePage: 'Elimina pagina',
      emptyPage: 'Pagina vuota',
      movePageLeft: 'Sposta a sinistra',
      movePageRight: 'Sposta a destra',
      pageCounter: 'Pagina {{current}} di {{total}}',
      noLayer: 'Nessun elemento sulla tela',
      noSnapshot: 'Nessuno snapshot salvato',
      saveSnapshot: 'Salva',
      snapshotName: 'Nome snapshot',
      restore: 'Ripristina',
      toggleVisible: 'Mostra / Nascondi',
      toggleLock: 'Blocca / Sblocca',
      renameHint: 'Doppio clic per rinominare',
      alignTop: 'Allinea in alto',
      alignMiddle: 'Allinea al centro',
      alignBottom: 'Allinea in basso',
      distributeH: 'Distribuisci orizzontalmente',
      distributeV: 'Distribuisci verticalmente',
      uniformSize: 'Stessa dimensione',
      snapSelectionToGrid: 'Allinea alla griglia',
      closeDialog: 'Chiudi',
      contextMenu: 'Menu contestuale',
      switchShape: 'Cambia forma',
      paste: 'Incolla',
      selectAll: 'Seleziona tutto',
      deselect: 'Deseleziona',
      geometry: 'Geometria',
      posX: 'X',
      posY: 'Y',
      geoWidth: 'Larghezza',
      geoHeight: 'Altezza',
      layerFront: 'Porta in primo piano',
      layerForward: 'Porta avanti',
      layerBackward: 'Porta indietro',
      layerBack: 'Porta in secondo piano',
      group: 'Raggruppa',
      ungroup: 'Separa gruppo',
      edgeStyle: 'Stile collegamento',
      edgeType: 'Tipo di linea',
      edgeDash: 'Tratto',
      edgeStartArrow: 'Inizio',
      edgeEndArrow: 'Fine',
      straight: 'Linea retta',
      bezier: 'Bézier',
      smoothstep: 'Angolo arrotondato',
      step: 'Angolo retto',
      solid: 'Piena',
      dashed: 'Tratteggiata',
      dotted: 'Punteggiata',
      arrowNone: 'Nessuna',
      arrowArrow: 'Freccia',
      arrowCircle: 'Cerchio',
      templateUmlUseCase: 'Diagramma dei casi d’uso',
      templateUmlClass: 'Diagramma delle classi',
      templateUmlSequence: 'Diagramma di sequenza',
      templateUmlActivity: 'Diagramma di attività',
      templateUmlState: 'Diagramma di stato',
      templateBpmnProcess: 'Processo aziendale',
      templateNetTopology: 'Topologia di rete',
      templateOrgChart: 'Organigramma',
      templateMindMap: 'Mappa mentale',
      templateErDiagram: 'Diagramma ER',
      templateApproval: 'Processo di approvazione',
      templateOnboarding: 'Percorso di inserimento',
      templateSwimlane2: 'Processo a due corsie',
      templateUmlComponent: 'Diagramma dei componenti',
      templateBpmnCollab: 'Processo collaborativo',
      templateNetSubnet: 'Topologia di sottorete',
      theme: 'Tema',
      themeDefault: 'Predefinito',
      themeBusiness: 'Business',
      themeMinimal: 'Minimal',
      themeDark: 'Scuro',
      applyThemeAll: 'Applica a tutto',
      applyThemeSelection: 'Applica alla selezione',
      formatBrush: 'Copia stile',
      applyStyle: 'Incolla stile',
      exportPrintPdf: 'Stampa PDF paginata',
      printLandscape: 'Stampa orizzontale',
      err: {
        EMPTY: 'La tela è vuota',
        EXPORT_FAILED: 'Esportazione non riuscita',
        IMPORT_FAILED: 'Importazione non riuscita: formato file non riconosciuto',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: 'Processo',
  roundRect: 'Rettangolo arrotondato',
  ellipse: 'Ellisse',
  diamond: 'Diamante',
  parallelogram: 'Parallelogramma',
  trapezoid: 'Trapezio',
  hexagon: 'Esagono',
  cylinder: 'Cilindro',
  note: 'Nota',
  startEnd: 'Inizio / Fine',
  decision: 'Decisione',
  data: 'Dati',
  document: 'Documento',
  predefined: 'Processo predefinito',
  manualInput: 'Inserimento manuale',
  manualOperation: 'Operazione manuale',
  preparation: 'Preparazione',
  database: 'Database',
  display: 'Visualizzazione',
  onPageConnector: 'Connettore stessa pagina',
  offPageConnector: 'Connettore altra pagina',
  terminator: 'Terminatore',
  parallelMode: 'Modalità parallela',
  loopLimit: 'Limite ciclo',
  umlActor: 'Attore',
  umlUseCase: "Caso d'uso",
  umlClass: 'Classe',
  umlInterface: 'Interfaccia',
  umlPackage: 'Pacchetto',
  umlNote: 'Nota',
  umlLifeline: 'Linea di vita',
  umlState: 'Stato',
  umlStateInitial: 'Stato iniziale',
  umlStateFinal: 'Stato finale',
  umlForkJoin: 'Biforcazione / Unione',
  bpmnEventStart: 'Evento di inizio',
  bpmnEventIntermediate: 'Evento intermedio',
  bpmnEventEnd: 'Evento di fine',
  bpmnGatewayExclusive: 'Gateway esclusivo',
  bpmnGatewayParallel: 'Gateway parallelo',
  bpmnGatewayInclusive: 'Gateway inclusivo',
  bpmnTask: 'Attività',
  bpmnSubProcess: 'Sottoprocesso',
  bpmnCallActivity: 'Attività di chiamata',
  bpmnDataObject: 'Oggetto dati',
  bpmnDataStore: 'Archivio dati',
  bpmnTextAnnotation: 'Annotazione di testo',
  netServer: 'Server',
  netClient: 'Client',
  netRouter: 'Router',
  netSwitch: 'Switch',
  netFirewall: 'Firewall',
  netLoadBalancer: 'Bilanciatore di carico',
  netCloud: 'Cloud',
  netCdn: 'CDN',
  netDatabase: 'Database',
  netStorage: 'Archiviazione',
  orgUnit: 'Unità',
  orgAssistant: 'Assistente',
  orgTeam: 'Team',
  mindCenter: 'Argomento centrale',
  mindTopic: 'Argomento',
  mindSub: 'Sotto-argomento',
  erEntity: 'Entità',
  erAttribute: 'Attributo',
  erRelationship: 'Relazione',
  erWeakEntity: 'Entità debole',
  swimlane: 'Corsia orizzontale',
  swimlaneV: 'Corsia verticale',
  group: 'Gruppo',
  triangle: 'Triangolo',
  star: 'Stella',
  pentagon: 'Pentagono',
  octagon: 'Ottagono',
  chevron: 'Chevron',
  card: 'Scheda',
  callout: 'Fumetto',
  cloud: 'Nuvola',
  cross: 'Croce',
  plus: 'Più',
  flag: 'Bandiera',
  lightning: 'Fulmine',
  arrow: 'Freccia',
  bracket: 'Parentesi',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
