/**
 * ja 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新規キャンバス',
      docTitle: 'フローチャートのタイトル',
      present: 'スライドショー',
      exitPresent: '終了（Esc）',
      presentLoading: '表示用の画像を生成中…',
      presentFailed: '表示用の画像の生成に失敗しました',
      titlePlaceholder: '無題のフローチャート',
      clear: 'クリア',
      exportPng: 'PNG 書き出し',
      exportSvg: 'SVG 書き出し',
      templates: 'テンプレート',
      autoLayout: '自動配置',
      fitView: 'キャンバスに合わせる',
      zoomActual: '実際のサイズ',
      undo: '元に戻す',
      redo: 'やり直す',
      duplicate: '複製',
      delete: '削除',
      panelTitle: 'プロパティ',
      paletteTitle: '図形',
      searchShape: '図形を検索',
      noShape: '一致する図形なし',
      resizeSidebar: 'ドラッグでサイドバーの幅を調整',
      cat_general: '基本図形',
      cat_flow: 'フローチャート',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'ネットワークとクラウド',
      cat_org: '組織図',
      cat_mind: 'マインドマップ',
      cat_er: 'ER 図',
      groupBasic: '基本図形',
      groupFlow: 'フロー記号',
      groupBpmn: 'スイムレーンと BPMN',
      shape_rect: '処理',
      shape_startEnd: '開始/終了',
      shape_decision: '判断',
      shape_data: 'データ',
      shape_swimlane: '横スイムレーン',
      shape_swimlaneV: '縦スイムレーン',
      shape_bpmnTask: 'BPMN タスク',
      canvasAria: 'フローチャートキャンバス',
      emptyHint: '左から図形をドラッグするか、テンプレートを選択してください',
      nodesLabel: 'ノード',
      edgesLabel: 'エッジ',
      saved: 'ローカル下書きに保存しました',
      saving: '編集を止めると自動保存します',
      noSelection: '要素が未選択です',
      selected: '{{count}} 個の要素を選択中',
      fill: '塗りつぶし',
      stroke: '枠線',
      strokeWidth: '線の太さ',
      fontSize: '文字サイズ',
      bold: '太字',
      italic: '斜体',
      align: '配置',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      label: 'テキスト',
      edgeLabel: 'エッジラベル',
      templateTitle: 'テンプレートを選択',
      templateBasic: '基本フロー',
      templateDecision: '判断フロー',
      templateSwimlane: '横スイムレーンフロー',
      templateSwimlaneV: '縦スイムレーンフロー',
      templateBpmn: 'BPMN 骨組み',
      templateHint: 'テンプレートを読み込むと現在のキャンバスを置き換えます',
      exportPanel: '書き出し',
      importFile: '読み込み',
      scale: '倍率',
      transparentBg: '透過背景',
      onlySelected: '選択のみ',
      padding: '余白',
      exportRange: '書き出し範囲',
      rangeCurrent: '現在のページ',
      rangeAll: 'すべてのページ',
      exporting: '書き出し中…',
      snapToGrid: 'グリッドに吸着',
      gridSize: 'グリッド',
      layoutDirection: 'レイアウト方向',
      layoutDensity: 'レイアウト間隔',
      densityCompact: 'コンパクト',
      densityNormal: '標準',
      densityLoose: 'ゆったり',
      alignTolerance: '整列しきい値',
      dirTB: '上から下',
      dirBT: '下から上',
      dirLR: '左から右',
      dirRL: '右から左',
      mixed: '混在',
      nodesSelected: '{{count}} 個のノードを選択中',
      importHint: '.flow.json / .drawio / .mmd に対応',
      waypoints: '折れ点',
      waypoint: '折れ点',
      waypointCount: '{{count}} 個',
      waypointHint:
        'オレンジの四角をドラッグして移動、ダブルクリックで削除。青い点をクリックすると挿入できます',
      autoRoute: '直交ルーティング',
      clearWaypoints: '折れ点をすべて削除',
      addWaypoint: '折れ点を挿入',
      removeWaypoint: '折れ点を削除',
      searchLayer: 'レイヤーを検索',
      moveOut: 'コンテナから出す',
      dropToRoot: 'ここにドロップしてコンテナから出す',
      insertImage: '画像を挿入',
      insertIcon: 'アイコンを挿入',
      insertFormula: '数式を挿入',
      formula: '数式',
      imageFailed: '画像を読み込めませんでした',
      draftTooLarge:
        '下書きが大きすぎます。画像は保存されませんでした。「プロジェクトを書き出す」をご利用ください',
      iconGroup_general: '一般',
      iconGroup_office: 'オフィス',
      iconGroup_tech: 'デバイス',
      iconGroup_people: '人物と協働',
      quickConnect: 'クイック接続',
      reconnectSource: '始点を再接続',
      reconnectTarget: '終点を再接続',
      defaultPageName: 'ページ {{n}}',
      layers: 'レイヤー',
      history: '履歴',
      addPage: '新規ページ',
      prevPage: '前のページ',
      nextPage: '次のページ',
      pageOverview: 'ページ一覧',
      openPageOverview: 'ページ一覧を開く',
      closeOverview: '一覧を閉じる',
      removePage: 'ページを削除',
      emptyPage: '空白ページ',
      movePageLeft: '左へ移動',
      movePageRight: '右へ移動',
      pageCounter: '{{current}} / {{total}} ページ',
      noLayer: 'キャンバスに要素がありません',
      noSnapshot: 'スナップショットはまだ保存されていません',
      saveSnapshot: '保存',
      snapshotName: 'スナップショット名',
      restore: '復元',
      toggleVisible: '表示 / 非表示',
      toggleLock: 'ロック / ロック解除',
      renameHint: 'ダブルクリックで名前変更',
      alignTop: '上揃え',
      alignMiddle: '垂直中央揃え',
      alignBottom: '下揃え',
      distributeH: '水平に等間隔配置',
      distributeV: '垂直に等間隔配置',
      layerFront: '最前面へ',
      layerForward: '前面へ',
      layerBackward: '背面へ',
      layerBack: '最背面へ',
      group: 'グループ化',
      ungroup: 'グループ解除',
      edgeStyle: 'エッジのスタイル',
      edgeType: '線の種類',
      edgeDash: '線種',
      edgeStartArrow: '開始',
      edgeEndArrow: '終了',
      straight: '直線',
      bezier: 'ベジェ',
      smoothstep: '角丸折れ線',
      step: '直角折れ線',
      solid: '実線',
      dashed: '破線',
      dotted: '点線',
      arrowNone: 'なし',
      arrowArrow: '矢印',
      arrowCircle: '丸',
      templateUmlUseCase: 'ユースケース図',
      templateUmlClass: 'クラス図',
      templateUmlSequence: 'シーケンス図',
      templateUmlActivity: 'アクティビティ図',
      templateUmlState: 'ステート図',
      templateBpmnProcess: 'ビジネスプロセス',
      templateNetTopology: 'ネットワークトポロジ',
      templateOrgChart: '組織図',
      templateMindMap: 'マインドマップ',
      templateErDiagram: 'ER 図',
      templateApproval: '承認フロー',
      templateOnboarding: '入社フロー',
      templateSwimlane2: '2 レーンのフロー',
      templateUmlComponent: 'コンポーネント図',
      templateBpmnCollab: 'コラボレーションフロー',
      templateNetSubnet: 'サブネット構成',
      theme: 'テーマ',
      themeDefault: 'デフォルト',
      themeBusiness: 'ビジネス',
      themeMinimal: 'ミニマル',
      themeDark: 'ダーク',
      applyThemeAll: 'すべてに適用',
      applyThemeSelection: '選択に適用',
      formatBrush: 'スタイルをコピー',
      applyStyle: 'スタイルを貼り付け',
      exportPrintPdf: 'ページ分割 PDF 印刷',
      printLandscape: '横向き印刷',
      err: {
        EMPTY: 'キャンバスが空です',
        EXPORT_FAILED: '書き出しに失敗しました',
        IMPORT_FAILED: '読み込みに失敗しました：ファイル形式を認識できません',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: '処理',
  roundRect: '角丸め長方形',
  ellipse: '楕円',
  diamond: '菱形',
  parallelogram: '平行四辺形',
  trapezoid: '台形',
  hexagon: '六角形',
  cylinder: '円柱',
  note: '付箋',
  startEnd: '開始/終了',
  decision: '判断',
  data: 'データ',
  document: '文書',
  predefined: '定義済み処理',
  manualInput: '手動入力',
  manualOperation: '手作業',
  preparation: '準備',
  database: 'データベース',
  display: '表示',
  onPageConnector: 'ページ内接続子',
  offPageConnector: 'ページ外接続子',
  terminator: '端子',
  parallelMode: '並行モード',
  loopLimit: 'ループ上限',
  umlActor: 'アクター',
  umlUseCase: 'ユースケース',
  umlClass: 'クラス',
  umlInterface: 'インターフェース',
  umlPackage: 'パッケージ',
  umlNote: 'ノート',
  umlLifeline: 'ライフライン',
  umlState: '状態',
  umlStateInitial: '初期状態',
  umlStateFinal: '終了状態',
  umlForkJoin: '分岐/合流',
  bpmnEventStart: '開始イベント',
  bpmnEventIntermediate: '中間イベント',
  bpmnEventEnd: '終了イベント',
  bpmnGatewayExclusive: '排他ゲートウェイ',
  bpmnGatewayParallel: '並列ゲートウェイ',
  bpmnGatewayInclusive: '包含ゲートウェイ',
  bpmnTask: 'タスク',
  bpmnSubProcess: 'サブプロセス',
  bpmnCallActivity: '呼び出しアクティビティ',
  bpmnDataObject: 'データオブジェクト',
  bpmnDataStore: 'データストア',
  bpmnTextAnnotation: 'テキスト注釈',
  netServer: 'サーバー',
  netClient: 'クライアント',
  netRouter: 'ルーター',
  netSwitch: 'スイッチ',
  netFirewall: 'ファイアウォール',
  netLoadBalancer: 'ロードバランサー',
  netCloud: 'クラウド',
  netCdn: 'CDN',
  netDatabase: 'データベース',
  netStorage: 'ストレージ',
  orgUnit: '組織単位',
  orgAssistant: '補佐',
  orgTeam: 'チーム',
  mindCenter: '中心トピック',
  mindTopic: 'トピック',
  mindSub: 'サブトピック',
  erEntity: 'エンティティ',
  erAttribute: '属性',
  erRelationship: 'リレーションシップ',
  erWeakEntity: '弱エンティティ',
  swimlane: '横スイムレーン',
  swimlaneV: '縦スイムレーン',
  group: 'グループ',
  triangle: '三角形',
  star: '星',
  pentagon: '五角形',
  octagon: '八角形',
  chevron: '矢印',
  card: 'カード',
  callout: '吹き出し',
  cloud: '雲',
  cross: 'バツ',
  plus: 'プラス',
  flag: '旗',
  lightning: '雷',
  arrow: '矢印図形',
  bracket: '大括弧',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
