/**
 * ja 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新規キャンバス',
      docTitle: 'フローチャートのタイトル',
      present: 'スライドショー',
      exitPresent: '終了（Esc）',
      presentLoading: '表示用の画像を生成中…',
      presentFailed: '表示用の画像の生成に失敗しました',
      titlePlaceholder: '無題のフローチャート',
      clear: 'クリア',
      exportPng: 'PNG 書き出し',
      exportSvg: 'SVG 書き出し',
      templates: 'テンプレート',
      autoLayout: '自動配置',
      fitView: 'キャンバスに合わせる',
      zoomActual: '実際のサイズ',
      undo: '元に戻す',
      redo: 'やり直す',
      duplicate: '複製',
      delete: '削除',
      panelTitle: 'プロパティ',
      paletteTitle: '図形',
      searchShape: '図形を検索',
      noShape: '一致する図形なし',
      resizeSidebar: 'ドラッグでサイドバーの幅を調整',
      cat_general: '基本図形',
      cat_flow: 'フローチャート',
      cat_uml: 'UML',
      cat_umlCommon: 'UML 共通',
      cat_umlUseCase: 'UML ユースケース図',
      cat_umlClass: 'UML クラス図',
      cat_umlObject: 'UML オブジェクト/パッケージ図',
      cat_umlSequence: 'UML シーケンス図',
      cat_umlActivity: 'UML アクティビティ図',
      cat_umlState: 'UML 状態図',
      cat_umlComponent: 'UML コンポーネント図',
      cat_umlDeployment: 'UML 配置図',
      cat_bpmn: 'BPMN',
      cat_network: 'ネットワークとクラウド',
      cat_org: '組織図',
      cat_mind: 'マインドマップ',
      cat_er: 'ER 図',
      groupBasic: '基本図形',
      groupFlow: 'フロー記号',
      groupBpmn: 'スイムレーンと BPMN',
      shape_rect: '処理',
      shape_startEnd: '開始/終了',
      shape_decision: '判断',
      shape_data: 'データ',
      shape_swimlane: '横スイムレーン',
      shape_swimlaneV: '縦スイムレーン',
      shape_bpmnTask: 'BPMN タスク',
      canvasAria: 'フローチャートキャンバス',
      emptyHint: '左から図形をドラッグするか、テンプレートを選択してください',
      showGuide: 'クイックスタート',
      onboardingTitle: 'クイックスタート',
      onboardingStepPalette:
        '左の図形ライブラリからクリックまたはドラッグで図形を配置できます。画像・アイコン・数式・表も挿入できます。',
      onboardingStepConnect:
        '図形の端にポインタを合わせ、青いアンカーまたは四方のクイック接続矢印をドラッグして接続します。',
      onboardingStepArrange:
        '複数選択したら、右側の「整列」パネルで整列・等間隔配置・サイズ統一ができます。',
      onboardingStepExport:
        '上部の「書き出し」は PNG / SVG（ベクター）/ PDF / Draw.io / Mermaid とページ分割印刷に対応します。',
      onboardingSkip: 'スキップ',
      onboardingNext: '次へ',
      onboardingDone: 'はじめる',
      nodesLabel: 'ノード',
      edgesLabel: 'エッジ',
      saved: 'ローカル下書きに保存しました',
      saving: '編集を止めると自動保存します',
      noSelection: '要素が未選択です',
      selected: '{{count}} 個の要素を選択中',
      fill: '塗りつぶし',
      stroke: '枠線',
      strokeWidth: '線の太さ',
      fontSize: '文字サイズ',
      bold: '太字',
      italic: '斜体',
      align: '配置',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      label: 'テキスト',
      edgeLabel: 'エッジラベル',
      templateTitle: 'テンプレートを選択',
      templateBasic: '基本フロー',
      templateDecision: '判断フロー',
      templateSwimlane: '横スイムレーンフロー',
      templateSwimlaneV: '縦スイムレーンフロー',
      templateBpmn: 'BPMN 骨組み',
      templateHint: 'テンプレートを読み込むと現在のキャンバスを置き換えます',
      exportPanel: '書き出し',
      importFile: '読み込み',
      scale: '倍率',
      transparentBg: '透過背景',
      onlySelected: '選択のみ',
      padding: '余白',
      exportRange: '書き出し範囲',
      rangeCurrent: '現在のページ',
      rangeAll: 'すべてのページ',
      exporting: '書き出し中…',
      snapToGrid: 'グリッドに吸着',
      gridSize: 'グリッド',
      layoutDirection: 'レイアウト方向',
      layoutDensity: 'レイアウト間隔',
      densityCompact: 'コンパクト',
      densityNormal: '標準',
      densityLoose: 'ゆったり',
      alignTolerance: '整列しきい値',
      dirTB: '上から下',
      dirBT: '下から上',
      dirLR: '左から右',
      dirRL: '右から左',
      mixed: '混在',
      nodesSelected: '{{count}} 個のノードを選択中',
      importHint: '.flow.json / .drawio / .mmd に対応',
      waypoints: '折れ点',
      waypoint: '折れ点',
      waypointCount: '{{count}} 個',
      waypointHint:
        'オレンジの四角をドラッグして移動、ダブルクリックで削除。青い点をクリックすると挿入できます',
      autoRoute: '直交ルーティング',
      routeAll: '全ページを配線',
      clearWaypoints: '折れ点をすべて削除',
      addWaypoint: '折れ点を挿入',
      removeWaypoint: '折れ点を削除',
      searchLayer: 'レイヤーを検索',
      moveOut: 'コンテナから出す',
      dropToRoot: 'ここにドロップしてコンテナから出す',
      insertImage: '画像を挿入',
      insertIcon: 'アイコンを挿入',
      insertFormula: '数式を挿入',
      insertTable: '表を挿入',
      tableInsertRow: '下に行を挿入',
      tableInsertCol: '右に列を挿入',
      tableRemoveRow: '行を削除',
      tableRemoveCol: '列を削除',
      tableMerge: '右のセルと結合',
      tableSplit: 'セルを分割',
      tableSection: '表',
      tableRows: '行数',
      tableColumns: '列数',
      tableHint:
        'セルをダブルクリックで編集。セルを選択し、上のツールバーで行・列の追加/削除や結合/分割ができます。',
      textFormat: 'テキスト形式',
      textFormatPlain: 'プレーンテキスト',
      textFormatMarkdown: 'Markdown',
      formula: '数式',
      imageFailed: '画像を読み込めませんでした',
      draftTooLarge:
        '下書きが大きすぎます。画像は保存されませんでした。「プロジェクトを書き出す」をご利用ください',
      iconGroup_general: '一般',
      iconGroup_office: 'オフィス',
      iconGroup_tech: 'デバイス',
      iconGroup_people: '人物と協働',
      quickConnect: 'クイック接続',
      reconnectSource: '始点を再接続',
      reconnectTarget: '終点を再接続',
      defaultPageName: 'ページ {{n}}',
      layers: 'レイヤー',
      history: '履歴',
      addPage: '新規ページ',
      prevPage: '前のページ',
      nextPage: '次のページ',
      pageOverview: 'ページ一覧',
      openPageOverview: 'ページ一覧を開く',
      closeOverview: '一覧を閉じる',
      removePage: 'ページを削除',
      emptyPage: '空白ページ',
      movePageLeft: '左へ移動',
      movePageRight: '右へ移動',
      pageCounter: '{{current}} / {{total}} ページ',
      noLayer: 'キャンバスに要素がありません',
      noSnapshot: 'スナップショットはまだ保存されていません',
      saveSnapshot: '保存',
      snapshotName: 'スナップショット名',
      restore: '復元',
      toggleVisible: '表示 / 非表示',
      toggleLock: 'ロック / ロック解除',
      renameHint: 'ダブルクリックで名前変更',
      alignTop: '上揃え',
      alignMiddle: '垂直中央揃え',
      alignBottom: '下揃え',
      distributeH: '水平に等間隔配置',
      distributeV: '垂直に等間隔配置',
      uniformSize: 'サイズを統一',
      arrangePanel: '整列',
      arrangeScope: '基準',
      scopeSelection: '選択',
      scopeCanvas: 'キャンバス',
      scopePage: 'ページ',
      distributeSpacing: '等間隔',
      distributeEdges: '両端に合わせる',
      snapSelectionToGrid: 'グリッドに整列',
      closeDialog: '閉じる',
      contextMenu: 'コンテキストメニュー',
      switchShape: '図形を変更',
      paste: '貼り付け',
      selectAll: 'すべて選択',
      deselect: '選択を解除',
      geometry: 'ジオメトリ',
      posX: 'X 座標',
      posY: 'Y 座標',
      geoWidth: '幅',
      geoHeight: '高さ',
      layerFront: '最前面へ',
      layerForward: '前面へ',
      layerBackward: '背面へ',
      layerBack: '最背面へ',
      group: 'グループ化',
      ungroup: 'グループ解除',
      edgeStyle: 'エッジのスタイル',
      edgeType: '線の種類',
      edgeDash: '線種',
      edgeStartArrow: '開始',
      edgeEndArrow: '終了',
      straight: '直線',
      bezier: 'ベジェ',
      smoothstep: '角丸折れ線',
      step: '直角折れ線',
      solid: '実線',
      dashed: '破線',
      dotted: '点線',
      arrowNone: 'なし',
      arrowArrow: '矢印',
      arrowCircle: '丸',
      arrowTriangle: '白抜き三角',
      arrowDiamondHollow: '白抜きひし形',
      templateUmlUseCase: 'ユースケース図',
      templateUmlClass: 'クラス図',
      templateUmlSequence: 'シーケンス図',
      templateUmlActivity: 'アクティビティ図',
      templateUmlState: 'ステート図',
      templateBpmnProcess: 'ビジネスプロセス',
      templateNetTopology: 'ネットワークトポロジ',
      templateOrgChart: '組織図',
      templateMindMap: 'マインドマップ',
      templateErDiagram: 'ER 図',
      templateApproval: '承認フロー',
      templateOnboarding: '入社フロー',
      templateSwimlane2: '2 レーンのフロー',
      templateUmlComponent: 'コンポーネント図',
      templateBpmnCollab: 'コラボレーションフロー',
      templateNetSubnet: 'サブネット構成',
      theme: 'テーマ',
      themeDefault: 'デフォルト',
      themeBusiness: 'ビジネス',
      themeMinimal: 'ミニマル',
      themeDark: 'ダーク',
      applyThemeAll: 'すべてに適用',
      applyThemeSelection: '選択に適用',
      formatBrush: 'スタイルをコピー',
      applyStyle: 'スタイルを貼り付け',
      exportPrintPdf: 'ページ分割 PDF 印刷',
      printLandscape: '横向き印刷',
      shapeParams: '図形パラメータ',
      shapeParamHint: '黄色いハンドルをドラッグ、またはスライダー／入力欄で微調整',
      reset: 'リセット',
      shapeParam: {
        cornerRadius: '角丸の大きさ',
        foldSize: '折り返しの大きさ',
        skew: '傾き',
        inset: '内側オフセット',
        capHeight: '上面の高さ',
        waveHeight: '波の高さ',
        chevronDepth: '矢印の深さ',
        barWidth: '縦線の幅',
        roofHeight: '屋根の高さ',
        loopNotch: '切り欠き',
        lifelineHeader: '見出しの高さ',
        tabHeight: 'タブの高さ',
        componentTab: 'タブの幅',
        partitionHeader: '左カラム幅',
        cubeDepth: '奥行き',
        starInner: '内径比',
        plusArm: '腕の太さ',
        calloutTail: 'しっぽの高さ',
        arrowHead: '矢じりの長さ',
        bracketArm: '括弧の太さ',
        annotationBracket: '括弧の幅',
        dividerTop: '上の区切り線',
        dividerBottom: '下の区切り線',
        laneHeader: '見出し帯の太さ',
        activeClassInset: '二重線の間隔',
        templateTab: 'タブの高さ',
      },
      transform: '変形',
      rotation: '回転角度',
      rotationValue: '角度',
      rotateHint: 'ドラッグで回転（15° スナップ、Shift 45°、Alt 自由）',
      rotateCw: '時計回りに 90° 回転',
      rotateCcw: '反時計回りに 90° 回転',
      flipH: '左右反転',
      flipV: '上下反転',
      collapseContainer: 'コンテナを折りたたむ',
      expandContainer: 'コンテナを展開',
      textLayout: 'テキストレイアウト',
      verticalAlign: '垂直方向の配置',
      lineHeight: '行の高さ',
      autoShrink: 'テキストを自動縮小',
      labelBackground: 'ラベルの背景',
      link: 'ハイパーリンク',
      linkInvalid: 'http / https / mailto のみ対応',
      edgeSourceLabel: '始点ラベル',
      edgeTargetLabel: '終点ラベル',
      edgeLabelPosition: 'ラベル位置',
      labelPos_center: '中央',
      labelPos_nearSource: '始点寄り',
      labelPos_nearTarget: '終点寄り',
      relationPreset: '関係プリセット',
      relationAssociation: '関連',
      relationGeneralization: '汎化',
      relationRealization: '実現',
      relationDependency: '依存',
      relationAggregation: '集約',
      relationComposition: 'コンポジション',
      edgeJump: 'ラインジャンプ',
      jump_none: 'ジャンプなし',
      jump_arc: '円弧でまたぐ',
      pasteFailed: 'クリップボードの draw.io 内容を認識できません',
      cut: '切り取り',
      copy: 'コピー',
      editText: 'テキストを編集',
      container: 'コンテナ',
      duplicatePage: 'ページを複製',
      pageCopySuffix: 'のコピー',
      paperSize: '用紙',
      paper_none: '境界なし',
      paper_a4l: 'A4 横',
      paper_a4p: 'A4 縦',
      paper_a3l: 'A3 横',
      paper_letterl: 'Letter 横',
      paper_letterp: 'Letter 縦',
      paper_custom: 'カスタム',
      wheelMode: 'ホイール',
      wheel_pan: 'ホイールで移動',
      wheel_zoom: 'ホイールでズーム',
      gridStyle: 'グリッド',
      grid_dots: 'ドット',
      grid_lines: 'ライン',
      grid_cross: 'クロス',
      grid_none: 'グリッドなし',
      canvasBackground: '背景',
      bgTransparent: '透明',
      rulers: 'ルーラー',
      shortcutHelp: 'キーボードショートカット',
      searchNodes: '検索',
      searchNodesPlaceholder: 'テキストでノードを検索…',
      searchNoResult: '一致するノードがありません',
      scGroupEdit: '編集',
      scGroupArrange: '整列と変形',
      scGroupCanvas: 'キャンバスとヘルプ',
      scUndo: '元に戻す',
      scRedo: 'やり直す',
      scClipboard: '切り取り / コピー / 貼り付け',
      scDuplicate: '複製',
      scSelectAll: 'すべて選択',
      scDelete: '選択を削除',
      scSave: '下書きを保存',
      scTextNewline: 'テキスト編集中の改行',
      scTextCommit: 'テキスト編集を確定',
      scRotateCw: '時計回りに 90°',
      scRotateCcw: '反時計回りに 90°',
      scFlipH: '左右反転',
      scFlipV: '上下反転',
      scGroup: 'グループ化 / 解除',
      scNudge: '選択を微調整（⇧ で 10px）',
      scSpawnRight: '右側に接続ノードを作成',
      scSpawnDown: '下側に接続ノードを作成',
      scRename: '選択を名前変更',
      scDeselect: '選択解除',
      scSwitchPage: '前 / 次のページ',
      scPan: 'キャンバスを移動',
      scZoom: 'キャンバスをズーム',
      scHandles: '形状パラメータ / 回転',
      scEditLabel: 'ラベルをその場で編集',
      scHelp: 'このヘルプを開く',
      err: {
        EMPTY: 'キャンバスが空です',
        EXPORT_FAILED: '書き出しに失敗しました',
        IMPORT_FAILED: '読み込みに失敗しました：ファイル形式を認識できません',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: '処理',
  roundRect: '角丸め長方形',
  ellipse: '楕円',
  diamond: '菱形',
  parallelogram: '平行四辺形',
  trapezoid: '台形',
  hexagon: '六角形',
  cylinder: '円柱',
  note: '付箋',
  startEnd: '開始/終了',
  decision: '判断',
  data: 'データ',
  document: '文書',
  predefined: '定義済み処理',
  manualInput: '手動入力',
  manualOperation: '手作業',
  preparation: '準備',
  database: 'データベース',
  display: '表示',
  onPageConnector: 'ページ内接続子',
  offPageConnector: 'ページ外接続子',
  terminator: '端子',
  parallelMode: '並行モード',
  loopLimit: 'ループ上限',
  umlActor: 'アクター',
  umlNote: 'ノート',
  umlBoundary: 'バウンダリ',
  umlControl: 'コントロール',
  umlEntity: 'エンティティ',
  umlFrame: 'フレーム',
  umlUseCase: 'ユースケース',
  umlSubject: 'サブジェクト',
  umlInclude: 'インクルード',
  umlExtend: 'エクステンド',
  umlExtensionPoint: '拡張点',
  umlClass: 'クラス',
  umlInterface: 'インターフェース',
  umlEnumeration: '列挙型',
  umlDataType: 'データ型',
  umlAbstractClass: '抽象クラス',
  umlActiveClass: 'アクティブクラス',
  umlTemplateClass: 'テンプレートクラス',
  umlAssociationClass: '関連クラス',
  umlPackage: 'パッケージ',
  umlObject: 'オブジェクト',
  umlObjectSlot: 'オブジェクト（スロット）',
  umlModel: 'モデル',
  umlProfile: 'プロファイル',
  umlLifeline: 'ライフライン',
  umlActivation: '活性化',
  umlDestroy: '破棄',
  umlCombinedFragment: '複合フラグメント',
  umlInteractionUse: '相互作用使用',
  umlStateInvariant: '状態不変条件',
  umlGate: 'ゲート',
  umlForkJoin: '分岐/合流',
  umlAction: 'アクション',
  umlActivity: 'アクティビティ',
  umlDecisionMerge: '判断 / マージ',
  umlInitialNode: '開始ノード',
  umlActivityFinal: 'アクティビティ終了',
  umlFlowFinal: 'フロー終了',
  umlObjectNode: 'オブジェクトノード',
  umlSendSignal: 'シグナル送信',
  umlReceiveSignal: 'シグナル受信',
  umlActivityPartition: 'アクティビティ区画',
  umlState: '状態',
  umlStateInitial: '初期状態',
  umlStateFinal: '終了状態',
  umlChoice: '選択',
  umlJunction: 'ジャンクション',
  umlTerminate: '終止',
  umlEntryPoint: '入口点',
  umlExitPoint: '出口点',
  umlHistory: '浅い履歴',
  umlHistoryDeep: '深い履歴',
  umlCompositeState: '複合状態',
  umlComponent: 'コンポーネント',
  umlProvidedInterface: '提供インターフェース',
  umlRequiredInterface: '要求インターフェース',
  umlPort: 'ポート',
  umlSubsystem: 'サブシステム',
  umlNode: 'ノード',
  umlDevice: 'デバイス',
  umlExecutionEnvironment: '実行環境',
  umlArtifact: '成果物',
  umlDeploymentSpec: '配置仕様',
  bpmnEventStart: '開始イベント',
  bpmnEventIntermediate: '中間イベント',
  bpmnEventEnd: '終了イベント',
  bpmnGatewayExclusive: '排他ゲートウェイ',
  bpmnGatewayParallel: '並列ゲートウェイ',
  bpmnGatewayInclusive: '包含ゲートウェイ',
  bpmnTask: 'タスク',
  bpmnSubProcess: 'サブプロセス',
  bpmnCallActivity: '呼び出しアクティビティ',
  bpmnDataObject: 'データオブジェクト',
  bpmnDataStore: 'データストア',
  bpmnTextAnnotation: 'テキスト注釈',
  netServer: 'サーバー',
  netClient: 'クライアント',
  netRouter: 'ルーター',
  netSwitch: 'スイッチ',
  netFirewall: 'ファイアウォール',
  netLoadBalancer: 'ロードバランサー',
  netCloud: 'クラウド',
  netCdn: 'CDN',
  netDatabase: 'データベース',
  netStorage: 'ストレージ',
  orgUnit: '組織単位',
  orgAssistant: '補佐',
  orgTeam: 'チーム',
  mindCenter: '中心トピック',
  mindTopic: 'トピック',
  mindSub: 'サブトピック',
  erEntity: 'エンティティ',
  erAttribute: '属性',
  erRelationship: 'リレーションシップ',
  erWeakEntity: '弱エンティティ',
  swimlane: '横スイムレーン',
  swimlaneV: '縦スイムレーン',
  group: 'グループ',
  triangle: '三角形',
  star: '星',
  pentagon: '五角形',
  octagon: '八角形',
  chevron: '矢印',
  card: 'カード',
  callout: '吹き出し',
  cloud: '雲',
  cross: 'バツ',
  plus: 'プラス',
  flag: '旗',
  lightning: '雷',
  arrow: '矢印図形',
  bracket: '大括弧',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
