/**
 * pt 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nova tela',
      docTitle: 'Título do diagrama',
      present: 'Apresentar',
      exitPresent: 'Sair (Esc)',
      presentLoading: 'A preparar a apresentação…',
      presentFailed: 'Falha ao preparar a apresentação',
      titlePlaceholder: 'Diagrama sem título',
      clear: 'Limpar',
      exportPng: 'Exportar PNG',
      exportSvg: 'Exportar SVG',
      templates: 'Modelos',
      autoLayout: 'Auto layout',
      fitView: 'Ajustar à tela',
      zoomActual: 'Tamanho real',
      undo: 'Anular',
      redo: 'Refazer',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      panelTitle: 'Propriedades',
      paletteTitle: 'Formas',
      searchShape: 'Buscar formas',
      noShape: 'Nenhuma forma correspondente',
      resizeSidebar: 'Arraste para redimensionar a barra',
      cat_general: 'Geral',
      cat_flow: 'Fluxograma',
      cat_uml: 'UML',
      cat_umlCommon: 'UML geral',
      cat_umlUseCase: 'UML casos de uso',
      cat_umlClass: 'UML classes',
      cat_umlObject: 'UML objetos/pacotes',
      cat_umlSequence: 'UML sequência',
      cat_umlActivity: 'UML atividade',
      cat_umlState: 'UML estados',
      cat_umlComponent: 'UML componentes',
      cat_umlDeployment: 'UML implantação',
      cat_bpmn: 'BPMN',
      cat_network: 'Rede e nuvem',
      cat_org: 'Organização',
      cat_mind: 'Mapa mental',
      cat_er: 'Diagrama ER',
      groupBasic: 'Formas básicas',
      groupFlow: 'Símbolos de fluxo',
      groupBpmn: 'Raias e BPMN',
      shape_rect: 'Processo',
      shape_startEnd: 'Início / Fim',
      shape_decision: 'Decisão',
      shape_data: 'Dados',
      shape_swimlane: 'Raia horizontal',
      shape_swimlaneV: 'Raia vertical',
      shape_bpmnTask: 'Tarefa BPMN',
      canvasAria: 'Tela do diagrama',
      emptyHint: 'Arraste uma forma da esquerda ou escolha um modelo',
      nodesLabel: 'Nós',
      edgesLabel: 'Ligações',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de editar',
      noSelection: 'Nenhum elemento selecionado',
      selected: '{{count}} elementos selecionados',
      fill: 'Preenchimento',
      stroke: 'Contorno',
      strokeWidth: 'Espessura',
      fontSize: 'Tamanho',
      bold: 'Negrito',
      italic: 'Itálico',
      align: 'Alinhamento',
      alignLeft: 'Esquerda',
      alignCenter: 'Centro',
      alignRight: 'Direita',
      label: 'Texto',
      edgeLabel: 'Etiqueta da ligação',
      templateTitle: 'Escolher modelo',
      templateBasic: 'Fluxo básico',
      templateDecision: 'Fluxo de decisão',
      templateSwimlane: 'Fluxo de raia horizontal',
      templateSwimlaneV: 'Fluxo de raia vertical',
      templateBpmn: 'Esqueleto BPMN',
      templateHint: 'Carregar um modelo substitui a tela atual',
      exportPanel: 'Exportar',
      importFile: 'Importar',
      scale: 'Escala',
      transparentBg: 'Transparente',
      onlySelected: 'Só seleção',
      padding: 'Margem',
      exportRange: 'Intervalo',
      rangeCurrent: 'Página atual',
      rangeAll: 'Todas as páginas',
      exporting: 'Exportando…',
      snapToGrid: 'Alinhar à grade',
      gridSize: 'Grade',
      layoutDirection: 'Direção do layout',
      layoutDensity: 'Espaçamento',
      densityCompact: 'Compacto',
      densityNormal: 'Normal',
      densityLoose: 'Amplo',
      alignTolerance: 'Limite de alinhamento',
      dirTB: 'De cima para baixo',
      dirBT: 'De baixo para cima',
      dirLR: 'Da esquerda para a direita',
      dirRL: 'Da direita para a esquerda',
      mixed: 'Misto',
      nodesSelected: '{{count}} nós selecionados',
      importHint: 'Compatível com .flow.json / .drawio / .mmd',
      waypoints: 'Pontos de passagem',
      waypoint: 'Ponto de passagem',
      waypointCount: '{{count}}',
      waypointHint:
        'Arraste os quadrados laranja para mover um ponto, clique duas vezes para excluir; clique num ponto azul para inserir.',
      autoRoute: 'Roteamento ortogonal',
      clearWaypoints: 'Limpar pontos',
      addWaypoint: 'Inserir ponto',
      removeWaypoint: 'Remover ponto',
      searchLayer: 'Pesquisar camadas',
      moveOut: 'Mover para fora do contentor',
      dropToRoot: 'Solte aqui para sair do contentor',
      insertImage: 'Inserir imagem',
      insertIcon: 'Inserir ícone',
      insertFormula: 'Inserir fórmula',
      formula: 'Fórmula',
      imageFailed: 'Não foi possível ler a imagem',
      draftTooLarge:
        'Rascunho demasiado grande: as imagens não foram guardadas. Use «Exportar projeto».',
      iconGroup_general: 'Geral',
      iconGroup_office: 'Escritório',
      iconGroup_tech: 'Tecnologia',
      iconGroup_people: 'Pessoas',
      quickConnect: 'Conexão rápida',
      reconnectSource: 'Reconectar início',
      reconnectTarget: 'Reconectar fim',
      defaultPageName: 'Página {{n}}',
      layers: 'Camadas',
      history: 'Histórico',
      addPage: 'Nova página',
      prevPage: 'Página anterior',
      nextPage: 'Página seguinte',
      pageOverview: 'Visão geral das páginas',
      openPageOverview: 'Abrir a visão geral',
      closeOverview: 'Fechar a visão geral',
      removePage: 'Excluir página',
      emptyPage: 'Página vazia',
      movePageLeft: 'Mover para a esquerda',
      movePageRight: 'Mover para a direita',
      pageCounter: 'Página {{current}} de {{total}}',
      noLayer: 'Nenhum elemento na tela',
      noSnapshot: 'Nenhum instantâneo salvo ainda',
      saveSnapshot: 'Guardar',
      snapshotName: 'Nome do instantâneo',
      restore: 'Restaurar',
      toggleVisible: 'Mostrar / Ocultar',
      toggleLock: 'Bloquear / Desbloquear',
      renameHint: 'Duplo clique para renomear',
      alignTop: 'Alinhar ao topo',
      alignMiddle: 'Alinhar ao centro',
      alignBottom: 'Alinhar à base',
      distributeH: 'Distribuir horizontalmente',
      distributeV: 'Distribuir verticalmente',
      uniformSize: 'Mesmo tamanho',
      snapSelectionToGrid: 'Alinhar à grelha',
      closeDialog: 'Fechar',
      contextMenu: 'Menu de contexto',
      switchShape: 'Alterar forma',
      paste: 'Colar',
      selectAll: 'Selecionar tudo',
      deselect: 'Limpar seleção',
      geometry: 'Geometria',
      posX: 'X',
      posY: 'Y',
      geoWidth: 'Largura',
      geoHeight: 'Altura',
      layerFront: 'Trazer para frente',
      layerForward: 'Avançar',
      layerBackward: 'Recuar',
      layerBack: 'Enviar para trás',
      group: 'Agrupar',
      ungroup: 'Desagrupar',
      edgeStyle: 'Estilo da ligação',
      edgeType: 'Tipo de linha',
      edgeDash: 'Traço',
      edgeStartArrow: 'Início',
      edgeEndArrow: 'Fim',
      straight: 'Linha reta',
      bezier: 'Bézier',
      smoothstep: 'Canto arredondado',
      step: 'Canto reto',
      solid: 'Sólida',
      dashed: 'Tracejada',
      dotted: 'Pontilhada',
      arrowNone: 'Nenhuma',
      arrowArrow: 'Seta',
      arrowCircle: 'Círculo',
      arrowTriangle: 'Triângulo vazio',
      arrowDiamondHollow: 'Losango vazio',
      templateUmlUseCase: 'Diagrama de casos de uso',
      templateUmlClass: 'Diagrama de classes',
      templateUmlSequence: 'Diagrama de sequência',
      templateUmlActivity: 'Diagrama de atividade',
      templateUmlState: 'Diagramma de estados',
      templateBpmnProcess: 'Processo de negócio',
      templateNetTopology: 'Topologia de rede',
      templateOrgChart: 'Organograma',
      templateMindMap: 'Mapa mental',
      templateErDiagram: 'Diagrama ER',
      templateApproval: 'Fluxo de aprovação',
      templateOnboarding: 'Processo de integração',
      templateSwimlane2: 'Fluxo de duas faixas',
      templateUmlComponent: 'Diagrama de componentes',
      templateBpmnCollab: 'Fluxo colaborativo',
      templateNetSubnet: 'Topologia de sub-rede',
      theme: 'Tema',
      themeDefault: 'Padrão',
      themeBusiness: 'Empresarial',
      themeMinimal: 'Minimalista',
      themeDark: 'Escuro',
      applyThemeAll: 'Aplicar a tudo',
      applyThemeSelection: 'Aplicar à seleção',
      formatBrush: 'Copiar estilo',
      applyStyle: 'Colar estilo',
      exportPrintPdf: 'Imprimir PDF paginado',
      printLandscape: 'Impressão horizontal',
      shapeParams: 'Parâmetros da forma',
      shapeParamHint: 'Arraste a alça âmbar ou ajuste com o controle / campo',
      reset: 'Redefinir',
      shapeParam: {
        cornerRadius: 'Raio do canto',
        foldSize: 'Tamanho da dobra',
        skew: 'Inclinação',
        inset: 'Recuo',
        capHeight: 'Altura da tampa',
        waveHeight: 'Altura da onda',
        chevronDepth: 'Profundidade da seta',
        barWidth: 'Largura das barras',
        roofHeight: 'Altura do telhado',
        loopNotch: 'Recorte',
        lifelineHeader: 'Altura do cabeçalho',
        tabHeight: 'Altura da aba',
        componentTab: 'Largura da aba',
        partitionHeader: 'Largura da coluna',
        cubeDepth: 'Profundidade',
        starInner: 'Raio interno',
        plusArm: 'Espessura do braço',
        calloutTail: 'Altura da cauda',
        arrowHead: 'Comprimento da ponta',
        bracketArm: 'Espessura do colchete',
        annotationBracket: 'Largura do colchete',
        dividerTop: 'Divisor superior',
        dividerBottom: 'Divisor inferior',
        laneHeader: 'Espessura do cabeçalho',
        activeClassInset: 'Espaço das linhas duplas',
        templateTab: 'Altura da aba',
      },
      transform: 'Transformação',
      rotation: 'Rotação',
      rotationValue: 'Ângulo',
      rotateHint: 'Arraste para rodar (15° com ímã, Shift 45°, Alt livre)',
      rotateCw: 'Rodar 90° no sentido horário',
      rotateCcw: 'Rodar 90° no sentido anti-horário',
      flipH: 'Espelhar horizontal',
      flipV: 'Espelhar vertical',
      collapseContainer: 'Recolher contêiner',
      expandContainer: 'Expandir contêiner',
      textLayout: 'Layout do texto',
      verticalAlign: 'Alinhamento vertical',
      lineHeight: 'Altura da linha',
      autoShrink: 'Ajustar o texto automaticamente',
      labelBackground: 'Fundo do rótulo',
      link: 'Hiperlink',
      linkInvalid: 'Somente http / https / mailto são permitidos',
      edgeSourceLabel: 'Rótulo de origem',
      edgeTargetLabel: 'Rótulo de destino',
      edgeLabelPosition: 'Posição do rótulo',
      labelPos_center: 'Centralizado',
      labelPos_nearSource: 'Perto da origem',
      labelPos_nearTarget: 'Perto do destino',
      relationPreset: 'Relacionamento predefinido',
      relationAssociation: 'Associação',
      relationGeneralization: 'Generalização',
      relationRealization: 'Realização',
      relationDependency: 'Dependência',
      relationAggregation: 'Agregação',
      relationComposition: 'Composição',
      edgeJump: 'Salto de linha',
      jump_none: 'Sem salto',
      jump_arc: 'Salto em arco',
      pasteFailed: 'Conteúdo draw.io da área de transferência não reconhecido',
      cut: 'Recortar',
      copy: 'Copiar',
      editText: 'Editar texto',
      container: 'Contêiner',
      duplicatePage: 'Duplicar página',
      pageCopySuffix: 'cópia',
      paperSize: 'Papel',
      paper_none: 'Sem borda',
      paper_a4l: 'A4 paisagem',
      paper_a4p: 'A4 retrato',
      paper_a3l: 'A3 paisagem',
      paper_letterl: 'Letter paisagem',
      paper_letterp: 'Letter retrato',
      paper_custom: 'Personalizado',
      wheelMode: 'Roda',
      wheel_pan: 'A roda desloca',
      wheel_zoom: 'A roda amplia',
      gridStyle: 'Grade',
      grid_dots: 'Pontos',
      grid_lines: 'Linhas',
      grid_cross: 'Cruz',
      grid_none: 'Sem grade',
      canvasBackground: 'Fundo',
      bgTransparent: 'Transparente',
      rulers: 'Réguas',
      shortcutHelp: 'Atalhos de teclado',
      searchNodes: 'Pesquisar',
      searchNodesPlaceholder: 'Pesquisar nós por texto…',
      searchNoResult: 'Nenhum nó correspondente',
      scGroupEdit: 'Edição',
      scGroupArrange: 'Alinhar e transformar',
      scGroupCanvas: 'Tela e ajuda',
      scUndo: 'Desfazer',
      scRedo: 'Refazer',
      scClipboard: 'Recortar / copiar / colar',
      scDuplicate: 'Duplicar',
      scSelectAll: 'Selecionar tudo',
      scDelete: 'Excluir seleção',
      scSave: 'Salvar rascunho',
      scRotateCw: 'Rodar 90° horário',
      scRotateCcw: 'Rodar 90° anti-horário',
      scFlipH: 'Espelhar horizontal',
      scFlipV: 'Espelhar vertical',
      scGroup: 'Agrupar / desagrupar',
      scNudge: 'Mover aos poucos (⇧ para 10px)',
      scSpawnRight: 'Criar nó conectado à direita',
      scSpawnDown: 'Criar nó conectado abaixo',
      scRename: 'Renomear seleção',
      scDeselect: 'Desmarcar',
      scSwitchPage: 'Página anterior / próxima',
      scPan: 'Deslocar a tela',
      scZoom: 'Ampliar a tela',
      scHandles: 'Ajustar forma / rodar',
      scEditLabel: 'Editar rótulo no local',
      scHelp: 'Abrir esta ajuda',
      err: {
        EMPTY: 'A tela está vazia',
        EXPORT_FAILED: 'Falha ao exportar',
        IMPORT_FAILED: 'Falha ao importar: formato de arquivo não reconhecido',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: 'Processo',
  roundRect: 'Retângulo arredondado',
  ellipse: 'Elipse',
  diamond: 'Losango',
  parallelogram: 'Paralelograma',
  trapezoid: 'Trapézio',
  hexagon: 'Hexágono',
  cylinder: 'Cilindro',
  note: 'Nota',
  startEnd: 'Início / Fim',
  decision: 'Decisão',
  data: 'Dados',
  document: 'Documento',
  predefined: 'Processo predefinido',
  manualInput: 'Entrada manual',
  manualOperation: 'Operação manual',
  preparation: 'Preparação',
  database: 'Base de dados',
  display: 'Exibição',
  onPageConnector: 'Conector mesma página',
  offPageConnector: 'Conector outra página',
  terminator: 'Terminador',
  parallelMode: 'Modo paralelo',
  loopLimit: 'Limite de loop',
  umlActor: 'Ator',
  umlNote: 'Nota',
  umlBoundary: 'Fronteira',
  umlControl: 'Controle',
  umlEntity: 'Entidade',
  umlFrame: 'Moldura',
  umlUseCase: 'Caso de uso',
  umlSubject: 'Sujeito',
  umlInclude: 'Inclusão',
  umlExtend: 'Extensão',
  umlExtensionPoint: 'Ponto de extensão',
  umlClass: 'Classe',
  umlInterface: 'Interface',
  umlEnumeration: 'Enumeração',
  umlDataType: 'Tipo de dado',
  umlAbstractClass: 'Classe abstrata',
  umlActiveClass: 'Classe ativa',
  umlTemplateClass: 'Classe modelo',
  umlAssociationClass: 'Classe de associação',
  umlPackage: 'Pacote',
  umlObject: 'Objeto',
  umlObjectSlot: 'Objeto (slots)',
  umlModel: 'Modelo',
  umlProfile: 'Perfil',
  umlLifeline: 'Linha de vida',
  umlActivation: 'Ativação',
  umlDestroy: 'Destruição',
  umlCombinedFragment: 'Fragmento combinado',
  umlInteractionUse: 'Uso de interação',
  umlStateInvariant: 'Invariante de estado',
  umlGate: 'Portão',
  umlForkJoin: 'Bifurcação / União',
  umlAction: 'Ação',
  umlActivity: 'Atividade',
  umlDecisionMerge: 'Decisão / Mesclagem',
  umlInitialNode: 'Nó inicial',
  umlActivityFinal: 'Fim da atividade',
  umlFlowFinal: 'Fim do fluxo',
  umlObjectNode: 'Nó de objeto',
  umlSendSignal: 'Enviar sinal',
  umlReceiveSignal: 'Receber sinal',
  umlActivityPartition: 'Partição de atividade',
  umlState: 'Estado',
  umlStateInitial: 'Estado inicial',
  umlStateFinal: 'Estado final',
  umlChoice: 'Escolha',
  umlJunction: 'Junção',
  umlTerminate: 'Terminar',
  umlEntryPoint: 'Ponto de entrada',
  umlExitPoint: 'Ponto de saída',
  umlHistory: 'Histórico raso',
  umlHistoryDeep: 'Histórico profundo',
  umlCompositeState: 'Estado composto',
  umlComponent: 'Componente',
  umlProvidedInterface: 'Interface fornecida',
  umlRequiredInterface: 'Interface requerida',
  umlPort: 'Porta',
  umlSubsystem: 'Subsistema',
  umlNode: 'Nó',
  umlDevice: 'Dispositivo',
  umlExecutionEnvironment: 'Ambiente de execução',
  umlArtifact: 'Artefato',
  umlDeploymentSpec: 'Especificação de implantação',
  bpmnEventStart: 'Evento de início',
  bpmnEventIntermediate: 'Evento intermediário',
  bpmnEventEnd: 'Evento final',
  bpmnGatewayExclusive: 'Gateway exclusivo',
  bpmnGatewayParallel: 'Gateway paralelo',
  bpmnGatewayInclusive: 'Gateway inclusivo',
  bpmnTask: 'Tarefa',
  bpmnSubProcess: 'Subprocesso',
  bpmnCallActivity: 'Atividade de chamada',
  bpmnDataObject: 'Objeto de dados',
  bpmnDataStore: 'Armazém de dados',
  bpmnTextAnnotation: 'Anotação de texto',
  netServer: 'Servidor',
  netClient: 'Cliente',
  netRouter: 'Roteador',
  netSwitch: 'Switch',
  netFirewall: 'Firewall',
  netLoadBalancer: 'Balanceador de carga',
  netCloud: 'Nuvem',
  netCdn: 'CDN',
  netDatabase: 'Base de dados',
  netStorage: 'Armazenamento',
  orgUnit: 'Unidade',
  orgAssistant: 'Assistente',
  orgTeam: 'Equipe',
  mindCenter: 'Tópico central',
  mindTopic: 'Tópico',
  mindSub: 'Subtópico',
  erEntity: 'Entidade',
  erAttribute: 'Atributo',
  erRelationship: 'Relacionamento',
  erWeakEntity: 'Entidade fraca',
  swimlane: 'Raia horizontal',
  swimlaneV: 'Raia vertical',
  group: 'Grupo',
  triangle: 'Triângulo',
  star: 'Estrela',
  pentagon: 'Pentágono',
  octagon: 'Octágono',
  chevron: 'Chevron',
  card: 'Cartão',
  callout: 'Balão',
  cloud: 'Nuvem',
  cross: 'Cruz',
  plus: 'Mais',
  flag: 'Bandeira',
  lightning: 'Raio',
  arrow: 'Seta',
  bracket: 'Colchete',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
