/**
 * zh 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';
import { SHAPE_LABELS } from '../model/types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新建画布',
      docTitle: '流程图标题',
      present: '放映',
      exitPresent: '退出放映（Esc）',
      presentLoading: '正在生成放映画面…',
      presentFailed: '放映画面生成失败',
      titlePlaceholder: '未命名流程图',
      clear: '清空',
      exportPng: '导出 PNG',
      exportSvg: '导出 SVG',
      templates: '模板',
      autoLayout: '自动布局',
      fitView: '适应画布',
      zoomActual: '实际大小',
      undo: '撤销',
      redo: '重做',
      duplicate: '复制',
      delete: '删除',
      panelTitle: '属性',
      paletteTitle: '图形库',
      searchShape: '搜索图形',
      noShape: '没有匹配的图形',
      resizeSidebar: '拖拽调整侧边栏宽度',
      exportPanel: '导出',
      importFile: '导入',
      scale: '分辨率',
      transparentBg: '透明背景',
      onlySelected: '仅导出选中',
      padding: '边距',
      exportRange: '导出范围',
      rangeCurrent: '当前页',
      rangeAll: '全部页',
      exporting: '导出中…',
      snapToGrid: '网格吸附',
      gridSize: '网格',
      layoutDirection: '布局方向',
      layoutDensity: '布局间距',
      densityCompact: '紧凑',
      densityNormal: '标准',
      densityLoose: '宽松',
      alignTolerance: '对齐阈值',
      dirTB: '自上而下',
      dirBT: '自下而上',
      dirLR: '自左向右',
      dirRL: '自右向左',
      mixed: '混合',
      nodesSelected: '已选中 {{count}} 个节点',
      importHint: '支持 .flow.json / .drawio / .mmd',
      waypoints: '折点',
      waypoint: '折点',
      waypointCount: '{{count}} 个',
      waypointHint: '拖动橙色方块调整折点，双击删除；点击蓝色圆点插入折点',
      autoRoute: '正交自动布线',
      clearWaypoints: '清除折点',
      addWaypoint: '插入折点',
      removeWaypoint: '删除折点',
      searchLayer: '搜索图层',
      moveOut: '移出容器',
      dropToRoot: '拖到此处移出容器',
      insertImage: '插入图片',
      insertIcon: '插入图标',
      insertFormula: '插入公式',
      formula: '公式',
      imageFailed: '图片读取失败',
      draftTooLarge: '草稿体积过大：图片未保存到本地草稿，请用「导出项目文件」保存',
      iconGroup_general: '通用',
      iconGroup_office: '文档办公',
      iconGroup_tech: '设备技术',
      iconGroup_people: '人物协作',
      quickConnect: '快速连线',
      reconnectSource: '重连起点',
      reconnectTarget: '重连终点',
      defaultPageName: '页面 {{n}}',
      layers: '图层',
      history: '历史',
      addPage: '新建页面',
      prevPage: '上一页',
      nextPage: '下一页',
      pageOverview: '页面总览',
      openPageOverview: '打开页面总览',
      closeOverview: '关闭总览',
      removePage: '删除页面',
      emptyPage: '空白页',
      movePageLeft: '左移',
      movePageRight: '右移',
      pageCounter: '第 {{current}} / {{total}} 页',
      noLayer: '画布上还没有元素',
      noSnapshot: '还没有保存任何快照',
      saveSnapshot: '保存',
      snapshotName: '快照名称',
      restore: '回滚',
      toggleVisible: '显示/隐藏',
      toggleLock: '锁定/解锁',
      renameHint: '双击可重命名',
      cat_general: '通用图形',
      cat_flow: '流程图',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: '网络与云',
      cat_org: '组织结构',
      cat_mind: '思维导图',
      cat_er: 'ER 图',
      groupBasic: '基础图形',
      groupFlow: '流程符号',
      groupBpmn: '泳道与 BPMN',
      shape_rect: '过程',
      shape_startEnd: '开始/结束',
      shape_decision: '判断',
      shape_data: '数据',
      shape_swimlane: '横向泳道',
      shape_swimlaneV: '纵向泳道',
      shape_bpmnTask: 'BPMN 任务',
      canvasAria: '流程图画布',
      emptyHint: '从左侧拖入图形，或选择一个模板开始',
      nodesLabel: '节点',
      edgesLabel: '连线',
      saved: '已保存到本地草稿',
      saving: '停止编辑后自动保存',
      noSelection: '未选中元素',
      selected: '已选中 {{count}} 个元素',
      fill: '填充色',
      stroke: '描边色',
      strokeWidth: '线宽',
      fontSize: '字号',
      bold: '加粗',
      italic: '斜体',
      align: '对齐',
      alignLeft: '左对齐',
      alignCenter: '居中',
      alignRight: '右对齐',
      alignTop: '顶对齐',
      alignMiddle: '垂直居中',
      alignBottom: '底对齐',
      distributeH: '水平等距分布',
      distributeV: '垂直等距分布',
      layerFront: '置于顶层',
      layerForward: '上移一层',
      layerBackward: '下移一层',
      layerBack: '置于底层',
      group: '编组',
      ungroup: '解组',
      edgeStyle: '连线样式',
      edgeType: '线型',
      edgeDash: '线条',
      edgeStartArrow: '起点箭头',
      edgeEndArrow: '终点箭头',
      edgeSourceNode: '起点节点',
      edgeTargetNode: '终点节点',
      straight: '直线',
      bezier: '曲线',
      smoothstep: '圆角折线',
      step: '直角折线',
      solid: '实线',
      dashed: '虚线',
      dotted: '点线',
      arrowNone: '无',
      arrowArrow: '箭头',
      arrowCircle: '圆点',
      label: '文字',
      edgeLabel: '连线文字',
      templateTitle: '选择模板',
      templateBasic: '基础流程',
      templateDecision: '判断流程',
      templateSwimlane: '横向泳道流程',
      templateSwimlaneV: '纵向泳道流程',
      templateUmlUseCase: '用例图',
      templateUmlClass: '类图',
      templateUmlSequence: '时序图',
      templateUmlActivity: '活动图',
      templateUmlState: '状态图',
      templateBpmnProcess: '业务流程',
      templateNetTopology: '网络拓扑',
      templateOrgChart: '组织结构图',
      templateMindMap: '思维导图',
      templateErDiagram: 'ER 图',
      templateApproval: '审批流程',
      templateOnboarding: '入职流程',
      templateSwimlane2: '双泳道流程',
      templateUmlComponent: '组件图',
      templateBpmnCollab: '协作流程',
      templateNetSubnet: '子网拓扑',
      theme: '主题',
      themeDefault: '默认',
      themeBusiness: '商务蓝',
      themeMinimal: '极简灰',
      themeDark: '暗色',
      applyThemeAll: '应用到全部',
      applyThemeSelection: '应用到选中',
      formatBrush: '复制样式',
      applyStyle: '粘贴样式',
      exportPrintPdf: '分页打印 PDF',
      printLandscape: '横向打印',
      templateBpmn: 'BPMN 骨架',
      templateHint: '载入模板将替换当前画布内容',
      edgeStyleLabel: '连线样式',
      startArrowLabel: '开始箭头',
      endArrowLabel: '结束箭头',
      dashdot: '点划线',
      sketch: '实线手绘',
      sketchDashed: '虚线手绘',
      arrowSolid: '实心箭头',
      arrowOpen: '空心箭头',
      arrowDiamond: '菱形',
      arrowSquare: '方块',
      arrowBar: '竖线',
      appearance: '外观',
      opacity: '透明度',
      shadow: '阴影',
      textColor: '文字颜色',
      cornerRadius: '圆角大小',
      foldSize: '折角大小',
      fontFamily: '字体',
      err: {
        EMPTY: '画布为空，无法导出',
        EXPORT_FAILED: '导出失败',
        IMPORT_FAILED: '导入失败：无法识别该文件格式',
      },
    },
  },
};

const shapes: Record<string, string> = SHAPE_LABELS;

const bundle: LangBundle = { ui, shapes };

export default bundle;
