/**
 * zhTW 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新增畫布',
      docTitle: '流程圖標題',
      present: '放映',
      exitPresent: '結束放映（Esc）',
      presentLoading: '正在產生放映畫面…',
      presentFailed: '放映畫面產生失敗',
      titlePlaceholder: '未命名流程圖',
      clear: '清空',
      exportPng: '匯出 PNG',
      exportSvg: '匯出 SVG',
      templates: '模板',
      autoLayout: '自動排版',
      fitView: '畫布適應',
      zoomActual: '實際大小',
      undo: '復原',
      redo: '重做',
      duplicate: '複製',
      delete: '刪除',
      panelTitle: '屬性',
      paletteTitle: '圖形庫',
      searchShape: '搜尋圖形',
      noShape: '沒有符合的圖形',
      resizeSidebar: '拖拽調整側邊欄寬度',
      cat_general: '通用圖形',
      cat_flow: '流程圖',
      cat_uml: 'UML',
      cat_umlCommon: 'UML 通用',
      cat_umlUseCase: 'UML 用例圖',
      cat_umlClass: 'UML 類別圖',
      cat_umlObject: 'UML 物件/套件圖',
      cat_umlSequence: 'UML 時序圖',
      cat_umlActivity: 'UML 活動圖',
      cat_umlState: 'UML 狀態圖',
      cat_umlComponent: 'UML 組件圖',
      cat_umlDeployment: 'UML 部署圖',
      cat_bpmn: 'BPMN',
      cat_network: '網路與雲',
      cat_org: '組織結構',
      cat_mind: '心智圖',
      cat_er: 'ER 圖',
      groupBasic: '基礎圖形',
      groupFlow: '流程符號',
      groupBpmn: '泳道與 BPMN',
      shape_rect: '過程',
      shape_startEnd: '開始/結束',
      shape_decision: '判斷',
      shape_data: '資料',
      shape_swimlane: '橫向泳道',
      shape_swimlaneV: '縱向泳道',
      shape_bpmnTask: 'BPMN 任務',
      canvasAria: '流程圖畫布',
      emptyHint: '從左側拖入圖形，或選擇一個模板開始',
      showGuide: '查看快速上手',
      onboardingTitle: '快速上手',
      onboardingStepPalette:
        '從左側「圖形庫」點擊或拖入圖形到畫布；也可以插入圖片、圖示、公式與表格。',
      onboardingStepConnect: '把指標移到圖形邊緣，拖曳藍色錨點或四向快連箭頭即可連線。',
      onboardingStepArrange: '選取多個元素後，用右側「排列」面板對齊、等距分佈與統一尺寸。',
      onboardingStepExport:
        '頂部「匯出」支援 PNG / SVG（向量）/ PDF / Draw.io / Mermaid 與分頁列印。',
      onboardingSkip: '略過',
      onboardingNext: '下一步',
      onboardingDone: '開始使用',
      nodesLabel: '節點',
      edgesLabel: '連線',
      saved: '已儲存至本機草稿',
      saving: '停止編輯後自動儲存',
      noSelection: '未選取元素',
      selected: '已選取 {{count}} 個元素',
      fill: '填滿色彩',
      stroke: '外框色彩',
      strokeWidth: '線條寬度',
      fontSize: '字級',
      bold: '粗體',
      italic: '斜體',
      align: '對齊',
      alignLeft: '靠左',
      alignCenter: '置中',
      alignRight: '靠右',
      label: '文字',
      edgeLabel: '連線文字',
      templateTitle: '選擇模板',
      templateBasic: '基礎流程',
      templateDecision: '判斷流程',
      templateSwimlane: '橫向泳道流程',
      templateSwimlaneV: '縱向泳道流程',
      templateBpmn: 'BPMN 骨架',
      templateHint: '載入模板將取代目前畫布內容',
      exportPanel: '匯出',
      importFile: '匯入',
      scale: '解析度',
      transparentBg: '透明背景',
      onlySelected: '僅匯出選取',
      padding: '邊距',
      exportRange: '匯出範圍',
      rangeCurrent: '目前頁面',
      rangeAll: '全部頁面',
      exporting: '匯出中…',
      snapToGrid: '網格吸附',
      gridSize: '網格',
      layoutDirection: '佈局方向',
      layoutDensity: '佈局間距',
      densityCompact: '緊湊',
      densityNormal: '標準',
      densityLoose: '寬鬆',
      alignTolerance: '對齊閾值',
      dirTB: '由上而下',
      dirBT: '由下而上',
      dirLR: '由左而右',
      dirRL: '由右而左',
      mixed: '混合',
      nodesSelected: '已選取 {{count}} 個節點',
      importHint: '支援 .flow.json / .drawio / .mmd',
      waypoints: '折點',
      waypoint: '折點',
      waypointCount: '{{count}} 個',
      waypointHint: '拖動橙色方塊調整折點，雙擊刪除；點擊藍色圓點插入折點',
      autoRoute: '正交自動佈線',
      routeAll: '全頁佈線',
      clearWaypoints: '清除折點',
      addWaypoint: '插入折點',
      removeWaypoint: '刪除折點',
      searchLayer: '搜尋圖層',
      moveOut: '移出容器',
      dropToRoot: '拖到此處移出容器',
      insertImage: '插入圖片',
      insertIcon: '插入圖示',
      insertFormula: '插入公式',
      insertTable: '插入表格',
      tableInsertRow: '在下方插入行',
      tableInsertCol: '在右側插入欄',
      tableRemoveRow: '刪除該行',
      tableRemoveCol: '刪除該欄',
      tableMerge: '向右合併儲存格',
      tableSplit: '拆分儲存格',
      tableSection: '表格',
      tableRows: '行數',
      tableColumns: '欄數',
      tableHint: '按兩下儲存格編輯文字；選取儲存格後用上方工具列增刪列欄，或合併 / 拆分儲存格。',
      textFormat: '文字格式',
      textFormatPlain: '純文字',
      textFormatMarkdown: 'Markdown',
      formula: '公式',
      imageFailed: '圖片讀取失敗',
      draftTooLarge: '草稿體積過大：圖片未儲存到本機草稿，請改用「匯出專案檔」',
      iconGroup_general: '一般',
      iconGroup_office: '文件辦公',
      iconGroup_tech: '裝置技術',
      iconGroup_people: '人物協作',
      quickConnect: '快速連線',
      reconnectSource: '重連起點',
      reconnectTarget: '重連終點',
      defaultPageName: '頁面 {{n}}',
      layers: '圖層',
      history: '歷史',
      addPage: '新增頁面',
      prevPage: '上一頁',
      nextPage: '下一頁',
      pageOverview: '頁面總覽',
      openPageOverview: '開啟頁面總覽',
      closeOverview: '關閉總覽',
      removePage: '刪除頁面',
      emptyPage: '空白頁',
      movePageLeft: '左移',
      movePageRight: '右移',
      pageCounter: '第 {{current}} / {{total}} 頁',
      noLayer: '畫布上還沒有元素',
      noSnapshot: '還沒有儲存任何快照',
      saveSnapshot: '儲存',
      snapshotName: '快照名稱',
      restore: '回滾',
      toggleVisible: '顯示 / 隱藏',
      toggleLock: '鎖定 / 解鎖',
      renameHint: '雙擊可重新命名',
      alignTop: '頂對齊',
      alignMiddle: '垂直置中',
      alignBottom: '底對齊',
      distributeH: '水平等距分布',
      distributeV: '垂直等距分布',
      uniformSize: '統一尺寸',
      arrangePanel: '排列',
      arrangeScope: '對齊參照',
      scopeSelection: '選取元素',
      scopeCanvas: '畫布內容',
      scopePage: '頁面紙張',
      distributeSpacing: '等間距',
      distributeEdges: '貼合兩端',
      snapSelectionToGrid: '對齊到網格',
      closeDialog: '關閉',
      contextMenu: '右鍵選單',
      switchShape: '切換形狀',
      paste: '貼上',
      selectAll: '全選',
      deselect: '取消選取',
      geometry: '幾何',
      posX: 'X 座標',
      posY: 'Y 座標',
      geoWidth: '寬度',
      geoHeight: '高度',
      layerFront: '置於頂層',
      layerForward: '上移一層',
      layerBackward: '下移一層',
      layerBack: '置於底層',
      group: '編組',
      ungroup: '解組',
      edgeStyle: '連線樣式',
      edgeType: '線型',
      edgeDash: '線條',
      edgeStartArrow: '起點',
      edgeEndArrow: '終點',
      straight: '直線',
      bezier: '曲線',
      smoothstep: '圓角折線',
      step: '直角折線',
      solid: '實線',
      dashed: '虛線',
      dotted: '點線',
      arrowNone: '無',
      arrowArrow: '箭頭',
      arrowCircle: '圓點',
      arrowTriangle: '空心三角',
      arrowDiamondHollow: '空心菱形',
      templateUmlUseCase: '用例圖',
      templateUmlClass: '類別圖',
      templateUmlSequence: '時序圖',
      templateUmlActivity: '活動圖',
      templateUmlState: '狀態圖',
      templateBpmnProcess: '業務流程',
      templateNetTopology: '網路拓撲',
      templateOrgChart: '組織架構圖',
      templateMindMap: '心智圖',
      templateErDiagram: 'ER 圖',
      templateApproval: '審批流程',
      templateOnboarding: '入職流程',
      templateSwimlane2: '雙泳道流程',
      templateUmlComponent: '元件圖',
      templateBpmnCollab: '協作流程',
      templateNetSubnet: '子網拓撲',
      theme: '主題',
      themeDefault: '預設',
      themeBusiness: '商務藍',
      themeMinimal: '極簡灰',
      themeDark: '暗色',
      applyThemeAll: '套用到全部',
      applyThemeSelection: '套用到選取',
      formatBrush: '複製樣式',
      applyStyle: '貼上樣式',
      exportPrintPdf: '分頁列印 PDF',
      printLandscape: '橫向列印',
      shapeParams: '形狀參數',
      shapeParamHint: '拖曳琥珀色調整頂點，或使用滑桿/輸入框微調',
      reset: '重設',
      shapeParam: {
        cornerRadius: '圓角大小',
        foldSize: '折角大小',
        skew: '斜切',
        inset: '內縮',
        capHeight: '頂蓋高度',
        waveHeight: '波浪高度',
        chevronDepth: '箭頭深度',
        barWidth: '豎線寬度',
        roofHeight: '屋脊高度',
        loopNotch: '缺角大小',
        lifelineHeader: '標題框高度',
        tabHeight: '標籤高度',
        componentTab: '凸塊寬度',
        partitionHeader: '左欄寬度',
        cubeDepth: '立體深度',
        starInner: '內徑比例',
        plusArm: '臂厚度',
        calloutTail: '尾巴高度',
        arrowHead: '箭頭長度',
        bracketArm: '括號厚度',
        annotationBracket: '括號寬度',
        dividerTop: '上分欄線',
        dividerBottom: '下分欄線',
        laneHeader: '標題條厚度',
        activeClassInset: '雙線間距',
        templateTab: '標籤高度',
      },
      transform: '變換',
      rotation: '旋轉角度',
      rotationValue: '角度',
      rotateHint: '拖曳旋轉（15° 吸附，Shift 45°，Alt 自由）',
      rotateCw: '順時針旋轉 90°',
      rotateCcw: '逆時針旋轉 90°',
      flipH: '水平翻轉',
      flipV: '垂直翻轉',
      collapseContainer: '折疊容器',
      expandContainer: '展開容器',
      textLayout: '文字排版',
      verticalAlign: '垂直對齊',
      lineHeight: '行高',
      autoShrink: '文字自動縮放',
      labelBackground: '標籤背景',
      link: '超連結',
      linkInvalid: '僅支援 http / https / mailto 連結',
      edgeSourceLabel: '起點標籤',
      edgeTargetLabel: '終點標籤',
      edgeLabelPosition: '標籤位置',
      labelPos_center: '居中',
      labelPos_nearSource: '靠近起點',
      labelPos_nearTarget: '靠近終點',
      relationPreset: '關係預設',
      relationAssociation: '關聯',
      relationGeneralization: '泛化',
      relationRealization: '實現',
      relationDependency: '依賴',
      relationAggregation: '聚合',
      relationComposition: '組合',
      edgeJump: '連線跳線',
      jump_none: '不跳線',
      jump_arc: '弧線跨越',
      pasteFailed: '無法識別剪貼簿中的 draw.io 內容',
      cut: '剪下',
      copy: '複製',
      editText: '編輯文字',
      container: '容器',
      duplicatePage: '複製頁面',
      pageCopySuffix: '副本',
      paperSize: '紙張',
      paper_none: '無邊界',
      paper_a4l: 'A4 橫向',
      paper_a4p: 'A4 縱向',
      paper_a3l: 'A3 橫向',
      paper_letterl: 'Letter 橫向',
      paper_letterp: 'Letter 縱向',
      paper_custom: '自訂',
      wheelMode: '滾輪',
      wheel_pan: '滾輪平移',
      wheel_zoom: '滾輪縮放',
      gridStyle: '網格',
      grid_dots: '點陣',
      grid_lines: '網格線',
      grid_cross: '十字',
      grid_none: '無網格',
      canvasBackground: '背景',
      bgTransparent: '透明',
      rulers: '標尺',
      shortcutHelp: '快速鍵',
      searchNodes: '搜尋',
      searchNodesPlaceholder: '依文字搜尋節點…',
      searchNoResult: '沒有符合的節點',
      scGroupEdit: '編輯',
      scGroupArrange: '排列與變換',
      scGroupCanvas: '畫布與說明',
      scUndo: '復原',
      scRedo: '重做',
      scClipboard: '剪下 / 複製 / 貼上',
      scDuplicate: '原地複製',
      scSelectAll: '全選',
      scDelete: '刪除選取',
      scSave: '儲存草稿',
      scTextNewline: '編輯文字時換行',
      scTextCommit: '提交文字編輯',
      scRotateCw: '順時針旋轉 90°',
      scRotateCcw: '逆時針旋轉 90°',
      scFlipH: '水平翻轉',
      scFlipV: '垂直翻轉',
      scGroup: '編組 / 解組',
      scNudge: '微移選取（⇧ 加速）',
      scSpawnRight: '在右側產生相連節點',
      scSpawnDown: '在下方產生相連節點',
      scRename: '重新命名選取節點',
      scDeselect: '取消選取',
      scSwitchPage: '上一頁 / 下一頁',
      scPan: '平移畫布',
      scZoom: '縮放畫布',
      scHandles: '調整形狀參數 / 旋轉',
      scEditLabel: '就地編輯標籤',
      scHelp: '開啟本說明',
      err: {
        EMPTY: '畫布為空，無法匯出',
        EXPORT_FAILED: '匯出失敗',
        IMPORT_FAILED: '匯入失敗：無法識別該檔案格式',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: '過程',
  roundRect: '圓角矩形',
  ellipse: '橢圓',
  diamond: '菱形',
  parallelogram: '平行四邊形',
  trapezoid: '梯形',
  hexagon: '六邊形',
  cylinder: '圓柱',
  note: '便簽',
  startEnd: '開始/結束',
  decision: '判斷',
  data: '資料',
  document: '文件',
  predefined: '預定義過程',
  manualInput: '手動輸入',
  manualOperation: '人工操作',
  preparation: '準備',
  database: '資料庫',
  display: '顯示',
  onPageConnector: '同頁連接符',
  offPageConnector: '離頁連接符',
  terminator: '終止',
  parallelMode: '並行模式',
  loopLimit: '迴圈上限',
  umlActor: '角色',
  umlNote: '註釋',
  umlBoundary: '邊界',
  umlControl: '控制',
  umlEntity: '實體',
  umlFrame: '圖框',
  umlUseCase: '使用案例',
  umlSubject: '系統邊界',
  umlInclude: '包含關係',
  umlExtend: '擴充關係',
  umlExtensionPoint: '擴充點',
  umlClass: '類別',
  umlInterface: '介面',
  umlEnumeration: '列舉',
  umlDataType: '資料型別',
  umlAbstractClass: '抽象類別',
  umlActiveClass: '主動類別',
  umlTemplateClass: '模板類別',
  umlAssociationClass: '關聯類別',
  umlPackage: '套件',
  umlObject: '物件',
  umlObjectSlot: '物件（含槽）',
  umlModel: '模型',
  umlProfile: '剖面',
  umlLifeline: '生命線',
  umlActivation: '啟用條',
  umlDestroy: '銷毀',
  umlCombinedFragment: '組合片段',
  umlInteractionUse: '互動使用',
  umlStateInvariant: '狀態不變式',
  umlGate: '閘道',
  umlForkJoin: '分岔/會合',
  umlAction: '動作',
  umlActivity: '活動',
  umlDecisionMerge: '判斷/合併',
  umlInitialNode: '起始節點',
  umlActivityFinal: '活動結束',
  umlFlowFinal: '流程結束',
  umlObjectNode: '物件節點',
  umlSendSignal: '傳送訊號',
  umlReceiveSignal: '接收訊號',
  umlActivityPartition: '活動分區',
  umlState: '狀態',
  umlStateInitial: '初始狀態',
  umlStateFinal: '終止狀態',
  umlChoice: '選擇',
  umlJunction: '匯合點',
  umlTerminate: '終止',
  umlEntryPoint: '進入點',
  umlExitPoint: '離開點',
  umlHistory: '淺歷史',
  umlHistoryDeep: '深歷史',
  umlCompositeState: '組合狀態',
  umlComponent: '組件',
  umlProvidedInterface: '提供介面',
  umlRequiredInterface: '需求介面',
  umlPort: '埠',
  umlSubsystem: '子系統',
  umlNode: '節點',
  umlDevice: '裝置',
  umlExecutionEnvironment: '執行環境',
  umlArtifact: '成品',
  umlDeploymentSpec: '部署規格',
  bpmnEventStart: '開始事件',
  bpmnEventIntermediate: '中間事件',
  bpmnEventEnd: '結束事件',
  bpmnGatewayExclusive: '排他閘道',
  bpmnGatewayParallel: '平行閘道',
  bpmnGatewayInclusive: '包容閘道',
  bpmnTask: '任務',
  bpmnSubProcess: '子流程',
  bpmnCallActivity: '呼叫活動',
  bpmnDataObject: '資料物件',
  bpmnDataStore: '資料儲存',
  bpmnTextAnnotation: '文字註解',
  netServer: '伺服器',
  netClient: '用戶端',
  netRouter: '路由器',
  netSwitch: '交換器',
  netFirewall: '防火牆',
  netLoadBalancer: '負載平衡',
  netCloud: '雲端',
  netCdn: 'CDN',
  netDatabase: '資料庫',
  netStorage: '儲存',
  orgUnit: '組織單位',
  orgAssistant: '助理',
  orgTeam: '團隊',
  mindCenter: '中心主題',
  mindTopic: '子主題',
  mindSub: '次主題',
  erEntity: '實體',
  erAttribute: '屬性',
  erRelationship: '關聯',
  erWeakEntity: '弱實體',
  swimlane: '橫向泳道',
  swimlaneV: '縱向泳道',
  group: '群組',
  triangle: '三角形',
  star: '星形',
  pentagon: '五邊形',
  octagon: '八邊形',
  chevron: '箭頭',
  card: '卡片',
  callout: '標註',
  cloud: '雲',
  cross: '叉號',
  plus: '加號',
  flag: '旗幟',
  lightning: '閃電',
  arrow: '箭頭圖形',
  bracket: '方括號',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
