/**
 * zhTW 文案：UI 文案 + 图形名（84 个图形）。
 * 由 `strings/index.ts` 按需 import() 合并注册，键路径 `tools.flowchart.*`。
 */

import type { LangBundle, ResourceTree } from './types';

const ui: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新增畫布',
      docTitle: '流程圖標題',
      present: '放映',
      exitPresent: '結束放映（Esc）',
      presentLoading: '正在產生放映畫面…',
      presentFailed: '放映畫面產生失敗',
      titlePlaceholder: '未命名流程圖',
      clear: '清空',
      exportPng: '匯出 PNG',
      exportSvg: '匯出 SVG',
      templates: '模板',
      autoLayout: '自動排版',
      fitView: '畫布適應',
      zoomActual: '實際大小',
      undo: '復原',
      redo: '重做',
      duplicate: '複製',
      delete: '刪除',
      panelTitle: '屬性',
      paletteTitle: '圖形庫',
      searchShape: '搜尋圖形',
      noShape: '沒有符合的圖形',
      resizeSidebar: '拖拽調整側邊欄寬度',
      cat_general: '通用圖形',
      cat_flow: '流程圖',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: '網路與雲',
      cat_org: '組織結構',
      cat_mind: '心智圖',
      cat_er: 'ER 圖',
      groupBasic: '基礎圖形',
      groupFlow: '流程符號',
      groupBpmn: '泳道與 BPMN',
      shape_rect: '過程',
      shape_startEnd: '開始/結束',
      shape_decision: '判斷',
      shape_data: '資料',
      shape_swimlane: '橫向泳道',
      shape_swimlaneV: '縱向泳道',
      shape_bpmnTask: 'BPMN 任務',
      canvasAria: '流程圖畫布',
      emptyHint: '從左側拖入圖形，或選擇一個模板開始',
      nodesLabel: '節點',
      edgesLabel: '連線',
      saved: '已儲存至本機草稿',
      saving: '停止編輯後自動儲存',
      noSelection: '未選取元素',
      selected: '已選取 {{count}} 個元素',
      fill: '填滿色彩',
      stroke: '外框色彩',
      strokeWidth: '線條寬度',
      fontSize: '字級',
      bold: '粗體',
      italic: '斜體',
      align: '對齊',
      alignLeft: '靠左',
      alignCenter: '置中',
      alignRight: '靠右',
      label: '文字',
      edgeLabel: '連線文字',
      templateTitle: '選擇模板',
      templateBasic: '基礎流程',
      templateDecision: '判斷流程',
      templateSwimlane: '橫向泳道流程',
      templateSwimlaneV: '縱向泳道流程',
      templateBpmn: 'BPMN 骨架',
      templateHint: '載入模板將取代目前畫布內容',
      exportPanel: '匯出',
      importFile: '匯入',
      scale: '解析度',
      transparentBg: '透明背景',
      onlySelected: '僅匯出選取',
      padding: '邊距',
      exportRange: '匯出範圍',
      rangeCurrent: '目前頁面',
      rangeAll: '全部頁面',
      exporting: '匯出中…',
      snapToGrid: '網格吸附',
      gridSize: '網格',
      layoutDirection: '佈局方向',
      layoutDensity: '佈局間距',
      densityCompact: '緊湊',
      densityNormal: '標準',
      densityLoose: '寬鬆',
      alignTolerance: '對齊閾值',
      dirTB: '由上而下',
      dirBT: '由下而上',
      dirLR: '由左而右',
      dirRL: '由右而左',
      mixed: '混合',
      nodesSelected: '已選取 {{count}} 個節點',
      importHint: '支援 .flow.json / .drawio / .mmd',
      waypoints: '折點',
      waypoint: '折點',
      waypointCount: '{{count}} 個',
      waypointHint: '拖動橙色方塊調整折點，雙擊刪除；點擊藍色圓點插入折點',
      autoRoute: '正交自動佈線',
      clearWaypoints: '清除折點',
      addWaypoint: '插入折點',
      removeWaypoint: '刪除折點',
      searchLayer: '搜尋圖層',
      moveOut: '移出容器',
      dropToRoot: '拖到此處移出容器',
      insertImage: '插入圖片',
      insertIcon: '插入圖示',
      insertFormula: '插入公式',
      formula: '公式',
      imageFailed: '圖片讀取失敗',
      draftTooLarge: '草稿體積過大：圖片未儲存到本機草稿，請改用「匯出專案檔」',
      iconGroup_general: '一般',
      iconGroup_office: '文件辦公',
      iconGroup_tech: '裝置技術',
      iconGroup_people: '人物協作',
      quickConnect: '快速連線',
      reconnectSource: '重連起點',
      reconnectTarget: '重連終點',
      defaultPageName: '頁面 {{n}}',
      layers: '圖層',
      history: '歷史',
      addPage: '新增頁面',
      prevPage: '上一頁',
      nextPage: '下一頁',
      pageOverview: '頁面總覽',
      openPageOverview: '開啟頁面總覽',
      closeOverview: '關閉總覽',
      removePage: '刪除頁面',
      emptyPage: '空白頁',
      movePageLeft: '左移',
      movePageRight: '右移',
      pageCounter: '第 {{current}} / {{total}} 頁',
      noLayer: '畫布上還沒有元素',
      noSnapshot: '還沒有儲存任何快照',
      saveSnapshot: '儲存',
      snapshotName: '快照名稱',
      restore: '回滾',
      toggleVisible: '顯示 / 隱藏',
      toggleLock: '鎖定 / 解鎖',
      renameHint: '雙擊可重新命名',
      alignTop: '頂對齊',
      alignMiddle: '垂直置中',
      alignBottom: '底對齊',
      distributeH: '水平等距分布',
      distributeV: '垂直等距分布',
      layerFront: '置於頂層',
      layerForward: '上移一層',
      layerBackward: '下移一層',
      layerBack: '置於底層',
      group: '編組',
      ungroup: '解組',
      edgeStyle: '連線樣式',
      edgeType: '線型',
      edgeDash: '線條',
      edgeStartArrow: '起點',
      edgeEndArrow: '終點',
      straight: '直線',
      bezier: '曲線',
      smoothstep: '圓角折線',
      step: '直角折線',
      solid: '實線',
      dashed: '虛線',
      dotted: '點線',
      arrowNone: '無',
      arrowArrow: '箭頭',
      arrowCircle: '圓點',
      templateUmlUseCase: '用例圖',
      templateUmlClass: '類別圖',
      templateUmlSequence: '時序圖',
      templateUmlActivity: '活動圖',
      templateUmlState: '狀態圖',
      templateBpmnProcess: '業務流程',
      templateNetTopology: '網路拓撲',
      templateOrgChart: '組織架構圖',
      templateMindMap: '心智圖',
      templateErDiagram: 'ER 圖',
      templateApproval: '審批流程',
      templateOnboarding: '入職流程',
      templateSwimlane2: '雙泳道流程',
      templateUmlComponent: '元件圖',
      templateBpmnCollab: '協作流程',
      templateNetSubnet: '子網拓撲',
      theme: '主題',
      themeDefault: '預設',
      themeBusiness: '商務藍',
      themeMinimal: '極簡灰',
      themeDark: '暗色',
      applyThemeAll: '套用到全部',
      applyThemeSelection: '套用到選取',
      formatBrush: '複製樣式',
      applyStyle: '貼上樣式',
      exportPrintPdf: '分頁列印 PDF',
      printLandscape: '橫向列印',
      err: {
        EMPTY: '畫布為空，無法匯出',
        EXPORT_FAILED: '匯出失敗',
        IMPORT_FAILED: '匯入失敗：無法識別該檔案格式',
      },
    },
  },
};

const shapes: Record<string, string> = {
  rect: '過程',
  roundRect: '圓角矩形',
  ellipse: '橢圓',
  diamond: '菱形',
  parallelogram: '平行四邊形',
  trapezoid: '梯形',
  hexagon: '六邊形',
  cylinder: '圓柱',
  note: '便簽',
  startEnd: '開始/結束',
  decision: '判斷',
  data: '資料',
  document: '文件',
  predefined: '預定義過程',
  manualInput: '手動輸入',
  manualOperation: '人工操作',
  preparation: '準備',
  database: '資料庫',
  display: '顯示',
  onPageConnector: '同頁連接符',
  offPageConnector: '離頁連接符',
  terminator: '終止',
  parallelMode: '並行模式',
  loopLimit: '迴圈上限',
  umlActor: '角色',
  umlUseCase: '使用案例',
  umlClass: '類別',
  umlInterface: '介面',
  umlPackage: '套件',
  umlNote: '註釋',
  umlLifeline: '生命線',
  umlState: '狀態',
  umlStateInitial: '初始狀態',
  umlStateFinal: '終止狀態',
  umlForkJoin: '分岔/會合',
  bpmnEventStart: '開始事件',
  bpmnEventIntermediate: '中間事件',
  bpmnEventEnd: '結束事件',
  bpmnGatewayExclusive: '排他閘道',
  bpmnGatewayParallel: '平行閘道',
  bpmnGatewayInclusive: '包容閘道',
  bpmnTask: '任務',
  bpmnSubProcess: '子流程',
  bpmnCallActivity: '呼叫活動',
  bpmnDataObject: '資料物件',
  bpmnDataStore: '資料儲存',
  bpmnTextAnnotation: '文字註解',
  netServer: '伺服器',
  netClient: '用戶端',
  netRouter: '路由器',
  netSwitch: '交換器',
  netFirewall: '防火牆',
  netLoadBalancer: '負載平衡',
  netCloud: '雲端',
  netCdn: 'CDN',
  netDatabase: '資料庫',
  netStorage: '儲存',
  orgUnit: '組織單位',
  orgAssistant: '助理',
  orgTeam: '團隊',
  mindCenter: '中心主題',
  mindTopic: '子主題',
  mindSub: '次主題',
  erEntity: '實體',
  erAttribute: '屬性',
  erRelationship: '關聯',
  erWeakEntity: '弱實體',
  swimlane: '橫向泳道',
  swimlaneV: '縱向泳道',
  group: '群組',
  triangle: '三角形',
  star: '星形',
  pentagon: '五邊形',
  octagon: '八邊形',
  chevron: '箭頭',
  card: '卡片',
  callout: '標註',
  cloud: '雲',
  cross: '叉號',
  plus: '加號',
  flag: '旗幟',
  lightning: '閃電',
  arrow: '箭頭圖形',
  bracket: '方括號',
};

const bundle: LangBundle = { ui, shapes };

export default bundle;
