/**
 * 流程图编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 * 与 slide-editor 保持同一套约定：UI 文案不进首屏语言包，工具被懒加载时由
 * `registerFlowchartStrings` 合并进 i18next，键路径 `tools.flowchart.*`。
 * 工具元数据（名称/描述）仍写在 `core/i18n/locales/*` 的 `toolsMeta` 中。
 */

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { flowchart: StringTree } };

const zh: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新建画布',
      clear: '清空',
      exportPng: '导出 PNG',
      exportSvg: '导出 SVG',
      templates: '模板',
      autoLayout: '自动布局',
      undo: '撤销',
      redo: '重做',
      duplicate: '复制',
      delete: '删除',
      panelTitle: '属性',
      paletteTitle: '图形库',
      groupBasic: '基础图形',
      groupFlow: '流程符号',
      groupBpmn: '泳道与 BPMN',
      shape_rect: '过程',
      shape_startEnd: '开始/结束',
      shape_decision: '判断',
      shape_data: '数据',
      shape_swimlane: '横向泳道',
      shape_swimlaneV: '纵向泳道',
      shape_bpmnTask: 'BPMN 任务',
      canvasAria: '流程图画布',
      emptyHint: '从左侧拖入图形，或选择一个模板开始',
      nodesLabel: '节点',
      edgesLabel: '连线',
      saved: '已保存到本地草稿',
      saving: '停止编辑后自动保存',
      noSelection: '未选中元素',
      selected: '已选中 {{count}} 个元素',
      fill: '填充色',
      stroke: '描边色',
      strokeWidth: '线宽',
      fontSize: '字号',
      bold: '加粗',
      italic: '斜体',
      align: '对齐',
      alignLeft: '左对齐',
      alignCenter: '居中',
      alignRight: '右对齐',
      label: '文字',
      edgeLabel: '连线文字',
      templateTitle: '选择模板',
      templateBasic: '基础流程',
      templateDecision: '判断流程',
      templateSwimlane: '横向泳道流程',
      templateSwimlaneV: '纵向泳道流程',
      templateBpmn: 'BPMN 骨架',
      templateHint: '载入模板将替换当前画布内容',
      err: {
        EMPTY: '画布为空，无法导出',
        EXPORT_FAILED: '导出失败',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'New canvas',
      clear: 'Clear',
      exportPng: 'Export PNG',
      exportSvg: 'Export SVG',
      templates: 'Templates',
      autoLayout: 'Auto layout',
      undo: 'Undo',
      redo: 'Redo',
      duplicate: 'Duplicate',
      delete: 'Delete',
      panelTitle: 'Properties',
      paletteTitle: 'Shapes',
      groupBasic: 'Basic shapes',
      groupFlow: 'Flow symbols',
      groupBpmn: 'Swimlanes & BPMN',
      shape_rect: 'Process',
      shape_startEnd: 'Start / End',
      shape_decision: 'Decision',
      shape_data: 'Data',
      shape_swimlane: 'Horizontal lane',
      shape_swimlaneV: 'Vertical lane',
      shape_bpmnTask: 'BPMN task',
      canvasAria: 'Flowchart canvas',
      emptyHint: 'Drag a shape from the left, or pick a template to start',
      nodesLabel: 'Nodes',
      edgesLabel: 'Edges',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop editing',
      noSelection: 'No element selected',
      selected: '{{count}} elements selected',
      fill: 'Fill',
      stroke: 'Stroke',
      strokeWidth: 'Stroke width',
      fontSize: 'Font size',
      bold: 'Bold',
      italic: 'Italic',
      align: 'Align',
      alignLeft: 'Left',
      alignCenter: 'Center',
      alignRight: 'Right',
      label: 'Text',
      edgeLabel: 'Edge label',
      templateTitle: 'Choose a template',
      templateBasic: 'Basic flow',
      templateDecision: 'Decision flow',
      templateSwimlane: 'Horizontal lane flow',
      templateSwimlaneV: 'Vertical lane flow',
      templateBpmn: 'BPMN skeleton',
      templateHint: 'Loading a template replaces the current canvas',
      err: {
        EMPTY: 'Canvas is empty, nothing to export',
        EXPORT_FAILED: 'Export failed',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新增畫布',
      clear: '清空',
      exportPng: '匯出 PNG',
      exportSvg: '匯出 SVG',
      templates: '模板',
      autoLayout: '自動排版',
      undo: '復原',
      redo: '重做',
      duplicate: '複製',
      delete: '刪除',
      panelTitle: '屬性',
      paletteTitle: '圖形庫',
      groupBasic: '基礎圖形',
      groupFlow: '流程符號',
      groupBpmn: '泳道與 BPMN',
      shape_rect: '過程',
      shape_startEnd: '開始/結束',
      shape_decision: '判斷',
      shape_data: '資料',
      shape_swimlane: '橫向泳道',
      shape_swimlaneV: '縱向泳道',
      shape_bpmnTask: 'BPMN 任務',
      canvasAria: '流程圖畫布',
      emptyHint: '從左側拖入圖形，或選擇一個模板開始',
      nodesLabel: '節點',
      edgesLabel: '連線',
      saved: '已儲存至本機草稿',
      saving: '停止編輯後自動儲存',
      noSelection: '未選取元素',
      selected: '已選取 {{count}} 個元素',
      fill: '填滿色彩',
      stroke: '外框色彩',
      strokeWidth: '線條寬度',
      fontSize: '字級',
      bold: '粗體',
      italic: '斜體',
      align: '對齊',
      alignLeft: '靠左',
      alignCenter: '置中',
      alignRight: '靠右',
      label: '文字',
      edgeLabel: '連線文字',
      templateTitle: '選擇模板',
      templateBasic: '基礎流程',
      templateDecision: '判斷流程',
      templateSwimlane: '橫向泳道流程',
      templateSwimlaneV: '縱向泳道流程',
      templateBpmn: 'BPMN 骨架',
      templateHint: '載入模板將取代目前畫布內容',
      err: {
        EMPTY: '畫布為空，無法匯出',
        EXPORT_FAILED: '匯出失敗',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新規キャンバス',
      clear: 'クリア',
      exportPng: 'PNG 書き出し',
      exportSvg: 'SVG 書き出し',
      templates: 'テンプレート',
      autoLayout: '自動配置',
      undo: '元に戻す',
      redo: 'やり直す',
      duplicate: '複製',
      delete: '削除',
      panelTitle: 'プロパティ',
      paletteTitle: '図形',
      groupBasic: '基本図形',
      groupFlow: 'フロー記号',
      groupBpmn: 'スイムレーンと BPMN',
      shape_rect: '処理',
      shape_startEnd: '開始/終了',
      shape_decision: '判断',
      shape_data: 'データ',
      shape_swimlane: '横スイムレーン',
      shape_swimlaneV: '縦スイムレーン',
      shape_bpmnTask: 'BPMN タスク',
      canvasAria: 'フローチャートキャンバス',
      emptyHint: '左から図形をドラッグするか、テンプレートを選択してください',
      nodesLabel: 'ノード',
      edgesLabel: 'エッジ',
      saved: 'ローカル下書きに保存しました',
      saving: '編集を止めると自動保存します',
      noSelection: '要素が未選択です',
      selected: '{{count}} 個の要素を選択中',
      fill: '塗りつぶし',
      stroke: '枠線',
      strokeWidth: '線の太さ',
      fontSize: '文字サイズ',
      bold: '太字',
      italic: '斜体',
      align: '配置',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      label: 'テキスト',
      edgeLabel: 'エッジラベル',
      templateTitle: 'テンプレートを選択',
      templateBasic: '基本フロー',
      templateDecision: '判断フロー',
      templateSwimlane: '横スイムレーンフロー',
      templateSwimlaneV: '縦スイムレーンフロー',
      templateBpmn: 'BPMN 骨組み',
      templateHint: 'テンプレートを読み込むと現在のキャンバスを置き換えます',
      err: {
        EMPTY: 'キャンバスが空です',
        EXPORT_FAILED: '書き出しに失敗しました',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nouveau canevas',
      clear: 'Effacer',
      exportPng: 'Exporter PNG',
      exportSvg: 'Exporter SVG',
      templates: 'Modèles',
      autoLayout: 'Disposition auto',
      undo: 'Annuler',
      redo: 'Rétablir',
      duplicate: 'Dupliquer',
      delete: 'Supprimer',
      panelTitle: 'Propriétés',
      paletteTitle: 'Formes',
      groupBasic: 'Formes de base',
      groupFlow: 'Symboles de flux',
      groupBpmn: 'Lignes de nage et BPMN',
      shape_rect: 'Processus',
      shape_startEnd: 'Début / Fin',
      shape_decision: 'Décision',
      shape_data: 'Données',
      shape_swimlane: 'Ligne de nage horizontale',
      shape_swimlaneV: 'Ligne de nage verticale',
      shape_bpmnTask: 'Tâche BPMN',
      canvasAria: 'Canevas de diagramme',
      emptyHint: 'Glissez une forme depuis la gauche ou choisissez un modèle',
      nodesLabel: 'Nœuds',
      edgesLabel: 'Liens',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement auto après la saisie',
      noSelection: 'Aucun élément sélectionné',
      selected: '{{count}} éléments sélectionnés',
      fill: 'Remplissage',
      stroke: 'Contour',
      strokeWidth: 'Épaisseur',
      fontSize: 'Taille',
      bold: 'Gras',
      italic: 'Italique',
      align: 'Alignement',
      alignLeft: 'Gauche',
      alignCenter: 'Centre',
      alignRight: 'Droite',
      label: 'Texte',
      edgeLabel: 'Libellé du lien',
      templateTitle: 'Choisir un modèle',
      templateBasic: 'Flux de base',
      templateDecision: 'Flux conditionnel',
      templateSwimlane: 'Flux en lignes horizontales',
      templateSwimlaneV: 'Flux en lignes verticales',
      templateBpmn: 'Squelette BPMN',
      templateHint: 'Charger un modèle remplace le canevas actuel',
      err: {
        EMPTY: 'Le canevas est vide',
        EXPORT_FAILED: "Échec de l'export",
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Neue Fläche',
      clear: 'Leeren',
      exportPng: 'PNG exportieren',
      exportSvg: 'SVG exportieren',
      templates: 'Vorlagen',
      autoLayout: 'Auto-Layout',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      duplicate: 'Duplizieren',
      delete: 'Löschen',
      panelTitle: 'Eigenschaften',
      paletteTitle: 'Formen',
      groupBasic: 'Basisformen',
      groupFlow: 'Flusssymbole',
      groupBpmn: 'Swimlanes & BPMN',
      shape_rect: 'Prozess',
      shape_startEnd: 'Start / Ende',
      shape_decision: 'Entscheidung',
      shape_data: 'Daten',
      shape_swimlane: 'Horizontale Swimlane',
      shape_swimlaneV: 'Vertikale Swimlane',
      shape_bpmnTask: 'BPMN-Aufgabe',
      canvasAria: 'Flussdiagramm-Fläche',
      emptyHint: 'Form von links ziehen oder Vorlage wählen',
      nodesLabel: 'Knoten',
      edgesLabel: 'Kanten',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Bearbeitung',
      noSelection: 'Kein Element ausgewählt',
      selected: '{{count}} Elemente ausgewählt',
      fill: 'Füllung',
      stroke: 'Rahmen',
      strokeWidth: 'Linienstärke',
      fontSize: 'Schriftgröße',
      bold: 'Fett',
      italic: 'Kursiv',
      align: 'Ausrichtung',
      alignLeft: 'Links',
      alignCenter: 'Mitte',
      alignRight: 'Rechts',
      label: 'Text',
      edgeLabel: 'Kantenbeschriftung',
      templateTitle: 'Vorlage wählen',
      templateBasic: 'Basisfluss',
      templateDecision: 'Entscheidungsfluss',
      templateSwimlane: 'Horizontaler Swimlane-Fluss',
      templateSwimlaneV: 'Vertikaler Swimlane-Fluss',
      templateBpmn: 'BPMN-Gerüst',
      templateHint: 'Laden einer Vorlage ersetzt die aktuelle Fläche',
      err: {
        EMPTY: 'Fläche ist leer',
        EXPORT_FAILED: 'Export fehlgeschlagen',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nuova tela',
      clear: 'Pulisci',
      exportPng: 'Esporta PNG',
      exportSvg: 'Esporta SVG',
      templates: 'Modelli',
      autoLayout: 'Disposizione auto',
      undo: 'Annulla',
      redo: 'Ripeti',
      duplicate: 'Duplica',
      delete: 'Elimina',
      panelTitle: 'Proprietà',
      paletteTitle: 'Forme',
      groupBasic: 'Forme base',
      groupFlow: 'Simboli di flusso',
      groupBpmn: 'Swimlane e BPMN',
      shape_rect: 'Processo',
      shape_startEnd: 'Inizio / Fine',
      shape_decision: 'Decisione',
      shape_data: 'Dati',
      shape_swimlane: 'Swimlane orizzontale',
      shape_swimlaneV: 'Swimlane verticale',
      shape_bpmnTask: 'Attività BPMN',
      canvasAria: 'Tela del diagramma',
      emptyHint: 'Trascina una forma da sinistra o scegli un modello',
      nodesLabel: 'Nodi',
      edgesLabel: 'Collegamenti',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la modifica',
      noSelection: 'Nessun elemento selezionato',
      selected: '{{count}} elementi selezionati',
      fill: 'Riempimento',
      stroke: 'Contorno',
      strokeWidth: 'Spessore',
      fontSize: 'Dimensione',
      bold: 'Grassetto',
      italic: 'Corsivo',
      align: 'Allineamento',
      alignLeft: 'Sinistra',
      alignCenter: 'Centro',
      alignRight: 'Destra',
      label: 'Testo',
      edgeLabel: 'Etichetta collegamento',
      templateTitle: 'Scegli un modello',
      templateBasic: 'Flusso base',
      templateDecision: 'Flusso decisionale',
      templateSwimlane: 'Flusso swimlane orizzontale',
      templateSwimlaneV: 'Flusso swimlane verticale',
      templateBpmn: 'Scheletro BPMN',
      templateHint: 'Caricare un modello sostituisce la tela corrente',
      err: {
        EMPTY: 'La tela è vuota',
        EXPORT_FAILED: 'Esportazione non riuscita',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nuevo lienzo',
      clear: 'Vaciar',
      exportPng: 'Exportar PNG',
      exportSvg: 'Exportar SVG',
      templates: 'Plantillas',
      autoLayout: 'Auto diseño',
      undo: 'Deshacer',
      redo: 'Rehacer',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      panelTitle: 'Propiedades',
      paletteTitle: 'Formas',
      groupBasic: 'Formas básicas',
      groupFlow: 'Símbolos de flujo',
      groupBpmn: 'Carriles y BPMN',
      shape_rect: 'Proceso',
      shape_startEnd: 'Inicio / Fin',
      shape_decision: 'Decisión',
      shape_data: 'Datos',
      shape_swimlane: 'Carril horizontal',
      shape_swimlaneV: 'Carril vertical',
      shape_bpmnTask: 'Tarea BPMN',
      canvasAria: 'Lienzo de diagrama',
      emptyHint: 'Arrastra una forma desde la izquierda o elige una plantilla',
      nodesLabel: 'Nodos',
      edgesLabel: 'Enlaces',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de editar',
      noSelection: 'Ningún elemento seleccionado',
      selected: '{{count}} elementos seleccionados',
      fill: 'Relleno',
      stroke: 'Contorno',
      strokeWidth: 'Grosor',
      fontSize: 'Tamaño',
      bold: 'Negrita',
      italic: 'Cursiva',
      align: 'Alineación',
      alignLeft: 'Izquierda',
      alignCenter: 'Centro',
      alignRight: 'Derecha',
      label: 'Texto',
      edgeLabel: 'Etiqueta de enlace',
      templateTitle: 'Elegir plantilla',
      templateBasic: 'Flujo básico',
      templateDecision: 'Flujo de decisión',
      templateSwimlane: 'Flujo de carril horizontal',
      templateSwimlaneV: 'Flujo de carril vertical',
      templateBpmn: 'Esqueleto BPMN',
      templateHint: 'Cargar una plantilla reemplaza el lienzo actual',
      err: {
        EMPTY: 'El lienzo está vacío',
        EXPORT_FAILED: 'Error al exportar',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nova tela',
      clear: 'Limpar',
      exportPng: 'Exportar PNG',
      exportSvg: 'Exportar SVG',
      templates: 'Modelos',
      autoLayout: 'Auto layout',
      undo: 'Anular',
      redo: 'Refazer',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      panelTitle: 'Propriedades',
      paletteTitle: 'Formas',
      groupBasic: 'Formas básicas',
      groupFlow: 'Símbolos de fluxo',
      groupBpmn: 'Raias e BPMN',
      shape_rect: 'Processo',
      shape_startEnd: 'Início / Fim',
      shape_decision: 'Decisão',
      shape_data: 'Dados',
      shape_swimlane: 'Raia horizontal',
      shape_swimlaneV: 'Raia vertical',
      shape_bpmnTask: 'Tarefa BPMN',
      canvasAria: 'Tela do diagrama',
      emptyHint: 'Arraste uma forma da esquerda ou escolha um modelo',
      nodesLabel: 'Nós',
      edgesLabel: 'Ligações',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de editar',
      noSelection: 'Nenhum elemento selecionado',
      selected: '{{count}} elementos selecionados',
      fill: 'Preenchimento',
      stroke: 'Contorno',
      strokeWidth: 'Espessura',
      fontSize: 'Tamanho',
      bold: 'Negrito',
      italic: 'Itálico',
      align: 'Alinhamento',
      alignLeft: 'Esquerda',
      alignCenter: 'Centro',
      alignRight: 'Direita',
      label: 'Texto',
      edgeLabel: 'Etiqueta da ligação',
      templateTitle: 'Escolher modelo',
      templateBasic: 'Fluxo básico',
      templateDecision: 'Fluxo de decisão',
      templateSwimlane: 'Fluxo de raia horizontal',
      templateSwimlaneV: 'Fluxo de raia vertical',
      templateBpmn: 'Esqueleto BPMN',
      templateHint: 'Carregar um modelo substitui a tela atual',
      err: {
        EMPTY: 'A tela está vazia',
        EXPORT_FAILED: 'Falha ao exportar',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const flowchartStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把本工具文案合并进 i18next（工具被懒加载时调用，键路径 tools.flowchart.*） */
export function registerFlowchartStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(flowchartStrings)) {
    instance.addResourceBundle(lng, 'translation', resources, true, true);
  }
}
