/**
 * 流程图编辑器 UI 文案：随工具 chunk 懒加载注入 i18next。
 * 与 slide-editor 保持同一套约定：UI 文案不进首屏语言包，工具被懒加载时由
 * `registerFlowchartStrings` 合并进 i18next，键路径 `tools.flowchart.*`。
 * 工具元数据（名称/描述）仍写在 `core/i18n/locales/*` 的 `toolsMeta` 中。
 */

import { SHAPE_LABELS_I18N } from './model/shapeLabels';

type StringTree = { [key: string]: string | StringTree };
type ResourceTree = { tools: { flowchart: StringTree } };

const zh: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新建画布',
      docTitle: '流程图标题',
      titlePlaceholder: '未命名流程图',
      clear: '清空',
      exportPng: '导出 PNG',
      exportSvg: '导出 SVG',
      templates: '模板',
      autoLayout: '自动布局',
      undo: '撤销',
      redo: '重做',
      duplicate: '复制',
      delete: '删除',
      panelTitle: '属性',
      paletteTitle: '图形库',
      searchShape: '搜索图形',
      noShape: '没有匹配的图形',
      resizeSidebar: '拖拽调整侧边栏宽度',
      exportPanel: '导出',
      importFile: '导入',
      scale: '分辨率',
      transparentBg: '透明背景',
      onlySelected: '仅导出选中',
      layers: '图层',
      history: '历史',
      addPage: '新建页面',
      noLayer: '画布上还没有元素',
      noSnapshot: '还没有保存任何快照',
      saveSnapshot: '保存',
      snapshotName: '快照名称',
      restore: '回滚',
      toggleVisible: '显示/隐藏',
      toggleLock: '锁定/解锁',
      renameHint: '双击可重命名',
      cat_general: '通用图形',
      cat_flow: '流程图',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: '网络与云',
      cat_org: '组织结构',
      cat_mind: '思维导图',
      cat_er: 'ER 图',
      groupBasic: '基础图形',
      groupFlow: '流程符号',
      groupBpmn: '泳道与 BPMN',
      shape_rect: '过程',
      shape_startEnd: '开始/结束',
      shape_decision: '判断',
      shape_data: '数据',
      shape_swimlane: '横向泳道',
      shape_swimlaneV: '纵向泳道',
      shape_bpmnTask: 'BPMN 任务',
      canvasAria: '流程图画布',
      emptyHint: '从左侧拖入图形，或选择一个模板开始',
      nodesLabel: '节点',
      edgesLabel: '连线',
      saved: '已保存到本地草稿',
      saving: '停止编辑后自动保存',
      noSelection: '未选中元素',
      selected: '已选中 {{count}} 个元素',
      fill: '填充色',
      stroke: '描边色',
      strokeWidth: '线宽',
      fontSize: '字号',
      bold: '加粗',
      italic: '斜体',
      align: '对齐',
      alignLeft: '左对齐',
      alignCenter: '居中',
      alignRight: '右对齐',
      alignTop: '顶对齐',
      alignMiddle: '垂直居中',
      alignBottom: '底对齐',
      distributeH: '水平等距分布',
      distributeV: '垂直等距分布',
      layerFront: '置于顶层',
      layerForward: '上移一层',
      layerBackward: '下移一层',
      layerBack: '置于底层',
      group: '编组',
      ungroup: '解组',
      edgeStyle: '连线样式',
      edgeType: '线型',
      edgeDash: '线条',
      edgeStartArrow: '起点箭头',
      edgeEndArrow: '终点箭头',
      edgeSourceNode: '起点节点',
      edgeTargetNode: '终点节点',
      straight: '直线',
      bezier: '曲线',
      smoothstep: '圆角折线',
      step: '直角折线',
      solid: '实线',
      dashed: '虚线',
      dotted: '点线',
      arrowNone: '无',
      arrowArrow: '箭头',
      arrowCircle: '圆点',
      label: '文字',
      edgeLabel: '连线文字',
      templateTitle: '选择模板',
      templateBasic: '基础流程',
      templateDecision: '判断流程',
      templateSwimlane: '横向泳道流程',
      templateSwimlaneV: '纵向泳道流程',
      templateUmlUseCase: '用例图',
      templateUmlClass: '类图',
      templateUmlSequence: '时序图',
      templateUmlActivity: '活动图',
      templateUmlState: '状态图',
      templateBpmnProcess: '业务流程',
      templateNetTopology: '网络拓扑',
      templateOrgChart: '组织结构图',
      templateMindMap: '思维导图',
      templateErDiagram: 'ER 图',
      templateBpmn: 'BPMN 骨架',
      templateHint: '载入模板将替换当前画布内容',
      edgeStyleLabel: '连线样式',
      startArrowLabel: '开始箭头',
      endArrowLabel: '结束箭头',
      dashdot: '点划线',
      sketch: '实线手绘',
      sketchDashed: '虚线手绘',
      arrowSolid: '实心箭头',
      arrowOpen: '空心箭头',
      arrowDiamond: '菱形',
      arrowSquare: '方块',
      arrowBar: '竖线',
      appearance: '外观',
      opacity: '透明度',
      shadow: '阴影',
      textColor: '文字颜色',
      cornerRadius: '圆角大小',
      foldSize: '折角大小',
      fontFamily: '字体',
      err: {
        EMPTY: '画布为空，无法导出',
        EXPORT_FAILED: '导出失败',
        IMPORT_FAILED: '导入失败：无法识别该文件格式',
      },
    },
  },
};

const en: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'New canvas',
      docTitle: 'Diagram title',
      titlePlaceholder: 'Untitled diagram',
      clear: 'Clear',
      exportPng: 'Export PNG',
      exportSvg: 'Export SVG',
      templates: 'Templates',
      autoLayout: 'Auto layout',
      undo: 'Undo',
      redo: 'Redo',
      duplicate: 'Duplicate',
      delete: 'Delete',
      panelTitle: 'Properties',
      paletteTitle: 'Shapes',
      searchShape: 'Search shapes',
      noShape: 'No matching shape',
      resizeSidebar: 'Drag to resize sidebar',
      exportPanel: 'Export',
      importFile: 'Import',
      scale: 'Scale',
      transparentBg: 'Transparent',
      onlySelected: 'Selection only',
      layers: 'Layers',
      history: 'History',
      addPage: 'New page',
      noLayer: 'No elements on the canvas',
      noSnapshot: 'No snapshots saved yet',
      saveSnapshot: 'Save',
      snapshotName: 'Snapshot name',
      restore: 'Restore',
      toggleVisible: 'Show / Hide',
      toggleLock: 'Lock / Unlock',
      renameHint: 'Double-click to rename',
      cat_general: 'General',
      cat_flow: 'Flowchart',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Network & Cloud',
      cat_org: 'Organization',
      cat_mind: 'Mind map',
      cat_er: 'ER diagram',
      groupBasic: 'Basic shapes',
      groupFlow: 'Flow symbols',
      groupBpmn: 'Swimlanes & BPMN',
      shape_rect: 'Process',
      shape_startEnd: 'Start / End',
      shape_decision: 'Decision',
      shape_data: 'Data',
      shape_swimlane: 'Horizontal lane',
      shape_swimlaneV: 'Vertical lane',
      shape_bpmnTask: 'BPMN task',
      canvasAria: 'Flowchart canvas',
      emptyHint: 'Drag a shape from the left, or pick a template to start',
      nodesLabel: 'Nodes',
      edgesLabel: 'Edges',
      saved: 'Saved to local draft',
      saving: 'Auto-saves after you stop editing',
      noSelection: 'No element selected',
      selected: '{{count}} elements selected',
      fill: 'Fill',
      stroke: 'Stroke',
      strokeWidth: 'Stroke width',
      fontSize: 'Font size',
      bold: 'Bold',
      italic: 'Italic',
      align: 'Align',
      alignLeft: 'Left',
      alignCenter: 'Center',
      alignRight: 'Right',
      alignTop: 'Align top',
      alignMiddle: 'Align middle',
      alignBottom: 'Align bottom',
      distributeH: 'Distribute horizontally',
      distributeV: 'Distribute vertically',
      layerFront: 'Bring to front',
      layerForward: 'Bring forward',
      layerBackward: 'Send backward',
      layerBack: 'Send to back',
      group: 'Group',
      ungroup: 'Ungroup',
      edgeStyle: 'Edge style',
      edgeType: 'Line type',
      edgeDash: 'Stroke',
      edgeStartArrow: 'Arrow at start',
      edgeEndArrow: 'Arrow at end',
      edgeSourceNode: 'Source node',
      edgeTargetNode: 'Target node',
      straight: 'Straight',
      bezier: 'Bezier',
      smoothstep: 'Rounded step',
      step: 'Right-angle step',
      solid: 'Solid',
      dashed: 'Dashed',
      dotted: 'Dotted',
      arrowNone: 'None',
      arrowArrow: 'Arrow',
      arrowCircle: 'Circle',
      label: 'Text',
      edgeLabel: 'Edge label',
      templateTitle: 'Choose a template',
      templateBasic: 'Basic flow',
      templateDecision: 'Decision flow',
      templateSwimlane: 'Horizontal lane flow',
      templateSwimlaneV: 'Vertical lane flow',
      templateUmlUseCase: 'Use case diagram',
      templateUmlClass: 'Class diagram',
      templateUmlSequence: 'Sequence diagram',
      templateUmlActivity: 'Activity diagram',
      templateUmlState: 'State diagram',
      templateBpmnProcess: 'Business process',
      templateNetTopology: 'Network topology',
      templateOrgChart: 'Organization chart',
      templateMindMap: 'Mind map',
      templateErDiagram: 'ER diagram',
      templateBpmn: 'BPMN skeleton',
      templateHint: 'Loading a template replaces the current canvas',
      edgeStyleLabel: 'Edge style',
      startArrowLabel: 'Start arrow',
      endArrowLabel: 'End arrow',
      dashdot: 'Dash-dot',
      sketch: 'Sketch',
      sketchDashed: 'Sketch dashed',
      arrowSolid: 'Solid arrow',
      arrowOpen: 'Open arrow',
      arrowDiamond: 'Diamond',
      arrowSquare: 'Square',
      arrowBar: 'Bar',
      appearance: 'Appearance',
      opacity: 'Opacity',
      shadow: 'Shadow',
      textColor: 'Text color',
      cornerRadius: 'Corner radius',
      foldSize: 'Fold size',
      fontFamily: 'Font',
      err: {
        EMPTY: 'Canvas is empty, nothing to export',
        EXPORT_FAILED: 'Export failed',
        IMPORT_FAILED: 'Import failed: unsupported file format',
      },
    },
  },
};

const zhTW: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新增畫布',
      docTitle: '流程圖標題',
      titlePlaceholder: '未命名流程圖',
      clear: '清空',
      exportPng: '匯出 PNG',
      exportSvg: '匯出 SVG',
      templates: '模板',
      autoLayout: '自動排版',
      undo: '復原',
      redo: '重做',
      duplicate: '複製',
      delete: '刪除',
      panelTitle: '屬性',
      paletteTitle: '圖形庫',
      searchShape: '搜尋圖形',
      noShape: '沒有符合的圖形',
      resizeSidebar: '拖拽調整側邊欄寬度',
      cat_general: '通用圖形',
      cat_flow: '流程圖',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: '網路與雲',
      cat_org: '組織結構',
      cat_mind: '心智圖',
      cat_er: 'ER 圖',
      groupBasic: '基礎圖形',
      groupFlow: '流程符號',
      groupBpmn: '泳道與 BPMN',
      shape_rect: '過程',
      shape_startEnd: '開始/結束',
      shape_decision: '判斷',
      shape_data: '資料',
      shape_swimlane: '橫向泳道',
      shape_swimlaneV: '縱向泳道',
      shape_bpmnTask: 'BPMN 任務',
      canvasAria: '流程圖畫布',
      emptyHint: '從左側拖入圖形，或選擇一個模板開始',
      nodesLabel: '節點',
      edgesLabel: '連線',
      saved: '已儲存至本機草稿',
      saving: '停止編輯後自動儲存',
      noSelection: '未選取元素',
      selected: '已選取 {{count}} 個元素',
      fill: '填滿色彩',
      stroke: '外框色彩',
      strokeWidth: '線條寬度',
      fontSize: '字級',
      bold: '粗體',
      italic: '斜體',
      align: '對齊',
      alignLeft: '靠左',
      alignCenter: '置中',
      alignRight: '靠右',
      label: '文字',
      edgeLabel: '連線文字',
      templateTitle: '選擇模板',
      templateBasic: '基礎流程',
      templateDecision: '判斷流程',
      templateSwimlane: '橫向泳道流程',
      templateSwimlaneV: '縱向泳道流程',
      templateBpmn: 'BPMN 骨架',
      templateHint: '載入模板將取代目前畫布內容',
      exportPanel: '匯出',
      importFile: '匯入',
      scale: '解析度',
      transparentBg: '透明背景',
      onlySelected: '僅匯出選取',
      layers: '圖層',
      history: '歷史',
      addPage: '新增頁面',
      noLayer: '畫布上還沒有元素',
      noSnapshot: '還沒有儲存任何快照',
      saveSnapshot: '儲存',
      snapshotName: '快照名稱',
      restore: '回滾',
      toggleVisible: '顯示 / 隱藏',
      toggleLock: '鎖定 / 解鎖',
      renameHint: '雙擊可重新命名',
      alignTop: '頂對齊',
      alignMiddle: '垂直置中',
      alignBottom: '底對齊',
      distributeH: '水平等距分布',
      distributeV: '垂直等距分布',
      layerFront: '置於頂層',
      layerForward: '上移一層',
      layerBackward: '下移一層',
      layerBack: '置於底層',
      group: '編組',
      ungroup: '解組',
      edgeStyle: '連線樣式',
      edgeType: '線型',
      edgeDash: '線條',
      edgeStartArrow: '起點',
      edgeEndArrow: '終點',
      straight: '直線',
      bezier: '曲線',
      smoothstep: '圓角折線',
      step: '直角折線',
      solid: '實線',
      dashed: '虛線',
      dotted: '點線',
      arrowNone: '無',
      arrowArrow: '箭頭',
      arrowCircle: '圓點',
      templateUmlUseCase: '用例圖',
      templateUmlClass: '類別圖',
      templateUmlSequence: '時序圖',
      templateUmlActivity: '活動圖',
      templateUmlState: '狀態圖',
      templateBpmnProcess: '業務流程',
      templateNetTopology: '網路拓撲',
      templateOrgChart: '組織架構圖',
      templateMindMap: '心智圖',
      templateErDiagram: 'ER 圖',
      err: {
        EMPTY: '畫布為空，無法匯出',
        EXPORT_FAILED: '匯出失敗',
        IMPORT_FAILED: '匯入失敗：無法識別該檔案格式',
      },
    },
  },
};

const ja: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: '新規キャンバス',
      docTitle: 'フローチャートのタイトル',
      titlePlaceholder: '無題のフローチャート',
      clear: 'クリア',
      exportPng: 'PNG 書き出し',
      exportSvg: 'SVG 書き出し',
      templates: 'テンプレート',
      autoLayout: '自動配置',
      undo: '元に戻す',
      redo: 'やり直す',
      duplicate: '複製',
      delete: '削除',
      panelTitle: 'プロパティ',
      paletteTitle: '図形',
      searchShape: '図形を検索',
      noShape: '一致する図形なし',
      resizeSidebar: 'ドラッグでサイドバーの幅を調整',
      cat_general: '基本図形',
      cat_flow: 'フローチャート',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'ネットワークとクラウド',
      cat_org: '組織図',
      cat_mind: 'マインドマップ',
      cat_er: 'ER 図',
      groupBasic: '基本図形',
      groupFlow: 'フロー記号',
      groupBpmn: 'スイムレーンと BPMN',
      shape_rect: '処理',
      shape_startEnd: '開始/終了',
      shape_decision: '判断',
      shape_data: 'データ',
      shape_swimlane: '横スイムレーン',
      shape_swimlaneV: '縦スイムレーン',
      shape_bpmnTask: 'BPMN タスク',
      canvasAria: 'フローチャートキャンバス',
      emptyHint: '左から図形をドラッグするか、テンプレートを選択してください',
      nodesLabel: 'ノード',
      edgesLabel: 'エッジ',
      saved: 'ローカル下書きに保存しました',
      saving: '編集を止めると自動保存します',
      noSelection: '要素が未選択です',
      selected: '{{count}} 個の要素を選択中',
      fill: '塗りつぶし',
      stroke: '枠線',
      strokeWidth: '線の太さ',
      fontSize: '文字サイズ',
      bold: '太字',
      italic: '斜体',
      align: '配置',
      alignLeft: '左揃え',
      alignCenter: '中央揃え',
      alignRight: '右揃え',
      label: 'テキスト',
      edgeLabel: 'エッジラベル',
      templateTitle: 'テンプレートを選択',
      templateBasic: '基本フロー',
      templateDecision: '判断フロー',
      templateSwimlane: '横スイムレーンフロー',
      templateSwimlaneV: '縦スイムレーンフロー',
      templateBpmn: 'BPMN 骨組み',
      templateHint: 'テンプレートを読み込むと現在のキャンバスを置き換えます',
      exportPanel: '書き出し',
      importFile: '読み込み',
      scale: '倍率',
      transparentBg: '透過背景',
      onlySelected: '選択のみ',
      layers: 'レイヤー',
      history: '履歴',
      addPage: '新規ページ',
      noLayer: 'キャンバスに要素がありません',
      noSnapshot: 'スナップショットはまだ保存されていません',
      saveSnapshot: '保存',
      snapshotName: 'スナップショット名',
      restore: '復元',
      toggleVisible: '表示 / 非表示',
      toggleLock: 'ロック / ロック解除',
      renameHint: 'ダブルクリックで名前変更',
      alignTop: '上揃え',
      alignMiddle: '垂直中央揃え',
      alignBottom: '下揃え',
      distributeH: '水平に等間隔配置',
      distributeV: '垂直に等間隔配置',
      layerFront: '最前面へ',
      layerForward: '前面へ',
      layerBackward: '背面へ',
      layerBack: '最背面へ',
      group: 'グループ化',
      ungroup: 'グループ解除',
      edgeStyle: 'エッジのスタイル',
      edgeType: '線の種類',
      edgeDash: '線種',
      edgeStartArrow: '開始',
      edgeEndArrow: '終了',
      straight: '直線',
      bezier: 'ベジェ',
      smoothstep: '角丸折れ線',
      step: '直角折れ線',
      solid: '実線',
      dashed: '破線',
      dotted: '点線',
      arrowNone: 'なし',
      arrowArrow: '矢印',
      arrowCircle: '丸',
      templateUmlUseCase: 'ユースケース図',
      templateUmlClass: 'クラス図',
      templateUmlSequence: 'シーケンス図',
      templateUmlActivity: 'アクティビティ図',
      templateUmlState: 'ステート図',
      templateBpmnProcess: 'ビジネスプロセス',
      templateNetTopology: 'ネットワークトポロジ',
      templateOrgChart: '組織図',
      templateMindMap: 'マインドマップ',
      templateErDiagram: 'ER 図',
      err: {
        EMPTY: 'キャンバスが空です',
        EXPORT_FAILED: '書き出しに失敗しました',
        IMPORT_FAILED: '読み込みに失敗しました：ファイル形式を認識できません',
      },
    },
  },
};

const fr: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nouveau canevas',
      docTitle: 'Titre du diagramme',
      titlePlaceholder: 'Diagramme sans titre',
      clear: 'Effacer',
      exportPng: 'Exporter PNG',
      exportSvg: 'Exporter SVG',
      templates: 'Modèles',
      autoLayout: 'Disposition auto',
      undo: 'Annuler',
      redo: 'Rétablir',
      duplicate: 'Dupliquer',
      delete: 'Supprimer',
      panelTitle: 'Propriétés',
      paletteTitle: 'Formes',
      searchShape: 'Rechercher une forme',
      noShape: 'Aucune forme correspondante',
      resizeSidebar: 'Glissez pour redimensionner le panneau',
      cat_general: 'Général',
      cat_flow: 'Diagramme',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Réseau & Cloud',
      cat_org: 'Organisation',
      cat_mind: 'Carte mentale',
      cat_er: 'Diagramme ER',
      groupBasic: 'Formes de base',
      groupFlow: 'Symboles de flux',
      groupBpmn: 'Lignes de nage et BPMN',
      shape_rect: 'Processus',
      shape_startEnd: 'Début / Fin',
      shape_decision: 'Décision',
      shape_data: 'Données',
      shape_swimlane: 'Ligne de nage horizontale',
      shape_swimlaneV: 'Ligne de nage verticale',
      shape_bpmnTask: 'Tâche BPMN',
      canvasAria: 'Canevas de diagramme',
      emptyHint: 'Glissez une forme depuis la gauche ou choisissez un modèle',
      nodesLabel: 'Nœuds',
      edgesLabel: 'Liens',
      saved: 'Enregistré dans le brouillon local',
      saving: 'Enregistrement auto après la saisie',
      noSelection: 'Aucun élément sélectionné',
      selected: '{{count}} éléments sélectionnés',
      fill: 'Remplissage',
      stroke: 'Contour',
      strokeWidth: 'Épaisseur',
      fontSize: 'Taille',
      bold: 'Gras',
      italic: 'Italique',
      align: 'Alignement',
      alignLeft: 'Gauche',
      alignCenter: 'Centre',
      alignRight: 'Droite',
      label: 'Texte',
      edgeLabel: 'Libellé du lien',
      templateTitle: 'Choisir un modèle',
      templateBasic: 'Flux de base',
      templateDecision: 'Flux conditionnel',
      templateSwimlane: 'Flux en lignes horizontales',
      templateSwimlaneV: 'Flux en lignes verticales',
      templateBpmn: 'Squelette BPMN',
      templateHint: 'Charger un modèle remplace le canevas actuel',
      exportPanel: 'Exporter',
      importFile: 'Importer',
      scale: 'Échelle',
      transparentBg: 'Transparent',
      onlySelected: 'Sélection uniquement',
      layers: 'Calques',
      history: 'Historique',
      addPage: 'Nouvelle page',
      noLayer: 'Aucun élément sur le canevas',
      noSnapshot: 'Aucun instantané enregistré',
      saveSnapshot: 'Enregistrer',
      snapshotName: "Nom de l'instantané",
      restore: 'Restaurer',
      toggleVisible: 'Afficher / Masquer',
      toggleLock: 'Verrouiller / Déverrouiller',
      renameHint: 'Double-cliquez pour renommer',
      alignTop: 'Aligner en haut',
      alignMiddle: 'Aligner au centre',
      alignBottom: 'Aligner en bas',
      distributeH: 'Distribuer horizontalement',
      distributeV: 'Distribuer verticalement',
      layerFront: 'Mettre au premier plan',
      layerForward: 'Avancer',
      layerBackward: 'Reculer',
      layerBack: 'Mettre en arrière-plan',
      group: 'Grouper',
      ungroup: 'Dissocier',
      edgeStyle: 'Style du lien',
      edgeType: 'Type de ligne',
      edgeDash: 'Trait',
      edgeStartArrow: 'Début',
      edgeEndArrow: 'Fin',
      straight: 'Ligne droite',
      bezier: 'Bézier',
      smoothstep: 'Ligne brisée arrondie',
      step: 'Ligne brisée à angle droit',
      solid: 'Pleine',
      dashed: 'Tirets',
      dotted: 'Pointillés',
      arrowNone: 'Aucune',
      arrowArrow: 'Flèche',
      arrowCircle: 'Rond',
      templateUmlUseCase: 'Diagramme de cas d’usage',
      templateUmlClass: 'Diagramme de classes',
      templateUmlSequence: 'Diagramme de séquence',
      templateUmlActivity: 'Diagramme d’activité',
      templateUmlState: 'Diagramme d’états',
      templateBpmnProcess: 'Processus métier',
      templateNetTopology: 'Topologie réseau',
      templateOrgChart: 'Organigramme',
      templateMindMap: 'Carte mentale',
      templateErDiagram: 'Diagramme ER',
      err: {
        EMPTY: 'Le canevas est vide',
        EXPORT_FAILED: "Échec de l'export",
        IMPORT_FAILED: 'Échec de l’import : format de fichier non reconnu',
      },
    },
  },
};

const de: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Neue Fläche',
      docTitle: 'Diagrammtitel',
      titlePlaceholder: 'Unbenanntes Diagramm',
      clear: 'Leeren',
      exportPng: 'PNG exportieren',
      exportSvg: 'SVG exportieren',
      templates: 'Vorlagen',
      autoLayout: 'Auto-Layout',
      undo: 'Rückgängig',
      redo: 'Wiederholen',
      duplicate: 'Duplizieren',
      delete: 'Löschen',
      panelTitle: 'Eigenschaften',
      paletteTitle: 'Formen',
      searchShape: 'Form suchen',
      noShape: 'Keine passende Form',
      resizeSidebar: 'Ziehen zum Ändern der Breite',
      cat_general: 'Allgemein',
      cat_flow: 'Flussdiagramm',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Netzwerk & Cloud',
      cat_org: 'Organisation',
      cat_mind: 'Mindmap',
      cat_er: 'ER-Diagramm',
      groupBasic: 'Basisformen',
      groupFlow: 'Flusssymbole',
      groupBpmn: 'Swimlanes & BPMN',
      shape_rect: 'Prozess',
      shape_startEnd: 'Start / Ende',
      shape_decision: 'Entscheidung',
      shape_data: 'Daten',
      shape_swimlane: 'Horizontale Swimlane',
      shape_swimlaneV: 'Vertikale Swimlane',
      shape_bpmnTask: 'BPMN-Aufgabe',
      canvasAria: 'Flussdiagramm-Fläche',
      emptyHint: 'Form von links ziehen oder Vorlage wählen',
      nodesLabel: 'Knoten',
      edgesLabel: 'Kanten',
      saved: 'Im lokalen Entwurf gespeichert',
      saving: 'Automatisches Speichern nach der Bearbeitung',
      noSelection: 'Kein Element ausgewählt',
      selected: '{{count}} Elemente ausgewählt',
      fill: 'Füllung',
      stroke: 'Rahmen',
      strokeWidth: 'Linienstärke',
      fontSize: 'Schriftgröße',
      bold: 'Fett',
      italic: 'Kursiv',
      align: 'Ausrichtung',
      alignLeft: 'Links',
      alignCenter: 'Mitte',
      alignRight: 'Rechts',
      label: 'Text',
      edgeLabel: 'Kantenbeschriftung',
      templateTitle: 'Vorlage wählen',
      templateBasic: 'Basisfluss',
      templateDecision: 'Entscheidungsfluss',
      templateSwimlane: 'Horizontaler Swimlane-Fluss',
      templateSwimlaneV: 'Vertikaler Swimlane-Fluss',
      templateBpmn: 'BPMN-Gerüst',
      templateHint: 'Laden einer Vorlage ersetzt die aktuelle Fläche',
      exportPanel: 'Exportieren',
      importFile: 'Importieren',
      scale: 'Maßstab',
      transparentBg: 'Transparent',
      onlySelected: 'Nur Auswahl',
      layers: 'Ebenen',
      history: 'Verlauf',
      addPage: 'Neue Seite',
      noLayer: 'Keine Elemente auf der Fläche',
      noSnapshot: 'Noch keine Snapshots gespeichert',
      saveSnapshot: 'Speichern',
      snapshotName: 'Snapshot-Name',
      restore: 'Wiederherstellen',
      toggleVisible: 'Ein- / Ausblenden',
      toggleLock: 'Sperren / Entsperren',
      renameHint: 'Doppelklick zum Umbenennen',
      alignTop: 'Oben ausrichten',
      alignMiddle: 'Mitte ausrichten',
      alignBottom: 'Unten ausrichten',
      distributeH: 'Horizontal verteilen',
      distributeV: 'Vertikal verteilen',
      layerFront: 'Nach vorne',
      layerForward: 'Eine Ebene vor',
      layerBackward: 'Eine Ebene zurück',
      layerBack: 'Nach hinten',
      group: 'Gruppieren',
      ungroup: 'Gruppe auflösen',
      edgeStyle: 'Kantenstil',
      edgeType: 'Linientyp',
      edgeDash: 'Linie',
      edgeStartArrow: 'Start',
      edgeEndArrow: 'Ende',
      straight: 'Gerade',
      bezier: 'Bézier',
      smoothstep: 'Abgerundete Ecke',
      step: 'Rechteckige Ecke',
      solid: 'Durchgezogen',
      dashed: 'Gestrichelt',
      dotted: 'Gepunktet',
      arrowNone: 'Keine',
      arrowArrow: 'Pfeil',
      arrowCircle: 'Kreis',
      templateUmlUseCase: 'Anwendungsfalldiagramm',
      templateUmlClass: 'Klassendiagramm',
      templateUmlSequence: 'Sequenzdiagramm',
      templateUmlActivity: 'Aktivitätsdiagramm',
      templateUmlState: 'Zustandsdiagramm',
      templateBpmnProcess: 'Geschäftsprozess',
      templateNetTopology: 'Netzwerktopologie',
      templateOrgChart: 'Organigramm',
      templateMindMap: 'Mindmap',
      templateErDiagram: 'ER-Diagramm',
      err: {
        EMPTY: 'Fläche ist leer',
        EXPORT_FAILED: 'Export fehlgeschlagen',
        IMPORT_FAILED: 'Import fehlgeschlagen: Dateiformat nicht erkannt',
      },
    },
  },
};

const it: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nuova tela',
      docTitle: 'Titolo del diagramma',
      titlePlaceholder: 'Diagramma senza titolo',
      clear: 'Pulisci',
      exportPng: 'Esporta PNG',
      exportSvg: 'Esporta SVG',
      templates: 'Modelli',
      autoLayout: 'Disposizione auto',
      undo: 'Annulla',
      redo: 'Ripeti',
      duplicate: 'Duplica',
      delete: 'Elimina',
      panelTitle: 'Proprietà',
      paletteTitle: 'Forme',
      searchShape: 'Cerca forma',
      noShape: 'Nessuna forma corrispondente',
      resizeSidebar: 'Trascina per ridimensionare il pannello',
      cat_general: 'Generale',
      cat_flow: 'Diagramma di flusso',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Rete & Cloud',
      cat_org: 'Organizzazione',
      cat_mind: 'Mappa mentale',
      cat_er: 'Diagramma ER',
      groupBasic: 'Forme base',
      groupFlow: 'Simboli di flusso',
      groupBpmn: 'Swimlane e BPMN',
      shape_rect: 'Processo',
      shape_startEnd: 'Inizio / Fine',
      shape_decision: 'Decisione',
      shape_data: 'Dati',
      shape_swimlane: 'Swimlane orizzontale',
      shape_swimlaneV: 'Swimlane verticale',
      shape_bpmnTask: 'Attività BPMN',
      canvasAria: 'Tela del diagramma',
      emptyHint: 'Trascina una forma da sinistra o scegli un modello',
      nodesLabel: 'Nodi',
      edgesLabel: 'Collegamenti',
      saved: 'Salvato nella bozza locale',
      saving: 'Salvataggio automatico dopo la modifica',
      noSelection: 'Nessun elemento selezionato',
      selected: '{{count}} elementi selezionati',
      fill: 'Riempimento',
      stroke: 'Contorno',
      strokeWidth: 'Spessore',
      fontSize: 'Dimensione',
      bold: 'Grassetto',
      italic: 'Corsivo',
      align: 'Allineamento',
      alignLeft: 'Sinistra',
      alignCenter: 'Centro',
      alignRight: 'Destra',
      label: 'Testo',
      edgeLabel: 'Etichetta collegamento',
      templateTitle: 'Scegli un modello',
      templateBasic: 'Flusso base',
      templateDecision: 'Flusso decisionale',
      templateSwimlane: 'Flusso swimlane orizzontale',
      templateSwimlaneV: 'Flusso swimlane verticale',
      templateBpmn: 'Scheletro BPMN',
      templateHint: 'Caricare un modello sostituisce la tela corrente',
      exportPanel: 'Esporta',
      importFile: 'Importa',
      scale: 'Scala',
      transparentBg: 'Trasparente',
      onlySelected: 'Solo selezione',
      layers: 'Livelli',
      history: 'Cronologia',
      addPage: 'Nuova pagina',
      noLayer: 'Nessun elemento sulla tela',
      noSnapshot: 'Nessuno snapshot salvato',
      saveSnapshot: 'Salva',
      snapshotName: 'Nome snapshot',
      restore: 'Ripristina',
      toggleVisible: 'Mostra / Nascondi',
      toggleLock: 'Blocca / Sblocca',
      renameHint: 'Doppio clic per rinominare',
      alignTop: 'Allinea in alto',
      alignMiddle: 'Allinea al centro',
      alignBottom: 'Allinea in basso',
      distributeH: 'Distribuisci orizzontalmente',
      distributeV: 'Distribuisci verticalmente',
      layerFront: 'Porta in primo piano',
      layerForward: 'Porta avanti',
      layerBackward: 'Porta indietro',
      layerBack: 'Porta in secondo piano',
      group: 'Raggruppa',
      ungroup: 'Separa gruppo',
      edgeStyle: 'Stile collegamento',
      edgeType: 'Tipo di linea',
      edgeDash: 'Tratto',
      edgeStartArrow: 'Inizio',
      edgeEndArrow: 'Fine',
      straight: 'Linea retta',
      bezier: 'Bézier',
      smoothstep: 'Angolo arrotondato',
      step: 'Angolo retto',
      solid: 'Piena',
      dashed: 'Tratteggiata',
      dotted: 'Punteggiata',
      arrowNone: 'Nessuna',
      arrowArrow: 'Freccia',
      arrowCircle: 'Cerchio',
      templateUmlUseCase: 'Diagramma dei casi d’uso',
      templateUmlClass: 'Diagramma delle classi',
      templateUmlSequence: 'Diagramma di sequenza',
      templateUmlActivity: 'Diagramma di attività',
      templateUmlState: 'Diagramma di stato',
      templateBpmnProcess: 'Processo aziendale',
      templateNetTopology: 'Topologia di rete',
      templateOrgChart: 'Organigramma',
      templateMindMap: 'Mappa mentale',
      templateErDiagram: 'Diagramma ER',
      err: {
        EMPTY: 'La tela è vuota',
        EXPORT_FAILED: 'Esportazione non riuscita',
        IMPORT_FAILED: 'Importazione non riuscita: formato file non riconosciuto',
      },
    },
  },
};

const es: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nuevo lienzo',
      docTitle: 'Título del diagrama',
      titlePlaceholder: 'Diagrama sin título',
      clear: 'Vaciar',
      exportPng: 'Exportar PNG',
      exportSvg: 'Exportar SVG',
      templates: 'Plantillas',
      autoLayout: 'Auto diseño',
      undo: 'Deshacer',
      redo: 'Rehacer',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      panelTitle: 'Propiedades',
      paletteTitle: 'Formas',
      searchShape: 'Buscar formas',
      noShape: 'Sin formas coincidentes',
      resizeSidebar: 'Arrastra para ajustar el ancho',
      cat_general: 'General',
      cat_flow: 'Diagrama de flujo',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Red y nube',
      cat_org: 'Organización',
      cat_mind: 'Mapa mental',
      cat_er: 'Diagrama ER',
      groupBasic: 'Formas básicas',
      groupFlow: 'Símbolos de flujo',
      groupBpmn: 'Carriles y BPMN',
      shape_rect: 'Proceso',
      shape_startEnd: 'Inicio / Fin',
      shape_decision: 'Decisión',
      shape_data: 'Datos',
      shape_swimlane: 'Carril horizontal',
      shape_swimlaneV: 'Carril vertical',
      shape_bpmnTask: 'Tarea BPMN',
      canvasAria: 'Lienzo de diagrama',
      emptyHint: 'Arrastra una forma desde la izquierda o elige una plantilla',
      nodesLabel: 'Nodos',
      edgesLabel: 'Enlaces',
      saved: 'Guardado en el borrador local',
      saving: 'Se guarda automáticamente al dejar de editar',
      noSelection: 'Ningún elemento seleccionado',
      selected: '{{count}} elementos seleccionados',
      fill: 'Relleno',
      stroke: 'Contorno',
      strokeWidth: 'Grosor',
      fontSize: 'Tamaño',
      bold: 'Negrita',
      italic: 'Cursiva',
      align: 'Alineación',
      alignLeft: 'Izquierda',
      alignCenter: 'Centro',
      alignRight: 'Derecha',
      label: 'Texto',
      edgeLabel: 'Etiqueta de enlace',
      templateTitle: 'Elegir plantilla',
      templateBasic: 'Flujo básico',
      templateDecision: 'Flujo de decisión',
      templateSwimlane: 'Flujo de carril horizontal',
      templateSwimlaneV: 'Flujo de carril vertical',
      templateBpmn: 'Esqueleto BPMN',
      templateHint: 'Cargar una plantilla reemplaza el lienzo actual',
      exportPanel: 'Exportar',
      importFile: 'Importar',
      scale: 'Escala',
      transparentBg: 'Transparente',
      onlySelected: 'Solo selección',
      layers: 'Capas',
      history: 'Historial',
      addPage: 'Nueva página',
      noLayer: 'No hay elementos en el lienzo',
      noSnapshot: 'Aún no hay instantáneas guardadas',
      saveSnapshot: 'Guardar',
      snapshotName: 'Nombre de instantánea',
      restore: 'Restaurar',
      toggleVisible: 'Mostrar / Ocultar',
      toggleLock: 'Bloquear / Desbloquear',
      renameHint: 'Doble clic para renombrar',
      alignTop: 'Alinear arriba',
      alignMiddle: 'Alinear al centro',
      alignBottom: 'Alinear abajo',
      distributeH: 'Distribuir horizontalmente',
      distributeV: 'Distribuir verticalmente',
      layerFront: 'Traer al frente',
      layerForward: 'Acercar',
      layerBackward: 'Alejar',
      layerBack: 'Enviar atrás',
      group: 'Agrupar',
      ungroup: 'Desagrupar',
      edgeStyle: 'Estilo de enlace',
      edgeType: 'Tipo de línea',
      edgeDash: 'Trazo',
      edgeStartArrow: 'Inicio',
      edgeEndArrow: 'Fin',
      straight: 'Línea recta',
      bezier: 'Bézier',
      smoothstep: 'Esquina redondeada',
      step: 'Esquina recta',
      solid: 'Sólida',
      dashed: 'Guionada',
      dotted: 'Punteada',
      arrowNone: 'Ninguna',
      arrowArrow: 'Flecha',
      arrowCircle: 'Círculo',
      templateUmlUseCase: 'Diagrama de casos de uso',
      templateUmlClass: 'Diagrama de clases',
      templateUmlSequence: 'Diagrama de secuencia',
      templateUmlActivity: 'Diagrama de actividad',
      templateUmlState: 'Diagrama de estados',
      templateBpmnProcess: 'Proceso de negocio',
      templateNetTopology: 'Topología de red',
      templateOrgChart: 'Organigrama',
      templateMindMap: 'Mapa mental',
      templateErDiagram: 'Diagrama ER',
      err: {
        EMPTY: 'El lienzo está vacío',
        EXPORT_FAILED: 'Error al exportar',
        IMPORT_FAILED: 'Error al importar: formato de archivo no reconocido',
      },
    },
  },
};

const pt: ResourceTree = {
  tools: {
    flowchart: {
      newDoc: 'Nova tela',
      docTitle: 'Título do diagrama',
      titlePlaceholder: 'Diagrama sem título',
      clear: 'Limpar',
      exportPng: 'Exportar PNG',
      exportSvg: 'Exportar SVG',
      templates: 'Modelos',
      autoLayout: 'Auto layout',
      undo: 'Anular',
      redo: 'Refazer',
      duplicate: 'Duplicar',
      delete: 'Eliminar',
      panelTitle: 'Propriedades',
      paletteTitle: 'Formas',
      searchShape: 'Buscar formas',
      noShape: 'Nenhuma forma correspondente',
      resizeSidebar: 'Arraste para redimensionar a barra',
      cat_general: 'Geral',
      cat_flow: 'Fluxograma',
      cat_uml: 'UML',
      cat_bpmn: 'BPMN',
      cat_network: 'Rede e nuvem',
      cat_org: 'Organização',
      cat_mind: 'Mapa mental',
      cat_er: 'Diagrama ER',
      groupBasic: 'Formas básicas',
      groupFlow: 'Símbolos de fluxo',
      groupBpmn: 'Raias e BPMN',
      shape_rect: 'Processo',
      shape_startEnd: 'Início / Fim',
      shape_decision: 'Decisão',
      shape_data: 'Dados',
      shape_swimlane: 'Raia horizontal',
      shape_swimlaneV: 'Raia vertical',
      shape_bpmnTask: 'Tarefa BPMN',
      canvasAria: 'Tela do diagrama',
      emptyHint: 'Arraste uma forma da esquerda ou escolha um modelo',
      nodesLabel: 'Nós',
      edgesLabel: 'Ligações',
      saved: 'Guardado no rascunho local',
      saving: 'Guarda automaticamente após parar de editar',
      noSelection: 'Nenhum elemento selecionado',
      selected: '{{count}} elementos selecionados',
      fill: 'Preenchimento',
      stroke: 'Contorno',
      strokeWidth: 'Espessura',
      fontSize: 'Tamanho',
      bold: 'Negrito',
      italic: 'Itálico',
      align: 'Alinhamento',
      alignLeft: 'Esquerda',
      alignCenter: 'Centro',
      alignRight: 'Direita',
      label: 'Texto',
      edgeLabel: 'Etiqueta da ligação',
      templateTitle: 'Escolher modelo',
      templateBasic: 'Fluxo básico',
      templateDecision: 'Fluxo de decisão',
      templateSwimlane: 'Fluxo de raia horizontal',
      templateSwimlaneV: 'Fluxo de raia vertical',
      templateBpmn: 'Esqueleto BPMN',
      templateHint: 'Carregar um modelo substitui a tela atual',
      exportPanel: 'Exportar',
      importFile: 'Importar',
      scale: 'Escala',
      transparentBg: 'Transparente',
      onlySelected: 'Só seleção',
      layers: 'Camadas',
      history: 'Histórico',
      addPage: 'Nova página',
      noLayer: 'Nenhum elemento na tela',
      noSnapshot: 'Nenhum instantâneo salvo ainda',
      saveSnapshot: 'Guardar',
      snapshotName: 'Nome do instantâneo',
      restore: 'Restaurar',
      toggleVisible: 'Mostrar / Ocultar',
      toggleLock: 'Bloquear / Desbloquear',
      renameHint: 'Duplo clique para renomear',
      alignTop: 'Alinhar ao topo',
      alignMiddle: 'Alinhar ao centro',
      alignBottom: 'Alinhar à base',
      distributeH: 'Distribuir horizontalmente',
      distributeV: 'Distribuir verticalmente',
      layerFront: 'Trazer para frente',
      layerForward: 'Avançar',
      layerBackward: 'Recuar',
      layerBack: 'Enviar para trás',
      group: 'Agrupar',
      ungroup: 'Desagrupar',
      edgeStyle: 'Estilo da ligação',
      edgeType: 'Tipo de linha',
      edgeDash: 'Traço',
      edgeStartArrow: 'Início',
      edgeEndArrow: 'Fim',
      straight: 'Linha reta',
      bezier: 'Bézier',
      smoothstep: 'Canto arredondado',
      step: 'Canto reto',
      solid: 'Sólida',
      dashed: 'Tracejada',
      dotted: 'Pontilhada',
      arrowNone: 'Nenhuma',
      arrowArrow: 'Seta',
      arrowCircle: 'Círculo',
      templateUmlUseCase: 'Diagrama de casos de uso',
      templateUmlClass: 'Diagrama de classes',
      templateUmlSequence: 'Diagrama de sequência',
      templateUmlActivity: 'Diagrama de atividade',
      templateUmlState: 'Diagramma de estados',
      templateBpmnProcess: 'Processo de negócio',
      templateNetTopology: 'Topologia de rede',
      templateOrgChart: 'Organograma',
      templateMindMap: 'Mapa mental',
      templateErDiagram: 'Diagrama ER',
      err: {
        EMPTY: 'A tela está vazia',
        EXPORT_FAILED: 'Falha ao exportar',
        IMPORT_FAILED: 'Falha ao importar: formato de arquivo não reconhecido',
      },
    },
  },
};

/** 语言代码 → 资源树，键与 `Lang` 保持一致 */
export const flowchartStrings: Record<string, ResourceTree> = {
  zh,
  en,
  'zh-TW': zhTW,
  ja,
  fr,
  de,
  it,
  es,
  pt,
};

/** 把图形名按 `shape_<kind>` 并入资源树（形状较多，单独在 shapeLabels.ts 维护） */
function withShapeLabels(lng: string, base: ResourceTree): ResourceTree {
  const labels = SHAPE_LABELS_I18N[lng];
  if (!labels) return base;
  const shapeKeys: StringTree = {};
  for (const [kind, name] of Object.entries(labels)) {
    shapeKeys[`shape_${kind}`] = name;
  }
  return { tools: { flowchart: { ...base.tools.flowchart, ...shapeKeys } } };
}

/** 把本工具文案合并进 i18next（工具被懒加载时调用，键路径 tools.flowchart.*） */
export function registerFlowchartStrings(instance: {
  addResourceBundle: (
    lng: string,
    ns: string,
    resources: ResourceTree,
    deep: boolean,
    overwrite: boolean,
  ) => void;
}): void {
  for (const [lng, resources] of Object.entries(flowchartStrings)) {
    instance.addResourceBundle(lng, 'translation', withShapeLabels(lng, resources), true, true);
  }
}
