/** CSS Level 4 命名颜色（含 rebeccapurple），hex 为大写 #RRGGBB */

export type WebColorGroup =
  | 'red'
  | 'orange'
  | 'yellow'
  | 'green'
  | 'cyan'
  | 'blue'
  | 'purple'
  | 'pink'
  | 'brown'
  | 'white'
  | 'gray'
  | 'black';

export interface WebColor {
  name: string;
  hex: string;
  group: WebColorGroup;
}

export const WEB_COLOR_GROUPS: WebColorGroup[] = [
  'red',
  'orange',
  'yellow',
  'green',
  'cyan',
  'blue',
  'purple',
  'pink',
  'brown',
  'white',
  'gray',
  'black',
];

export const WEB_COLORS: WebColor[] = [
  { name: 'IndianRed', hex: '#CD5C5C', group: 'red' },
  { name: 'LightCoral', hex: '#F08080', group: 'red' },
  { name: 'Salmon', hex: '#FA8072', group: 'red' },
  { name: 'DarkSalmon', hex: '#E9967A', group: 'red' },
  { name: 'LightSalmon', hex: '#FFA07A', group: 'red' },
  { name: 'Crimson', hex: '#DC143C', group: 'red' },
  { name: 'Red', hex: '#FF0000', group: 'red' },
  { name: 'FireBrick', hex: '#B22222', group: 'red' },
  { name: 'DarkRed', hex: '#8B0000', group: 'red' },
  { name: 'Coral', hex: '#FF7F50', group: 'orange' },
  { name: 'Tomato', hex: '#FF6347', group: 'orange' },
  { name: 'OrangeRed', hex: '#FF4500', group: 'orange' },
  { name: 'DarkOrange', hex: '#FF8C00', group: 'orange' },
  { name: 'Orange', hex: '#FFA500', group: 'orange' },
  { name: 'Gold', hex: '#FFD700', group: 'yellow' },
  { name: 'Yellow', hex: '#FFFF00', group: 'yellow' },
  { name: 'LightYellow', hex: '#FFFFE0', group: 'yellow' },
  { name: 'LemonChiffon', hex: '#FFFACD', group: 'yellow' },
  { name: 'LightGoldenrodYellow', hex: '#FAFAD2', group: 'yellow' },
  { name: 'PapayaWhip', hex: '#FFEFD5', group: 'yellow' },
  { name: 'Moccasin', hex: '#FFE4B5', group: 'yellow' },
  { name: 'PeachPuff', hex: '#FFDAB9', group: 'yellow' },
  { name: 'PaleGoldenrod', hex: '#EEE8AA', group: 'yellow' },
  { name: 'Khaki', hex: '#F0E68C', group: 'yellow' },
  { name: 'DarkKhaki', hex: '#BDB76B', group: 'yellow' },
  { name: 'Lavender', hex: '#E6E6FA', group: 'purple' },
  { name: 'Thistle', hex: '#D8BFD8', group: 'purple' },
  { name: 'Plum', hex: '#DDA0DD', group: 'purple' },
  { name: 'Violet', hex: '#EE82EE', group: 'purple' },
  { name: 'Orchid', hex: '#DA70D6', group: 'purple' },
  { name: 'Fuchsia', hex: '#FF00FF', group: 'purple' },
  { name: 'Magenta', hex: '#FF00FF', group: 'purple' },
  { name: 'MediumOrchid', hex: '#BA55D3', group: 'purple' },
  { name: 'MediumPurple', hex: '#9370DB', group: 'purple' },
  { name: 'RebeccaPurple', hex: '#663399', group: 'purple' },
  { name: 'BlueViolet', hex: '#8A2BE2', group: 'purple' },
  { name: 'DarkViolet', hex: '#9400D3', group: 'purple' },
  { name: 'DarkOrchid', hex: '#9932CC', group: 'purple' },
  { name: 'DarkMagenta', hex: '#8B008B', group: 'purple' },
  { name: 'Purple', hex: '#800080', group: 'purple' },
  { name: 'Indigo', hex: '#4B0082', group: 'purple' },
  { name: 'SlateBlue', hex: '#6A5ACD', group: 'purple' },
  { name: 'DarkSlateBlue', hex: '#483D8B', group: 'purple' },
  { name: 'MediumSlateBlue', hex: '#7B68EE', group: 'purple' },
  { name: 'GreenYellow', hex: '#ADFF2F', group: 'green' },
  { name: 'Chartreuse', hex: '#7FFF00', group: 'green' },
  { name: 'LawnGreen', hex: '#7CFC00', group: 'green' },
  { name: 'Lime', hex: '#00FF00', group: 'green' },
  { name: 'LimeGreen', hex: '#32CD32', group: 'green' },
  { name: 'PaleGreen', hex: '#98FB98', group: 'green' },
  { name: 'LightGreen', hex: '#90EE90', group: 'green' },
  { name: 'MediumSpringGreen', hex: '#00FA9A', group: 'green' },
  { name: 'SpringGreen', hex: '#00FF7F', group: 'green' },
  { name: 'MediumSeaGreen', hex: '#3CB371', group: 'green' },
  { name: 'SeaGreen', hex: '#2E8B57', group: 'green' },
  { name: 'ForestGreen', hex: '#228B22', group: 'green' },
  { name: 'Green', hex: '#008000', group: 'green' },
  { name: 'DarkGreen', hex: '#006400', group: 'green' },
  { name: 'YellowGreen', hex: '#9ACD32', group: 'green' },
  { name: 'OliveDrab', hex: '#6B8E23', group: 'green' },
  { name: 'Olive', hex: '#808000', group: 'green' },
  { name: 'DarkOliveGreen', hex: '#556B2F', group: 'green' },
  { name: 'MediumAquamarine', hex: '#66CDAA', group: 'green' },
  { name: 'DarkSeaGreen', hex: '#8FBC8F', group: 'green' },
  { name: 'LightSeaGreen', hex: '#20B2AA', group: 'cyan' },
  { name: 'DarkCyan', hex: '#008B8B', group: 'cyan' },
  { name: 'Teal', hex: '#008080', group: 'cyan' },
  { name: 'Aqua', hex: '#00FFFF', group: 'cyan' },
  { name: 'Cyan', hex: '#00FFFF', group: 'cyan' },
  { name: 'LightCyan', hex: '#E0FFFF', group: 'cyan' },
  { name: 'PaleTurquoise', hex: '#AFEEEE', group: 'cyan' },
  { name: 'Aquamarine', hex: '#7FFFD4', group: 'cyan' },
  { name: 'Turquoise', hex: '#40E0D0', group: 'cyan' },
  { name: 'MediumTurquoise', hex: '#48D1CC', group: 'cyan' },
  { name: 'DarkTurquoise', hex: '#00CED1', group: 'cyan' },
  { name: 'CadetBlue', hex: '#5F9EA0', group: 'blue' },
  { name: 'SteelBlue', hex: '#4682B4', group: 'blue' },
  { name: 'LightSteelBlue', hex: '#B0C4DE', group: 'blue' },
  { name: 'PowderBlue', hex: '#B0E0E6', group: 'blue' },
  { name: 'LightBlue', hex: '#ADD8E6', group: 'blue' },
  { name: 'SkyBlue', hex: '#87CEEB', group: 'blue' },
  { name: 'LightSkyBlue', hex: '#87CEFA', group: 'blue' },
  { name: 'DeepSkyBlue', hex: '#00BFFF', group: 'blue' },
  { name: 'DodgerBlue', hex: '#1E90FF', group: 'blue' },
  { name: 'CornflowerBlue', hex: '#6495ED', group: 'blue' },
  { name: 'RoyalBlue', hex: '#4169E1', group: 'blue' },
  { name: 'Blue', hex: '#0000FF', group: 'blue' },
  { name: 'MediumBlue', hex: '#0000CD', group: 'blue' },
  { name: 'DarkBlue', hex: '#00008B', group: 'blue' },
  { name: 'Navy', hex: '#000080', group: 'blue' },
  { name: 'MidnightBlue', hex: '#191970', group: 'blue' },
  { name: 'Cornsilk', hex: '#FFF8DC', group: 'brown' },
  { name: 'BlanchedAlmond', hex: '#FFEBCD', group: 'brown' },
  { name: 'Bisque', hex: '#FFE4C4', group: 'brown' },
  { name: 'NavajoWhite', hex: '#FFDEAD', group: 'brown' },
  { name: 'Wheat', hex: '#F5DEB3', group: 'brown' },
  { name: 'BurlyWood', hex: '#DEB887', group: 'brown' },
  { name: 'Tan', hex: '#D2B48C', group: 'brown' },
  { name: 'RosyBrown', hex: '#BC8F8F', group: 'brown' },
  { name: 'SandyBrown', hex: '#F4A460', group: 'brown' },
  { name: 'Goldenrod', hex: '#DAA520', group: 'brown' },
  { name: 'DarkGoldenrod', hex: '#B8860B', group: 'brown' },
  { name: 'Peru', hex: '#CD853F', group: 'brown' },
  { name: 'Chocolate', hex: '#D2691E', group: 'brown' },
  { name: 'SaddleBrown', hex: '#8B4513', group: 'brown' },
  { name: 'Sienna', hex: '#A0522D', group: 'brown' },
  { name: 'Brown', hex: '#A52A2A', group: 'brown' },
  { name: 'Maroon', hex: '#800000', group: 'brown' },
  { name: 'White', hex: '#FFFFFF', group: 'white' },
  { name: 'Snow', hex: '#FFFAFA', group: 'white' },
  { name: 'HoneyDew', hex: '#F0FFF0', group: 'white' },
  { name: 'MintCream', hex: '#F5FFFA', group: 'white' },
  { name: 'Azure', hex: '#F0FFFF', group: 'white' },
  { name: 'AliceBlue', hex: '#F0F8FF', group: 'white' },
  { name: 'GhostWhite', hex: '#F8F8FF', group: 'white' },
  { name: 'WhiteSmoke', hex: '#F5F5F5', group: 'white' },
  { name: 'Seashell', hex: '#FFF5EE', group: 'white' },
  { name: 'Beige', hex: '#F5F5DC', group: 'white' },
  { name: 'OldLace', hex: '#FDF5E6', group: 'white' },
  { name: 'FloralWhite', hex: '#FFFAF0', group: 'white' },
  { name: 'Ivory', hex: '#FFFFF0', group: 'white' },
  { name: 'AntiqueWhite', hex: '#FAEBD7', group: 'white' },
  { name: 'Linen', hex: '#FAF0E6', group: 'white' },
  { name: 'LavenderBlush', hex: '#FFF0F5', group: 'pink' },
  { name: 'MistyRose', hex: '#FFE4E1', group: 'pink' },
  { name: 'Gainsboro', hex: '#DCDCDC', group: 'gray' },
  { name: 'LightGray', hex: '#D3D3D3', group: 'gray' },
  { name: 'LightGrey', hex: '#D3D3D3', group: 'gray' },
  { name: 'Silver', hex: '#C0C0C0', group: 'gray' },
  { name: 'DarkGray', hex: '#A9A9A9', group: 'gray' },
  { name: 'DarkGrey', hex: '#A9A9A9', group: 'gray' },
  { name: 'Gray', hex: '#808080', group: 'gray' },
  { name: 'Grey', hex: '#808080', group: 'gray' },
  { name: 'DimGray', hex: '#696969', group: 'gray' },
  { name: 'DimGrey', hex: '#696969', group: 'gray' },
  { name: 'LightSlateGray', hex: '#778899', group: 'gray' },
  { name: 'LightSlateGrey', hex: '#778899', group: 'gray' },
  { name: 'SlateGray', hex: '#708090', group: 'gray' },
  { name: 'SlateGrey', hex: '#708090', group: 'gray' },
  { name: 'DarkSlateGray', hex: '#2F4F4F', group: 'gray' },
  { name: 'DarkSlateGrey', hex: '#2F4F4F', group: 'gray' },
  { name: 'Black', hex: '#000000', group: 'black' },
  { name: 'Pink', hex: '#FFC0CB', group: 'pink' },
  { name: 'LightPink', hex: '#FFB6C1', group: 'pink' },
  { name: 'HotPink', hex: '#FF69B4', group: 'pink' },
  { name: 'DeepPink', hex: '#FF1493', group: 'pink' },
  { name: 'MediumVioletRed', hex: '#C71585', group: 'pink' },
  { name: 'PaleVioletRed', hex: '#DB7093', group: 'pink' },
];
